### ISSUE TITLE
Sublineage in BA.5.2.1, is it a sequencing artifact  ?

### ISSUE THREAD

**Issue by RaphaelRaphael** [cov-lineages/pango-designation#1069]
Considering the MSA codon aligned made available from GISAID (downloaded on 2022-09-01) and GISAID metadata downloaded on 2022-09-05, we did a subset of sequences assigned to pangolin lineage BA.5.2.1 (without descendants) and found a messy alignment region of 3 deleted codons that are positioned at 2 different places : [28361,28369] or  [28364,28372]

Here's a frequency table showing it :
![image](https://user-images.githubusercontent.com/3922571/190246621-f449f26e-5d1f-41cc-b36e-960e4a19a47f.png)

The 3 moving nucleotides are GGT (ref is GGA) in most BA.5.2.1 and also in descendants (BF*) but around 24K sequences have a TTT and make the alignment quite different.

Then we split BA.5.2.1 in 2 different set of sequences and looked at allele frequency of each set. There is 3 synonymous mutations in orf1ab present only in one of the 2 sets ( GGT and TTT ) - legend for mutations are in the graph shown above.

![Screenshot from 2022-09-14 15-45-11](https://user-images.githubusercontent.com/3922571/190248196-52c075c3-7e14-4d6a-833c-e158a5709fac.png)

Since the alignment is made a bit differently in Nexstrain we can check for state at position 28361 (G in green are GGT and T in blue are TTT) it seems monophyletic

![Screenshot from 2022-09-14 14-29-29](https://user-images.githubusercontent.com/3922571/190248773-a2b32294-6afd-4b63-bba3-93a80defdf45.png)

We can conclude to a real sub variant of BA.5.2.1 but ..

Then we did check for number of sequences per week per country and we saw a very surprising result where both kind of sequence are present in the same ratio everywhere, mostly pointing now to a sequencing artifact. ( TTT->blue and GGT-­>red )

![Screenshot from 2022-09-14 15-52-31](https://user-images.githubusercontent.com/3922571/190249400-30fc5ac4-33df-43d8-bf16-07d0cec7d252.png)

We would be glad to help confirming if it s an artifact or a subvariant !

Thank you

**Comment by AngieHinrichs** [comment]
Nice visualizations!  I believe this is more of a sequencing artefact due to some genome assembly pipelines being unable to detect deletions, and even among pipelines that can detect deletions, as you noted there is ambiguity about where the deletion may be placed.  

That deletion is expected in all Omicron sequences -- for example you can see it in Andrew Rambaut's [comparison](https://github.com/cov-lineages/pango-designation/issues/367#issuecomment-993024300) of BA.1, BA.2 and BA.3 mutations, back when BA.3 was first identified (search for "28362_28370del" or "ERS31del").  Unfortunately the many different genome assembly pipelines in use give inconsistent results, often including spurious "substitutions" at the edges of or adjacent to the deleted region.

**Comment by RaphaelRaphael** [comment]
Thx for the answer ! 
Now if it s a sequencing artifact, why 5284C->T is in linkage with it ? And how this artifact could lead to GGT(gly)->TTT(phe) change on so many sequences ?

Any idea on how to investigate would be welcome !

**Comment by corneliusroemer** [comment]
I had a quick look yesterday and thought the linkage is suggestive of either this being a true lineage - the two T mutations being real. Or it being a more complex artefact where the mutation 5284 is due to the same primer/workflow error as the two T mutations.

I agree that it's not clear either way.

**Comment by jcgrenier** [comment]
Hi all, we looked at the amplicons for the ArticV4 amplification kit, and it's far from the primers. The closer amplicon is the amplicon 95. Not sure there were any issues encountered for this one. The fact the trend is the same between both might just be reflecting that there's no real advantage of one sublineage over the other?

**Comment by RaphaelRaphael** [comment]
I just found a single country with enough sequence to say that there is not the TTT codon confirming @corneliusroemer on the two T mutations being real.

![Screenshot from 2022-09-15 10-58-06](https://user-images.githubusercontent.com/3922571/190437980-5f28ee9f-f4c5-41ec-8c3c-6c6eb888190a.png)

**Comment by FedeGueli** [comment]
@asinickle didnt you propose or make a very similar analysis in an issue that then you had closed due the @AngieHinrichs explanation in BF.7 issue?

**Comment by RaphaelRaphael** [comment]
@corneliusroemer I think BF.7 is having this double deletion

**Comment by corneliusroemer** [comment]
Closing as stale
