### ISSUE TITLE
Potential BA.2.3 sublineage with many mutations (singleton, Indonesia)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1080]
Proposal for a sublineage of BA.2.3
Earliest sequence: 20.08.2022 (Indonesia)
Countries detected: Indonesia (1)

I noticed a strange sequence uploaded today from Indonesia (**EPI_ISL_15005560**) carrying a total of c.115 mutations compared to root (see below). I t also carries 8 spike mutations (S:W64R, S:L176F, S:T240I, S:K417T, S:F486P, S:V610I, S:A647V, S:M1229T) whereas S:F486P is a double nuc mutation. Sequence quality, besides the number of private mutations, is apparently fine.  Its a singleton but probably worth highlighting given that it clusters close to BS.1 and BA.2.3.20. 

Provisorial GISAID query: 

Spike_W64R, Spike_F486P, Spike_M1229T
or 
N_N11S,Spike_F486P, NSP13_R392C (@FedeGueli )

Defining mutations:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/litho/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/litho/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

nuc | unique | C1853T, G3050A, G3072A, G3230A, T3343C,   C3535T, A3845G, C3912T, C4093T, G5572A, A6687G, C8809T, G9355A, G9751A,   C10165T, A11586G, A12421G, G13148A, A13653G, G15814A, C16726T, T20246C,   A21512G, T21752C, C22088T, C22281T, A22812C, T23018C, T23019C, G23390A,   C23502T, T25248C, T25779C, C26054T, C27431T, A28305G, G28925A, C29675T
-- | -- | --
nuc | homoplasies | C527T, A1033G, C1912T, G11071A, C18060T, G22898A, G22942T, T28636C
nuc | reversionsToRoot | G22942T
ORF1ab | unique | E929K, C936Y, G989S, K1194E, T1216I, M1769I, Y2141C, M3030I, N3774S,   V4295I, V5184I, H5488Y, M6661T, N7083S
S | unique | W64R, L176F, T240I, K417T, F486P, V610I, A647V, M1229T
S | homoplasies | G446S, K460N
ORF3a | unique | T221I
ORF7a | unique | A13V
N | unique | N11S, A218T
  |   |  

</body>

</html>

NOTE: I duplicated the sequence to generate a node in usher (its still a singleton):

![grafik](https://user-images.githubusercontent.com/102166254/190889689-ebe5930d-1ef5-4ad3-a9b8-3c05941cad0e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_609a_706470.json?branchLabel=Spike%20mutations&c=pango_lineage_usher
![grafik](https://user-images.githubusercontent.com/102166254/190889718-636d2afb-5354-40ac-8dc7-130c6b403c27.png)

![grafik](https://user-images.githubusercontent.com/102166254/190889752-ca3563cc-1760-47df-985c-62594b040fdc.png)

EPI_ISL_15005560

**Comment by JosetteSchoenma** [comment]
Yes, I noticed this one yesterday as well. @Ryhisner, which I somehow seen to be unable to tag, had some interesting analysis, he might want to share.

**Comment by FedeGueli** [comment]
There are more mutations than the ones listed.
@JosetteSchoenma  yesterday shared with us a nextclade screenshot where i can see Orf7a:A105V (that @ryhisner identified as recurrent in heavily mutated seauences)
and
Orf9B:M8V
and
E:S55F

**Comment by JosetteSchoenma** [comment]
Here it is. Mutations compared to BA.2, according to Nextclade.
![image](https://user-images.githubusercontent.com/94831035/190897543-d0c2523d-5636-485f-9905-09c332e312d0.png)

**Comment by FedeGueli** [comment]
Spike_F486P, NSP13_R392C

The gisaid query for BA.2.10.4 catches it too!

So a potential Gisaid query is
N_N11S,Spike_F486P, NSP13_R392C

**Comment by thomasppeacock** [comment]
As this is a singleton (and could therefore be a chronic infection) I'm going to close for the time being to keep the open page uncluttered - give one of us a shout if more sequences are found though and we can reopen and consider assigning. thanks!

**Comment by ryhisner** [comment]
100% of the 45 unlabeled private nucleotide mutations relative to the tree here are transitions (A>G, G>A, C>T, T>C), with zero transversions (A>C, C>A, A>T, T>A, C>G, G>C, G>T, T>G). Converting the adjusted nucleotide mutation rates from this @rneher page and converting them to percentages, I calculate that the expected transition-to-transversion ratio (Tr/Tv) is 2.03 to 1. Thanks to Zach Hensel (not sure what his tag here is) for pointing me to this source. https://github.com/neherlab/SC2_variant_rates/blob/master/data/mutation_rates.tsv

![image](https://user-images.githubusercontent.com/33738461/190932354-ecdd43f2-fd58-42a1-9205-c413db545b0a.png)

The ratio for this sequence's for unlabeled private mutations is 45 to 0. Using the nucleotide mutations listed by @agamedilab from the Usher tree—and assuming K460N is an artifact of the Usher tree, as I feel certain it is—the Tr/Tv ratio is 45 to 1. 

This calls for an explanation, and I suspect that explanation involves molnupiravir, which is known to cause higher Tr/Tv ratios. https://assets.researchsquare.com/files/rs-1835695/v1_covered.pdf?c=1658178636

![image](https://user-images.githubusercontent.com/33738461/190932581-a4d5b49c-e641-4e70-9ee2-8ab4074a4db5.png)

There may be other non-molnupiravir explanations for such an extraordinarily unusual Tr/Tv ratio. If anyone knows of any, please share. I'm not an expert and have no formal training in any of this, so I could be overlooking something obvious. However, I find it appalling that there seems to be no monitoring of molnupiravir-treated patients to see whether or not is might risk accelerating the emergence of hypermutated sequences like this one. 

In any case, the evidence indicates molnupiravir is not an effective treatment for Covid anyway—see the excellent analysis "Making Statistical Sense of the Molnupiravir MOVe-OUT Clinical Trial." https://www.ajtmh.org/view/journals/tpmd/106/5/article-p1301.xml Among other things, there have been at least three unpublished trials showing no benefit from molnupiravir compared to placebo. One of these studies, remarkably, was stopped for ethical reasons when there was a slightly higher death rate in the molnupiravir group. 

![image](https://user-images.githubusercontent.com/33738461/190933031-f723aa42-bc2e-4aad-9305-bac521801c01.png)

Even in the last half of the official clinical trial——by far the most relevant part because it coincided with the first significant immune-evasive variant and because the immune characteristics of the population were closer to what currently prevails—the molnupiravir-treatment group had a 33% higher hospitalization rate than the placebo group.  
![image](https://user-images.githubusercontent.com/33738461/190933153-4134c597-a891-45a2-afe6-c9a1d0189d5c.png)

Anyway, this rant is already way too long, but I'd love to hear what others' thoughts are on this.

**Comment by agamedilab** [comment]
@ryhisner many thanks for the interesting point! I did not notice the unusual Tr/Tv ratio but is definitely something to keep an eye on!
