### ISSUE TITLE
BS.1 lineage with S:K356T

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1097]
I noticed that two BS.1 have also got S:K356T

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/25161793/191462088-8eac2461-a83d-455c-9204-0bb48632d24b.png">

```
hCoV-19/Japan/IC-13842/2022|EPI_ISL_14853710|2022-08-20
hCoV-19/Singapore/11651/2022|EPI_ISL_15031895|2022-09-11
```

GISAID: Spike_S640F,Spike_L452R,Spike_K356T,Spike_R346T

**Comment by FedeGueli** [comment]
Big upload from Japan airport surveillance today, it is now : 13 sequences.
There is also a new south korean sequence not labelled as travel related. i think it deserves a designation, being 9 out of 900 samples containing the word Vietnam in the Gisaid uploads since 1/9/2022 suggesting some sort of prevalence there of this sublineage

**Comment by shay671** [comment]
It seems to be in the same step with :
C27752T
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16794_b319a0.json?c=userOrOld&label=nuc%20mutations:C629T,A2442C,C4763T,A5405G,A5648C,C6573T,C9979T,A10393C,C11750T,C15654T,C16418T,C20946T,G22599C,T22917G,G22988A,C23481T,C26408T,T26733C,C28677T
