### ISSUE TITLE
BM.1.1 sublineage with S:L5F, ORF1b:T1050I, ORF1a:S167G (174 seq., international as of 09.11.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1099]
Proposal for a sublineage of BM.1.1
Earliest sequence: 02.08.2022 (India)
Countries detected: Austria (16), India (9), USA (7), Singapore (1), Australia (1)

Defining mutations:
A764G = ORF1a:S167G
C16616T = ORF1b:T1050I
C21575T = S:L5F

This sublineage of BM.1.1 is defined by S:L5F, ORF1a:S167G, ORF1b:T1050I and was first detected in India and is now present in five countries across three continents. A total of 12 sequences are derived from yesterdays Austria upload.

![grafik](https://user-images.githubusercontent.com/102166254/191679540-8dcaa644-8326-4b0e-9fbd-4e4e6c5a3e8f.png)
![grafik](https://user-images.githubusercontent.com/102166254/191679726-9109d852-9366-4f7b-948a-44bf7fc95100.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_c2a1_c00940.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A764G,C16616T

However for some reason C21575T=S:L5F is not shown in Usher. 
![grafik](https://user-images.githubusercontent.com/102166254/191678003-4548c88f-bb07-49c4-a377-587546b60316.png)
![grafik](https://user-images.githubusercontent.com/102166254/191678587-b3516c47-e0ad-47f6-8d07-06b446f806e7.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AL5F&nucMutations=C16616T%2CC21575T&pangoLineage=Ba.2.75*&

EPI_ISL_14445845, EPI_ISL_14722475, EPI_ISL_14722513, EPI_ISL_14722562, EPI_ISL_14722601, EPI_ISL_14722669, EPI_ISL_14866361, EPI_ISL_14915896, EPI_ISL_14915960, EPI_ISL_14916075, EPI_ISL_14917722, EPI_ISL_14948260, EPI_ISL_14993329, EPI_ISL_15017961, EPI_ISL_15057624, EPI_ISL_15057631, EPI_ISL_15057634, EPI_ISL_15057641, EPI_ISL_15057642, EPI_ISL_15057657, EPI_ISL_15057658, EPI_ISL_15057659, EPI_ISL_15057661, EPI_ISL_15057662, EPI_ISL_15057663, EPI_ISL_15057664, EPI_ISL_15057665, EPI_ISL_15057667, EPI_ISL_15057671

OP367846.1, OP371839.1, OP387646.1, OP406711.1, OP407482.1

**Comment by Sinickle** [comment]
Does it seem that S:5F came after ORF1b:1050I in this sublineage? 

If this one gets reviewed for designation, I'd consider designating at ORF1b:1050I, to avoid the scenario we have with ORF1b:1050N on BA.5.2. Additionally, I notice our first BA.2.75* + S:486P also is BM.1.1 with ORF1b:1050I, but without S:5F.

**Comment by corneliusroemer** [comment]
S:5F is not a good defining mutation - it appears very often and is masked by Usher for that reason.

Let's wait a bit more what happens - whether the ORF1b provides a growth advantage for example.

**Comment by agamedilab** [comment]
@corneliusroemer many thanks! Is there a list with masked usher sites?

**Comment by AngieHinrichs** [comment]
There are two types of masking in the UShER tree daily update process:

1. Sites recommended for masking in the [Problematic Sites](https://github.com/W-L/ProblematicSites_SARS-CoV2) repository are masked (to reference, by removing them from the input VCF) in all new sequences before UShER places them in the tree.  The effect of this is to make it appear that those mutations never happen.

2. After placement in the tree, other sites are masked on specific branches by removing disallowed mutations from nodes in those branches by a [script](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/maskDelta.sh) (a little out of date at the moment, I need to commit & push recent additions for BA.2.75 and BA.5) that uses `matUtils mask -m`.  The sites on this list are mostly lineage-specific deletion/insertion regions where some genome assembly pipelines may add spurious "substitutions" and sites where we have a lot of trouble with false "reversions" caused by amplicon dropout and genome assembly pipelines that backfill reference values instead of honest Ns.  After this type of masking is performed, we run `matOptimize` in case there are better placements when these assumed errors have been removed.  The effect of this is to preserve expected mutations despite some sequences not having them.

**Comment by agamedilab** [comment]
51 seq on usher as of 30.09.22. Expansion into UK.

![grafik](https://user-images.githubusercontent.com/102166254/193206900-322b8257-de70-4700-affe-4e2abd47538f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_aabc_68da90.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A764G,C16616T

**Comment by agamedilab** [comment]
74 on usher as of 08.10.22.

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_19d76_19ddf0.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C16616T

![grafik](https://user-images.githubusercontent.com/102166254/194716541-85e4c3e5-3aa2-4ab0-ba43-6ce57926f72c.png)

**Comment by agamedilab** [comment]
112 on usher as of 28.10.22.
![grafik](https://user-images.githubusercontent.com/102166254/198520464-7f29d722-7374-46f2-ac57-88754006df2d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40e12_b76f70.json?branchLabel=aa%20mutations&c=Nextstrain_clade_usher&label=nuc%20mutations:A13498G

**Comment by agamedilab** [comment]
174 on usher as of 09.11.22.

![grafik](https://user-images.githubusercontent.com/102166254/200872734-8cc42f54-7617-451d-a0fc-146bfeec5edc.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1cc34_bc8010.json

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. Unfortunately, there appears to be negative trends (in USA, India, UK, and world wide) over the past three months. Consequently, this proposal can be closed for now, but please do re-propose or prompt for re-opening should this lineage show future positive and marked changes in growth.
