### ISSUE TITLE
Small but widespread BA.2.75.1 sublineage with S:R346S (6 seq, 5 countries, 3 continents)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1105]
Proposal for a sublineage of BA.2.75.1
Earliest sequence: 08.2022 (India)
Countries detected: Austria, India, Canada, Denmark, Bahrain

Defining mutations:
A22600T = S:R346S
C27903T = ORF8:L4F
C28744T 
G29540C

This sublineage of BA.2.75.1 is defined by S:R346S, ORF8:L4F and was firste detected in India. The sublineage is small but widespread (6 seq. across five countries/three countinents as of 24.09.22). 
 
![grafik](https://user-images.githubusercontent.com/102166254/192103190-6c17172c-4d12-4220-9140-299c95fdf4b7.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1f4e4_f0f370.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:A22600T,C27903T,C28744T,G29540C

![grafik](https://user-images.githubusercontent.com/102166254/192103498-ffbddcd7-03ac-4e7d-a3ae-5705505e4581.png)

EPI_ISL_14355579
EPI_ISL_14492169
EPI_ISL_14952734
EPI_ISL_15072354
EPI_ISL_15100391

OP457136.1

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BL.5 with 8 newly designated sequences, and 0 updated designations. Defining mutations A22600T (S:R346S), C27903T (ORF8:L4F), C28744T, G29540C (following A26612T).

**Comment by jinyu-ncbi** [comment]
Based on the data we have at NCBI, it seems there are sequencing or mutation call error with S:R346T and S:F486S, among some BA.2 sublineages, especially in BA.2.75 sequences. It is very likely that S:R346T exists in all BA.2.75 sequences, but the mutation cannot be correctly sequenced and called due to some technical difficulties. S:F486S might exist in all sequences of BA.2.75.2, BA.2.75.3, BA.2.75.4, BA.2.75.6, BA.2.75.9, but the call rates of the mutation are low for similar reasons. We need to be very careful when designating new BA.2.75 sublineages using these two mutations.

**Comment by jinyu-ncbi** [comment]
Sorry I just noticed that this new lineage is defined with R346S, not R346T. Anyways, there are many BA.2.75 sublineages defined using S346T, and we might want to check them again.
