### ISSUE TITLE
BA.5.2 +Orf1b:1050N sublineage with S:Y248H circulating in Peru ( 31 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1109]
I spotted this sublineage of  BA.5.2 with Orf1b:T1050N defined by S:Y248H.

Being this mutation associated with increased transmissibility , as in BF.15,  i propose it immediately.

Tree:
![Schermata 2022-09-24 alle 23 16 15](https://user-images.githubusercontent.com/87669813/192119051-d83e67e0-bb44-4624-908c-2a745c765a6c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_12298_f72470.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C2716T

Defining mutations:
C2716T then S:Y248H

5 sequences as today  : 5 from Peru', 2 From Usa, one from Chile.

This sublineage shows already some diversity with one sequence with S:450D and another couple , interestingly one from Chile, with N:A152V

CovSpectrum Query: C2716T + ORF1b:T1050N, S:Y248H
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1b%3A1050N%2CS%3AY248H&nucMutations=2716T&

Prevalence in Peru' around 2% in the last month.
![Schermata 2022-09-24 alle 23 22 04](https://user-images.githubusercontent.com/87669813/192119182-8e1c5eb2-90ba-4dcd-9062-e185410e7457.png)

**Comment by FedeGueli** [comment]
Big upload of this sublineage yesterday from Chile and Peru' , nextclading it right now. 23 are already on Usher but on Gisaid i see a lot more than that: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_411f0_2f5460.json?label=nuc%20mutations:T22304C
<img width="1085" alt="Schermata 2022-09-27 alle 15 11 23" src="https://user-images.githubusercontent.com/87669813/192535563-a0d3520b-2c48-4c59-b75f-a690b79b4b6a.png">

@corneliusroemer @InfrPopGen  i suggest a fast designation of this one

**Comment by FedeGueli** [comment]
With the complete USher tree i count, manually , 31 sequences belonging to this lineage:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_6c42_2fc190.json?branchLabel=aa%20mutations&label=nuc%20mutations:T22304C
<img width="1130" alt="Schermata 2022-09-27 alle 16 51 27" src="https://user-images.githubusercontent.com/87669813/192560284-77867b90-41ab-44ef-9f27-f2bd31526bf7.png">

Interestingly one of sequences has S:444N too.

**Comment by FedeGueli** [comment]
@AngieHinrichs i found another Ba.5.2 + Orf1b:1050N sublineage with S:Y248H circulating in Peru' that seems diverging from this one proposed by one nuc mutation: C2716T 

It seems weird to me that two lineages with the same S:Y248H emerged in the same area independently:
Downsampled tree of the two lineages:
<img width="1157" alt="Schermata 2022-09-27 alle 17 07 53" src="https://user-images.githubusercontent.com/87669813/192564284-a87df1c8-f6b6-42b7-97e3-e0bc7aa09830.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_6c42_2fc1a0.json?branchLabel=nuc%20mutations
tree of the sibling lineage not proposed here:
<img width="1154" alt="Schermata 2022-09-27 alle 17 08 19" src="https://user-images.githubusercontent.com/87669813/192564384-74fff95b-f59b-4349-ad19-d611c65f1020.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_6c42_2fc190.json?branchLabel=nuc%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C2716T

**Comment by AngieHinrichs** [comment]
> It seems weird to me that two lineages with the same S:Y248H emerged in the same area independently:

"Weird" is polite, you can say the tree looks wrong.  😄  I see some of the sequences have {G12310A, C16616A, C27012T, C27513T} as expected, but others have only {G12310A, C16616A} and not {C27012T, C27513T} so a different branch has been created for those.  It seems more likely to me that the sequences are missing C27012T and C27513T due to sequencing error but UShER doesn't know that.  To make them all look the same to UShER, I would need to mask those locations (which I don't like doing but can resort to if errors are causing major tree problems).

And then, as you point out, on the branch that's missing C27012T and C27513T, UShER is putting C2716T before T22304C for some of those sequences... wow, only on the basis of one sample with C2716T only (USA/CT-Yale-21532/2022|EPI_ISL_14315637|2022-07-22, in your subtree 3).  I'm a little surprised that the C2716T >  T22304C node hasn't been moved by optimization to the larger node with only T22304C, to become T22304C > C2716T -- but then, it's the same from a parsimony point of view.   It's only when the numbers of samples are considered that T22304C > C2716T is clearly better.

Here is a view of your downsampled tree, zoomed out to BA.5.2 and colored by Pango lineage assigned by placement on the tree, with large blue circles being the uploaded samples:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/186983/192571910-e5680308-7925-4650-9a7d-d3c333b0659d.png">
Interesting that beyond the above issues, some but not all of the sequences on the main {G12310A, C16616A, C27012T, C27513T} polytomy are polytomy + C23707T (BA.5.2.20) + T22304C.  It would be interesting to see where these sequences have Ns / low coverage.

**Comment by FedeGueli** [comment]
@corneliusroemer there isnt a specific gisaid query for them. For that reason the only thing is to split the most of sublineages. 

About the specific issue there is probably a split in two branches of the same lineage this proposed from Peru' as highlighted in the comment above. 

Being in Peru' and growing quite fast i disagree on closing it , S:248X was one of the hotspots  in BA.2 and quite fast in BF.15, so i would not discard it as irrelevant.

**Comment by FedeGueli** [comment]
> > It seems weird to me that two lineages with the same S:Y248H emerged in the same area independently:
> 
> "Weird" is polite, you can say the tree looks wrong. 😄 I see some of the sequences have {G12310A, C16616A, C27012T, C27513T} as expected, but others have only {G12310A, C16616A} and not {C27012T, C27513T} so a different branch has been created for those. It seems more likely to me that the sequences are missing C27012T and C27513T due to sequencing error but UShER doesn't know that. To make them all look the same to UShER, I would need to mask those locations (which I don't like doing but can resort to if errors are causing major tree problems).
> 
> And then, as you point out, on the branch that's missing C27012T and C27513T, UShER is putting C2716T before T22304C for some of those sequences... wow, only on the basis of one sample with C2716T only (USA/CT-Yale-21532/2022|EPI_ISL_14315637|2022-07-22, in your subtree 3). I'm a little surprised that the C2716T > T22304C node hasn't been moved by optimization to the larger node with only T22304C, to become T22304C > C2716T -- but then, it's the same from a parsimony point of view. It's only when the numbers of samples are considered that T22304C > C2716T is clearly better.
> 
> Here is a view of your downsampled tree, zoomed out to BA.5.2 and colored by Pango lineage assigned by placement on the tree, with large blue circles being the uploaded samples: <img alt="image" width="1231" src="https://user-images.githubusercontent.com/186983/192571910-e5680308-7925-4650-9a7d-d3c333b0659d.png"> ~Interesting that beyond the above issues, some but not all of the sequences on the main {G12310A, C16616A, C27012T, C27513T} polytomy are polytomy + C23707T (BA.5.2.20) + T22304C.~[edit: Never mind, I see now those are from England and you proposed in #1127.]
> 
> It would be interesting to see where these sequences have Ns / low coverage.

Thank you very much @AngieHinrichs ! i noticed the same thing for a BA.5.2.6 like lineage with S:346T , i was proposing it yesterday but i got convinced that is just a part of BA.5.2.6 misplaced for the same reason shown here, but maybe instead is it a sublineage of BA.5..2.20? i'll try to re collect the same tree and hopefully i will send to u.

**Comment by FedeGueli** [comment]
@corneliusroemer after the point of view expressed by @AngieHinrichs the total count of this lineage is 41 sequences.
Waiting Usher to be updated i thinnk this represents 1-3% of samples from Peru in the last two months.
I suggest to reopen it and eventually designate if it grows

**Comment by AngieHinrichs** [comment]
> i noticed the same thing for a BA.5.2.6 like lineage with S:346T , i was proposing it yesterday but i got convinced that is just a part of BA.5.2.6 misplaced for the same reason shown here, but maybe instead is it a sublineage of BA.5..2.20? i'll try to re collect the same tree and hopefully i will send to u.

@FedeGueli I think I see what you mean (especially the branch that finally gets 27012 as well, e.g. England/PHEC-YYG5XRC/2022) -- I'll add it to the list.  It definitely looks like BA.5.2.6 not BA.5.2.20 to me because BA.5.2.20 has C23707T but this doesn't.  If you see anything odd, yes please always let me know -- sequence names are helpful, I can find them very quickly in taxonium.

**Comment by FedeGueli** [comment]
44 sequences as today
