### ISSUE TITLE
Proposal for a new lineage within B.1.617.2 with S:A222V found in 12% of the samples labelled as B.1.617.2

### ISSUE THREAD

**Issue by animesh-workplace** [cov-lineages/pango-designation#112]
## Description

Sub-lineage of: B.1.617.2
Earliest sequence: 2020-12-10 (hCoV-19/India/MH-ICMR-NIV-INSACOG-2019nCoV-279084/2020) (EPI_ISL_2131509)
Most recent sequence: 2021-06-11 (hCoV-19/Australia/QLD1925/2021) (EPI_ISL_2507092)
Countries circulating: UK, India, USA, Germany, Canada, Singapore, Belgium, Vietnam, France, Japan, Poland, Mexico, Spain, Australia

Sequences were downloaded from GISAID on 16 June, 2021. 52015 sequences were labelled B.1.617.2 and out of that 6414 (12.33%) sequences were found to have S:A222V mutation with M:I82T co-occuring together.

List of characteristic amino acid changes of the new lineage:
**Substitution/Deletion**
:-----:
Spike\_A222V
M\_I82T
Spike\_D614G
NSP13\_P77L
Spike\_P681R
NSP12\_G671S
NSP6\_V149A
NSP12\_P323L
NS3\_S26L
NSP6\_T181I
N\_R203M
N\_D377Y
NSP4\_A446V
Spike\_L452R
NSP3\_P822L
Spike\_T478K
N\_D63G
NS7a\_T120I
NS7a\_V82A
Spike\_D950N
Spike\_R158del
Spike\_F157del
Spike\_E156G
Spike\_T19R
Spike\_G142D

## Genomes

[accession_ids.txt](https://github.com/cov-lineages/pango-designation/files/6663739/accession_ids.txt)

**Comment by shay671** [comment]
I used Virusurf to get a group from the sequences you defined here (based on the mutation list) and found the consensus mutation pattern of this variant using Coronannotator and did the same to  B.1, B.1.617.2 and AY.2. 
The  31 mutations in the pattern of the variant you describe here were  - 
4/4 of B.1
19/19 of B.1.617.2
8/15 of AY.2 
So it seems to me that what you describe here might be the ancestor of AY.2

**Comment by zach-hensel** [comment]
I think you can classify 4 major Delta branches with a few simple rules that rarely go wrong; the yellow branch might be better defined by S:A222V than ORF1a:T3750I because at least in this subsample the S mutation one time comes without the ORF1a mutation. Whether the differences are significant, I don't know.

By the way one interesting thing is that ORF1a:T3646A is not common at all but shows up in both B.1.617.1 and B.1.617.2. Maybe reversion or recombination?

![image](https://user-images.githubusercontent.com/23096983/124002727-ffea4b80-d9cd-11eb-98cc-b7bc74430ec1.png)

**Comment by chrisruis** [comment]
Thanks @animesh-workplace for submitting and the further discussion. We're just working on applying the Pango rules to B.1.617.2 and will hopefully have an update soon. I'll close this for now but potentially link back once we have the update
