### ISSUE TITLE
Apparent B.1.617.2 samples labelled B.1.530

### ISSUE THREAD

**Issue by jeremydratcliff** [cov-lineages/pango-designation#113]
Genomes

hCoV-19/India/GJ-ICMR-NIV-INSACOG-GSEQ-3137/2021
hCoV-19/India/GJ-ICMR-NIV-INSACOG-GSEQ-3045/2021
hCoV-19/India/PY-SEQ_294_S22_R1_001/2021
hCoV-19/Malaysia/IMR_682164/2021
hCoV-19/Japan/IC-1175/2021
hCoV-19/USA/NC-CDC-ASC2100060871/2021
hCoV-19/USA/TX-CDC-ASC210037740/2021
There might be a few more, this was just a cursory glance.

Evidence

All contain the following B.1.617.2 characteristic spike mutations and are circulating in areas with known B.1.617.2:
T19R
L452R
T478K
D614G
P681R
D950N

**Comment by rmcolq** [comment]
This issue is resolved for this specific case by the latest pangolin release, which overwrites the lineage assignation with a scorpio call if it is not a child of it (ie. where there is a conflict the scorpio call is used)

I see that on the tree, these samples seem to be nearby several more which are being assigned different lineages - I think some new mutation(s) is making it harder for them to be placed.

<img width="1153" alt="Screenshot 2021-06-17 at 13 58 54" src="https://user-images.githubusercontent.com/9866043/122401134-3ce92380-cf74-11eb-9d9f-701a6d176430.png">

**Comment by chrisruis** [comment]
Thanks @jeremydratcliff for submitting. As @rmcolq says, it looks like more recent pangolin versions are now assigning these sequences correctly. But to try to help further, we've now also designated these sequences as B.1.617.2 in [v1.2.26](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.26). We couldn't designate hCoV-19/India/GJ-ICMR-NIV-INSACOG-GSEQ-3137/2021 as that has >5% ambiguous nucleotides
