### ISSUE TITLE
Collection of undesignated BA.5.1 diversity

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1135]
- [ ] BA.5.1 + ORF9b:T83I : Germany, Denmark, 4k https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?aaMutations=ORF9b%3AT83I&nextcladePangoLineage=BA.5.1&
- [x] BA.5.1 + ORF7b:H42Y : Mexico, Peru, 3k https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF7b%3AH42Y&nextcladePangoLineage=BA.5.1*&
- [ ] BA.5.1 + ORF3a:D155Y and ORF1b:A2589T : Europe, 3k sequences https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF3a%3AD155Y&nextcladePangoLineage=BA.5.1*&
- [x] BA.5.1 + ORF1b:S1273L : France, Denmark, Germany, 13k https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AS1273L&nextcladePangoLineage=BA.5.1*&
- [x] BA.5.1 + ORF1b:V1271L : 10% in Finland, 6k, https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1b%3AV1271L&nextcladePangoLineage=BA.5.1*&
- [x] BA.5.1 + ORF1a:S302F : 8% in Spain, 11k, https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AS302F&nextcladePangoLineage=BA.5.1*&

**Comment by alurqu** [comment]
I don't know if it will help, but I've just created some CoV-Spectrum collections with all of the pango designation + mutation combinations that I'm seeing in recent GenBank data (with some minimum floors on occurrence).  Due to the size of the total collection, it is split into parts.  The BA.5.1 part is https://cov-spectrum.org/collections/41.  Sorting that collection on number of sequences might help identify large pieces of the BA.5.1 diversity.
