### ISSUE TITLE
BA.2.75.5 with S:490S on ORF1a:G392D branch [14 seqs, Germany, Netherlands]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1149]
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/25161793/193458324-0f32a8eb-97de-49ff-90ce-208eb2e14913.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_11e09_99a170.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T23031C

**Comment by InfrPopGen** [comment]
Thank you for keeping an eye on the tree. As this particular lineage has, since November, been showing signs of a consistent growth disadvantage in all territories where it is commonly detected (except for a slight spurt in Australia a week ago, which did not last), it can be closed, at least for now.
