### ISSUE TITLE
Collection of BL.1 spike diversity

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1167]
Noticed some interesting developments in BL.1 spike:
- [ ] S:L452M, 4 seqs, 1x India, 2x US-NJ, 1x England, `Spike_L452M, Spike_D574V, Spike_R346T`
- [ ] S:F490S, 4 seqs, 1 Germany-BW, 1x USA-WI, 2x India (1x GJ, 1x KA)
- [x] S:F490V, 2 seqs, 2x IND-KA -> BL.1.4
- [x] S:F490L, 2 seqs, 2x IND-KA -> BL.1.3

**Comment by ryhisner** [comment]
Just a singlet right now, but a BL.1 with S:Y489H + N:R41Q popped up in Australia today, collected Sept 24. EPI_ISL_15250307

**Comment by ryhisner** [comment]
There are now six BL.1 sequences with F490V, the two most recent uploads being from New Zealand and France, though the New Zealand one was collected back on August 22. They all also have the synonymous nuc mutations C4456T and T6086C, as well as ORF1b:R1430K, making them easy to search for on CovSpectrum or GISAID. 

GISAID Query: Spike_D574V, Spike_R346T, Spike_F490V, NSP13_R507K
CovSpectrum Query: Nextcladepangolineage:BL.1* & C4456T & T6086C & S:F490V

EPI_ISL_14915906, EPI_ISL_15074319, EPI_ISL_15146721, EPI_ISL_15146833, EPI_ISL_15271203, EPI_ISL_15276423

**Comment by ryhisner** [comment]
S:F490V is now up to seven sequences. There are also now 5 sequences on the S:L452M + ORF1b:R1430K + ORF1a:A138T branch, and the two from New Jersey (USA) also have S:G213A and Spike_ins213VTAVG. 
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/33738461/195450387-2d2dcbe8-f272-4b48-a941-df4c3dffc504.png">

**Comment by ryhisner** [comment]
Here's the S:F490V branch, where I've added the two additional interesting mutations on unlabeled branches. ORF1a:L3829F is most likely the reason BE.1.1 out competed BE.1, and is also a convergent mutation that's independently evolved many times elsewhere. 
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/33738461/195451425-737e25db-8e8e-4a79-834a-83c4e9be5d42.png">

**Comment by ryhisner** [comment]
BL.1 + S:S446T is up to 25 sequence and should perhaps be considered for designation. S446T involves a second nucleotide substitution (G22899C). 
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/33738461/196043428-2e83e974-1433-47e4-be7d-531d35304521.png">

It's difficult to tell how fast this branch is growing because the places it is most common have had long delays between sample collection and GISAID submission dates. There have, however, been eight sequences uploaded to GISAID from October 10-15.

The branch already has a couple interesting twigs extending from it. One, which has two sequences from Karnataka, India, uploaded on Oct 3, has S:G184S and S:S704L. I think S:S704L was an underestimated factor in the success of BA.2.12.1. When BA.2.12.1 arrived in NW Europe but BA.4/5 hadn't yet, there were two lineages of BA.2.12.1—one with S704L and one without it. The lineage with S704L grew fairly quickly while the one without it did not. 

Both long branches in the tree below are bad sequences with reversions and false mutations, so the overall diversity here is lower than it appears. 
Permalink to current Usher tree: https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BL.1%2BS446T-subtreeAuspice1_genome_3689f_c07ab0.json
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/33738461/196042349-b86dea4a-4257-4b0a-b827-b9c4f79bcb93.png">

Also notable is a four-sequence sub-branch from the USA with ORF7a:H47Y and N:S412I. One of the four sequences also has the ORF1b suboptimal sgmRNA mutation ORF1b:R2613S, creating an AAGCGAAC pattern (pictured below), one nucleotide change away from the optimal AAACGAAC. The path to the full, optimal ORF1b sgmRNA pattern with extended homology (which has independently evolved many, many times) involves three nucleotide mutations (as pictured below), so this branch is one-third of the way there. If the lineage survives long enough, there's a good chance it will develop ORF1b:S2613N and possibly ORF1b:P2612L, as many other lineages have done before.
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/33738461/196043012-7ec46fdf-a8e2-48fa-89b0-795b7b6201c9.png">

**Comment by corneliusroemer** [comment]
@ryhisner it would be more helpful if you listed your proposals in a succinct form in a comment near the top, all the details on why something is interesting are nice but I don't have time for that at the moment.

If you emulate the style used by Fede and me with bullets that's much nice, ideally with a Gisaid query, thanks!

**Comment by corneliusroemer** [comment]
@ryhisner I meant something like this:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/25161793/196280056-8bc6fa87-a523-4c83-bad2-3053ed7e0c6f.png">
