### ISSUE TITLE
Potential (XBB or BJ.1) and CJ.1 recombinant (2 seqs, Bangladesh/India, 2022-10-13)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1217]
I've noticed something looking similar to XBB/BJ.1 with a different RBD similar to CJ.1 that is predicted to be very fit by the Bloom immune escape and ACE2 calculator.

Maybe it's real, maybe not, but the RBD is interesting in any case:

These are changes with respect to BA.2:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/25161793/195710595-b43e1398-8456-4e2b-9a2e-0b749e448f15.png">

hCoV-19/Bangladesh/icddrb-G060/2022|EPI_ISL_15157635|2022-09-20
hCoV-19/India/OR-RMRC_B-ICMR-INSACOG-BBS430981/2022|EPI_ISL_15231495|2022-09-17

**Comment by JosetteSchoenma** [comment]
I have been keeping an eye on the one from Bangladesh, ever since I found it on the 28th of August. It is easy to do, because the spike mutations F486P and G252V make it unique. Bangladesh has not uploaded any new samples since.

I do not think the Indian one is related. It misses G252V, plus the rest of the spike that looks like XBB.1.
Usher does not link them and calls the Indian one BA.2.76.
They are far apart in the downsampled tree.
![image](https://user-images.githubusercontent.com/94831035/195773386-28b36c3c-f2cd-4c40-9226-d3c7f5fe8fc7.png)

And here they are, compared to BA.2 in Nextclade. The one from Bangladesh at the top.
![image](https://user-images.githubusercontent.com/94831035/195773605-3a5cf957-c218-4919-addc-8f044a203364.png)

**Comment by corneliusroemer** [comment]
Thanks @JosetteSchoenma - I had totally missed that you had mentioned this one before - at least it shows that we find most things pretty quickly at least twice ;)

**Comment by Mydtlwn** [comment]
How many sequences are there now?

**Comment by FedeGueli** [comment]
> How many sequences are there now?

it reached 11 seqs today all from Aus

**Comment by JosetteSchoenma** [comment]
I still only see the one from Bangladesh with S:F486P and S:G252V.

**Comment by FedeGueli** [comment]
sorry wrong issue

**Comment by FedeGueli** [comment]
> I still only see the one from Bangladesh with S:F486P and S:G252V.

sorry i was commenting #1259  thx for noticing.

**Comment by corneliusroemer** [comment]
I'll close this due to no more sequences. But in the meantime we've had XBF from Australia which has basically the same signature.
