### ISSUE TITLE
BA.1.17.2 with ~28 mutations, only 2 Spike AA substitutions, all mutations C->T or G-> A (2 seq., UK)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1224]
Proposal for a sublineage of BA.1.17.2
Earliest sequence: 03.10.2022 (England)
Countries detected: England (2)

Defining mutations:

nuc	unique	G521T, A1318G, A1856G, C2137T, C2263T, T3256C, G4300A, G5992A, G7360T, T8050C, T8764C, G12569A, C13887T, G14712A, C22082T, T23680C, G23782A, C25685T, G25913A, A26699G, T27682C, C27945T, C29733T
nuc	homoplasies	C186T, C1044T, C3096T, A8040G, C8092T, C19017T, T25557C, C28087T
ORF1ab	unique	V86F, S531G, M2365I, V4102I
ORF1ab	homoplasies	A260V, S944L, D2592G
S	unique	P174S
S	homoplasies	M740I
ORF3a	unique	A98V, G174D
ORF7a	unique	Y97H
ORF8	unique	Q18*
ORF8	homoplasies	A65V

This sublineage of BA.1.17.2 is defined by a total of c.90 mutations compared to root (see above) and was only detected in England so far. The two accessions contain each a number of non-ACTGN characters which hints at possible recombination (if not contamination).

![grafik](https://user-images.githubusercontent.com/102166254/196175451-a5f9d056-7750-4bf8-8045-d7c60a6ed31c.png)
![grafik](https://user-images.githubusercontent.com/102166254/196176017-5363b3e2-855d-48c0-89c6-f739cf55c654.png)

![grafik](https://user-images.githubusercontent.com/102166254/196177323-fb0b49f8-c287-47a0-842d-5e7bb654f43c.png)

A big jump for BA.1 if confirmed.
![grafik](https://user-images.githubusercontent.com/102166254/196177851-d4d2243f-2155-42e1-80be-8ef81fe163b8.png)

EPI_ISL_15385769
EPI_ISL_15385709

**Comment by corneliusroemer** [comment]
Could be chronic? It's got a pretty unexciting Spike, hasn't it?

Almost all mutations are C->T or G->A, I think this means something.

**Comment by ryhisner** [comment]
Thanks for posting about this. I'll add it to my list of candidates for molnupiravir-created sequences as this is another perfect MOV suspect. I've analyzed about a dozen others, and I'm not actively searching for them. I also haven't dedicated that much time to finding them, mainly because personal health issues have severely limited my time in the past 2 weeks. Here's another compelling one I analyzed recently that had 61 private nucleotide mutations. (Note: This one almost certainly got an assist from sotrovimab as it has the classic sotrovimab-induced mutation at S:340.)

The possibility of molnupiravir-created variants is an issue that deserves far more attention than it has gotten, particularly since molnupiravir is an ineffective medication to begin with.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/33738461/196206477-1690aa9b-022f-4c6f-8a41-a54d4c997bdc.png">

**Comment by ryhisner** [comment]
I suspect the non-accounting nucleotides don't mean contamination or recombination but rather polymorphic viral populations, which are not uncommon in chronic cases. I know nothing of the technical details of sequencing, but as I understand it, there's a "call threshold" that has to be met for a nucleotide to be registered, and if there is a mixture of nucleotides at that position such that no single nucleotide reaches the threshold, it's called mixed or non-accounting. This could be due to multiple variants battling for supremacy within the patient, none of which is entirely dominant, or it could be from different viral populations occupying different niches in the patient's body, perhaps in different organs. And perhaps it would not be surprising if molnupiravir mutations, randomly distributed in the genome, resulted in a mixture of nucleotides that are either synonymous or results in unimportant AA changes. 

In this case, the first non-accounting nucleotide (15521) is a common sequencing error (ORF1b:F685) and therefore can be dismissed. The second non-accounting one (18252) is almost certainly synonymous; it's a C at the 3rd nuc of ORF1b:1595, and C-->T is synonymous. C-->A and C-->G result in ORF1b:N1595K, which is a mutation that's only been seen 7 times in mediocre-or-good sequences in the entire pandemic. The others are at 21145, 23699, 25714, 25896, 26337, and 28087, which correspond to AA sites ORF1b:L2560(nuc 1), S:A713(1), ORF3a:L108(1), ORF3a:V168(3), E:L31(3—synonymous), and ORF8:A65. I'm not sure what W, Y, and R refer to in the non-accounting nucleotide list. 
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/33738461/196220083-f70b3569-62fc-4a01-ad0e-fbf72f430319.png">

**Comment by ryhisner** [comment]
Here's my analysis of the further sequence on the tree. It seems hard to explain the existence of such sequences without invoking molnupiravir.
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/33738461/196229139-a9d3d103-3b91-4161-ab7f-3f2c8922229a.png">

**Comment by agamedilab** [comment]
Hi @ryhisner many thanks for your comments! 

Do you think it would be possible to get details about the patients treatment ( e.g from the submitting or originating labs)? I think this would be very valueable for the case.

**Comment by agamedilab** [comment]
@ryhisner hi the link is apparently not work...

https://nextstrain.org/fetchraw.githubusercontent.com/ryhisner/jsons/main/Molnupiravir_BA.1.17.2_31_of_33_Transitions_subtreeAuspice1_genome_b501_d7a050_%40agamedilab_spot.json

**Comment by agamedilab** [comment]
I think i can close this for the time...
