### ISSUE TITLE
Potential BN.1.3 sublineage with T4435C, C3787T, and ORF1a:F3486L (88 good-quality seqs as of 2022-10-31; Europe, Israel, USA, Cambodia)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1257]
There may be a BN.1.3 sublineage with T4435C, C3787T, and ORF1a:F3486L (T10721C; NSP5:F223L) first detected in Portugal.

The defining mutation would be ORF1a:F3486L. There is also a high-frequency post-BN.1 non-synonymous mutation ORF1a:M3627I (G11146T; NSP6:M58I) in the tree from which there may be a sibling lineage marked by ORF1a:H110Y.

As of 2022-10-26, this potential sublineage shows potential high growth comparable to BQ.1.1.6 and has only a slightly lesser number of sequences reported.

As of 2022-10-26, Cov-Spectrum reports 33 BN.1.3+ORF1a:3486L+ORF1a:M3627I+3787T+4435C sequences with good quality control scores (35 overall).
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABN.1.3+%26+ORF1a%3AF3486L+%26+C3787T+%26+T4435C&nextcladeQcOverallScoreTo=29&

As of 2022-10-26, UShER shows all of the good-quality CoV-Spectrum samples are on a single subtree:
![BN 1 3+ORF1a_3486L+3787T+4435C-UShER](https://user-images.githubusercontent.com/88959107/198160601-68817029-5040-4131-bd27-09698df85634.png)

To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2022/10/subtreeAuspice1_genome_cov-spectrum_BN.1.3%2BORF1a_3486L%2B3787T%2B4435C.json?branchLabel=aa%20mutations&c=gt-ORF1ab_3486&label=nuc%20mutations:C26078T

With GISAID lineage definitions as of 2022-10-26, the GISAID query is lineage BN.1 with substitutions NS3_T229I, NSP5_F223L

First GISAID sequence: Portugal 2022-09-16

First GenBank sequence: Virginia, USA 2022-09-29 

Most Recent GenBank sequence: Texas, USA 2022-10-08

Most Recent GISAID sequence: England 2022-10-18

A zip archive of GenBank-formatted and derived metadata and FASTA files plus GenBank and CoV-Spectrum UShER output files for these sequences is available at [Support-BN.1.3+ORF1a_3486L+3787T+4435C.zip](https://github.com/cov-lineages/pango-designation/files/9874539/Support-BN.1.3%2BORF1a_3486L%2B3787T%2B4435C.zip)

A list of GISAID identifiers for the good-quality CoV-Spectrum sequences is in this Cov-Spectrum sequence list file:
[contributors-BN.1.3+ORF1a_3486L+3787T+4435C.csv](https://github.com/cov-lineages/pango-designation/files/9874536/contributors-BN.1.3%2BORF1a_3486L%2B3787T%2B4435C.csv)

**Comment by alurqu** [comment]
GISAID searches may also need to use lineage BA.2.75 with substitutions NS3_T229I, NSP5_F223L

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BN.1.3.1 with 39 newly designated sequences, and 2 updated designations from BN.1.3. Defining mutation T10721C (ORF1a:F3486L) (NSP5:F223L) (following T4435C).

**Comment by FedeGueli** [comment]
Just to highlight how rapidly ORF1a:F3486L is growing as share of total viruses circulating in the last 4 weeks
![Schermata 2022-12-11 alle 09 35 13](https://user-images.githubusercontent.com/87669813/206894064-a0e15fc2-509e-4b01-9ad0-edd38af4b675.png).

Really great catch @alurqu this is not just a lineage but you found a potential very beneficial mutation assuming the other two nuc T4435C, C3787T not doing so much

**Comment by silcn** [comment]
@FedeGueli it doesn't seem clear to me that there's much, if any, advantage over the parental lineages BN.1.3 and BN.1. That last data point of 2.5% from week 48 isn't representative: BN.1.3.1 has reasonably high prevalence in Denmark, and Danish samples are heavily over-represented in week 48 (nearly 40% of all worldwide genomes!) because of their quick sequencing.

**Comment by FedeGueli** [comment]
@silcn weird but true. https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?nextcladePangoLineage=BN.1.3*&nextcladePangoLineage1=BN.1.3.1*&analysisMode=CompareToBaseline&

**Comment by silcn** [comment]
@FedeGueli I'm not doubting that ORF1a mutations can be advantageous! I just don't think the evidence is there for this one. In Denmark you can see a flattening out over the last month or so, suggesting there might have been a bit of a founder effect. Europe and World are skewed by Denmark's over-representation in the most recent weeks so should be avoided. Not much sign of any growth advantage in UK or US.

Don't know what you're getting at with 9866C. The mutation to 9866T appeared to have basically [no effect](https://cov-spectrum.org/explore/South%20Africa/AllSamples/from=2022-01-01&to=2022-03-31/variants?nucMutations=9866C&nextcladePangoLineage=BA.2*&nucMutations1=9866T&nextcladePangoLineage1=BA.2*&analysisMode=CompareToBaseline&) in South Africa where both were prevalent.

**Comment by FedeGueli** [comment]
@silcn  too much time to be a founder effect (even if introduction effect is more evident in countries with small pop and hi frequency intensity if not highlighted in metadata) . Lately world comparison is the best predictor for lineages advantages and way better than Uk, Denmark which should be avoided or if taken in consideration is better to crosschecking with Usa.

**Comment by silcn** [comment]
> Lately world comparison is the best predictor for lineages advantages and way better than Uk, Denmark which should be avoided or if taken in consideration is better to crosschecking with Usa.

The fact that World is usually the best predictor doesn't mean it'll be the best in every specific case. If a large proportion of samples of a given lineage come from one particular country, and that country makes up a higher proportion of worldwide sequencing in recent weeks than previous weeks (e.g. because it sequences very quickly), then that lineage will *automatically* appear to have rising prevalence worldwide, even if it has no growth advantage. 

To take an extreme example, BQ.1.1.20 has 813 sequences worldwide in the last 2 months on cov-spectrum, 810 of which are from Denmark. Its growth advantage over BQ.1.1* is estimated at [25% in Denmark](https://cov-spectrum.org/explore/Denmark/AllSamples/Past2M/variants?nextcladePangoLineage=BQ.1.1*&nextcladePangoLineage1=BQ.1.1.20&analysisMode=CompareToBaseline&). Since there are virtually no sequences from outside Denmark, we shouldn't be able to gain any information about BQ.1.1.20 by looking at a world comparison. But when we move to World, we suddenly find a [73% advantage](https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nextcladePangoLineage=BQ.1.1*&nextcladePangoLineage1=BQ.1.1.20&analysisMode=CompareToBaseline&). The reason is clear: Danish sequences are over-represented in the most recent weeks, and since Denmark is basically the only place where BQ.1.1.20 is found, its worldwide prevalence is artificially inflated.

Something similar is going on with BN.1.3.1, but not as extreme because only 40% of sequences come from Denmark rather than >99%.
