### ISSUE TITLE
BA.5.2.3 x CJ.1 (BM.1.1.1.1) recombinant [AUS-VIC, 9 sequences as of 2022-10-29]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1259]
I've spotted what appears to be a very clean BA.5* x CJ.1 (BM.1.1.1 + S:F486P) recombinant that has been sequenced 9 times in the Australian state of Victoria between October 16 and 19.

While it is only one lab so far all the sequences are identical, so this doesn't appear to be due to contamination/artefact.

The breakpoint seems to be before 9866. The event seems to have happened very recently, maybe 1-2 months ago as there are no private mutations in the 20k bp downstream of 9866.

```

hCoV-19/Australia/VIC73540/2022|EPI_ISL_15532273|2022-10-19
hCoV-19/Australia/VIC73525/2022|EPI_ISL_15532233|2022-10-19
hCoV-19/Australia/VIC73489/2022|EPI_ISL_15532146|2022-10-19
hCoV-19/Australia/VIC73384/2022|EPI_ISL_15531882|2022-10-18
hCoV-19/Australia/VIC73383/2022|EPI_ISL_15531880|2022-10-18
hCoV-19/Australia/VIC73325/2022|EPI_ISL_15531741|2022-10-17
hCoV-19/Australia/VIC73308/2022|EPI_ISL_15531699|2022-10-17
hCoV-19/Australia/VIC73221/2022|EPI_ISL_15531489|2022-10-17
hCoV-19/Australia/VIC73119/2022|EPI_ISL_15471479|2022-10-16
```

<img width="754" alt="image" src="https://user-images.githubusercontent.com/25161793/198753652-7f233ce8-2972-4d6d-9542-8d111d2b2b51.png">
<img width="2528" alt="image" src="https://user-images.githubusercontent.com/25161793/198753648-05079a51-d023-4566-a633-241e93afbfe0.png">

**Comment by c19850727** [comment]
Cornelius it's interesting that there are multiple clusters of recombinant now where the 5' part of ORF1a in BA.2.75.2 is swapped. 

I have a few others under monitoring. Might be worth proposing?

**Comment by FedeGueli** [comment]
@c19850727 with or without Orf6 mutated? 
Rhe thing here is that we have a BA.2.75 that should not be attenuated by that

**Comment by FedeGueli** [comment]
NSP1_K120N,Spike_F486P,E_T11A Gisaid Query seems accurate and finds 10 sequences all from Victoria.

**Comment by FedeGueli** [comment]
11 sequences as today with NSP1_K120N,Spike_F486P,E_T11A

**Comment by corneliusroemer** [comment]
Resolved by 366f80e

I decided to designate because of the high predicted immune escape and ACE2 binding, combined with detection in two different labs.

**Comment by FedeGueli** [comment]
Already 23 sequences @corneliusroemer @thomasppeacock certainly one to be flagged to authorities.

**Comment by FedeGueli** [comment]
@corneliusroemer jumped to 90. i think something is going on i Australia today big jumps for CJ.1 XBF anf Xbc.1 there beyond BR.2.1

**Comment by corneliusroemer** [comment]
@c19850727 @AngieHinrichs 
Looking at the Usher tree, I noticed that XBF starts with G625T, but there are lots of sequences that just lack this one mutation.

The profile is very non-Australian, though. Do we think these are independent recombinants? With something that's not BA.5.2.3? G625T has been observed before, it's possible it's beneficial.

There are actually lots of Australian XBF (?) that just lack this mutation. So it could be that it was acquired independently.

Right now you classify all these as BM.1.1.1 which seems wrong - as they have BA.5 profile up to 20k and are CJ.1 below.

<img width="1974" alt="image" src="https://user-images.githubusercontent.com/25161793/218220454-9ab392a7-4b0f-4e3f-a04e-7b396eb075dd.png">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_169b2_6cd3e0.json?branchLabel=Spike%20mutations&label=id:node_8248977&showBranchLabels=all

**Comment by AngieHinrichs** [comment]
When XBF was designated, the final node in the UShER tree at the time had four mutations: G625T, T3339C, C6070T, and C8692T -- i.e. sequences either had all four of those past XBK, or none of them..  Since then, many sequences have been added and there are now four nodes C6070T > C8692T > T3339C > G625T.  It looks like a good case for removing G625T as a requirement since there are now a lot of sequences that have T3339C, C6070T, and C8692T and not G625T.

> Right now you classify all these as BM.1.1.1 which seems wrong - as they have BA.5 profile up to 20k and are CJ.1 below.

This is what the neighborhood looks like in taxonium, colored by nt:261 (pink=G, red=A):
<img width="558" alt="image" src="https://user-images.githubusercontent.com/186983/218237959-501f0686-0dbc-4dc5-870c-2522ac77e0bf.png">

-- CJ.1 is BM.1.1.1 > G261A > T23018C (S:S486P).  XBF does not have G261A, so it's not placed on CJ.1.   XBK and XBF are on a different branch of BM.1.1.1 with C1627T > T23018C.

Moving the XBF label back so that G625T is not required will take care of most sequences on BM.1.1.1 > C1627T > T23018C  that are neither XBK nor XBF.  There are ~100 on BM.1.1.1 > C1627T > T23018C > G14829T (ORF1b:M454I) that would be called BM.1.1.1 despite being more like miscBA.5.2_CJ.1 (e.g. Japan/TKYhug10808/2022).  If it really bothers you I can add a misc label.  :)

BA.5.2.3 has not only G625T, but also G2305A, and XBF does not have G2305A, so are we really sure XBF is from BA.5.2.3 not just BA.5.2?

**Comment by FedeGueli** [comment]
@AngieHinrichs i proposed the orf1b:M454I in
https://github.com/cov-lineages/pango-designation/issues/1440

we closed it cause it wasnt clear if it was just XBK

**Comment by AngieHinrichs** [comment]
OK, I will move the XBF label back so it includes the sequences that don't have G625T(ORF1a:K120N).  And I will add a label miscBA.5.2CJ.1 at BM.1.1.1 > C1627T > T23018C so (at least in the web interface) the sequences outside of XBK and XBF won't be called BM.1.1.1.  (After the next data release, pangolin will probably call them CJ.1.)
