### ISSUE TITLE
Sublineage of BM.2 with 8 additional spike mutations (9 seq, Australia)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#1286]
**Description**
Sub-lineage of: BM.2
Earliest sequence: 2022-9-11, Australia, Australian Capital Territory — EPI_ISL_15477002
Most recent sequence: 2022-9-23, Australia, Australian Capital Territory – EPI_ISL_15477133
Countries circulating: Australia (9)
Number of Sequences: 9
GISAID Query: Spike_D111N,Spike_D574N
CovSpectrum Query: S:111N,S:574N

**Substitutions on top of BM.2**
Spike: D111N, S151N, V289I, T549I, D574N, A701V, L841F, V1230M
ORF1a: R184H, A354T, L397F, L454F, V1287M, C2165Y, T2823I, G2868S, V3261I, Q3332R, A3610V
ORF1b: V464I, V666I, A1291V, T1697K
ORF3a: A143V, E181K, P267L
ORF6: H3Y
ORF8:V81I
Nucleotide: C50-, G816A, A895G, G1325A, C1454T, C1549T, C1625T, A2410G, G4124A, C5192T, G6759A, C6968T, C8733T, G8867A, G10046A, A10260G, G10318A, C10369T, C11094T, C11224T, C14184T, G14857A, G15463A, C17339T, C18557A, G18612A, C19386T, G21893A, G22014A, G22427A, C23208T, G23282A, C23664T, G23749A, C24083T, G25250A, C25710T, C25820T, C25854T, G25933A, C26192T, C27208T, A27989G, G28134A, G29692A

**USHER Tree**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_22c20_12d910.json?label=nuc%20mutations:A27989G,G28134A

![image](https://user-images.githubusercontent.com/94097102/199620837-a0c782e6-a535-4105-8532-2b734ea57303.png)

 
**Evidence**: 
Although all of the genomes for the proposed variant were de-identified and submitted by one group (Schwessinger Lab, Australian National University), they have confirmed that all 9 sequences are from unique patients. The “Collection Date” on GISAID is actually when the lab received the sequences, but 9/11 is the accurate first collection date, and 9/23 is the accurate last collection date. Additionally, they have re-sequenced two of these samples and found no disagreements when sequencing was repeated. The lab is planning to re-run the rest of the samples to further confirm the sequences. Public health have been notified and are investigating if there are epidemiological links between these patients. This issue will be updated as more info comes in from those investigations.
 
I believe the USHER phylogeny found the correct ancestral sequences to the proposed lineage. From the screenshot, the branch with ORF3a:143V contains 3 unique NT mutations, all of which are in the proposed lineage. There are only 6 sequences that have been uploaded to GISAID with that set of mutations, aside from the ones being proposed. The next mutation in the tree, ORF1ab:T6098K also remains in the proposed lineage, and there are no reversions on the long branch. This implies that from approximately 8/29 to 9/11, the genome accumulated 35 NT (24 AA) mutations. The Schwessinger lab have confirmed that no closer ancestral sequences have been recovered, even when including sequences not yet publicly available. SARS-CoV-2 sequencing rates in the ACT during September (when these samples were collected) ranged from 8-14% of all notified cases (PCR- and RAT-based diagnosis); thus, if intermediary sequences were present in the population there is a high probability that at least some would have been sequenced.
Beyond the remarkable speed with which these mutations appeared, they are not at all the convergent mutations we have been seeing in recent saltations. I believe that @ryhisner has a plausible explanation for this. “Molnupiravir works by preferentially causing transition mutations, especially C->T and G->A mutations. 41/42 nuc mutations here are transitions, and 37/42 are C->T or G->A.” Molnupiravir can be prescribed in the ACT, so this is a possibility. 

To my knowledge, this is the most divergent BA.2-derived non-recombinant variant to have been observed in multiple patients so far. If Molnupiravir selection has contributed to the emergence of these mutations, then I’d expect this will not be a very fit variant, but it is still notable that it has been found in 9 different patients so far. Hopefully the epidemiological tracing will be able to answer if this proposed lineage is likely to be transmitting in a wider community setting. 

**Genomes**: EPI_ISL_15477002, EPI_ISL_15477006, EPI_ISL_15477080, EPI_ISL_15477087, EPI_ISL_15477167, EPI_ISL_15477089, EPI_ISL_15477133, EPI_ISL_15477122, EPI_ISL_15477123

**Comment by ryhisner** [comment]
Below is the molnupiravir analysis I've done for one of the sequences in this branch. As @Sinickle described above, molnupiravir functions by causing transition mutations (C->T, T->C, A->G, G->A) at random locations throughout the viral genome. It increases C->T and G->A mutations more than any others. This lineage looks to me like a perfect candidate for being a molnupiravir creation, not only because of the absurdly high Transition/Transversion ratio (Ts/Tv), but also because of the seemingly random distribution of mutations and the unusually high percentage of synonymous nucleotide mutations. I list the G->A mutations because they can't be explained by an overactive APOBEC response, and it's notably the G->A mutations that are most overrepresented here.

The "expected" numbers listed below are from the analysis of SARS-CoV-2 mutations by Richard Neher here: https://github.com/neherlab/SC2_variant_rates/blob/master/data/mutation_rates.tsv

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/33738461/199749617-5c992489-57c4-4a44-9649-c34c424fddaf.png">

**Comment by robynhall** [comment]
We have just re-sequenced all of these samples (same RNA extracts, fresh cDNA synthesis/PCR/library prep/sequencing) and can confirm that these are not sequencing errors. All sequences match their initial sample.

**Comment by FedeGueli** [comment]
@ryhisner @Sinickle on twitter an account pointed to another explanation of this kind of pattern for nuc mutations, linking that to bats : https://twitter.com/olireiv/status/1589090018228076544?s=20&t=gUMNaj5LPI65SeSzuFCeZQ

**Comment by shay671** [comment]
This is a combination of samples from reliable sources with data that seems unrealistic. 
I see 31 novel SNPs (~71% NS) + 9 SNPs in the mediator branch ( ~44% NS). 
The metadata is of 9 unique patients meaning the first patient was probably first infected sometime before 9/11.
Even if we take a theoretical assumption that the mediator branch is not real, it would mean that we got 40 mutations over ~2 months (since BM.2 started rising) in a chronic case. Also not that realistic. 
It takes time for such saltation to be formed. Even if there was an extreme bottleneck created by some treatment making this variant the dominating in the body of that chronic patient, it means that this patient had some time in his infection with very minimal viral load, meaning being able to infect only afterward. 

The last time I saw such unrealistic data was when @thomasppeacock sent me three seq he noticed to have some weird saltation, which was the first 3 BA.1's. And then, of course, I told it to him - Probably a technical problem; no way such a thing is real.

**Comment by Sinickle** [comment]
@shay671 That is part of why I agree that Ryan's explanation of MOV is likely accurate. It isn't reasonable for this many mutations to have appeared so quickly with the normal mutational rate. 

@FedeGueli The mutations that accumulated on this are much more than you'd expect just from a prolonged infection though. Unless bats can induce mutations at a rapid rate, I don't think that would make sense as an explanation.

**Comment by shay671** [comment]
@Sinickle I was talking about the process through a chronic patient, of course. Even then, it's very unlikely.

**Comment by InfrPopGen** [comment]
Thank you for highlighting this sub-lineage. As it has not shown growth over the last two months, and appears to relate to a local event, this issue is being closed  for now.
