### ISSUE TITLE
Sublineage of BA.5.1 + NSP2_G265D (6 sequences)

### ISSUE THREAD

**Issue by VirologiaHUCA** [cov-lineages/pango-designation#1297]
By VirologiaHUCA
Description
Sub-lineage of: BA.5.1
Earliest sequence: 2022-09-05
Most recent sequence: 2022-09-27
Countries circulating: Spain (6 Asturias) 
Written description
In BA.5.1 variants, this clade gained the NSP2:G265D mutation.
Genomes
EPI_ISL_15022757, EPI_ISL_15022787, EPI_ISL_15252628, EPI_ISL_15287440, EPI_ISL_15349351, EPI_ISL_15349358

Evidence
![image](https://user-images.githubusercontent.com/105294581/200318454-9e9eaca9-c6cb-4c09-a86c-5a5c5b0206c4.png)

**Comment by InfrPopGen** [comment]
Assuming that this is really defined as BA.5.1 + ORF1a:G445D, ORF8:P38L, then this clade (currently 12 sequences) has not been detected over the past two months, and although it showed slight promise in November, it has since declined. Consequently, this can be closed for now. Please re-propose (with the defining mutations) or request reopening should this lineage show a future surge of growth.
