### ISSUE TITLE
BA.4.6.4 sublineage with S:W152R, S:G252S plus 10 aa mutations (6 seq. Australia)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1334]
Proposal for a sublineage of BA.4.6.4
Earliest sequence: 28.09.22 (Australia)
Countries detected: Australia(6)

Defining mutations:

nuc	unique	G2393A, A4501G, C4893T, G5329A, C6593T, G10255A, C13247T, C14325T, C15752T, G18851A, T19135C, T22016C, G25429A, G25993A, G27214A, G29579A
nuc	homoplasies	G6344A, C18120T, C19560T, G22316A
ORF1ab	unique	V710I, T1543I, P2110S, A5163V, S6196N
ORF1ab	homoplasies	V2027I
S	homoplasies	W152R, G252S
ORF3a	unique	V13I, V201I
ORF6	unique	V5I
ORF10	unique	A8T

GISAID query: Spike_W152R, Spike_G252S

This subvariant is defined by S:W152R, S:G252S plus 10 aa mutations (see above) and was only detected Australia so far (3 uploads from 2 different labs). The group sits on a branch also defined by E:I9T, N:A217T.

![grafik](https://user-images.githubusercontent.com/102166254/201605939-d0ae9f79-4229-40c0-9821-3d2b5aaacd1d.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3ce98_1f00a0.json?c=pango_lineage_usher

EPI_ISL_15756004
EPI_ISL_15755997
EPI_ISL_15357186
EPI_ISL_15471118
EPI_ISL_15756044
EPI_ISL_15357173

**Comment by ryhisner** [comment]
I'm going to have to wait until I get home from school today to do a full analysis, but this looks like yet another perfect candidate for a molnupiravir creation. Counting both branches, there are 22 nucleotide mutations. They are 100% transitions. Furthermore, by far the most overrepresented mutation is G-->A, which is caused by molnupiravir but not APOBEC (to my knowledge). It looks like on the same tree there are even more molnupiravir candidates, again from Australia. This needs to be investigated. 
![image](https://user-images.githubusercontent.com/33738461/201666696-0ddcfe67-b46d-495a-a117-512c4fc9b5c0.png)

**Comment by FedeGueli** [comment]
7 viruses last collected on November 7th , reflecting the usual size of this sublineage likely related to Molnupiravir use.

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there has been no new detection of this over the past two months, this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.
