### ISSUE TITLE
B.1.351-ish with L452R+T478K, but without E484K+N501Y, in Botswana and RSA

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#134]
Hi there,

I was browsing through the Beta variants in Botswana on Nextstrain today, and came across a few strange ones that are different from the usual B.1.351 that I know of.

In those ones, E484K, N501Y (and sometimes DEL241/243) are missing, replaced by L452R and T478K，which, together with K417N from the original Beta variant, looks strikingly similar to AY.1 and AY.2 that are causing a lot of trouble in various parts of the world.

It seems there are more than 20 of them in Botswana (out of only a few hundred sequences), and additional handful in RSA, such as:

EPI ISL 2372283
EPI ISL 2386152 (classified as B.1.617.2)
EPI ISL 2386153
EPI ISL 2386154
EPI ISL 2386155
EPI ISL 2386156 (earliest sequence, 2021-03-18)
EPI ISL 2386157
EPI ISL 2566205
EPI ISL 2566206
EPI ISL 2566207
EPI ISL 2566208
EPI ISL 2566209
EPI ISL 2648194 (K417N is missing)
EPI ISL 2648196 (K417N is missing)
EPI ISL 2648198 (K417N is missing)
EPI ISL 2648199 (classified as B.1)
EPI ISL 2648202 (K417N is missing)
EPI ISL 2648204 (K417N is missing)
EPI ISL 2648207 (K417N is missing)
EPI ISL 2648208 
EPI ISL 2648217 (K417N is missing)
EPI ISL 2648218
EPI ISL 2648219 (K417N is missing)
EPI ISL 2648220 (K417N is missing)
EPI ISL 2648229 (classified as B.1)
EPI ISL 2648230 (with L18F mutation)
EPI ISL 2648234 (K417N is missing)
EPI ISL 2648238 (classified as B.1)
EPI ISL 2648240 (K417N is missing)
EPI ISL 2695769
EPI ISL 2710322 (with L18F mutation)

![image](https://user-images.githubusercontent.com/86835836/124286288-5cda3300-db81-11eb-8079-f26b437f300a.png)

C.

**Comment by chrisruis** [comment]
Thanks @c19850727 for submitting. It looks like this clade is most likely a subclade within B.1.351. We've therefore designated this as lineage B.1.351.4 in [v1.2.36](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.36)

We've done a bit of filtering to get the set of designated sequences. We need all designated sequences to have <5% ambiguous nucleotide positions so a few were taken out with that. Sample South_Africa/KRISP-K018720/2021 potentially clusters away from this clade so might have acquired L452R and T478K independently. We therefore haven't included this one in the designations for B.1.351.4.

Also sequences South_Africa/NICD-N8499/2021 and Botswana/R18B16_BHP_AAB59607/2021 have N's at positions 22917 and 22995, the positions responsible for L452R and T478K, respectively. To try to give this clade a strong signal we've excluded these 2 from the designations as well.

So that leaves us with these 17 sequences that have been designated B.1.351.4:
Botswana/R14B14_BHP_AAB25910/2021, Botswana/R18B32_BHP_AAB60589/2021, Botswana/R18B21_BHP_AAB60600/2021, Botswana/R18B33_BHP_AAB60588/2021, Botswana/R14B12_BHP_AAB25823/2021, Botswana/R14B5_BHP_AAB37957/2021, Botswana/R14B21_BHP_CV2708372/2021, Botswana/R14B25_BHP_b59_121047451/2021, Botswana/R14B24_BHP_b58_121047443/2021, Botswana/R18B45_BHP_AAB65796/2021, Botswana/R18B6_BHP_CV2405450/2021, Botswana/R18B12_BHP_AAB64667/2021, Botswana/R18B20_BHP_AAB60601/2021, Botswana/R14B4_BHP_AAB39488/2021, Botswana/R18B31_BHP_AAB60590/2021, Botswana/R18B43_BHP_AAB65798/2021 and Botswana/R18B49_BHP_AAB65786/2021

Thanks again for submitting

**Comment by babarlelephant** [comment]
@chrisruis A small lineage originating in Africa having 142D,452R,478K,681H

(Usher tree)
https://nextstrain.org/community/babarlelephant/cov/subtreeAuspice1/genome/5556b/acca20?c=gt-S_142,452,478,681

**Comment by grovesn** [comment]
I've taken a look at these sequences and I think there is evidence that they are Beta sequences contaminated with Delta.

If you look at the mutations present in the sequences, there are Delta mutations (purple boxes) other than 478K/452R that appear in 1 or 2 sequences and some of the Beta mutations (red boxes) look to be either wild type or missing.

![Slide2](https://user-images.githubusercontent.com/15730790/125491623-e2ad1dc0-dda0-4f8e-9186-7494a7a0cbad.jpg)

The most consistent Beta mutation seen in these sequences (D80A) is in a tile that is not amplified in Delta sequences because of a deletion in the right primer for amplicon 72, also supporting the contamination hypothesis. Similarly, if you look at where the mutation replacement has happened (i.e. 484K/501Y replaced by 478K/452R), it lines up with a specific amplicon (76) which is often missing in sequences. 

![Slide3](https://user-images.githubusercontent.com/15730790/125492222-dfd82390-b00c-4de8-8c0b-ea724ca9402b.jpg)

**Comment by chrisruis** [comment]
Thanks @grovesn for this! We agree that this looks like good evidence of potential contamination which nicely explains why these sequences are often missing B.1.351 SNPs. We've therefore withdrawn lineage B.1.351.4 from [v1.2.38](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.38)

**Comment by c19850727** [comment]
It seems that there are a couple of similar gnomes outside of Botswana, such as:

hCoV-19/Qatar/QA.QU_18.16.D9/2021
hCoV-19/South Africa/KRISP-K018720/2021
