### ISSUE TITLE
BQ.1.1 with Orf1a:ins141EGE after Orf1a:141-143del (>70 seq. United States, Chile)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1353]
Orf1a:141-143del (the same deletion as BA.4) seems to happen quite often recently. There's already >300 sequences of BQ.1.1 with Orf1a:141-143del (the US has the most). This sublineage is more interesting because it seems that an insertion of EGE happened after that deletion. This is not the only time that an insertion happened after Orf1a:141-143del, but this one seems to be the most successful one so far.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BE*%26Orf1a%3A141E%26Orf1a%3A143E&

**Comment by oobb45729** [comment]
>70 sequence now, newly found in UK and Germany.

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there has been little growth advantage over the parent, and this has declined since November (now negative in US and Chile), this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked "improvements" in the future.
