### ISSUE TITLE
Proposal of a new lineage: Proposed new lineage with Spike mutations L18F, del67-69, G257S, E484K, F490S, N501T, T859N

### ISSUE THREAD

**Issue by insapathogenomics** [cov-lineages/pango-designation#136]
By: Bioinformatics Unit, National Institute of Health Dr Ricardo Jorge (INSA), Portugal

**Description**
Sub-lineage of: B.1
Clade: 20C
Country: Portugal
Earliest sequence: 2021-04-16
Most recent sequence: 2021-06-11

In Portugal, we have been detecting a few introductions of SARS-CoV-2 with this genetic profile, containing a specific set of mutations of interest in protein Spike (see below). The considerable genetic diversity within this cluster suggests some degree of virus expansion in the geographical regions of origin.

**Defining mutations in Spike:**
L18F
del67-69
G257S
E484K
F490S
N501T
T859N

**Genomes**

Sample Id	GISAID Id	Sampling date	Location
Portugal/PT6380/2021	EPI_ISL_1854260	2021-04-19	Portugal
Portugal/PT6388/2021	EPI_ISL_1854261	2021-04-16	Portugal
Portugal/PT7242/2021	EPI_ISL_2248824	2021-05-10	Portugal
Portugal/PT7246/2021	EPI_ISL_2248828	2021-05-08	Portugal
Portugal/PT7424/2021	EPI_ISL_2249006	2021-05-04	Portugal
Portugal/PT7432/2021	EPI_ISL_2249014	2021-04-28	Portugal
Portugal/PT7952/2021	EPI_ISL_2340263	2021-05-04	Portugal
Portugal/PT7597/2021	EPI_ISL_2249180	2021-04-29	Portugal
Portugal/PT8391/2021	EPI_ISL_2445965	2021-05-13	Portugal
Portugal/PT8731/2021	EPI_ISL_2628956	2021-06-06	Portugal
Portugal/PT8732/2021	EPI_ISL_2628957	2021-06-06	Portugal
Portugal/PT9258/2021	EPI_ISL_2695118	2021-06-11	Portugal

**Evidence**

![new_lineage](https://user-images.githubusercontent.com/87025402/124636836-e723df00-de80-11eb-9cda-01f43a22a41a.png)

**Comment by chrisruis** [comment]
Thanks @insapathogenomics for submitting. I think this is the same clade that was designated B.1.626 in #118. Sorry, pangoLEARN hasn't been updated since B.1.626 was added so I think pangolin is still assigning these sequences as B.1. There should be a new pangoLEARN run in the next few days that will hopefully result in these sequences being assigned to B.1.626.

This clade also includes sequences from a few other countries, this is it in the latest UShER tree:
![image](https://user-images.githubusercontent.com/47785131/124915156-22d9b880-dfe9-11eb-8907-cd613a32e666.png)

We've added in the remaining sequences from this clade to the designations as B.1.626 so there are currently 55 designated sequences in this lineage
