### ISSUE TITLE
XBB.2 sublineage with S:L452R (10 seq, Peru)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1381]
Proposal for a sublineage of XBB.2
Earliest seq: 2022-11-05
Countries detected: Peru (10 seq, all from Lima)

Defining mutations:
C5144T, then T5731A, then S:L452R

GISAID query: Spike_D253G, Spike_V445P, Spike_L452R and nucleotide mutation T5731A

This looks to be the first notable XBB* lineage that has picked up S:L452R. The latest Peruvian upload had a lot of XBB.2 and most of those have the two silent mutations C5144T and T5731A (this may be the branch that @Vjimenez-vasquez was referring to in his comment on #1379). This lineage makes up about 10% of those XBB.2 sequences, and 2% of November sequences from Lima. These recent Peruvian XBB.2 sequences are not yet in the Usher tree - only the ones with L452R that I uploaded appear in the tree below.

<img width="733" alt="Peru_XBB2_L452R" src="https://user-images.githubusercontent.com/42699509/204679436-8cd22e25-2352-4a0c-b3c7-8ad4d7097d75.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_a7e3_6a3d60.json?c=gt-S_452&label=id:node_7464690](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_a7e3_6a3d60.json?c=gt-S_452&label=id:node_7464690)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A452R&nucMutations=T5731A&nextcladePangoLineage=XBB.2*&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A452R&nucMutations=T5731A&nextcladePangoLineage=XBB.2*&)

Samples:
EPI_ISL_15934106
EPI_ISL_15934168
EPI_ISL_15934169
EPI_ISL_15934173
EPI_ISL_15934176
EPI_ISL_15934224
EPI_ISL_15934226
EPI_ISL_15934227
EPI_ISL_15934232
EPI_ISL_15934243

**Comment by Vjimenez-vasquez** [comment]
Hi Everyone, 

I am sharing the phylogenetic reconstruction I referenced some days ago in #1379. As @silcn identified, this is a monophyletic group and seems to be appeared in Switzerland and finally spreaded to Peru. 

## Countries: 
France(5), India(2), Indonesia(1), Canada(1), Germany(1), Switzerland(1), Peru (10). 

## Codes : 
EPI_ISL_15384450
EPI_ISL_15433928
EPI_ISL_15709418
EPI_ISL_15636357
EPI_ISL_15527614
EPI_ISL_15527615
EPI_ISL_15527616
EPI_ISL_15629724
EPI_ISL_15854828
EPI_ISL_15854840
EPI_ISL_15684706

## Evidence: 
![propuesta](https://user-images.githubusercontent.com/89874227/205079656-ce35502a-5093-48e4-ac7a-32e17ef70cd2.jpg)

**Comment by Vjimenez-vasquez** [comment]
Hi Everyone, 

I am sharing the phylogenetic reconstruction I referenced some days ago in #1379. As @silcn identified, this is a monophyletic group and seems to be appeared in Switzerland and finally spreaded to Peru. 

## Countries: 
France(5), India(2), Indonesia(1), Canada(1), Germany(1), Switzerland(1), Peru (10). 

## Codes : 
EPI_ISL_15384450
EPI_ISL_15433928
EPI_ISL_15709418
EPI_ISL_15636357
EPI_ISL_15527614
EPI_ISL_15527615
EPI_ISL_15527616
EPI_ISL_15629724
EPI_ISL_15854828
EPI_ISL_15854840
EPI_ISL_15684706

## Evidence: 
![propuesta](https://user-images.githubusercontent.com/89874227/205079656-ce35502a-5093-48e4-ac7a-32e17ef70cd2.jpg)

**Comment by corneliusroemer** [comment]
Ok let's wait and see if this pops up outside of Peru - thanks @Vjimenez-vasquez for your continued sequencing work!

**Comment by Vjimenez-vasquez** [comment]
Hello @corneliusroemer and @silcn. We are following the spread of this XBB.2 sub-lineage containing mutations C5144T and T5731A in Peru and has recently exported to USA. Please I would appreciate your consideration. 

## nextstrain tree:
![tree](https://user-images.githubusercontent.com/89874227/206305714-2d983f5c-c9d1-49b6-bf69-56241f014b19.png)

## countries:
![countries](https://user-images.githubusercontent.com/89874227/206305734-0d270edc-cec3-4179-b76b-a9bd42d05f0b.png)

## metadata:
[clade_metadata.zip](https://github.com/cov-lineages/pango-designation/files/10180372/clade_metadata.zip)

## EPI codes:
[EPIS.txt](https://github.com/cov-lineages/pango-designation/files/10180385/EPIS.txt)

**Comment by corneliusroemer** [comment]
To me it looks like the 10 samples are from a single run. 

And there are signs of contamination: about half of the samples have a reversion, the other half have ambiguity at 22786.

Do you know which pipeline is used to prepare consensus sequences for this lab: `hCoV-19/Peru/LIM-INS-33578/2022`?

We haven't seen a 452R since the submission of this bunch so I'm skeptical for now:
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/25161793/206309178-0f45229b-1732-47b8-ae81-f6388a8ef481.png">

**Comment by silcn** [comment]
@Vjimenez-vasquez I did not propose the parent lineage with C5144T and T5731A because these are both silent mutations and so, as I understand it, the lineage is not eligible for its own Pango designation.

@corneliusroemer good spot, the lack of subsequent samples with L452R raises the possibility that this is an artefact. Certainly L452R could appear as a result of contamination. The only question I have is why there would be ambiguity at S:408 - what lineage without S:R408S is being sequenced?

**Comment by corneliusroemer** [comment]
> The only question I have is why there would be ambiguity at S:408 - what lineage without S:R408S is being sequenced?

Great point @silcn! Rather than showing contamination, 408 reversion/ambiguity instead seems to be indicative of general bioinfo issues. You're right that it's the other type of error: it says a mutation is absent that should be there, rather than the opposite, a mutation being indicated that shouldn't be there.

If you look at covSpectrum, it's quite fascinating how the proportion of S:408 wildtype varies between countries but is steady over 6 months -> this shows us countries with labs with false negative/reversion to reference problems.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/25161793/206632885-3b65f179-a1a7-4fa9-9f75-98cffa2a91f3.png">

**Comment by jamesmerrett** [comment]
We perform wastewater variant surveillance using short-read amplicon sequencing of the Spike gene and can distinguish XBB based on the presence of N460K, S477N, T478K, E484A, F486S, F490S, Q498R and N501Y. We have been observing XBB + L452R in wastewater sampled from Melbourne, Australia at a low % abundance for several weeks now. Wondering if anyone else has come across this variant and whether we should consider designating an XBB sub-lineage?

![XBB+L452R](https://user-images.githubusercontent.com/121136636/208796880-a176ba79-a3b0-4075-8448-eb766ce8c8a5.png)

**Comment by Wytamma** [comment]
We have one clinical XBB with L452R (EPI_ISL_15357963) collected 2022-10-06.

**Comment by jamesmerrett** [comment]
Thanks @Wytamma, that aligns temporally with our first detection. Is it possible to designate an XBB sub-lineage @corneliusroemer? On a separate note we've also been detecting an increased prevalence and abundance of XBF + L452R across our wastewater samples. Have you come across any clinical XBF samples with L452R lately?

![XBF+L452R_2](https://user-images.githubusercontent.com/121136636/208799308-3eaf62e2-c5a9-497f-923b-771d50253b89.png)

**Comment by Wytamma** [comment]
@jamesmerrett no XBF with L452R but I'll keep an eye on it.

**Comment by corneliusroemer** [comment]
Thanks @jamesmerrett for the heads-up! Now @DrYak can have a look whether they have spotted something similar in Swiss waste water. With less and less testing, waste water haplotype surveillance is increasingly interesting. Would be cool if there was a data sharing platform for waste water reads that could be searched with an interface similar to covSpectrum.

When looking at your contig plot, I notice that 452 is right at the 5' end, is that position reliably called or could the 452R be an artefact?

Since XBF = CJ.1 in that stretch, @Wytamma should also look for CJ.1 with 452R ;) 

The 2 Australian-NSW XBB with 452R don't look particularly clean, either contamination or recombination, but non-identical and multiple breakpoints make contam more likely in my eyes.

We can't designate without having a few good complete or nearly complete sequences.

**Comment by jamesmerrett** [comment]
Thanks @corneliusroemer, the contigs that are displayed have been trimmed and subjected to stringent quality filtering so we are confident that L452R is being reliably called. Furthermore, we have been observing an increase in both prevalence and abundance of these reads across wastewater samples for several weeks now. 

Good point. @Wytamma I should also point out that XBF = XBB.1.5 in this stretch also. We do not believe CJ.1 is circulating in Victoria as we performed WGS on selected wastewater samples which confirmed that the XBF signals detected using our short-read sequencing are indeed XBF and XBB.1.5; CJ.1 was not detected. This is consistent with the clinical samples that have been sequenced in Victoria.

**Comment by carlottaolivero** [comment]
It would be really interesting a data sharing platform for wastewater reads with an interface similar to covSpectrum!

**Comment by FedeGueli** [comment]
@corneliusroemer could be XBK too.

**Comment by silcn** [comment]
Closing as there haven't been any more sequences of this - quite possibly was an artefact
