### ISSUE TITLE
CJ.1 sublineage with S:V445A 12 seqs Malaysia, Japan , Singapore

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1384]
Here i want to propose a new sublineage of CJ.1 with S:V445A it si just 4 sequences but from 3 states (Malaysia 2 , Japan 1, Singapore 1)

S**equences**: 
EPI_ISL_15788621, EPI_ISL_15952829, EPI_ISL_15954672,
EPI_ISL_15955279

**Defining mutations:**
CJ.1 + ORF1a:T1581A (A5006G) then S:V445A( T22896C )

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_e5fb_7e0780.json?c=userOrOld&label=id:node_7617771
<img width="1163" alt="Schermata 2022-12-01 alle 00 19 55" src="https://user-images.githubusercontent.com/87669813/204928912-ecfeec4e-345b-4cc2-82a6-cf9725bd2832.png">

Gisaid Query : Spike_V445A,Spike_F486P,NSP14_V182I,NSP3_S403L

**Comment by Sinickle** [comment]
To me the proposed sublineage is very interesting since it is one of the few BA.2.75* sublineages to acquire 4 convergent RBD mutations already. S:346T, S:445A, S:486P, S:490S. 

I think this proposed sublineage would also be the BA.2.75 most similar to XBB.1.5's RBD

Starting with S:339, they share these RBD mutations that differ from BA.2 

1. S:339H
2. S:346T
3. S:446S
4. S:460K
5. S:486P
6. S:490S
7. S:493Q

They differ in that 
1. XBB has S:368I
2. XBB has S:445P, whereas the proposed sublineage has S:445A

However, S:445P is a 2 nucleotide mutation -- so, S:445A could be seen as the first step to acquiring S:445P. 
So, I think that this proposed lineage is getting very close to recreating XBB's RBD via incremental evolution through community spread, which would mean that the recombination event that created XBB's RBD did not actually move it onto an otherwise unattainable fitness landscape (at least for the RBD itself)

**Comment by FedeGueli** [comment]
One more sequence today from Japan

**Comment by FedeGueli** [comment]
New uploads from Singapore and Japan : it reached 12 sequences as today. @corneliusroemer i suggest to designate this one.

**Comment by FedeGueli** [comment]
@corneliusroemer @InfrPopGen @thomasppeacock @AngieHinrichs it seems quite fast doubling every 7 days. worth flagging it .
