### ISSUE TITLE
BQ.1.1 with additional mutations Orf1ab:F2338L, S6294F in peruvian genomes

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1390]
BQ.1.1 with additional mutations Orf1ab:F2338L, S6294F in peruvian genomes by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of BQ.1.1
Earliest sequence: hCoV-19/Peru/CAL-INS-32299/2022 (07/11/2022, Peru)
Most recent sequence: hCoV-19/Peru/LIM-INS-32302/2022 (08/11/2022, Peru)

**Countries circulating**
Peru (7)

This potential BQ.1.1 is principally distributed in Lima, Peru. 

**Genomes**
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/10136780/genomes.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2050_9244f0.json?c=gt-ORF1ab_2338,6294&label=id:node_6408456&tl=country

<img width="1436" alt="BQ 1 1" src="https://user-images.githubusercontent.com/87997149/205177172-28a646d7-eb86-4413-9673-27a2277bcf8a.png">

<img width="1254" alt="BQ 1 1_asupice" src="https://user-images.githubusercontent.com/87997149/205177190-8e2ae025-bd72-484a-9288-8fc2bbb19877.png">

**Comment by InfrPopGen** [comment]
Thank you for submitting this lineage proposal. As there appear to have been no detections of this clade over the past two months, and no growth since proposal, this proposal can be closed for now. Please feel free to re-propose or request re-opening should this lineage show marked advantages in the future.
