### ISSUE TITLE
validation of recombinant lineages

### ISSUE THREAD

**Issue by Lukas67** [cov-lineages/pango-designation#1437]
Dear All, 

since WHO declared XBB as variant under monitoring (VUM), I tried to find the breakpoint and the p-value.

I used three methods to observe the sequences.

3seq:
3seq could not identify XBB lineage as a child lineage of BA.2.10.1 and BA.2.75

Sc2rf:
Maybe it is already deprecated, but the program was not able to find recombinants in a set of fasta sequences of BA.2.10.1, BA.2.75 and XBB.

 Δm,n,2:
could find a breakpoint at position 28370 and 29836 with a siginificant p-value. 

My question is how recombinant lineages are validated against the hypothesis of convergent evolution?

**Comment by corneliusroemer** [comment]
No formal methods are used. We make things recombinants when the evidence for recombination seems overwhelming.

Here's the evidence for XBB:

nt 0-22898
very good match with BJ.1: all defining mutations of BM.1.1.1 are in XBB, and XBB has just one extra mutation: A19326G
lots of mismatches with BM.1.1.1: G261A, C3796T, C3927T, C4586T	C5183T and more are in BM.1.1.1 but not in XBB; 	C15738T, T15939C, T16342C, T17859C, A19326G and more are in XBB but not in BM.1.1.1

for 22898-end:
XBB clearly matches with BM.1.1.1 and not with BJ.1
BM.1.1.1: T22942G T23019C T23031C G23040A C25416T A26275G
XBB: T22942G T23019C T23031C G23040A C25416T A26275G
BJ.1 T23010C T23030G G23955A G24570T G26529T T27722C G28079T C29118T

If you look at those matches/mismatches it's unambiguous that this is a recombinant. I'm not sure how you configured the tools. You say you used BA.2.10.1 instead of BJ.1 (BA.2.10.1.1) that could be a reason. Also you used BA.2.75 instead of BM.1.1.1, yet another way your statistical power will suffer.

Generally speaking, that Pango calls something a recombinant just means that at the time of designation it looked like something was a recombinant. Sometimes the evidence changes and then things get renamed but one shouldn't rely on Pango lineage names to be the absolute truth.

**Comment by ktmeaton** [comment]
Hi @Lukas67, I do some recombinant validation over at the [ncov-recombinant](https://github.com/ktmeaton/ncov-recombinant) pipeline repository. At minimum, it validates all the designated recombinants, but I try to stay on top of the novel proposed lineages as well.

I write short little reports in the [issues](https://github.com/ktmeaton/ncov-recombinant/issues) for each recombinant (ex. [XBB](https://github.com/ktmeaton/ncov-recombinant/issues/114), [XBK](https://github.com/ktmeaton/ncov-recombinant/issues/213), [proposed1393](https://github.com/ktmeaton/ncov-recombinant/issues/211), etc.). Partially for development purposes, but also so I have a record of the genomic composition of each. This is unrelated to the pango-designation process, but you might find the reports/pipelines of interest if you're doing some independent validation.
