### ISSUE TITLE
Third CJ.1/BA.5.2 recombinant after XBF and XBK - 68 Sequences defined by Orf1b:M454I

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1440]
While staring at the Usher tree of XBK i noticed a small branch that was nor XBK neither XBF.

I think that USHER got it right ( @AngieHinrichs , @josetteshoenma ) this potential new recombinant differing from XBF for missing C6070T 
and from XBK missing T12574C and having a private mutation G14829T (Orf1b:M454I)
<img width="679" alt="Schermata 2022-12-16 alle 16 41 34" src="https://user-images.githubusercontent.com/87669813/208134870-7d1ebaed-8f3b-4705-a963-0a55a08767c5.png">

Tree:

<img width="1159" alt="Schermata 2022-12-16 alle 16 42 08" src="https://user-images.githubusercontent.com/87669813/208134962-bad0f896-8654-4c23-8364-ecdb5ea901d2.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3822d_c86e60.json?c=userOrOld&label=id:node_7738436

Gisaid query : NSP12_M463I,Spike_F486P,-Spike_V83A
Sequences: 
EPI_ISL_15909912, EPI_ISL_16005400, EPI_ISL_16039576,
EPI_ISL_16051110, EPI_ISL_16051346, EPI_ISL_16075391,
EPI_ISL_16107854, EPI_ISL_16111635, EPI_ISL_16121601,
EPI_ISL_16123433-16123434, EPI_ISL_16124690, EPI_ISL_16125265,
EPI_ISL_16142802

It is circulating in England and Japan:
<img width="1111" alt="Schermata 2022-12-16 alle 16 43 11" src="https://user-images.githubusercontent.com/87669813/208135178-38ef0c62-37d1-44f2-9b5f-7bb9568f8323.png">

**Comment by JosetteSchoenma** [comment]
Nice catch, @FedeGueli 

I think I would actually call them all XBK. Yes, Usher puts them on 2 separate (but close) branches, but there might be a common ancestor that misses both T12574C and G14829T that has not been sequenced. And since those mutations are both on the CJ.1 part of the recombinant and I cannot find a single CJ.1 with either one of these 2 mutations, I do think that's likely.

Plus the breaking point seems the same between the samples of these 2 branches, while it is very different from XBF.

![image](https://user-images.githubusercontent.com/94831035/208154316-b740bcd9-ae13-4507-9dc3-f89fca0fab0e.png)

**Comment by FedeGueli** [comment]
Agree @JosetteSchoenma

**Comment by FedeGueli** [comment]
@JosetteSchoenma this is still growing and no intermediate between  it and xbk still sampled. i reopen this one in the meanwhile we can wait for more samples to come.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1abb5_239b90.json?label=id:node_7771566

**Comment by corneliusroemer** [comment]
I saw this one when I designated XBK - I would have also called this XBK but then it would not have had a single distinguishing mutation compared to XBF so I didn't. I'm pretty sure Nextclade will call this lineage XBK as well.

**Comment by FedeGueli** [comment]
> I saw this one when I designated XBK - I would have also called this XBK but then it would not have had a single distinguishing mutation compared to XBF so I didn't. I'm pretty sure Nextclade will call this lineage XBK as well.

@corneliusroemer last time i checked Nextclade called them CJ.1

**Comment by JosetteSchoenma** [comment]
Nextclade calls all XBK CJ.1. Both branches! @corneliusroemer @FedeGueli

**Comment by FedeGueli** [comment]
38 sequences as today . a XBB.1.5 acquired the same non spike mutation so i ve changed the query in NSP12_M463I,Spike_F486P,-Spike_V83A

**Comment by FedeGueli** [comment]
This keeps going. It is not possible to be certain of it is XBK or not but i ll close this for now.

**Comment by FedeGueli** [comment]
68 sequences @corneliusroemer @JosetteSchoenma in my view we should try to say def if it is XBK or not

**Comment by JosetteSchoenma** [comment]
I stand with what I said. I think but branches should be called XBK. But without a combined parent, we can never be sure, of course.

And as I said in the other issue, I think it is important that Nextclade starts calling them XBK instead of CJ.1. It is still growing really fast and pooping up all over the world! @corneliusroemer 🙏

**Comment by corneliusroemer** [comment]
Designated as XBQ

**Comment by JosetteSchoenma** [comment]
XBQ
