### ISSUE TITLE
BQ.1.8 with additional mutations ORF1ab:V627F, Nuc:G2144T in Peru

### ISSUE THREAD

**Issue by LuisBarcenaF** [cov-lineages/pango-designation#1448]
BQ.1.8 with additional mutations ORF1ab:V627F, Nuc:G2144T by Group of Genomic Surveillance INS-PERU

**Description**
Sub-lineage of: Potential new sub-lineage of BQ.1.8
Earliest sequence: hCoV-19/Peru/LIM-INS-32332/2022 (07/11/2022, Peru)
Most recent sequence: hCoV-19/Peru/LIM-INS-35047/2022 (23/11/2022, Peru)

**Countries circulating**
Peru (9)

This potential BQ.1.8 is distributed in Lima, Peru.

**Genomes**
[genomes1.txt](https://github.com/cov-lineages/pango-designation/files/10263650/genomes1.txt)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35540_ec740.json?c=gt-ORF1ab_627&label=id:node_6469470&tl=country

<img width="1316" alt="BQ 1 8_2" src="https://user-images.githubusercontent.com/87997149/208552194-b3b9e8e2-a28a-4e78-a5ba-91afcd9176d7.png">

<img width="1676" alt="usher_BQ 1 8_2" src="https://user-images.githubusercontent.com/87997149/208552215-2d595ced-6936-4680-b684-b1a58bb6c761.png">

**Proposed sub-lineage name**
BQ.1.8.X

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. As this has not increased much since first proposed, has shown a marked growth disadvantage in Peru over the last three months, and only one sequence has been detected in the last two months, this can be closed for now. Please repropose or request re-opening should this lineage show marked growth in the future.
