### ISSUE TITLE
XBB with S:486P from US east coast  - artefact or homoplasy? [9 sequences US, 1 AUS]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1459]
Looking for homoplasy of S:486P in XBB (due to the apparent fast growth of XBB.1.5), I noticed this apparent lineage from the US east coast that looks like it's very much not XBB.1.5 - it lacks all of the 3 non-S:486 mutations of XBB.1.5 and shares mutations with a few other sequences. And there's no obvious artefact I can see.

However it's not from a big branch of XBB. So I'm confused whether this is homoplasy or an artefact. Any thoughts welcome.

It's defined by XBB + 14178T,14362T,22792A,25539T

There's one sequence from Australia as well apparently.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/25161793/209170580-cd4013cf-01dc-45a1-9343-1af29ca562f4.png">

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/25161793/209170576-14522e92-ae3f-4357-b8ec-9b770b140d2d.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_3737f_472530.json?branchLabel=back-mutations&gt=S.486L&label=id:node_7617106

EPI_ISL_16168600
EPI_ISL_16089826
EPI_ISL_16184328
EPI_ISL_16133568
EPI_ISL_15704652
EPI_ISL_16081991
EPI_ISL_15947141
EPI_ISL_16020835
EPI_ISL_16205389
EPI_ISL_16205459

**Comment by MCB6** [comment]
Maybe a little offtopic, but it's worth noting that in New England where most of the sequencing is done by Broad Inst with its unique pipeline, Pango is unable to call XBBs. So it assigns the putative XBB.1.5's to the generic BA.2 bin. But the trajectory of F486P growth is exactly the same as in the neighboring Connecticut and NY City where it's driven by XBB.1.5. (The final points on the graph are lower than they will eventually be because the most recent weeks are mostly represented by the earliest dates within the week)
![image](https://user-images.githubusercontent.com/93294184/209179552-4b13e8c9-2d68-4a1a-a1be-7b986b1e8fe2.png)

![image](https://user-images.githubusercontent.com/93294184/209179634-5706e6a8-d8ae-4e44-97c5-77e5831aa40e.png)

**Comment by MCB6** [comment]
PS: in yesterday's upload from NYU Langone, half of the sequences had F486P, but a half of those were generic BA.2 too

**Comment by corneliusroemer** [comment]
This is a pangoLEARN/pangolin issue - if you use pangolin in Usher mode or Nextclade they should all get classified correctly.

**Comment by FedeGueli** [comment]
Hi @corneliusroemer spotted that in the last days and wondering the same of you. thx for proposing it.

**Comment by FedeGueli** [comment]
@corneliusroemer i think many more of this one popped up. i m checking them

**Comment by FedeGueli** [comment]
@corneliusroemer it reached 18 sequences and now looks legit to me:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1751d_df0060.json?c=userOrOld&label=id:node_7695325

<img width="1159" alt="Schermata 2022-12-29 alle 20 58 10" src="https://user-images.githubusercontent.com/87669813/210005639-d15e7369-ada5-4a41-b1cb-130cf5de8193.png">

**Comment by corneliusroemer** [comment]
Very confusing, I'd probably wait a bit more in the hope things become clearer over time.

**Comment by AnonymousUserUse** [comment]
False milestone? It has been designated as XBB.6.1 if I understand correctly.
