### ISSUE TITLE
BA.5.2 sublineage with S:T883I and Orf1b:S997P circulating in China (75 seqs as of 2023-01-08)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1480]
Defining mutations: BA.5.2 > C27513T > C27012T > G12310A > Orf1b:1050N (C16616A) >S:T883I  (C24210T ) > A14673G, Orf1b:S997P (T16456C)

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_1acf9_b0ad20.json?c=userOrOld&label=id:node_6968987
<img width="1062" alt="Schermata 2022-12-27 alle 16 30 18" src="https://user-images.githubusercontent.com/87669813/209687896-c61cb02b-5c43-4d77-9779-39f95ffab12c.png">

Gisaid Query: NSP13_S74P,Spike_T883I,NSP13_T127N,M_D3N

Sequences: 15

EPI_ISL_15583088, EPI_ISL_16259473, EPI_ISL_16264217,
EPI_ISL_16278349, EPI_ISL_16278357, EPI_ISL_16278360,
EPI_ISL_16283873-16283874, EPI_ISL_16283959, EPI_ISL_16283963,
EPI_ISL_16283965, EPI_ISL_16283977-16283980

**Comment by FedeGueli** [comment]
2 new sequences from Singapore.

**Comment by FedeGueli** [comment]
26 Sequences as today all uploaded from Sichuan

**Comment by FedeGueli** [comment]
52 sequences as today: new uploads from Zhejiang, Shangai, Fujan

**Comment by FedeGueli** [comment]
56 sequences as today

**Comment by FedeGueli** [comment]
60 as today. new samples from pechino uploaded today.

**Comment by FedeGueli** [comment]
3 more sequences from Hunan

**Comment by FedeGueli** [comment]
72 as today . all the last samples are from travellers arriving to South Korea from China

**Comment by AnonymousUserUse** [comment]
@InfrPopGen @corneliusroemer 

I think this lineage should be designated as soon as possible, directly after the lineage BA.5.2.48 (i.e. designated as BA.5.2.49), to make it easier to remember both lineages circulating in the same country.

Eventually also the lineage from https://github.com/cov-lineages/pango-designation/issues/1498.

**Comment by FedeGueli** [comment]
One more sequence intercepted by japanese airport surveillance in a traveller from China, another confirmation that is circulating quite extensively there, being certainly the 3rd lineages after BA.5.2.48 and BF.7.14

**Comment by FedeGueli** [comment]
Two more sequences from Sichuan. this confirms that this is widely spread in ML CHina . @corneliusroemer @InfrPopGen @thomasppeacock maspeacock

**Comment by corneliusroemer** [comment]
What's confusing me about this lineage here is that it's _also_ got C8626T in a large sublineage. And C8626T is a mutation that occurred just before the defining mutation of BA.5.2.48

First an aside on what I learned about BA.5.2.48 after inspecting with Usher and covSpectrum:

BA.5.2.48 descends from an unnamed Russian lineage that has C2710T and C8626T on top of the standard BA.5.2 + ORF1b:T1050N. This BA.5.2.48 ancestor lineage has around 4k sequences, see: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*+%26+C2710T+%26+C8626T&

BA.5.2.48 is a sublineage of that unnamed lineage with extra T17208C. Due to the way Nextclade just looks for the closest match, Nextclade will call around 4k sequences BA.5.2.48 as soon as we update - even if these sequences miss the BA.5.2.48 defining T17208C. 

Now back to the lineage at issue here. 

It's defined by A14673G, T16456C after S:T883I if you look at Usher.

It branches off directly from the BA.5.2 + ORF1b:T1050N founder.

But then it has 8626T appearing as a major branch within - maybe contamination from BA.5.2.48? This lineage here seems otherwise clean so I guess we should designate it as BA.5.2.49.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/25161793/211229299-b2929caa-2ab3-47ab-96be-e0e88755f9a3.png">

**Comment by FedeGueli** [comment]
Thx Cornelius i missed that.

**Comment by AnonymousUserUse** [comment]
> But then it has 8626T appearing as a major branch within - maybe contamination from BA.5.2.48?

Are there any reasons why the contamination can occur exactly on the mutation 8626T, or it is just randomized contamination?
Given the high number of sequences with 8626T together with 11266T, I think it is more likely that BA.5.2.49 has acquired 8626T independently. Nevertheless, 8626T is labeled as homoplasic in Usher tree.
@corneliusroemer

**Comment by AnonymousUserUse** [comment]
Unexpectedly, Nextclade does not call those 4000 sequences from ancestor lineage with C2710T and C8626T as BA.5.2.48. Are there any reasons for that?
I know that C16887T is masked in Usher. Is this mutation taken into account by Nextclade?
@corneliusroemer
