### ISSUE TITLE
B.1.619 sequences on GISAID without S:E484K, S:N440K and other signature spike mutations

### ISSUE THREAD

**Issue by banijolly** [cov-lineages/pango-designation#149]
Hey team!

I have noticed a few sequences on GISAID that have been assigned B.1.619 but do not have the defining spike mutations. These sequences from India, for example, don't have either E484K or N440K or any of the spike mutations found in B.1.619.

![image](https://user-images.githubusercontent.com/47384613/126034410-444fe3e3-ae77-44d4-a3cf-dfe54f926f58.png)

The sequences from USA (again none of these has the lineage defining mutations for B.1.619) look like they could probably belong to B.1.526 instead of B1.619, for example -

![image](https://user-images.githubusercontent.com/47384613/126034550-3c13dfbe-50d0-45c8-bca6-1c5d725cadf3.png)

Here's a list of all such sequences that I could find on GISAID.
[B1619_accessions.txt](https://github.com/cov-lineages/pango-designation/files/6834608/B1619_accessions.txt)

**Comment by AngieHinrichs** [comment]
Thanks @banijolly for flagging those!  

AFAIK there isn't a way to tell pangoLEARN that some mutations are more important to get right than others, so there is no special treatment for Spike mutations.  

I uploaded your sequence IDs to the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) and here is a view of where they fall on a downsampled version of UCSC's tree (your samples in red):
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-149.global.json

Some are scattered across the global tree, and some of those seem to have not very many mutations (although they could have a lot of Ns, I'd have to look into that separately).  Of those, the ones with not too many Ns could be added as B.1 representative sequences.  

Many of the sequences look like they should be assigned B.1.526.  I'm baffled by that because B.1.526 and B.1.619 have very little in common, and all of the B.1.619 representative sequences [cluster neatly](https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-149.B.1.619.reps.json?branchLabel=Spike%20mutations) in the UCSC tree.  Adding more representative sequences for B.1.526 and B.1.619 might help.

Going through the sequences in more detail to tell which should be added as representative sequences, and to what lineages, will take more time - just wanted to send an update for what I've seen so far.

**Comment by chrisruis** [comment]
Thanks @banijolly! We've now looked through the B.1.619 clade in the latest UShER tree. It looks like there's a sub-lineage of B.1.619 in there that is circulating in South Korea - this is described in #160 and we've designated that clade as B.1.619.1.

We've also now designated sequences as B.1.619 if they:
1) are in the B.1.619 clade in the UShER tree
2) are not in B.1.619.1
3) have <5% ambiguity
This included 839 new B.1.619 designations to result in 882 sequences in total now designated B.1.619.

For the other sequences that were being assigned B.1.619 but cluster elsewhere:
* 5 of these have >5% ambiguity so we couldn't designate them - India/DL-NCDC-2809314/2021, USA/NY-PRL-2021_03_15_00G22/2021, USA/MD-CDC-LC0038159/2021, USA/WV-CDC-LC0059533/2021, USA/NY-PRL-2021_03_15_00J21/2021
* 1 is potentially in B.1.427 but is on a long branch so we've excluded this one for now - USA/PR-CDC-ASC210074914/2021
* We've designated 10 as B.1 - USA/NY-PRL-2021_03_15_01E01/2021, France/HDF-100002711299/2021, USA/NY-CDC-LC0049367/2021, India/DL-NCDC-2509291/2021, USA/NY-PRL-2021_02_19_00B22/2021, USA/NY-PRL-2021_03_12_00B08/2021, USA/NY-PRL-2021_03_01_00E16/2021, USA/NY-PRL-2021_03_15_01D03/2021, USA/NY-PRL-2021_03_12_00L01/2021, USA/MN-MDH-5185/2021
* We've designated 1 as B.1.427 - USA/CT-CDC-LC0040781/2021
* We've designated 1 as B.1.428 - Qatar/QA-WCMQ_FD18160881/2020

All of these can be found in [v1.2.44](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.44).

Thanks again for submitting.

**Comment by banijolly** [comment]
Thanks a lot for the update!
