### ISSUE TITLE
AT.1 not assigned by pangolin in all cases

### ISSUE THREAD

**Issue by luenling** [cov-lineages/pango-designation#152]
Dear Pango designation team,

I recently stumbled across an issue with some patient samples which have quite a few hallmark mutations of AT.1, but are assigned B.1.1. by Pangolin. When uploading the sequences to Usher, Usher classifies them as AT.1, but the next sequences in the tree are also classified as B.1.1 by pangolin. Not sure why this is the case.
Our sequences have the following (more or less) AA changes:
ORF1ab:S376L; ORF1ab:V1006F; ORF1ab:T1093A; ORF1ab:Q1201L; ORF1ab:T2247N; ORF1ab:T3255I; ORF1ab:A3688V; ORF1ab:S4119T; ORF1ab:P4715L; ORF1ab:T5574N; ORF1ab:S5674L; ORF1ab:V6306L; ORF1ab:A6832V; S:P9L; S:C136_Y144del; S:H245P; S:E484K; S:D614G; S:N679delinsKGIAL; S:E780K; ORF3a:L95M; M:L16I; N:R203K; N:G204R
Most of these fit very well with the mutations found in the 25 AT.1 lineages in GISAID, especially  S:P9L; S:C136_Y144del; S:H245P; S:E484K; S:D614G; S:N679delinsKGIAL and S:E780K. 
Maybe there are not enough sequences classified as AT.1 to allow identifying our samples by pangolin. 

[screenshot of usher with our sequences](https://user-images.githubusercontent.com/10516241/126387542-b708092a-298a-4551-8e37-3e8075b3e63a.png)
Fasta sequences of our potential AT.1 sequences:
[at_1_cand.fasta.gz](https://github.com/cov-lineages/pango-designation/files/6851028/at_1_cand.fasta.gz)

All the best and thanks for your great work,
Lukas

**Comment by luenling** [comment]
Hello,

Actually, I just checked for GISAID. In the GISAID metadata downloaded from July 13th there were 112 sequences classified as AT.1 while in todays (from July 20th) metadata or search interface there are only 26, of which 2 are classified as B.1.1.74 in the older metadata. So 97 sequences are classified as something else now in GISAID with a newer version of pangolin ( 96xB.1.1 , 1x B.1.1.171). 
Attached a tsv file with the EPI Ids of the different samples that are classified as AT.1 in at least one GISAID metadata file (from 0713 or 0720) and the Pangolin lineage given in the respective file.
I am not sure whether this should be a Pangolin issue or is related to this forum, as last time I had a similar issue Rachel @rmcolq rightly remarked on it being a designation issue.

All the best
Lukas
[AT.1_epi_0713_0720.tsv.gz](https://github.com/cov-lineages/pango-designation/files/6855658/AT.1_epi_0713_0720.tsv.gz)

**Comment by AngieHinrichs** [comment]
lineages.csv has only 6 representative sequences for AT.1 -- it could use some more.

FWIW there are 138 sequences on the branch of the UCSC tree found by matUtils annotate for AT.1:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-152.json?c=country&label=nuc%20mutations:A22206G

(really 137, I think Germany/SN-RKI-I-151811/2021|EPI_ISL_2263172|2021-05-08 and MS-10006-CVDP-A00057D8-3684-405C-BCE2-F2E8662A1077|OU204427.1|2021-05-08 are the same sequence but due to the difference in names my deduplication pipeline misses the Germany/*-RKI- vs. IMS-... sequences)

I'm attaching a file with 137 sequences that include 5 of the 6 currently designated sequences (the UCSC tree does not include Russia/PSK-16/2021 because it has 24 mutations relative to the node at which it is placed and we filter out >20).
[pango-designation-152.AT.1.ucsc.tsv.gz](https://github.com/cov-lineages/pango-designation/files/6858944/pango-designation-152.AT.1.ucsc.tsv.gz)
@chrisruis I haven't checked those for N content but aside from that I think they should be OK to designate as AT.1.

**Comment by chrisruis** [comment]
Thanks for submitting @luenling. We've now designated the sequences that @AngieHinrichs put together as AT.1 in [v1.2.40](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.40). There were 118 new sequences from this with <5% ambiguity so combined with the 6 previous designations, there are now 124 AT.1 sequence designations.

Hopefully this will help with the assignments. I'll close this issue for now but please do reply/reopen it if the assignments still don't look right. Thanks again
