### ISSUE TITLE
XBB.1*/BA.2.75*/XBB.1* recombinant with S:F486P (8 seq, Malaysia)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1532]
**Proposal for a recombinant lineage**
Earliest sequence: 2022-11-24 (Malaysia)
Countries detected: Malaysia (6), Japan ex-Malaysia (1), Singapore ex-Malaysia (1)
Potential breakpoints: 406-3795 (nsp1-nsp3) and 5184-12443 (nsp3-nsp8)

**Mutations inherited from BA.2.75\* donor:**
C3796T, C3927T (ORF1a:S1221L), C4586T, C5183T (ORF1a:P1640S)

**Private mutation that could be from either donor:**
G3446A (ORF1a:A1061T)

**Private mutations in XBB.1\* section (all inherited from donor):**
A20379G, T23018C (S:F486P), C28312T

GISAID query: nuc mutations G3446A, A20379G, C28312T

This is an XBB.1* where part of ORF1a has been replaced with BA.2.75*. The XBB.1* donor is a sibling lineage of XBB.1.5, defined by S:F486P, A20379G and C28312T. It isn't currently designated XBB.1.5 because it is missing T17124C; see #1491 for my previous thoughts on this and my first mention of this recombinant. All 8 known sequences of the A20379G+C28312T lineage (the cyan branch in the Usher tree below) have a further two mutations A18333G and T28853C; neither of these is in the section replaced by BA.2.75* in the recombinant, so the XBB.1* donor must be an unsampled ancestor of this branch before these two mutations occurred. Two of the Singapore sequences in the A18333G+T28853C branch are associated with travel from Saudi Arabia, which does very little sequencing, so it is possible that the XBB.1+A20379G+C28312T branch arose in the Middle East. 

The BA.2.75* donor can't be narrowed down at all unless we assume that it provided G3446A. There is no large BA.2.75* branch with G3446A; there are a few small ones that could potentially be the donor but none have been found in Malaysia. One has been found in Kuwait so could be the donor if the recombination happened in the Middle East, but it is BA.2.75.2 so the second breakpoint would have to be between 5184 and 5191 which seems unlikely.

Given the similarity to XBB.1.5, we should expect this recombinant to behave similarly. It could eventually become dominant in Malaysia, since XBB.1.5 has not yet been sampled there.

The recombinant is in yellow below; the XBB.1.5 lookalike descending from the presumptive XBB.1* donor is in cyan.

<img width="733" alt="XBB1_BA275_recombinant" src="https://user-images.githubusercontent.com/42699509/211128263-e546a8d1-877b-4bf6-88b6-5fa075ce699b.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2d26e_8d2e60.json?c=gt-ORF1ab_1221&label=id:node_7739739](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2d26e_8d2e60.json?c=gt-ORF1ab_1221&label=id:node_7739739)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G3446A%2CA20379G%2CC28312T&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=G3446A%2CA20379G%2CC28312T&)

EPI_ISL_16222732
EPI_ISL_16222888
EPI_ISL_16253248
EPI_ISL_16259751
EPI_ISL_16357558
EPI_ISL_16366911
EPI_ISL_16378738
EPI_ISL_16399449

**Comment by corneliusroemer** [comment]
Worth designating given it's got the same Spike as XBB.1.5

**Comment by ciscorucinski** [comment]
@corneliusroemer @silcn 

My code base has unexpectedly split this recombinant alias' parent lineages down one step further. It took both `XBB` which is` BJ.1` and `CJ`, from this new recombinant, and replaced them both with `BJ.1` and `CJ`

XBB.1* | XBB.1* | BA.2.75* | XBB.1* | XBB.1* 
-- | -- | -- | -- | --
B.1.1.529.2.10.1.1 | B.1.1.529.2.75.3.1.1.1.1 | B.1.1.529.2.75 | B.1.1.529.2.10.1.1 | B.1.1.529.2.75.3.1.1.1.1
BA.2.10.1.1 | BA.2.75.3.1.1.1.1 | BA.2.75 | BA.2.10.1.1 | BA.2.75.3.1.1.1.1
BJ.1 | CJ.1 | BA.2.75 | BJ.1 | CJ.1

My question is, while this makes perfect sense to do on paper, due to where recombinants can split, this further split to `BJ.1` and `CJ`  from `XBB` `might not work for other future variants. Is this a potential bug?  Should programmers not be doing this (intentionally) or is it still a safe representation?

**Comment by FedeGueli** [comment]
Now it is growing fast. i expect it  climbing up into the XBB.1.9ers XBB.1.5.10 range of collection24: https://cov-spectrum.org/collections/24

**Comment by AngieHinrichs** [comment]
> My question is, while this makes perfect sense to do on paper, due to where recombinants can split, this further split to BJ.1 and CJ from XBB might not work for other future variants. Is this a potential bug? Should programmers not be doing this (intentionally) or is it still a safe representation?

Yes, good point.  Without knowing the breakpoints for each recombinant, I don't think it's possible to correctly establish the order of ancestral segments after multiple recombinations.

**Comment by FedeGueli** [comment]
Hi @silcn and @AngieHinrichs (cc @corneliusroemer ) some help needed here.
After being solicited by @josetteshoenma who commented on XBL circulation some days ago,
I discovered a probable branch of XBL that is misplaced on Usher by masking A20379G and G3446A,
this is my thought but i need your help to check if true.

Here the two trees coloured by nuc : 3446,3796,3927,5183,20379

Original XBL as described here: 
![Schermata 2023-04-18 alle 10 15 23](https://user-images.githubusercontent.com/87669813/232715330-b0c51d97-95f3-42af-9a0b-3e6028e7a855.png)
(https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ad63_e4f720.json?c=gt-nuc_3446,3796,3927,5183,20379&label=id:node_5883520)

*********

NEW Second likely XBL tree:

![Schermata 2023-04-18 alle 10 16 52](https://user-images.githubusercontent.com/87669813/232715744-8efa7614-d9c5-40af-b340-ad99e6d03a7f.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_ad63_e4f720.json?c=gt-nuc_3446,3796,3927,5183,20379&label=id:node_5879500

accounting for 50 samples (+/-) depending where you start it.

Thank you very much if you have a time to look at it, it could be of some relevance due to the fact the "second tree" acquired Orf1a:t4175I and the samples belonging to it seem recent.
![Schermata 2023-04-18 alle 10 19 56](https://user-images.githubusercontent.com/87669813/232716655-14724805-4a23-4f10-bb92-efa2b3e494cb.png)

**Comment by JosetteSchoenma** [comment]
@FedeGueli You are catching the CH.1.1.1/XBB.1.9.1 recombination from issue #1876 with that query now.

Nextclade/people thinking it is XBL, XBB.1.9.1 or XBB.1.22 is one of the reasons why I hope it will get its own name soon! Thank you for proving my point ;-).

**Comment by FedeGueli** [comment]
EDiTED ahahhaha @josetteshoenma thank you!! 

and i was going on >>> ahahah sorry @silcn @AngieHinrichs @corneliusroemer for bothering i arrived there from totally different seas from Josette!

**SCRATCH SCRATCH SCRATCH**
@silcn @AngieHinrichs @corneliusroemer wait wait wait i think the second tree is a different recombinant XBB.1.9.1/CH.1.1.1
![Schermata 2023-04-18 alle 10 45 40](https://user-images.githubusercontent.com/87669813/232723749-f2ddd6aa-f638-40cf-9800-a896e8ea3b32.png)
Saying this cause it misses **C28312T** of XBL!
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1cbda_e56d40.json?c=gt-nuc_28312&label=id:node_5879517

while it has ORF1a:A427V, ORF1a:Q1198K which are in quite all CH.1.1.1 from Australia
https://cov-spectrum.org/explore/Australia/AllSamples/Past6M/variants?aaMutations=orf1a%3AA427V%2Corf1a%3AQ1198K&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&
![Schermata 2023-04-18 alle 10 48 38](https://user-images.githubusercontent.com/87669813/232724528-6fe3a42e-dfff-4d5b-822d-3fd42a004f51.png)

And these ones are our new Recombinant! 
![Schermata 2023-04-18 alle 10 49 39](https://user-images.githubusercontent.com/87669813/232724812-47a0f3ba-7031-4adb-8f28-5fa96214177f.png)
https://cov-spectrum.org/explore/Australia/AllSamples/Past6M/variants?aaMutations=orf1a%3AA427V%2Corf1a%3AQ1198K&nextcladePangoLineage=XBB.1.9.1*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&
**********************************

And so the Vienn diagram is the following:


New recomb vs CH.1.1.1
![Schermata 2023-04-18 alle 10 52 38](https://user-images.githubusercontent.com/87669813/232725609-2abb5562-c656-41e7-b2cd-0c1885c96749.png)

**Comment by JosetteSchoenma** [comment]
I am not sure sure which one you mean, but I am monitoring several CH.1.1/XBB recombinants. One from the Netherlands (2 samples) and one from the USA and a few other countries. I haven't proposed those, because they aren't growing like the Pakistan/NSW one.

**Comment by corneliusroemer** [comment]
I've designated the likely major donor as XBB.1.5.57

**Comment by JosetteSchoenma** [comment]
XBL
