### ISSUE TITLE
Suggestion - Change the use of "/" (or) to a more explicit reference

### ISSUE THREAD

**Issue by 3dgiordano** [cov-lineages/pango-designation#1546]
**Suggestion**  Change the use of "/" to a more explicit reference

**XAY** - Change "BA.4/5*" to "BA.4*", "BA.5*"  for a clearer statement
https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json#L150

**XBA** - Change "BA.4/5" to "BA.4", "BA.5"  for a clearer statement
https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json#L152

**Comment by 3dgiordano** [comment]
Ok, I understand then that there is a better way to designate the reference where it derivates.

Feel free to define what to do with the current issue.
If they create a new one or continue the current one, changing the title and incorporating a better description of what must be done with these recombinants.

Thanks.

**Comment by ciscorucinski** [comment]
Github issues for XAY and XBA https://github.com/cov-lineages/pango-designation/issues/844

**Comment by ciscorucinski** [comment]
@silcn so it's a divergent BA.2 that hasn't been designated? It seems like it hasn't been narrowed down any further than just a divergent BA.2

**Comment by ciscorucinski** [comment]
@silcn @corneliusroemer So the signature for at least one of the lineages should be...
`BA.2`, `AY.45`, `BA.2`, `AY.45`, `BA.2`, `AY.45`?

I took the liberty to transform the below comment into a table. Please review my transformation is correct. _Note: I use `BA.2&` to represent `BA.2 and more`_ 

>_However, based on https://github.com/cov-lineages/pango-designation/issues/844#issuecomment-1184831914, there seems to be at least one plain `BA.2`.  I don't know if the referenced `3'` means Break Point 3 or what (Therefore, `Line 3` would not be `BA.2&` but just `BA.2`)_
>
> _Based on the `3'` reference: `BA.2&`, `AY.45`, `BA.2`, `AY.45`, `BA.2&`, `AY.45`_

Line | | From | | | | To | |  | Break Point | Length
 | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
1  | 0-2790: | BA.2& | BA.4/5  || 2791-4180: |  AY.45 | 21J ||  Break Point 1  | ~3-4k
2  | 4181-21846: | AY.45 | 21J || 21847-21986: | BA.2& | BA.4/5 || Break Point 2 | 18-19k
3  | 21987-24912: | BA.2& | BA.4/5 | | 24913-24999: | AY.45 | 21J | | Break Point 3 |  3k
4  | 25000-28310: | AY.45 | 21J | |28271-28880: | BA.2& | BA.4/5 | |Break Point 4 |3-4k
5  | 28881-28916: | BA.2& | BA.4/5 | |28917-29401: | AY.45  | 21J | |Break Point 5 | 40-1.2k
6  | 29402-end: | AY.45 | 21J | |  | | | |  500-1k

> Based on https://github.com/cov-lineages/pango-designation/issues/844#issuecomment-1184915936
> ```
> 0-2790: BA.4/5 [length ~ 3-4k]
> 2791-4180: BA.4/5 -> 21J (BP1)
> 4181-21846: 21J [length 18-19k]
> 21847-21986: 21J -> BA.2 (BP2)
> 21987-24912: BA.4/5 [length 3k]
> 24913-24999: BA.4/5 -> 21J (BP3)
> 25000-28310: 21J [length 3-4k]
> 28271-28880: 21J -> BA.2 (BP4)
> 28881-28916: BA.4/5 [length 40-1.2k]
> 28917-29401: BA.4/5 -> 21J (BP5)
> 29402-end     : 21J [length 500-1k]
> ```

_**Note:** I believe `BA.2&` should fit into existing pipelines with minimal changes because existing pipelines must handle `BA.2*`_

**Comment by silcn** [comment]
Bumping this because XAY and XBA are still erroneously listed as being descended from BA.4/5, which is now feeding through to cov-spectrum too.

**Comment by corneliusroemer** [comment]
What needs to change? Lineage notes and/or alias? If someone made a PR that'd be great!

**Comment by ciscorucinski** [comment]
What is the accepted change?

Here is what currently exists...

Lineage Notes
```
XAY	Recombinant lineage of BA.2 and AY.45, South Africa lineage, from pango-designation issue #844
XBA	Recombinant lineage of perhaps AY.45 and perhaps BA.2 (with perhaps 5 breakpoints), South_Africa lineage, constellation 2 from pango-designation issue #1068 
```
Alias_key.json
```
    "XAY": ["AY.45","BA.4/5*"],
    "XBA": ["AY.45","BA.4/5"],
```

**Comment by AnonymousUserUse** [comment]
Are the new aliases correct?
I thought it should be:
"XAY": ["BA.2*","AY.45","BA.2*","AY.45","BA.2*","AY.45","BA.2*"]
"XBA": ["BA.2*","AY.45","BA.2*","AY.45","BA.2*","AY.45"]
