### ISSUE TITLE
XAY.1 sublineage with ORF1a:V86I (46 seq. Slovenia, Germany, Croatia, US)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1553]
Residues around ORF1a:M85 seem to be a hotspot for some reasons.
Defining mutations:
XAY.1+ORF1a:V86I (G521A)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3A86I&nextcladePangoLineage=XAY.1*&

**Comment by ryhisner** [comment]
Deletions at ORF1a:82-86 have been common ever since Delta, and it's not clear why. They seem to gradually increase in prevalence until a new variant takes over, at which point they rapidly drop before beginning to gradually increase again. A lot of labs have trouble getting deletions right, so I think most of the substitutions in this area are probably not real.

**Comment by oobb45729** [comment]
In the case of ORF1a:V86I though, I think most of them are real. There are overwhelmingly more cases of ORF1a:86I+ORF1a:85M than cases of ORF1a:86I+ORF1a:85-. Also, it seems that there were several Delta strains that gained ORF1a:V86I independently.

**Comment by Outpfmance** [comment]
The cov-Spectrum shows that there are now 46 sequences, maybe it's time to update the issue @oobb45729 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=Orf1a%3A86I&nextcladePangoLineage=XAY.1*&

**Comment by oobb45729** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33d2e_ea0800.json?f_userOrOld=uploaded%20sample
![V86I](https://user-images.githubusercontent.com/115189228/219492302-e488d231-5378-477d-bd43-dc67cb44572b.png)

**Comment by Outpfmance** [comment]
47 sequences now
