### ISSUE TITLE
BQ.1.1 + T1453C sublineage with insertion at S:247/248:  for Gisaid Spike_ins248AED +Spike_Y248S , for covspectrum S:Y248D + ins_S:247:SAE - 76 sequences 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1571]
I hardly identified a sublineage of BQ.1.1 with a NTD insertion in one of the already well known recurrent indel regions, S:248.

We were lucky that  this lineage has a nucleotide change that makes easy to identify it : **T1453C** .
Otherwise it would be impossible to identify it , with Usher misplacing it [all ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_4310a_ce1900.json?c=userOrOld&label=id:node_6384836)[over](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_4310a_ce1900.json?c=userOrOld&label=id:node_6164171) [the](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_4310a_ce1900.json?c=userOrOld&label=id:node_6399660) [tree ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_4310a_ce1900.json?c=userOrOld&label=id:node_6419688) [again](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_4310a_ce1900.json?c=userOrOld&label=id:node_6390983) and [again ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_4310a_ce1900.json?c=userOrOld&label=id:node_6252503).

Finally i managed to get an **Usher tree** that seems to collect the mayority of sequences of this lineage: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_4310a_ce1900.json?c=gt-S_248&label=id:node_6422991
<img width="1160" alt="Schermata 2023-01-22 alle 10 12 54" src="https://user-images.githubusercontent.com/87669813/213908414-1631cb0d-54c4-4c20-9aa9-676450f7ab22.png">

**Defining mutations:**
BQ.1.1 + A17039G > **T1453C, S:Y248D ins_S:247:SAE**

**Gisaid Query**: **Spike_ins248AED,Spike_Y248S** + NUC: **T1453C**

Sequences:
EPI_ISL_15921362, EPI_ISL_15983085, EPI_ISL_16003260,
EPI_ISL_16009238, EPI_ISL_16129718, EPI_ISL_16234403,
EPI_ISL_16234424, EPI_ISL_16265729, EPI_ISL_16265742,
EPI_ISL_16280357, EPI_ISL_16287099, EPI_ISL_16287210,
EPI_ISL_16287221, EPI_ISL_16292933-16292934, EPI_ISL_16299697,
EPI_ISL_16300239, EPI_ISL_16329259, EPI_ISL_16333083,
EPI_ISL_16333191, EPI_ISL_16365858, EPI_ISL_16377938,
EPI_ISL_16377959, EPI_ISL_16386738, EPI_ISL_16395819,
EPI_ISL_16399120, EPI_ISL_16429101, EPI_ISL_16437103,
EPI_ISL_16437113, EPI_ISL_16437116, EPI_ISL_16437118,
EPI_ISL_16437122, EPI_ISL_16446695, EPI_ISL_16449415,
EPI_ISL_16482561, EPI_ISL_16487150, EPI_ISL_16503838,
EPI_ISL_16507144, EPI_ISL_16507146, EPI_ISL_16514898,
EPI_ISL_16521243, EPI_ISL_16526337, EPI_ISL_16526467,
EPI_ISL_16527237, EPI_ISL_16539923, EPI_ISL_16540856,
EPI_ISL_16540858, EPI_ISL_16540871, EPI_ISL_16542501,
EPI_ISL_16547516, EPI_ISL_16547620, EPI_ISL_16553320,
EPI_ISL_16553414, EPI_ISL_16553464, EPI_ISL_16553575,
EPI_ISL_16554083, EPI_ISL_16554086, EPI_ISL_16554108,
EPI_ISL_16555402, EPI_ISL_16555418, EPI_ISL_16565328,
EPI_ISL_16565371, EPI_ISL_16565403, EPI_ISL_16570852,
EPI_ISL_16571418, EPI_ISL_16585103, EPI_ISL_16585105,
EPI_ISL_16586304, EPI_ISL_16590645, EPI_ISL_16593823,
EPI_ISL_16595298, EPI_ISL_16600814, EPI_ISL_16600889,
EPI_ISL_16601273, EPI_ISL_16606085, EPI_ISL_16608102,

Interestingly during the past two months  it seems competitive when compared to an imaginary baseline made by all lineages with S:F486P:
https://cov-spectrum.org/explore/Europe/AllSamples/from=2022-11-01&to=2023-01-22/variants?aaMutations=S%3AF486P&aaMutations1=S%3A248D&nucMutations1=t1453C&aaInsertions1=ins_S%3A247%3ASAE&nextcladePangoLineage1=BQ.1.1*&analysisMode=CompareToBaseline&

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BQ.1.1.37 with 29 newly designated sequences, and 0 updated. Defining mutation T1453C (following A17039G (ORF1b:N1191S)).

**Comment by FedeGueli** [comment]
91 as today it seems  growing fast @corneliusroemer . Kudos to scientists 
Mauro Pistello, Annalisa Capria, Pietro Giorgio Spezia, Susi Frateschi from Retrovirus Center - University of Pisa in Tuscany: they were tracking this lineage since some time and we both indepedently discovered this one.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs i m noticing that BQ.1.1.37 is scatterd in more than 20 different trees,
> Is there a way to collect them in one only??

The short answer is sorry, no, because usher cannot see the insertion, only T1453C -- which occurs in conjunction with many other substitutions that are also observed without T1453C, which is why there are so many different branches.

A small consolation is that most other branches with T1453C are tiny, only one or two sequences, while most BQ.1.1 sequences with T1453C are on the BQ.1.1 > T1453 branch labeled BQ.1.1.37 (54 sequences in the 2023-01-26 tree).

I used taxonium to highlight the other BQ.1.1 branches with T1453C in the 2023-01-06 tree (blue circles; red circle is BQ.1.1.37 main branch), and yes, there are many:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/186983/215222029-c0e9c315-f1ce-47ed-a9ba-7e2bc4263970.png">

But if I restrict it to only branches with more than 3 T1453C sequences, there is only BQ.1.1.37 and a branch with 6 sequences:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/186983/215222165-b9d768b4-b8f8-42df-b198-bf91f0454c44.png">

I downloaded 22 sequences on the biggest of the other little branches, aligned them to the reference, and looked for the insertion of interest and for Ns that might explain why the T1453C sequences got pulled into other branches.  21 of the 22 sequences contain the insertion, so they probably really do all belong in BQ.1.1.37.  (Not all genome assembly pipelines can handle insertions so I was impressed it was even 21 out of 22.)  I did not find Ns that would explain why these sequences with T1453C would be placed on branches with other mutations -- the sequences with T1453C really do also have those other mutations, and there are also sequences that share those other mutations but do not have T1453.  More details in the collapsed section below.

The next question is, do those other branches that seem to acquire T1453C also have any sequences with the insertion?  I will try to find some time to look into that next.

I think it's weird that so many other distinct mutations occur both with and without T1453C.  I don't have a good explanation for that.

<details>
  <summary>Click to expand details of the 22 sequences on smaller branches</summary>

* BQ.1.1 > T2698C > T1453C:
```
Netherlands/LI-RIVM-124207/2023
Belgium/Briant-12220059301/2022
Belgium/Briant-12220058301/2022
Germany/BY-RKI-I-1085906/2023
Spain/IB-HUSE-07282/2022
Ireland/TA-Enfer-110123004_E7/2023
```

* BQ.1.1 > C18312T > T1453C:
```
Netherlands/ZH-RIVM-122591/2022
Netherlands/GE-RIVM-124542/2023
Belgium/AZDelta-2252-11101/2023
```

* BQ.1.1 > C14318T > T1453C,T1578C,T4603C:
```
USA/MD-CDC-QDX44851249/2022
USA/MD-CDC-QDX44851178/2022
USA/CO-CDPHE-2103753504/2022
```

* BQ.1.1 > C2523T > C11020T > T2523C > T1453C (all identical, parent node has 80 seqs):
```
Sweden/01_SE100_23CS500117/2023
Sweden/01_SE100_23CS500058/2022
Sweden/01_SE100_23CS500044/2022
```

* BQ.1.1 > C1385T > T1453C,C24378T (parent node has 2.5k seqs, 2.4k of which are BQ.1.1.8):
```
Ukraine/73150/2022
Ukraine/73145/2022
Ukraine/73147/2022
```

* BQ.1.1 > C26822T > T1453C:
```
Netherlands/ZH-RIVM-124557/2022
Italy/CAM-TIGEM-IZSM-COLLI-43040/2023
```

* BQ.1_17039 > C28603T > G22599C > T1453C (I.e. misplaced BQ.1.1 > C28603T > T1453C):
```
Italy/EMR-IZSLER-009980-009-01/2023
Italy/UMB-LAOP-101-2-35/2023
```

All have the insertion after base 22304 (S:248) except Italy/CAM-TIGEM-IZSM-COLLI-43040/2023.
</details>

**Comment by FedeGueli** [comment]
Thank you @AngieHinrichs great analysis! i am still wondering about it , not clear to me how it could have happened independently in so many existing branches . 
Has there been any hint in the past around that residue to be artifactually mutated? 
@thomasppeacock is this insertion from viral genome or host genome in ur view?
