### ISSUE TITLE
XBB.1.5.15 sublineage with ORF1a:G519S and S:Q146K (mainly USA, >800 seq)

### ISSUE THREAD

**Issue by oobb45729** [cov-lineages/pango-designation#1600]
Defining mutations:

XBB.1.5.15(with G15957T) then ORF1a:G519S(G1820A)+S:Q146K(C21998A)

![1](https://user-images.githubusercontent.com/115189228/215630722-b7975471-4c64-4f17-9818-cf5d2f7ad418.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=10204c%2615957t%261820a%2621998a&
ORF1a:G519S is a frequently occurring mutation and it seems that S:Q146K happened multiple times in XBB.1.5.

**Comment by corneliusroemer** [comment]
That tree is too narrow, you should make one that encompasses as many nearest neighbours as possible (with 5000 context samples) like this:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/25161793/215750053-65a13fd0-9895-40c1-af9c-0fb28e2040a9.png">

When something appears to occur multiple times we also need to be careful. Have a look at the way issues from others like Ryan Hisner are written and try to emulate their style.

**Comment by oobb45729** [comment]
![2](https://user-images.githubusercontent.com/115189228/215755720-98e81046-7469-449b-89a1-ab219396c655.png)

**Comment by emily-smith1** [comment]
Hopefully this can help! 

### Description
**Sub-lineage of:** XBB.1.5
**Earliest sequence:** 2022-12-07 (USA-CA)
**Most recent sequence:** 2023-01-19 (USA-CA)
**Countries circulating:** USA, Canada
**Number of sequences:** 129
**GISAID query:** G1820A,G15957T,C21998A,C22000A,T23018C,T23019C,T22882G
**Substitutions on top of XBB.1.5:** S:H146K and ORF1a:G519S after G15957T

This one is tricky. There appears to be another XBB.1.5 cluster (n=7) that has S:H146K and ORF1a:G519S following G15957T as well if you zoom way out on the tree, but those have some reversions or frameshift in Spike that are likely sequencing artifacts. I was able to filter out by adding S:N440K (T22882G) to the GISAID query. 

### Evidence
**UShER tree (zoomed in to the proposed lineage):** https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_218e8_daae40.json?f_userOrOld=uploaded%20sample&label=id:node_3883100
![image](https://user-images.githubusercontent.com/84812104/216737486-09a55730-0dbb-4389-882e-b4f690a1bc3f.png)

**UShER tree (zoomed out to include all 5000 on subtree):** https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_218e8_daae40.json?c=gt-ORF1ab_519&label=id:node_3877569

![image](https://user-images.githubusercontent.com/84812104/216737523-8c6884fa-879b-4895-a64b-5a1851004ad8.png)


This proposed lineage currently has a 61% growth advantage worldwide since Dec 1 (using same combo of mutations listed above):
![image](https://user-images.githubusercontent.com/84812104/216737537-6d51cee6-8660-447c-9079-411953632e82.png)

**Comment by corneliusroemer** [comment]
Thanks @emily-smith1! What's this growth advantage with respect to, and for which region? Should be against XBB.1.5 and US - maybe that is already the case :)

**Comment by emily-smith1** [comment]
You're welcome! The previous one was worldwide, without a baseline. Agreed that since this is mostly US, something more specific would make sense.

**Here is one specifically for the US, last 3 months, relative to XBB.1.5:**

![image](https://user-images.githubusercontent.com/84812104/216864733-3d6272fb-5ef1-4654-86b8-d271df104298.png)

![image](https://user-images.githubusercontent.com/84812104/216864701-a4ae0901-9cc5-4f20-8b42-7eff8547a64e.png)

**Comment by corneliusroemer** [comment]
Thanks! And here we see... mostly noise ;) I'll take a systematic look at XBB.1.5 this week

**Comment by corneliusroemer** [comment]
S:146K appears to be rising in XBB.1.5, but it seems very inconsistently sequenced. Bit tricky to designate that way.

**Comment by ryhisner** [comment]
ORF1a:G519S is also rising in prevalence lately, mostly in the US. Intriguingly, ORF1a:G519S also rose as a percentage of Delta over many months—though again, primarily in the US. The pattern is somewhat similar to what has been seen in ORF1a:82-86del and (as I recently noticed) A27000G, where the prevalence seems to gradually rise with ~3-7% growth advantage within a given variant but then falls back to very low levels with the emergence of a new variant. 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/33738461/227717144-b2315371-9e84-4b25-8d8d-a330c26b0917.png">

**Comment by oobb45729** [comment]
ORF1a:G519S is one of the most frequent ORF1ab mutations along with ORF1a:K3353R, ORF1a:L3606F, ORF1b:K2557R, etc.
