### ISSUE TITLE
RFC: XBB.1.9 with S:S486P

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1602]
Within XBB.1.9 there appear to be 2 lineages with S:S486P:
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/25161793/215751282-0f7d8896-6d9f-4536-95f5-e14d633e1a96.png">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_175a4_8ead10.json?branchLabel=nuc%20mutations&c=country&gt=S.486L

The first cluster is:
C11956T (167 seqs) > T23018C (153 seqs)
Geographic focus is probably Indonesia, with major circulation in Singapore/Malaysia but export to England/USA etc.

14 sequences are placed on 11956T but without 23018C. Most of them in Indonesia. This _could_ indicate that 11956T happened first, but I'm not convinced as it could also simply be dropout.

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/25161793/215752420-be5f4e4c-8a94-4ba2-9fee-c8009e141be4.png">

The second cluster is:
T23018C (57 seqs) > A27507C (56 seqs)  > A16878T (54 seqs)
Geographic focus again Indonesia/Singapore/Malaysia with export to England/USA etc

The one sequence from Latvia without 27507C could well be dropout/artefact. The same is potentially true about the 2 sequences missing 16878T. So it's not clear whether 23018C happened first or after one or both of the other nuc mutations.

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/25161793/215752348-4e35d181-9e96-4fd6-801a-ba8c8412ee53.png">

This poses the problem: how shall we name those two clusters? There are essentially 2 options:

1. Call both of them XBB.1.9.1, implicitly assuming 23018C happened first, then the clusters split
2. Call the larger one XBB.1.9.1, the smaller one XBB.1.9.2, assuming 23018C happened twice independently, or that if 23018C happened first, we just don't give it a name and give names only to the children.

Since I'm not sure about whether 23018C happened first or not, I'd say we stick with option 1 for now and reconsider if the dust settles.

If these remain the only large clusters, one could then decide to either stick with XBB.1.9.1, split into XBB.1.9.1/XBB.1.9.2 or make the clusters symmetric or asymmetric sublineages of XBB.1.9.1 if the evidence for this arises.

What do others think? @AngieHinrichs what's your view? Would it be awkward to name the two branches both XBB.1.9.1 for now?

These are only ~200 sequences for now, albeit mostly from regions with much less sampling than US/UK - so it's not super critical. But I'd prefer if we give all large clusters of XBB + S:486P names, so the current situation where only the larger cluster has a name is not ideal.

**Comment by FedeGueli** [comment]
@corneliusroemer there are s lot of clusters of XBB.2 + S:F486P i tried to propose a couple but there are more than those two.

**Comment by FedeGueli** [comment]
About this lineage i think masking 11956T they will be grouped in one tree? is not that way? 
They are both XBB.1.9.1 to me.

**Comment by corneliusroemer** [comment]
> there are s lot of clusters of XBB.2 + S:F486P i tried to propose a couple but there are more than those two.

Yes I know, I'll get on it, this was just one place to start. Better to have one issue per topic.

> About this lineage i think masking 11956T they will be grouped in one tree? is not that way? They are both XBB.1.9.1 to me.

Yes if you mask they may be put into one branch, but that doesn't make it right. Why would you mask it - do you have reasons not to rust that site/mutation?

**Comment by FedeGueli** [comment]
> > there are s lot of clusters of XBB.2 + S:F486P i tried to propose a couple but there are more than those two.
> 
> Yes I know, I'll get on it, this was just one place to start. Better to have one issue per topic.
> 
> > About this lineage i think masking 11956T they will be grouped in one tree? is not that way? They are both XBB.1.9.1 to me.
> 
> Yes if you mask they may be put into one branch, but that doesn't make it right. Why would you mask it - do you have reasons not to trust that site/mutation?
@corneliusroemer didnt you suspect they were dropouts?  but looking at the tree there are samples from Greece and Spain so unlikely they are all that way. so they are two lineages it should be XBB.1.9.2 the one

**Comment by FedeGueli** [comment]
@corneliusroemer i found something on C11956T it is widely homoplasic: look at it:

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C11956T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&
<img width="791" alt="Schermata 2023-01-31 alle 14 22 33" src="https://user-images.githubusercontent.com/87669813/215772067-20c69461-de2c-4b02-add7-fb183f39fe22.png">
<img width="757" alt="Schermata 2023-01-31 alle 14 22 48" src="https://user-images.githubusercontent.com/87669813/215772125-3b370e19-2760-4fe1-b73f-8ae26b8e4824.png">

<img width="749" alt="Schermata 2023-01-31 alle 14 23 02" src="https://user-images.githubusercontent.com/87669813/215772162-a3520729-d170-4d03-b92b-2a0c9354523a.png">


look at its prevalence:

<img width="1072" alt="Schermata 2023-01-31 alle 14 24 10" src="https://user-images.githubusercontent.com/87669813/215772441-b00d99dc-9168-4386-a941-61c7072d4967.png">


To me this could justify to mask it. it could have been acquired independently

**Comment by corneliusroemer** [comment]
Designating the second cluster as XBB.1.9.2 as it seems to be an independent acquisition due to the cleanness of the branches.

**Comment by FedeGueli** [comment]
@corneliusroemer isnt more likely that the highly homoplasic C11956T has been acquired two times independently (in XBB.1.9 and XBB.1.9.1 ) than S:F486P being acquired two times  independently? C11956T appeared in quite every lineage since the start of the pandemic while S:F486P popped up independently just 20x times

**Comment by AngieHinrichs** [comment]
A search in taxonium for any change at 11956 gives 3,457 nodes, and a search for any change at 23042 gives 3,236 nodes, so they're not that different from each other in terms of occurrence/homoplasy, although if we looked at number of samples for each (~ growth rate after mutation) I would expect it to be a different story.  (Restricting 11956 to T gives 3,304 and 23042 to C gives 3,069.)

> Are there any quantitative criterion to determine whether a mutation is highly homoplasic and should be masked? 

Good question @AnonymousUserUse and for the [Problematic Sites](https://github.com/W-L/ProblematicSites_SARS-CoV2) set, masked in all sequences before placement in tree, I would say yes: https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473/14

However, for [branch-specific masking](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/maskDelta.sh) applied after placement in the tree, so far that has all been based on my subjective opinion of the tradeoff between discarding information that I consider to be mostly noise and harmful to the tree structure vs. the risk of masking out true changes (mostly reversions, including the necessary "reversions" required in order to place a recombinant lineage somewhere in a tree data structure).  

These are the cases in which I feel sure that masking is the right thing to do:

* deletions/insertions: Most VoC lineages have at least one deletion.  However, many genome assembly pipelines used for SARS-CoV-2 genomes seem to have trouble with deletions: they may have Ns or reference bases in place of part or all of the deletion, or even "substitutions" in the deletion region that I think are from short read alignments that are extended into the deleted region instead of skipping to the other side.  So in practice, I see "substitutions" in regions that I believe are deleted popping up all over the branch and sometimes causing false branches when multiple sequences share the same "substitutions".  It's always a mess, so I think it is helpful to mask out bases in deleted regions when confident that a VoC branch has a deletion.  The genome assembly situation can be even messier for insertions: many bases around an insertion point can be very noisy with "substitutions".  BA.1 has a deletion at 22194-22196 and then an insertion after 22204, and I saw so much of what I considered to be noise in the tree that I started masking the whole region from 22194 to 22217 (S:211-218) in BA.1.  I regret that we may have missed some actual variation in that region, but without that masking, the BA.1 branch would be a mess and many more sequences would not be placed in the correct sublineages.

* large branches caused by common amplicon dropout/contam false reversions that start to repeat the diversity of their enclosing lineage: back in the Delta days, @russcd and I (and probably others) started to notice "mini-Deltas", i.e. branches separate from the main B.1.617.2 branch whose sub-branches contained multiple recognizable AY.* mutations, implying that their sequences probably should be placed in those different AY.* branches and not on some branch that started with reversions (or worse, began close to the root of B.1 with only a subset of B.1.617.2 mutations).  Over and over again, these "mini-Deltas" would attract more sequences, gradually acquiring more of the missing B.1.617.2 mutations until they were pulling large quantities of new sequences away from the main B.1.617.2 branch.  For branches that started out close to B.1 with a few mutations, branch-specific masking was not enough because there were no reversions to mask; I had to simply exclude sequences that were clearly very incomplete Deltas with a lot of reference back-filling.  With Omicron, there were so many mutations that it was rare for anything to consistently root nearer to B.1(.1) -- especially after I started automatically excluding sequences with an unbelievably small number of mutations for their collection date.  But there are many possible combinations of false reversions, hence many "mini-BA.1" and "mini-BA.2" branches.  This was especially frustrating in BA.2.75, so on that branch I mask out nearly all possible reversions, at the cost of misrepresenting some sites for recombinants placed on that branch.

When there's not an obvious "mini-VoC" pattern, just a branch that starts out with reversions or a suspicious streak of substitutions in consecutive bases, or a wandering branch from recombinant-land, it's definitely more of a judgment call, but if somebody complains on pango-designation, I'll try to fix it.  🙂 

The pangolin tool has always masked the untranslated regions at the beginning and end of the genome, bases 1-265 and 29674-29903.  Problematic Sites masks fewer bases at the beginning & end, bases 1-55 and 29804-29903.  There are some real lineage-associated mutations in the UTRs, such as B.1's C214T, Delta's G210T and G29742T, and those Delta mutations were handy for establishing breakpoints in Delta/Omicron recombinants, so I've been reluctant to mask the entire UTRs.  But I've noticed more trouble with noisy UTR sites in Omicron (perhaps because I spent more time looking), so I've been masking more of them in Omicron.

**Comment by AnonymousUserUse** [comment]
@AngieHinrichs Thanks for the detailed explanation.
Both Pangolin and Nextclade mask the whole untranslated regions and deletions & insertions; in contrast, Usher masks fewer bases at the beginning & end, and also involve deletions & insertion as long as it is not masked explicitly. Do I understand it correctly?

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs , @corneliusroemer did the right thing in designating two lineages and not one, i saw then he started deeper in the branch to distinguish the two i think it was a great idea.

**Comment by AngieHinrichs** [comment]
> Usher masks fewer bases at the beginning & end, and also involve deletions & insertion as long as it is not masked explicitly. Is that correct?

Almost, but the situation with deletions/insertions is a little more complicated.  

UShER does not have a concept of deleted or inserted base; there is only the coordinate system of the reference, and each base can only be A, C, G, T or some uncertain combination of those.  Ambiguous base calls are represented in sequence fasta by letters like R for "either A or G", or N for "A, C, G or T" (IUPAC [ambiguity codes](https://cran.r-project.org/web/packages/MLMOI/vignettes/StandardAmbiguityCodes.html)).

When a sequence with a deletion is aligned to the reference, "-" is used as a placeholder for the deleted base in MSA output.  For UShER we treat "-" the same as N.  

Insertions are just completely omitted from the alignment (that applies to pangolin too, not sure about nextclade).  Representing insertions would require expanding into a new coordinate space (and new dimension of potential software bugs).

The problem is that sometimes there is truly a deletion or insertion in the physical RNA molecule, but due to suboptimal genome assembly pipelines, the fasta sequence appears to have substitutions (like A to G) when aligned to the reference genome.  Then UShER starts building branches based on those "substitutions" -- unless they are masked out.

If sequence fasta has N or reference bases in the deleted region, then it does not cause problems for UShER -- only for people trying to make sense of when a deletion occurred relative to other mutations, and whether a given branch/lineage truly has the deletion or not.

A future version of UShER is being planned that will have deletions and insertions in its vocabulary... and I sure hope all the genome assembly pipelines can be improved to correctly process deletions and insertions by the time that version of UShER comes out.  🙂

**Comment by AnonymousUserUse** [comment]
@corneliusroemer 
Now it is clear that XBB.1.9.1 is defined by the mutation S:486P following C11956T. So I think in the staging tree https://nextstrain.org/staging/nextclade/sars-cov-2, C11956T should be added on the place to separate XBB.1.9.1 and XBB.1.9.
![image](https://user-images.githubusercontent.com/113214374/217975385-f5175220-3dbf-4002-b09f-42e6c7b4b6c7.png)
