### ISSUE TITLE
XBB.1.5 with S:F456L and Orf1b:A1643V apparently growing fastly in North Carolina , USA (48 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1614]
XBB.1.5 + S:F456L is showing advantage in the USA vs XBB.1.5:
<img width="929" alt="Schermata 2023-02-03 alle 14 11 52" src="https://user-images.githubusercontent.com/87669813/216611837-3fe7c8c8-27d8-4cc8-9d6c-5dc9b73564c9.png">
https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nextcladePangoLineage=XBB.1.5*&aaMutations1=S%3Af456L&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&

This could be due the fact it is spreading faster or instead could be a "cluster" effect we have already seen multiple times.
The fact its spread is limited to NC,Usa could hint to this second choice.
But still being a big escape mutation i think it is better to track it and eventually designate it early.

**Tree**:
<img width="1159" alt="Schermata 2023-02-03 alle 14 13 17" src="https://user-images.githubusercontent.com/87669813/216612123-953f47c1-87e2-4e4a-aa8b-57877f0cb377.png">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1fe76_d08360.json?c=gt-S_456&label=id:node_7948420

**Defining mutations**: Orf1b:A1643V + S:F456L

**Gisaid query**: NSP14_A119V,Spike_f456L,Spike_F486P

Sequences: 29 all from North Carolina
EPI_ISL_16382307, EPI_ISL_16516179, EPI_ISL_16666034,
EPI_ISL_16666240, EPI_ISL_16668468, EPI_ISL_16668784,
EPI_ISL_16670511, EPI_ISL_16670915, EPI_ISL_16684579,
EPI_ISL_16687062, EPI_ISL_16687113-16687115, EPI_ISL_16706979,
EPI_ISL_16710451, EPI_ISL_16710497-16710498, EPI_ISL_16729952,
EPI_ISL_16729961, EPI_ISL_16729971, EPI_ISL_16742316,
EPI_ISL_16742323, EPI_ISL_16742474, EPI_ISL_16742476,
EPI_ISL_16742587, EPI_ISL_16742597, EPI_ISL_16763483,
EPI_ISL_16763523, EPI_ISL_16765064

**Comment by corneliusroemer** [comment]
Good spot! But change the title to North Carolina as it's still entirely local to that region.

Unfortunately, I don't think we have any good methods yet to estimate growth advantages from such a small cluster taking into account lack of diversity. One would want to compare it to other clusters that once looked similar and then check how they ended up after a few weeks or months.

What do we know about the Spike mutation?

Seems to be two or three labs, so likely to be real.

**Comment by corneliusroemer** [comment]
It's a T22928C (C->T) mutation, one of the frequent ones.

The S:F456L mutation has the following effect according to Bloom lab calculator (measured directly on BA.2 hence only with limited applicability given other backbone mutations acquired since):

Immune escape: +0.11 (~10% of the remaining neutralizing antibody fraction is escaped)
ACE2-binding: -0.82 (~7 fold reduction in ACE2 binding affinity)

If these numbers are roughly correct, which is not necessarily true due to epistasis, this represents a big decrease in ACE2 affinity, to a worse level than before the S:F486P mutation but with additional immune escape. The ratio of the two scores +0.11 escape and -0.82 reduced binding is one that could be borderline beneficial, it's like that of some mutation that were beneficial in the past. If it turns out to be beneficial, it would represent an interesting 2-step move of XBB: first increasing ACE2 binding affinity through S486P, then trading that increase in affinity for immune escape. It's not surprising that 456L has not been seen much until now as the ACE2 binding decrease is rather large, making this mutation only survivable to viruses with already high ACE2 affinity.

456L appeared in some Delta lineages (AY.122) just before Omicron arrived.

It's been trending upwards recently in a few lineages in Chile, Israel and the US, most notably in BQ.1.2, though it has not been a defining mutation of any Pango lineage yet.

Let's monitor for now and designate if more sequences arrive, especially from other states/countries.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer you're right  456 popped up at the end of the AYs era usually in combo with S:455 @C19850727 spotted and tracked a handful of them. 
And  i remember 456 being cited very early in the pandemic as a possible way to escape but at high fitness costs for the virus.  So you confirmed my vague memories! thank you.

**Comment by oobb45729** [comment]
L455 and F456 are important for ACE2-binding. They fill a gap between RBD and ACE2. To optimize ACE2-binding, these two residues need to be: 1. hydrophobic. 2. not too large or too small. Take a look at how BA.2 RBD interacts with ACE2. [(PDB: 7XB0)](https://www.rcsb.org/structure/7XB0)
F455+F456 might be too large while L455+L456 might be too small. However, L455F+F456L means that L455 and F456 swap their places, so they as a whole wouldn't be too large or too small.
My theory that why L455F and F456L/V are often together is similar to the reason for F486P. It starts with L455F or F456L/V which results in immune escape but is detrimental for ACE2-binding, which leads to higher selection pressure for the other mutation.
Someone needs to experiment on how L455F+F456L/V would change ACE2-binding capability.
And L455W+F456L/V too since we saw L455W+F456L in wastewater lineages. and two chronic patients of BA.1.23 (with L455W) independently gained F456L. https://www.medrxiv.org/content/10.1101/2022.05.25.22275533v2.full-text
There are SARS-Cov like strains with W+V on these two residues and they have pretty strong ACE2-binding capability.

**Comment by corneliusroemer** [comment]
No new sequences uploaded of this in the past 2 days.

**Comment by FedeGueli** [comment]
@corneliusroemer yes i checked that too, usually beyond NY there are not so much sequences from USA in the weekends. But still hoping that  it has stopped growing.

**Comment by FedeGueli** [comment]
5 new sequences uploaded today from North Carolina , from two different labs all collected recently between 17 -18 january

@corneliusroemer @thomasppeacock @InfrPopGen @AngieHinrichs

**Comment by FedeGueli** [comment]
48 sequences as today @corneliusroemer it is growing really fast.
looking at Gisaid if restricting to samples collected after 20 january its share grow to around 4% (taking in account the whole month of January it is just 2% this meas inequivocally it is growing )

**Comment by corneliusroemer** [comment]
But a raw doubling per week is expected just based on XBB.1.5 alone. So not convinced this grows faster than XBB.1.5 - but let's designate to monitor.

**Comment by FedeGueli** [comment]
Added to collection24 now it seems in the high range of XBB.1.5 sublineages.

<img width="1297" alt="Schermata 2023-02-10 alle 16 12 48" src="https://user-images.githubusercontent.com/87669813/218126610-b88b23f7-9491-4f37-ba3d-3686edbf2a11.png">
