### ISSUE TITLE
BA.5.11 with 11 mutations and a missing deletion. 221 samples, mostly Europe. (recombined with XBK recently)

### ISSUE THREAD

**Issue by JosetteSchoenma** [cov-lineages/pango-designation#1640]
**Description:** BA.5.11 sublineage/saltation?, 221 samples
I have been keeping an eye on this one for a while. I was thinking of leaving it, until it recombined with XBK recently. First part from this sublineage, which contains most mutations. The recombination went from 1 to 5 samples in Denmark recently. I will describe it in another issue.
**Nucleotide mutations:** C1302T, G1463A, G2036T, G2095A, C3688T, G15372C, T16083C,  C27476T, C29077T
**No**: del27669_27807
![image](https://user-images.githubusercontent.com/94831035/217835844-b176d0cf-61e4-4758-b380-4db2fef5dbf6.png)

**Earliest sequence:** 2022-09-17 from Switzerland
**Most recent sequence:** 2023-01-25 from Denmark
**Countries circulating:** Switzerland 80, France 57, Germany 30, The Netherlands 8, plus some in 9 other European countries, USA 2, Australia 1.
**GISAID query:** Spike_L452R, Spike_R346T, -Spike_N658S, C3688T, G2095A
**Covspectrum query:**
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C3688T%2CG2095A&nextcladePangoLineage=BA.5*& 
**Evidence:**
**USHER tree:** Yellow dots, called BA.5.2_no28330 by Usher. Selected samples to show how it compares to BA.5.11.
![image](https://user-images.githubusercontent.com/94831035/217836753-04c2a19d-3828-4ed4-80bd-ce8c078bbe71.png)

Black dots
![image](https://user-images.githubusercontent.com/94831035/217836899-ff6649a5-843f-43b8-8315-c259178303c9.png)
**Growth advantage:**
None left. It is shrinking fast. Proposing it to be able to designate the recombination with XBK correctly.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.64 with 206 newly designated sequences, and 0 updated. Defining mutation C1302T (ORF1a:T346I) (following C3688T). Interestingly, this has C1627T, C27389T and G22599C like BA.5.11, but also G15372C. At the moment, this looks like it arises on the BA.5.2 branch that lacks A28330G.

**Comment by FedeGueli** [comment]
@InfrPopGen are you sure it is BA.5.2? to me it is BA.5.11? BA.5.2 starts with A28330G. We had already BA.5.10 and BA.5.11 designated after C1627T

**Comment by AngieHinrichs** [comment]
> We had already BA.5.10 and BA.5.11 designated after C1627T
> 
> Or better maybe designating the entire branch with C1627T + G15372C as BA.5.12

Good point.  It looks to me like G15372C came before G22599C (S:R346T), so this is distinct from BA.5.11.  But BA.5.10 and BA.5.11 were not considered sublineages of BA.5.2 despite having C1627T, so should this one be?

In hindsight the BA.5.2_no28330 label was perhaps misleading, although I still suspect that at least a few of the sequences on that BA.5 > C1627T branch might really have A28330G and be BA.5.2, but seem not to have it due to dropout.  There are a couple places on the branch that "acquire" A28330G after other mutations.  But if my label is leading to unclear designations, then I can remove it.  What do you think @InfrPopGen @corneliusroemer ?

**Comment by JosetteSchoenma** [comment]
@AngieHinrichs Why do you think G15372C came before G22599C (S:R346T)?

**Comment by JosetteSchoenma** [comment]
So, to summarize, 

-BA.5.11 and this one both have S:R346T (G22599C) and a 512-520 deletion, which BA.5.2 does not have.

-BA.5.11 and this one both do not have a A28330G mutation that, that BA.5.2 does have.

-BA.5.11 and this one do both not have a ORF1b:T1050N mutation that BA.5.2 often has. (Correct @FedeGueli ?)

-BA.5.11 has a 22669-27807 deletion that this one and BA.5.2 do not have.

-Only this one has a G15372C

-All 3 have a C1627T

**Comment by JosetteSchoenma** [comment]
To me it seems more likely that this one is a BA.5.11 sublineages than a BA.5.2 one, but BA.5.12 looks like the best solution.

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs Why do you think G15372C came before G22599C (S:R346T)?

Because there are many sequences that have BA.5 > C1627T, C27389T and G15372C without having G22599C, and the dates of the first sequences on the branch with G15372C go back quite far, to May 2022.  Then there are some sequences with G15372C and G22599C from July and August 2022.  In BA.5.11, the earliest dates are September 2022.  G22599C also seems to pop up quite frequently in genome sequences relative to less advantageous mutations, that are less likely to lead to increased transmissions and be detected by surveillance sequencing.  I.e. it's not surprising anymore to see G22599C and other advantageous Spike mutations pop up on multiple branches independently, but it would still be surprising to see some random boring mutation do that (we would be more suspicious that it's an artefact/error).

Here is a view of the branch with BA.5 > C1627T > C27389T, colored by nucleotide 22599:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-1640.json?branchLabel=nuc%20mutations&c=gt-nuc_22599&label=id:node_7286385
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/186983/220734790-51e5f55f-ba37-4cbb-bdc0-bd9cc45ee170.png">

The blue branch at the bottom (G22599C) is BA.5.11.  You can see that in the larger branch that starts with G15372C, your cluster is not the only one with G22599C, and in fact there's a branch with 142 sequences with G22599A.  It's a busy nucleotide.  🙂

**Comment by JosetteSchoenma** [comment]
Thanks @AngieHinrichs for explaining so clearly. I agree that R346T pops up everywhere!

So, unless you want to rename existing lineages and designate a new parental lineage for BA.5.11 and this one (and maybe others), naming this one BA.5.12 seems the best solution. Right?

**Comment by InfrPopGen** [comment]
The C27889T and T22917G, following G23040A, is consistent with BA.5.2, but they don't seem to be synchronous; thus, this one doesn't exactly match up with BA.5.2. Also, I think BA.5.2 was designated without C1627T. Consequently, re-designating this one as the next BA.5.x wouldn't be a bad idea.

**Comment by AngieHinrichs** [comment]
> Also, I think BA.5.2 was designated without C1627T

Good point!  The designation comment for BA.5.2 mentioned only A28330G (ORF9b:D16G) -- which at the time came after C1627T in the tree, although since then it switched to A28330G followed by C1627T (leaving the BA.5.2 > C1627T branch behind, which is probably why I gave it the label BA.5.2_no28330).  All of the original designated sequences for BA.5.2 (from commit b7a0fe7) have both C1627T (at least imputed) and A28330G.  So that's the way I specified BA.5.2, requiring both C1627T and A28330G, although in retrospect maybe only A28330G matters?

There are only 425 sequences on the BA.5 > A28330 branch excluding the A28330 > C1627T branch which has the label BA.5.2.  The BA.5 > C1627T branch now has 14,605 sequences, of which 7,368 are BA.5.11, 3,377 are BA.5.10 (or sublineages DF.*), and 263 are on the branch for this new lineage.  Both branches have a wide range of mid-to-late 2022 dates near the start so I don't see a clear winner for which of C1627T and A28330G really came first for BA.5.2.

But I will remove the BA.5.2_no28330 label (which will cause some sequences to get BA.5 instead of BA.5.2 assignments after the next release of pango-designation and then pangolin-data & pangolin-assignments) because it's misleading.

And I agree re-designating this to BA.5.12 is a good idea.

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs great analysis, i agree with you. I remember quite clearly that at the start of BA.5 i was digging a bit on its branches and C1627T had some branches without A28330G , and i think i proposed one or two of them but they then died off.

**Comment by InfrPopGen** [comment]
Now re-designated as BA.5.12.

**Comment by AnonymousUserUse** [comment]
Milestone BA.5.12 is missing @InfrPopGen
