### ISSUE TITLE
BR.2.1 x XBF recombinant (16 sequences as of 2023-03-06, from 5 states of Australia)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1669]
This potential recombinant was first spotted by @FedeGueli at #1653 . Many thanks!

### Description
**Recombinant between**: BR.2.1 and XBF
**Earliest sequence**: 2023/01/16 (Australia-VIC)
**Most recent sequence**: 2023/02/08 (Australia NSW)
**Countries circulating**: all sequences are from Australia, but from 4 different states, including NSW (6/11), VIC (2/11), SA (2/11) and QLD (1/11).
**Potential breakpoint**: NSP16 or Spike RBD (21055-22916)

**Mutation profile** (private mutations are in yellow color):
![image](https://user-images.githubusercontent.com/86835836/219830593-b554f0b6-62cf-4ecc-83c9-f154b383fe22.png)
**Private mutations**: G21305A, T28137A (10/11)
**GISAID and Cov-spectrum query**: C5183T, -C21304A, G21305A, T23031C, A23013C, T23018C, T23019C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/219830787-7f67bf3c-098c-4bb6-b751-122f0d5eb91e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40be1_51b00.json?c=gt-nuc_21305&label=id:node_8267435

### Genomes:
EPI_ISL_16887591, EPI_ISL_16887750, EPI_ISL_16887834, EPI_ISL_16899159, EPI_ISL_16902439, EPI_ISL_16902451, EPI_ISL_16910114, EPI_ISL_16910117, EPI_ISL_16947373, EPI_ISL_16947398, EPI_ISL_16947423

**Comment by FedeGueli** [comment]
Hi @c19850727 thanks for spotting! i think it is the same i proposed here: #1653

**Comment by c19850727** [comment]
Thanks @FedeGueli ! apparently I invented the wheel again. Will close this issue.

**Comment by FedeGueli** [comment]
@c19850727 would you like to keep this open? i think it is more complete than mine!

**Comment by c19850727** [comment]
@FedeGueli Okay then. Let me edit the proposal to give appropriate credits.

**Comment by corneliusroemer** [comment]
Worth designating once it gets a bit bigger

**Comment by FedeGueli** [comment]
12 as today: last one again from Australia - NSW

**Comment by FedeGueli** [comment]
14 sequences as today two new ones came from NSW

**Comment by c19850727** [comment]
15 sequences I think? @FedeGueli

**Comment by c19850727** [comment]
16 now. Newly emerged in ACT.

**Comment by corneliusroemer** [comment]
Going to designate this.

If I understand correctly, the 3' end (downstream of S:452) could be from CJ.1 or XBF - since XBF got that part from CJ.1 and there are no extra private mutations in that region in this recombinant that are only found in either of CJ.1 or XBF, it's not possible to tell which one donated.

I'll state that it's XBF because XBF is more common in Australia, but in either case, functionally, we have a "within BA.2.75" recombinant here: BR.2.1 is BA.2.75.4.2.1, while CJ.1 is BA.2.75.3.1.1.1.1

The Spike is CJ.1 like: (346T, no 452R, 486P, 490S), but it has lost the BA.2.75.3 defining ORF1b:V1706I, and also switched out some synonymous substitutions:
lost G261A, gained C9532T, G19962T, C21054T

So overall more or less just a CJ.1 (which has recently been on the rise in South Korea to ~5%) but without ORF1b:V1706I

**Comment by JosetteSchoenma** [comment]
XBY
