### ISSUE TITLE
Potential lineage related to B.1.635 with Spike  H655Y 

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#167]
Sublineage of B.1 (7 samples)
Earliest sequence: 30.04.21 (Mexico)
Most recent sequence: 17.06.21 (Mexico)

Shares all the mutations of B.1.635 except for :
NSP13:V479V (Synonymous mutation at Nucleotide 17673)
NSP15:S147I
ORF7a:P34L

Have the exclusive mutation pattern not present in B.1.635 : 
NSP2:I101S
NSP3:T237I
NSP10:T51I
NSP13:L297F
NSP14:H283H
S:H655Y
ORF3a:L86S
M:A69V
ORF7a:L116F
ORF8:D113Y
N:S2S

Gisaid references :
EPI_ISL_1811419
EPI_ISL_2091368
EPI_ISL_2681278
EPI_ISL_2681282
EPI_ISL_2942533
EPI_ISL_2942535
EPI_ISL_2970056

Usher tree showing the split from B.1.635 :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2674b_9b0760.json?c=gt-nuc_17673,20060,27494&label=nuc%20mutations:A3904T,A11430G,A16534G,C21618T,C21707T,C22338G,T22912G,G22992A,G26709A,A28273T,G28514T,G28917T

![image](https://user-images.githubusercontent.com/80166370/128088868-e356db41-3e81-4177-9e46-f56bfe065444.png)

**Comment by chrisruis** [comment]
Thanks @shay671. These 7 sequences are currently designated B.1.635. As your tree above shows, there are 2 subclades within B.1.635 but these are not distinct enough to warrant separate lineages at this stage. We'd therefore recommend that these sequences continue to be referred to as B.1.635

**Comment by shay671** [comment]
Hi @chrisruis   and thank you for your response.  
I would like to get your idea regarding to what is seen here: 

 we got here a lineage that somewhere was split into 2 clades according to the tree. The consensus of both of them is 15 mutations. 
 
Those clades are clearly distinct from one another. 
 
No stepwise process was seen (mostly absent in the upper clade in the tree).
 
one has 6 extra mutations  over the consensus. 4 of which are Non synonymous and 1 is highly converged with many other distinct variant. 

And here is my thought - knowing what we saw in other variants, it is not unlikely that sometime maybe a third distinct subclade will emerge, will it also be B.1.635 ? is it matter the added mutational signature it will have over the consensus?

**Comment by chrisruis** [comment]
Hi @shay671. These are the rules based on which we designate new lineages: https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/

We designate new lineages based on epidemiological events rather than mutations (although these events can include the acquisition of a set of mutations of interest). In this case, this clade warrants a lineage designation due to the epidemiological event of being introduced into Mexico with onward transmission. This event is shared by both of the subclades. While there are mutations separating the subclades, they are not sufficient in themselves to warrant a new lineage. So that's why in this case, under the Pango rules, all of these sequences should be designated as B.1.635.

Hope that helps.
