### ISSUE TITLE
Sudden Emergence of XBB.1.9.1+orf1a:G963S in England(27 seqs)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1746]
Sublineage of:XBB.1.9.1
Earliest Seq: EPI_ISL_16855658 2023.1.30(UK)
Latest Seq:EPI_ISL_17153729 2023.2.28(UK)
No. of seqs: 27 (26 UK, 1 Israel)
GISAID query: G23958T, G3152A, A29020G
mutations on top of XBB.1.9.1: C11956T,G23958T(N:T362I), A29020G,G3152A(orf1a:G963S)

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c31c_a86940.json?c=gt-ORF1ab_963)

this one is suddenly growing superfast and appears in multiple labs in England.

<img width="1375" alt="Screen Shot 2023-03-10 at 09 43 09" src="https://user-images.githubusercontent.com/10445944/224202713-d72196e6-0490-4153-95fc-5a1044c2d162.png">

<img width="672" alt="Screen Shot 2023-03-10 at 09 57 43" src="https://user-images.githubusercontent.com/10445944/224203729-51b2bc8d-4b29-4201-9c0c-500f5c92b83d.png">

**Comment by corneliusroemer** [comment]
It's normal for things to appear to grow fast in England as they use a very clustered sequencing approach. This has been discussed for a long time. Given the clustered nature of English sequences. As a rule of thumb, divide English sequence numbers by 10, that's how much fewer there are for statistical significance. 27/10 ~ 3 -> insignificant (at this point in time)

Also that Spike in the end is simply because of how few sequences there are. This is mostly noise.

It going up is because it's an XBB.1.5. So lots of reasons why this isn't something that deserves attention at this point in time.

**Comment by aviczhl2** [comment]
> It's normal for things to appear to grow fast in England as they use a very clustered sequencing approach. This has been discussed for a long time. Given the clustered nature of English sequences. As a rule of thumb, divide English sequence numbers by 10, that's how much fewer there are for statistical significance. 27/10 ~ 3 -> insignificant (at this point in time)
> 
> Also that Spike in the end is simply because of how few sequences there are. This is mostly noise.
> 
> It going up is because it's an XBB.1.5. So lots of reasons why this isn't something that deserves attention at this point in time.

Thanks for the information on UK sampling strategy. I didn't know that so sorry for the disruption.

This one was sampled by 3 different UK labs. Does the clustering sample nature of UK holds for every single lab, or does it hold even for multiple labs?(i.e. one cluster may be sent to multiple labs)
