### ISSUE TITLE
XBB.1.5.16 Sublineage with S:T284I, S:R403K, S:L513F, ORF3a:A31V, ORF3a:T269M, ORF1a:P309S (15 seq, Mar 24)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1751]
**Description**
**Sub-lineage of:** XBB.1.5.16
**Earliest sequence:** 2023-1-14, USA, Illinois — EPI_ISL_16681042
**Most recent sequence:** 2023-2-28, USA, Ohio — EPI_ISL_17181967
**Countries circulating:** USA (9) in US Midwest states of Ohio, Illinois, and Kentucky 
**Number of Sequences:** 9
**GISAID AA Query:** Spike_F486P, Spike_R403K, Spike_L513F
**GISAID Nucleotide Query:** T14766C, A24430C, C25484T
**CovSpectrum Query:** Nextcladepangolineage:XBB.1.5* & [5-of: T14766C, A24430C, C25484T, C1190T, C22413T, G22770A, C23099T, C26198T]
**Substitutions on top of XBB.1.5.16:**
**Spike:** T284I, R403K, L513F
**ORF3a:** A31V, T269M
**ORF1a:** P309S
**Nucleotide:** C1190T, C22413T, G22770A, C23099T, A24430C, C25484T, C26198T
 
**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/XBB.1.5_T284I_R403K_L513F_subtreeAuspice1_genome_390af_bf7a10.json
 
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/33738461/224485820-897222be-316e-493e-a8a5-d42c13799875.png">

**Evidence**
Mini-saltation lineage of XBB.1.5.16 featuring seven nucleotide mutations, six of which are non-synonymous. Of the three spike mutations, two are in the RBD and one in the NTD. Two ORF3a mutations in a single branch is uncommon as well. Th simultaneous addition of an ACE2-affinity-enhancing mutation (R403K) and an ACE2-affinity-decreasing mutation (L513F) here—one not associated with antibody evasion to my knowledge—seems to suggest that ACE2 affinity that is too high is deleterious. Apart from a very small number of singlets with no evidence of having been transmitted, I'm not sure I've ever seen a variant with pre-existing high ACE2 affinity acquire an ACE2-affinity-increasing mutation.
 
XBB.1.5 is possibly the first variant to unquestionably gain a large growth advantage due to an increase in ACE2 affinity. Neutralization studies show S486 and P486 to be approximately equivalent in terms of antibody evasion, but as Jesse Bloom and others have described, the S486P substitution results in a large increase in ACE2 binding strength, catapulting XBB.1(.5) from the bottom of the extant-lineage ACE2-affinity rankings to near the top. 
 
But can ACE2 binding strength be too high? Or is stronger ACE2 binding always advantageous in terms of evolutionary advantage? The simultaneous addition of ACE2-affinity-reducing escape mutations and ACE2-affinity-enhancing mutations is by now a well-recognized pattern in SARS-CoV-2. This has generally been viewed in one of two ways, which amount more or less to the same thing in my view, though they tacitly imply different temporal sequences:

1. Immune-evasive mutations reduce ACE2 affinity to a level incompatible with transmission and therefore require the (subsequent?) addition of ACE2-affinity-increasing mutations to be successful
 
2. ACE2-affinity-increasing mutations provide a sort of “evolutionary credit” to the virus, which it (subsequently?) spends on immune-evasive, ACE2-affinity-reducing mutations, which enhance fitness.
 
Both of these descriptions seem accurate to me, but I’d like to propose a third point of view, which supplements the others by emphasizing a possibly overlooked factor, which is that too much ACE2 affinity might be as harmful as too little.
 
The mutational dynamics of designated variants and chronic-infection saltation sequences seem to me to suggest that beyond a certain point, increased ACE2 affinity is highly deleterious. I suspect the reason XBB.1 saw such a huge fitness increase with S486P was because it had such low ACE2 affinity to begin with, well below the optimal level (whatever that might be). S:S486P brought XBB much closer to optimal ACE2 affinity, but I think another, similarly large increase would be deleterious. 
 
S:R403K is one of the few mutations known to greatly increase ACE2 affinity (on a BA.2 RBD background). It’s not surprising, therefore, that R403K has rarely been seen in XBB.1.5. In fact, P486 and R403K have only ever appeared together in 14 sequences, nine of which are in this lineage. The others are all singlets with the partial exception of two BA.2.12.1’s that are part of a fascinating, mysterious lineage circulating in Chile, which @Sinickle aptly describes in issue #1625. 
 
The addition of R403K by itself would, I suspect, give XBB.1.5 an untenably high ACE2 affinity and prevent it from circulating at all. However, in this circulating lineage, R403K is accompanied by S:L513F, which according to the Bloom Lab RBD heat map, reduces ACE2 binding strength. The fact that the only lineage with S:F486P and S:R403K that we know has transmitted also possesses a mutation that greatly reduces ACE2 affinity seems to me a strong piece of evidence in favor of the hypothesis that ACE2 binding strength can be deleteriously high.

![image](https://user-images.githubusercontent.com/33738461/224485860-f6da89b7-f1b7-442f-92a6-2e45a1b1d385.png)
 
**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_16681042, EPI_ISL_16835959, EPI_ISL_17023204, EPI_ISL_17023295, EPI_ISL_17099192, EPI_ISL_17179977, EPI_ISL_17180097, EPI_ISL_17180645, EPI_ISL_17181967
</details>

**Comment by FedeGueli** [comment]
Thx @ryhisner for proposing it, even if it is already around from a bit and likely it is not super fast its mutational profile is very interesting!

**Comment by oobb45729** [comment]
Unlike K417N or F486S, L513F is an RBD-destablizing mutation in the RBD core, and the reason of the ACE2 affinity loss is due to the RBD being unstable. The RBD-destablizing effect way too large that I don't think I've seen mutations like that in successful lineages before. L368I is near L513F, but I doubt it would be able to rescue it.

**Comment by oobb45729** [comment]
For ACE2-affinity-increasing mutations, I have a different theory. Prior to S486P, there weren't many cases of a single ACE2-binding-enhancing mutation causing a large advantage for the variant over its parent. Maybe someone can provide more examples, but I recall one case that is A.2.5.3 with S477N over A.2.5. Mostly, ACE2-binding-enhancing mutations appear alongside multiple other spike mutations in successful lineages.
Why? Why didn't we see more cases of Alpha/Beta/Gamma with Q498R or Delta with S477N? I doubt the ACE2-affinity of Delta+S477N would be too high. Actually, Delta+S477N wasn't too rare, and it may have an advantage over Delta, but many other S1 mutations were more successful in Delta.
Here's my theory. ACE2-binding-enhancing mutations may boost infectivity but they are not the only type of spike mutations that can boost infectivity and they were often outcompeted by other mutations that can boost infectivity more. For Gamma, clearly having a furin site mutation was more important. For Delta, the focus was on NTD. A222V is probably a major infectivity-boosting mutation. B.1.177 only had two non-synonymous mutations over B.1, but it was able to outcompete some lineages with much more mutations.
For Omicron, the focus had shifted to immune escape since BA.2.12.1. However, in earlier BA.2 lineages there were spike mutations like I68T or F371Y showing growth advantages. Since they are not in spotlight recently, I speculate that they improve infectivity.

**Comment by oobb45729** [comment]
Why is S486P different? I speculate that other than increasing ACE2 affinity, S486P may have another function.
In WT 1-up RBD position, the K378 of the "up" RBD may interact with the E484 of the nearby "down" RBD. This would no longer work after E484A. In BA.1 and maybe BA.2, the interaction is replaced by π–π interaction between F375 and F486, which won't work after F486S. On the other hand, P486/V486/I486 probably still can have some hydrophobic interactions with F375, although it would be weaker than the π–π interaction.
The inter-protomer interaction of RBD is important. BA.2 have 7(!) changes in total at the interface between RBDs of the 3-down RBD position: S371F, S373P, S375F, T376A, D405N, R408S, Y505H. R403K would be another one there.

**Comment by FedeGueli** [comment]
15 on Usher as today, interestingly the most recent sequence as also S:T478R

<img width="1118" alt="Schermata 2023-03-23 alle 15 08 52" src="https://user-images.githubusercontent.com/87669813/227229728-90cd60e2-0aad-4994-acc5-609625a63543.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice9_genome_16efd_c479c0.json?c=userOrOld&label=id:node_7769128

**Comment by ryhisner** [comment]
Up to 20 sequences now and spreading beyond the US Midwest into the Northeast US (New York, Massachusetts). Still growing quite slowly, however. One sequence from South Carolina has S:I584V while the one from Massachusetts has S:K478R.

**Comment by ryhisner** [comment]
I think this has been designated as FG.1. Could we get a milestone on the issue to make this more clear? Thanks.
