### ISSUE TITLE
Large “BA.4.1" messy branch in usher

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1761]
It seems that there's a large ’BA.4.1‘ branch on usher which actually contains almost every omicron lineage, especially some of the most recent XBB* lineages in undersampled areas like India.

Shall call a fix for this, for many seqs on this large "BA.4.1" branch, their pango assignments are also incorrect, leaving nowhere to find their correct lineage.

I'm proposing this because there's a visible upwarding trend of India seqs belonging to this "BA.4.1" branch. This branch contains ~900 seqs, less than 0.1% of the total omicron seqs from BA.4.  

In samples from India collected from 2023-1-1~2023-1-31, 3/334(0.9%) belongs to this branch. However, in seqs collected from 2023.2.1 to now, 7/218(3.2%) are on this branch. 

 @AngieHinrichs

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1a4f6_16c260.json?branchLabel=Spike%20mutations&c=pango_lineage)
 
<img width="1405" alt="Screen Shot 2023-03-15 at 15 00 24" src="https://user-images.githubusercontent.com/10445944/225231937-a33d8b4e-04a8-46f9-95de-8379b43c00a2.png">

<img width="1392" alt="Screen Shot 2023-03-15 at 15 04 05" src="https://user-images.githubusercontent.com/10445944/225232075-48bc0882-a4c4-4ed3-b061-f996d78a80ac.png">

**Comment by FedeGueli** [comment]
The omicron mini-me trees are a known issue, in the past it was BA 5.1 to host one of these mini trees. i dont know how much is worth to spending time to resolve, it is like the trash bin of sequences, even if it is true that rarely se real recombinant is hidden there.

**Comment by aviczhl2** [comment]
> The omicron mini-me trees are a known issue, in the past it was BA 5.1 to host one of these mini trees. i dont know how much is worth to spending time to resolve, it is like the trash bin of sequences, even if it is true that rarely se real recombinant is hidden there.

7 out of 218 seqs (3.2%) from India sampled from 2023.2.1 to now belongs to this single branch. I'm simply wondering where their real positions are...

**Comment by AngieHinrichs** [comment]
Yes, that is an ugly one, thanks @aviczhl2 for pointing that out.  It has become an attractor for common Omicron amplicon-dropout false reversions.  I will remove some or all of those sequences so that it doesn't continue to attract sequences with matching combinations of false reversions.

In fact, many of those sequences in gray further out on the branch should have been excluded from the daily build due to too many reversions found by nextclade, but my nextclade-parsing script needed a tweak to recognize 23A as omicron (happy new year!).  So I will be removing ~15k mostly XBB.1.5-ish sequences with >5 reversions that I assume are distributed among various dropout "trash bins" across Omicron.

**Comment by aviczhl2** [comment]
it seems that this bug is fixed.
