### ISSUE TITLE
One more XBB.1.9(or XBB.1.9.1?) sub-lineage with S:486P and orf1ab:G993S,S:A701V (133 seqs, 23 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1808]
Sub-lineage of: XBB.1.9
Mutations on top of XBB.1.9: C12970T,G3242A(orf1ab:G993S),C23664T(S:A701V),T23018C(S:486P),C11956T
GISAID query: C12970T,G3242A,C23664T,T23018C
No. of Sequences: 100 (Australia 3 Austria 1 Bharain 4 Canada 1 Denmark 1 UK 39 France 2 Germany 1 India 2 Indonesia 1 Israel 3 Italy 1 Japan 3 Malaysia 2 Netherlands 3 Oman 2 Singapore 2 Slovenia 2 South Korea 3 Spain 7 USA 17)

First Seq: EPI_ISL_17081627(Bahrain) 2023-1-14
Latest Seq: EPI_ISL_17281417(UK) 2023-3-17

It has C11956T, so pango calls it XBB.1.9.1, but usher seems to be categorizing it  on a different branch after C12970T,G3242A and C23664T, as there are some seqs with C12970T but without S:486P.

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_6bfa_129ef0.json?label=id:node_7704809)
<img width="1392" alt="Screen Shot 2023-03-27 at 14 57 03" src="https://user-images.githubusercontent.com/10445944/227863812-69cea475-d890-4a98-904b-31b6bb317a8b.png">

**Comment by BorisUitham** [comment]
Also note that S:L5F is growing in this sublineage, which has also a greater growth advantage in normal xbb.1.9.1 without a701v https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3Aa701v&nextcladePangoLineage=xbb.1.9.1*&aaMutations1=s%3A5f%2Cs%3A701v&nextcladePangoLineage1=xbb.1.9.1*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@aviczhl2 i had a look at this one  i think it is XBB.1.9.1 , the only one sequence splitting it from being a XBB.1.9.1 sublineage is India/MH-ICMR-NIV-G-13067/2023|EPI_ISL_16997497|2023-02-02 too little in my view.
plus C11956T it is highly homoplasic so the C11956T + C12970T branch without S:F486P could be easily explained with that.
the same combo popped up more than 100 sequences (beyond the proposed here) since the start of the pandemic and C12970T is highly homoplasic having popped up everywhere everytime.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C12970T&

but lets wait for @corneliusroemer take and @AngieHinrichs view on this one. it would be weird if we will have a third sublienage of XBB.1.9+486P defined by a very homoplasic nuc mutation, but still weird things could be real.

**Comment by aviczhl2** [comment]
120 seqs now.

**Comment by aviczhl2** [comment]
133 seqs and additional country of Switzerland and Portugal.

**Comment by FedeGueli** [comment]
Designated FL.1 via https://github.com/cov-lineages/pango-designation/commit/21b1e910a3640decb6f43c208bc61630992dc4a4
