### ISSUE TITLE
XBB.1.5 sublineage C1376T (ORF1:P371S), A2000C, A2306T (ORF1a:L681F), C2507T (ORF1a:P748S) and C12651T (ORF1a:T4129I)

### ISSUE THREAD

**Issue by Urruti** [cov-lineages/pango-designation#1845]
Description
Sub-lineage of: XBB.1.5
Earliest sequence: EPI_ISL_16918404 Collection date 2023-01-29
Most recent sequence: EPI_ISL_17373059 Collection date 2023-03-23

Countries: Basque Country (Spain), New York (USA), Chile

We have found a cluster of XBB.1.5 with following mutations C1376T (ORF1:P371S), A2000C, A2306T (ORF1a:L681F), C2507T (ORF1a:P748S) and C12651T (ORF1a:T4129I) that may represent a new XBB.1.5 sublineage

There are at least 15 sequences uploaded to GISAID: 
Basque Country: EPI_ISL_17373059, EPI_ISL_17360656, EPI_ISL_17360482, EPI_ISL_17360483,	EPI_ISL_17284733, EPI_ISL_17373259,	EPI_ISL_17373196,	EPI_ISL_17284701,	EPI_ISL_17347481,	EPI_ISL_17347481, EPI_ISL_17231809, EPI_ISL_17232985
New York: EPI_ISL_17352577 and EPI_ISL_16918404
Chile: EPI_ISL_16987034

**Comment by Outpfmance** [comment]
@Urruti Explain XBB.1.5 sublineage with what in your issue title and indicate the number of sequences.
Among the GISAID sequences you provided, I only found 11 sequences.
Nextstrain: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_264bf_c193f0.json?f_userOrOld=uploaded%20sample
![Uploading DA7E10FD-7298-47D7-8C36-D7B78F1F944C.jpeg…]()

**Comment by FedeGueli** [comment]
Nice catch , a mini saltation.

**Comment by InfrPopGen** [comment]
Thank you for proposing this lineage. The relatively long branch to this clade is noteworthy; however as a candidate Pango lineage, it has shown negligible growth since proposal, and the relative growth disadvantages over the past three months reflect this, so this can be closed for now. Please request re-opening should this clade show clear growth advantages, or be implicated in some future epidemiological event of note.
