### ISSUE TITLE
XBB.1.11.1 sublineage with S:S27L and S:69/70DEL (87 seqs as of 2023-04-11, mainly Singapore)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1847]
I am not sure if this is an artefact, but at face value, it seems growing quite fast in Singapore. It has a ~60% growth advantage in Singapore in the last 2 months relative to XBB.1.5*:
![image](https://user-images.githubusercontent.com/86835836/230114458-b053b26d-2814-4416-ba9e-c17ed8b68329.png)

**Sublineage of**: XBB.1.11.1
**Earliest sequence**: 2023/02/24 (Singapore)
**Most recent sequence**: 2023/03/25 (Singapore)
**Countries circulating**: Singapore, local cases in majority, and also 4 with travel history to Malaysia

**Mutations on top of XBB.1.11.1**: ORF1a:T2016I (C6312T), A6616G, S:S27L (C21642T), S:69/70DEL (21767/21772DEL)

**GISAID and Cov-spectrum query**: A6616G, C6312T, C13968A

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/230120066-0273e03a-873a-4dde-9330-d471de8e804c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30a58_d86610.json?label=id:node_7733151

### Genomes:
EPI_ISL_17094224, EPI_ISL_17094273, EPI_ISL_17094311, EPI_ISL_17094315, EPI_ISL_17146509, EPI_ISL_17207380, EPI_ISL_17207382, EPI_ISL_17207384-17207388, EPI_ISL_17207390, EPI_ISL_17262189-17262190, EPI_ISL_17262232, EPI_ISL_17262238, EPI_ISL_17262246, EPI_ISL_17262249, EPI_ISL_17262257, EPI_ISL_17262279, EPI_ISL_17262335, EPI_ISL_17262347, EPI_ISL_17262393-17262394, EPI_ISL_17262401, EPI_ISL_17262437, EPI_ISL_17347055-17347064, EPI_ISL_17347066, EPI_ISL_17347068-17347069, EPI_ISL_17347071-17347074, EPI_ISL_17347076-17347079, EPI_ISL_17347224-17347227, EPI_ISL_17347229, EPI_ISL_17388458, EPI_ISL_17388509-17388511, EPI_ISL_17388532, EPI_ISL_17388542, EPI_ISL_17388557-17388558, EPI_ISL_17388598, EPI_ISL_17388602, EPI_ISL_17388652, EPI_ISL_17388685, EPI_ISL_17388687, EPI_ISL_17388735, EPI_ISL_17388740, EPI_ISL_17388769

**Comment by silcn** [comment]
This isn't S:24/27del, it's actually S:S27L on top of the S:24/26del and S:A27S (21633/21641del) that all BA.2 has. The nucleotide mutation that produces S:S27L is C21642T, but 21633/21641del followed by C21642T looks exactly the same as 21635/21643del.

29734/29759del is in all BA.2. S:69/70del is the new one.

**Comment by FedeGueli** [comment]
thz @silcn great expl.

**Comment by AnonymousUserUse** [comment]
For a better understanding for myself, I also make a table for the situation here.
Starting with S:23 = nuc:21629
Variant | Spike | Nucleotide
------ | ------ | ------
Wildtype | QLPSAY | CAATTACCCCCTGCATAC
XBB.1.11.1 | QSY | CAATCATAC
This issue | QLY | CAATTATAC

**Comment by c19850727** [comment]
Thanks @silcn and @AnonymousUserUse ! Duly edited.

**Comment by AngieHinrichs** [comment]
Editing @AnonymousUserUse's table to show several possible alignments to reference:
<pre>
                222222222222222222
                111111111111111111
                666666666666666666
                233333333334444444
                901234567890123456

Wildtype	CAATTACCCCCTGCATAC
XBB.1.11.1	CAAT---------CATAC
This issue	CAAT---------TATAC (alignment to reference of XBB.1.11.1's del plus C21642T)
This issue      CAATTA---------TAC (naive alignment to reference, right-shifted)
This issue	CAATT---------ATAC (naive alignment to reference, left-shifted)
</pre>
As @silcn said:
> 21633/21641del followed by C21642T looks exactly the same as 21635/21643del.

-- that's the right-shifted alignment to reference.  There's also the possibility of a left-shifted alignment to reference, 21634_21642del.

An alignment tool presented with the reference and these sequences is not going to know anything about XBB.1.11.1, so it won't produce 21633_21641del + C21642T because (under the most common scoring scheme) that has a penalty of 10 (9 gap bases plus 1 substitution) while the left-shifted and right-shifted gap solutions both have a penalty of 9 gap bases, so it's a toss-up between them and different alignment tools have different behaviors when it comes to left/right shifting ambiguities.

To UShER, all those gap bases will look like Ns... and it could easily get confused if it's getting inputs with a mix of left-shifted and right-shifted gaps (not to mention sequences with reference-backfilling or gaps of the wrong size), so watch out for odd behavior at bases 21642 and 21643 in particular.

**Comment by c19850727** [comment]
73 seqs as of 2023-04-08. Newly found in Australia-Vic, New Zealand and Korea.

**Comment by c19850727** [comment]
87 seqs as of 2023-04-11

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FP.1 with 29 newly designated sequences, and 0 updated. Defining mutations A6616G (and cryptic S:S27L (C21642T)) (following C6312T (ORF1a:T2016I)).
