### ISSUE TITLE
CH.1.1.2 sublineage with S:T478R, Orf7b:L31F, Orf9b:P51L, Orf1a:A385V, Orf1a:T1597I after Orf1b:V1852A, Orf1a:P2046S, orf1a:S1102G (13sequences)  

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1863]
This could be a classical english cluster, but same i think better to monitor these last CH.1.1 descendants.

In this case i m talking about a small CH.1.1.2 (S:T883I) sublineage that acquired stepwisely several Orf1ab mutations and finlly did a saltation acquiring S:T478R, Orf7b:L31F, Orf9b:P51L, Orf1a:A385V and Orf1a:T1597I all in a row.

Defining mutations:

CH.1.1.2 >> > Orf1a:S1102G (A3569G) > Orf1a:P2046S (C6401T) > Orf1b:V1852A (T19022C) > T15420C > C27654T > Orf1a:A385V (C1419T) , Orf1a:T1597I (C5055T), C8956T, C19029T, S:t478R (A22995G), Orf7b:L31F (C27849T), Orf9b:P51L (C28435T)

Tree:
![Schermata 2023-04-09 alle 09 49 02](https://user-images.githubusercontent.com/87669813/230760871-b08218de-d4ff-48b7-bb28-29c4217b855f.png)

![Schermata 2023-04-09 alle 09 48 30](https://user-images.githubusercontent.com/87669813/230760841-4943611a-c9a5-44f2-99c3-9bcb1d63c1ff.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_16959_25c8d0.json?c=gt-S_478&label=id:node_8145226

Gisaid query: C1419T, C19029T, C28435T

Sequences: 13 - all from England
EPI_ISL_17400319, EPI_ISL_17400325, EPI_ISL_17400330,
EPI_ISL_17400356-17400358, EPI_ISL_17400383, EPI_ISL_17400392,
EPI_ISL_17400396, EPI_ISL_17400403, EPI_ISL_17416813,
EPI_ISL_17423310, EPI_ISL_17423383

**Comment by ryhisner** [comment]
Note the approximately 3-month time difference between the two most closely related sequences and this new lineage, all in a country with very good surveillance. It looks like another example of prolonged infection leading to intrahost evolution and eventual transmission—though on a fairly small scale compared to the major saltation lineages. Since chronic-infections typically contain a high percentage of mutations that are adaptive in some way, I'd say this is another bit of evidence in favor of S:K478R being a beneficial mutation in the current environment.

**Comment by FedeGueli** [comment]
No new sequence came this week, likely a cluster , i will wait the next before closing it.

**Comment by FedeGueli** [comment]
It was the classical english cluster. closing it now.
