### ISSUE TITLE
FK.1 sublineage with ORF1b:L2580I, ORF1a:A1060T, T1465C, C18657T, A23416T, and C27804T first detected in New Zealand (111 total, 78 good seqs as of 2023-04-12; New Zealand, Australia, USA, Japan, Canada, France, Denmark, South Korea, UK)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#1881]
There may be an FK.1 sublineage with ORF1b:L2580I (NSP16:L183I, C21205A), ORF1a:A1060T (NSP3:A242T; G3443A), and synonymous nucleotide mutations T1465C, C18657T, A23416T, and C27804T first detected in New Zealand.

As of 2023-04-12, Cov-Spectrum reports 78 good-quality (111 total) FK.1+ORF1a:1060T+ORF1b:2580I+1465C+18657T+23416T+27804T sequences.
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ACH.1.1%2A+%26+ORF1a%3AA1060T+%26+ORF1a%3AL3829F+%26+ORF1b%3AL2580I+%26+S%3AD215G+%26+S%3AQ613H+%26+T1465C+%26+C18657T+%26+A23416T+%26+C27804T+%26+C29555T&nextcladeQcOverallScoreTo=29&

As of 2023-04-12, using data from the past 6 months in New Zealand where this lineage has been observed the most, CoV-Spectrum reports a relative growth advantage of 63% (confidence interval 33-93%) over the parental FK.1 lineage:
![Growth_FK 1+ORF1a_1060T+ORF1b_2580I+1465C+18657T+23416T+27804T_vs_FK 1_New_Zealand](https://user-images.githubusercontent.com/88959107/231600719-c173d54b-341b-4d26-b26f-76ac8c6b66dd.png)
Source: https://cov-spectrum.org/explore/New%20Zealand/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ACH.1.1*+%26++ORF1a%3AL3829F+%26+S%3AD215G+%26+S%3AQ613H+%26+C29555T&variantQuery1=nextcladePangoLineage%3ACH.1.1*+%26+ORF1a%3AA1060T+%26+ORF1a%3AL3829F+%26+ORF1b%3AL2580I+%26+S%3AD215G+%26+S%3AQ613H+%26+T1465C+%26+C18657T+%26+A23416T+%26+C27804T+%26+C29555T&analysisMode=CompareToBaseline&

As of 2023-04-12, UShER shows all of the CoV-Spectrum samples are on a two subtree with evidence of additional branching. Since the two branches include multiple similar mutations, notably ORF1a:A1060T and N:G34E, the two subtrees may be due to an UShER artifact and not two actual separate subtrees:
![UShER_CoV-Spectrum_FK 1+ORF1a_1060T+ORF1b_2580I+1465C+18657T+23416T+27804T](https://user-images.githubusercontent.com/88959107/231600778-863da05c-a6b5-44e2-9571-b7e2fa074fe5.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/2023/04/subtreeAuspice1_genome_CoV-Spectrum_FK.1%2BORF1a_1060T%2BORF1b_2580I%2B1465C%2B18657T%2B23416T%2B27804T.json?c=gt-ORF1ab_1060&label=id%3Anode_6276920

GISAID query: T1465C, G3443A, C11750T, C18657T, C21205A, A22206G, G23401T, A23416T, C27804T, C29555T

First reported GISAID sequence: New Zealand 2023-02-08 

Most Recent GenBank sequence: Denmark 2023-03-31

A zip archive of GenBank-formatted and derived metadata and FASTA files plus CoV-Spectrum derived UShER output files for these sequences is available at [Support_FK.1_ORF1a_1060T+ORF1b_2580I+1465C+18657T_23416T+27807T.zip](https://github.com/cov-lineages/pango-designation/files/11216525/Support_FK.1_ORF1a_1060T%2BORF1b_2580I%2B1465C%2B18657T_23416T%2B27807T.zip)

A CoV-Spectrum list of GISAID EPI ISLs for good-quality sequences is available at [gisaid-epi-isl-FK.1+ORF1a_1060T+ORF1b_2580I+1465C+18657T+23416T+27804T.txt](https://github.com/cov-lineages/pango-designation/files/11216531/gisaid-epi-isl-FK.1%2BORF1a_1060T%2BORF1b_2580I%2B1465C%2B18657T%2B23416T%2B27804T.txt)

**Comment by AnonymousUserUse** [comment]
Note: FK = CH.1.1.17, characteristic AA mutation M:S212G

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage FK.1.1 with 0 newly designated sequences, and 18 updated. Defining mutation G3443A (ORF1a:A1060T) (following G28374A (N:G34E)).

**Comment by FedeGueli** [comment]
150 as today the fastest non recombinant lineage

**Comment by FedeGueli** [comment]
@alurqu this lineage has also a deletion that USher seems to get as N:G34E while Gisaid and Covspectrum get it as N_G34del , this is quite relevant cause it gives  **Orf9b:G31R** too!

This seems really fast in New Zealand.

**Comment by alurqu** [comment]
Yes. I had noticed the ORF9b:G31R, but I wasn't quite sure how it fit into the lineage. Thanks for tracking it to the deletion.

And yes this appears to be fast in New Zealand. Since it is already seeded in several other countries, there may be a test of how well it does outside of New Zealand.

**Comment by corneliusroemer** [comment]
In my view this was designated to early too deep, there's nothing special about it. You shouldn't over interpret global growth advantages for lineages that are from single countries, especially islands (@alurqu @FedeGueli). Such statements: "150 as today the fastest non recombinant lineage" aren't helpful.

There's no a priori reason why this particular branch would have an intrinsic growth advantage over other branches.

Now some very deep branch has gotten the FK.1.1 label meaning any of the earlier splits cannot be given names anymore. Not super important because this lineage is unlikely to become big globally but in other situations this could cause issues.

We don't need every small island cluster in well-sampled countries to have a Pango name. One could argue to have the big top and bottom branches be FK.1.1 and FK.1.2 but even that would be somewhat over-specific given that there's no Spike and this is predominantly a New Zealand lineage (well-sampled, hence unlikely to become globally important over time as it spreads).

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/25161793/233798979-e989ba2d-c0e4-4651-8728-320c321b6c6d.png">

**Comment by FedeGueli** [comment]
Hi @corneliusroemer i disagree FK.1.1 is important to remark it is  the faster non XBB and the highest ranking in collections since XBB.1.5 took the lead. it did the same as in NZL in NSW where it doubled from nothing to 1% and in April to 2% notwithstanding Australia has already everything is fast right now.
So while it is clear it will not become dominant, it has an advantage versus the most of the old era XBB.1+486Pers and certainty against all its sibling lineages: for example check the interesting N:G34E/ORF9b:G31R one is far behind it. 
So while it is always good to designate at te start of a branch in this case is completely justified in my 2 cent view.
