### ISSUE TITLE
Proposal to redesignate B.1.631 as recombinant lineage XB

### ISSUE THREAD

**Issue by benjamincjackson** [cov-lineages/pango-designation#189]
Lineage renaming proposal: B.1.631 -> XB

by Ben Jackson

Description
(see also [this tweet](https://twitter.com/babarlelephant/status/1425859582958653442), brought to our attention by @thomasppeacock)

It seems that lineage B.1.631 is likely a recombinant lineage descended from B.1.627 and B.1.628. Here are some summaries for the two parental lineages from the Gisaid dataset as of 14th August:

B.1.627 (2021-02-27 - 2021-07-09):
```
   1 Costa Rica
  17 El Salvador
   7 Honduras
  45 Mexico
 104 USA
```

B.1.628 (2021-02-23 - 2021-07-28):
```
   1 Cayman Islands
   8 El Salvador
  25 Honduras
 358 Mexico
 398 USA
```

And here is the summary for B.1.631 as it is currently:

B.1.631 (2021-03-30- 2021-07-27):
```
   8 El Salvador
   1 Honduras
  18 Mexico
  50 USA
```

I took the earliest B.1.631-assigned genome with no missing data (USA/NY-PRL-2021_0419_02G09/2021; sampled on 2021-04-18) and found the closest single B.1.627 (USA/MN-UMGC-3398/2021; 2021-04-24) and B.1.628 (USA/LA-BIE-LSUH000937/2021; 2021-06-19) sequences for the relevant two regions of its genome, and made this snipit:

![snp_plot](https://user-images.githubusercontent.com/5540087/129614526-571ef140-0926-4296-a2dd-722cdb807664.png)

(3 x 631/627 shared SNPs before spike and 9 x 631/628 shared SNPs in spike or after it. 0 x 627/628 shared SNPs)

Table of B.1.631s attached.
[B.1.631.github.csv](https://github.com/cov-lineages/pango-designation/files/6994725/B.1.631.github.csv)

**Comment by shay671** [comment]
Hi @benjamincjackson  
First of all thank you for referring to my tweet. 
In the analysis i tweeted there was also strong evidence regarding B.1.634 , What about it? any evidence threre?

**Comment by babarlelephant** [comment]
I think it is a bit early to tell which one is the recombinant. I took the accessions appearing in the relevant subtrees of [an usher-tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_42302_acc590.json) and looked at the mutation prevalences. 
![image](https://user-images.githubusercontent.com/6537565/129629833-ec47b383-680a-4b89-825f-1109b60c7d59.png)

My feeling is that **B.1.628 is very odd**: a lot of mutations in 14408-28330 (all in B.1.631) and zero mutation (relative to B.1) elsewhere.

**Comment by rambaut** [comment]
I think it looks clear that the break point is likely before the start of spike (just like the B.1.1.7 recombinants). Probably worth building a tree of ORF1ab and then spike and the rest. The other way of doing this is to put the putative recombinants (or some representative sample of them) in the alignment twice - once with spike-3' masked and once with ORF1ab masked.

**Comment by rambaut** [comment]
@babarlelephant would you mind posting that table here in CSV form?

**Comment by babarlelephant** [comment]
I corrected a bug so I hope not too much people saw it at first. I have set to 0 the prevalences < 1%

`,B.1.627,B.1.628,B.1.634,B.1.631
C241T,99.3,99.7,100,100
G613A,,,100,
C829T,1.4,,100
C841T,,,100,
A994G,100,,,100
C1912T,99.3,,,
C3037T,100,99.6,100,98.2
C3688T,,99.4,,
C3884T,,99.4,,
C4534T,,,,100
C6120T,,,,100
C6633T,,99.6,4.6,
C7113T,,,63.2,
A7142G,,97.7,98.9,
G7787A,,,,98.2
C7869T,99.3,,
T8634C,,,100,
C9226T,,,,43.6
C9611T,100,,,
A9614G,,99.7,98.9,
C9693T,,99.7,98.9,
A9754C,,99.1,96.6,
G9756A,100,,,100
C9924T,99.3,,,100
A10982G,98,,,100
G11283-,96.6,,96.4
T11284-,91.2,,85.5
T11285-,91.2,,85.5
T11288-,,94.3,97.7,
C11289-,,94,97.7,
T11290-,,93.9,97.7,
G11291-,,93.8,97.7,
G11292-,,93.6,97.7,
T11293-,,93.8,97.7,
T11294-,,93.5,97.7,
T11295-,,93.5,97.7,
T11296-,,93.5,97.7,
G14137A,,,47.1,
C14408T,100,100,100,100
G15451A,,99.9,100,
C16466T,,99.7,100,
T20124A,97.3,,,
C20823T,,1.2,100,
C21057T,,99.9,,
T21615G,,98.8,100,100
T21752A,85.1,,,
T21765-,,96.6,
A21766-,,96.6,
C21767-,,96.6,
A21768-,,96.6,
T21769-,,96.6,
G21770-,,96.6,
C21846T,99.6,100,100
T22020C,93.2,,,
A22036C,,99.7,100,100
T22882A,,61.5,,87.3
C22916A,,,,98.2
G23012A,,96.6,
A23403G,100,99.9,100,100
C23604A,100,99.9,,100
C23625T,100,99,100,100
T23765G,100,99.6,,100
C23854A,,,100,
C24442T,99.3,99.4,,100
C24642T,98.6,99.9,,100
T24717A,80.4,,,
C25465T,,,,100
G26158-,95.3,92.6,,92.7
T26159-,94.6,92.6,,92.7
T26160-,91.9,92.2,,87.3
A26161-,91.9,92.2,96.6,87.3
C26222T,98,99.1,,100
C26681T,,,100,
C27389T,,99,,
T27645C,,,95.4,
C27735T,,,97.7,
C27769T,,94.3,,100
G28048A,,95.8,,
A28271-,,89.7,,85.5
A28330G,,98.1,,100
C28531T,,100,
C28606T,,94.3,
C28830T,,,,100
C28854T,,99,,
G28907T,,,,100
A28910T,,99,100,
C28923T,98.6,,,
C28957T,,,98.2
T29574-,89.9,,,
T29575-,89.9,,,
T29576-,89.9,,,
T29577-,89.9,,,
C29578-,89.9,,,
G29579-,89.9,,,
C29580-,89.9,,,`

**Comment by rambaut** [comment]
Thanks. You can edit your posts here (unlike Twitter!).

**Comment by shay671** [comment]
For your convenience i share here the data i based the tweet on. the similarity matrix shows that B.1.634 probably has something in this issue as well :

![image](https://user-images.githubusercontent.com/80166370/129668189-4f23be77-a2be-433e-9de0-6cb29a0a2c32.png)
 

[Mexican Variants.xlsx](https://github.com/cov-lineages/pango-designation/files/6997260/Mexican.Variants.xlsx)

**Comment by babarlelephant** [comment]
So I tried with Beast + Recomb package and it agrees there is a recombination event involving B.1.628 and B.1.631, but it tends to prefer B.1.628 as the recombinant. 
![image](https://user-images.githubusercontent.com/6537565/129713141-30836628-a794-400f-9f24-ae602546b309.png)

**Comment by rambaut** [comment]
Deletions are useful because it is reasonable to assume they can't be reverted. 

They all have a deletion in NSP6
Both `B.1.631` and `B.1.627` have an out-of-frame 3 nuc deletion that results in SL->M

<img width="677" alt="image" src="https://user-images.githubusercontent.com/686405/129727296-f69108f3-a0b1-4bad-82b1-bebebd6bd5ca.png">
 (this is `631` but `627` is the same).

Both `B.1.634` and `B.1.628` have the classic SGF-del mutation in NSP6 as seen in Alpha,Beta,Gamma (and others). Although it is close to the SL-M deletion it is not exactly adjacent to one is not an extension of the other.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/686405/129727731-e5f2877b-721e-4b99-af6c-7a13006bcc18.png">

This suggests that in this part of ORF1ab the tree is: `((B.1.627,B.1.631),(B.1.628,B.1.634))`

**Comment by rambaut** [comment]
Although deletions are unlikely to be reverted (except through recombination), they can occur independently as seen by the NSP6 SGF- in Alpha, Beta and Gamma. However, here it seems likely it is two shared deletions.

**Comment by rambaut** [comment]
All of the SNPs before this are compatible with this tree too. After that point the SNPs suggest `(((B.1.631,B.1.628),B.1.627),B.1.634)` because of the deletion at 26158-26161 shared by 631,627&628 (although all 4 have a single nucleotide deletion already at the end of this run at 26161). Both of these cause a frame shift in ORF3a and a stop codon a short way down - so are truncating the protein product. 

Once the single one has occurred, extending the deletion by another 3 keeps the frameshift and thus the stop codon (shortens the protein by 1 aa further but seems plausible).

**Comment by rambaut** [comment]
So to me the most parsimonious description is pretty much as you have it above @babarlelephant but with `B.1.631` taking the spike and 3' end of `B.1.628`).

**Comment by rambaut** [comment]
So I think I would go with the tree is ((B.1.627,B.1.628),B.1.634) in the non-recombinant lineages and `B.1.631` is the recombinant.

**Comment by shay671** [comment]
So let's try and leave B.1.631 out as we consider it the only recombinant.
Now we  take B.1.627/628/634 consensus mutations and place them in ascending order (by nucleotide position) as presented below.  
What we get is still some puzzle : 

- The  3 variants are probably with some relatedness. There are 7 mutations shared by B.1.627 & B.1.628 (It has been seen in some cases of other variants but it is quite rare). But  B.1.628 & B.1.634 share 12 mutations, and this hasn't seen in any other non related variants. 

-There is only 1 mutation present in all those 3.  Is it likely that all the 3 evolved from an ancestor which had only 1 mutation (over the 4 of B.1 which i exclude of course from this analysis) ?

- There is not even 1 synonymous mutation shared by even 2 of those 3 variants. 

- All the 7 mutations shared by B.1.627 and B.1.628 are from the S gene and forward, and concentrated in a region <3Kb. 



![image](https://user-images.githubusercontent.com/80166370/129739801-6c48c89d-e5f0-4fb6-a7af-58bb57d2ea23.png)

**Comment by babarlelephant** [comment]
In other words 

- If you remove B.1.631 from (((B.1.631,B.1.628),B.1.627),B.1.634) and ((B.1.627,B.1.631),(B.1.628,B.1.634)) you still get
((B.1.628,B.1.627),B.1.634) and (B.1.627,(B.1.628,B.1.634)) so that **B.1.628 is still moving**,

  While if you remove B.1.628 you get a consistent tree.

- Equivalently I updated [my colored mutation list above](https://github.com/cov-lineages/pango-designation/issues/189#issuecomment-899822981) (according to Shay's observation) and if you remove only B.1.628 you do get two consistent phenotypes (green+purple and yellow+white) while if you remove only B.1.631 you still get B.1.628 mixing B.1.627's purple phenotype and B.1.634's yellow phenotype.

The small spike-ORF3 purple phenotype is I think very well supported (7 point mutations plus one deletion) and the yellow phenotype is based on 5 point mutations plus one deletion, 2 of the mutations appear only in B.1.628 and B.1.634 (A9614G and A9754C).

I don't think the green phenotype needs to be well supported in this analysis, what matters is that it is non-yellow.

**Comment by MarinaEscalera** [comment]
RE: Proposal to redesignate B.1.631 as recombinant lineage XB

We support the proposal to redesignate B.1.631 as recombinant lineage, following the preliminary results shown in issue #189, we performed detailed phylogenetic analysis to detect recombinant sequences/lineages and putative breakpoints within the virus genome. We find evidence for recombination for a large cluster of sequences comprising the majority of the B.1.631 lineage. Phylogenetic incongruencies were observed between the whole genome tree and the Orf1ab tree, as compared to the S and 3’-UP trees (Figure 1a, see methods). Under GARD analysis, 550 potential breakpoints were detected. Comparing the AICc score of the best fitting model allowing for different topologies between segments, and that of the model that assumes the same tree for all the partitions, one breakpoint reflects a true topological incongruence (alignment site 22490, corresponding to codon 22775-22778 [GAT, amino acid numbering 497D] in the Spike ORF for the Wuhan-Hu-1 complete genome (https://www.ncbi.nlm.nih.gov/projects/sviewer/?id=NC_045512)) (Figure 1b, see methods).

![Figure_1](https://user-images.githubusercontent.com/89410852/130496480-1f4912fa-7a5d-4a22-be22-5f4599e23207.png)

METHODS
•	Dataset collation and initial phylogenetic analysis
Complete genome datasets available in GSAID (https://www.gisaid.org/) for the B.1.627 (https://cov-lineages.org/lineage.html?lineage=B.1.627) (239 sequences, representative sequence USA/MN-UMGC-3398/2021; 2021-04-24), B.1.628 (https://cov-lineages.org/lineage.html?lineage=B.1.628) (1095 sequences, representative sequence USA/LA-BIE-LSUH000937/2021; 2021-06-19) and B.1.631 (https://cov-lineages.org/lineage.html?lineage=B.1.631) (154 sequences, representative sequence USA/NY-PRL-2021_0419_02G09/2021) virus lineages were downloaded as of 17/08/21 (total of 1487 sequences). For each dataset, sequences were mapped against the SARS-CoV-2 isolate Wuhan-Hu-1 complete genome (NC_045512) using Geneious (https://www.geneious.com/) to generate individual alignments that were verified visually. Sequences were removed from the datasets if (i) they were >1000nt shorter than full genome length, (ii) they were 100% similar to any other sequence, or (iii) if >10% of sites were ambiguities (including N or X). Each alignment was partitioned in three sub alignment according to different genomic regions: Orf1ab, S and an ‘3’ upstream region’ (3’-UP; encompassing all coding sequences after Spike, including Orf3 up to before the 3’ UTR). The partitioned and the whole genome alignments were used for estimating four initial large-scale Maximum Likelihood phylogenies (LS WG, Orf1ab, S and 3’-UP), using IQ-TREE (http://www.iqtree.org/) under a general time reversible nucleotide substitution model with gamma-distributed among-site rate variation (GTR+G) and branch support assessed using 100 bootstrap replicates. All trees were rooted using the basal NC_045512 node. 

•	Detection of recombinant patterns/sequences 
The initial large-scale Maximum Likelihood phylogenies were used to detect general phylogenetic pattern incongruencies by comparing the trees obtained for the different genomic regions. Large-scale trees were used for further subsampling all datasets in a phylogenetically-informed manner, in order to normalise the number of sequences representing each virus lineage and reduce alignment size by removing non-informative sequences. In total, 197 sequences were subsampled and the partitioned and the whole genome alignments were used for estimating four reduced Maximum Likelihood phylogenies (SS WG, Orf1ab, S and 3’-UP) using RAxML using the same parameters as described above. The congruency of general phylogenetic patterns between the large scale and subsampled trees was visually verified. The subsampled whole genome alignment (197 sequences, 25095 sites) was analysed by running GARD (Genetic Algorithm for Recombination Detection) (http://www.datamonkey.org/gard) in HYPHY, whilst the output was visualized using http://vision.hyphy.org/GARD.

Analysis done by:
(post will be uploaded in virological.org)

Marina Escalera-Zamudio1,2, Hugo Gildardo Castelán Sánchez1,3, Luis José Delaye Arredondo1,4, Bernardo Gutiérrez1,2
1. Department of Zoology, University of Oxford, Parks Rd Oxford, OX1 3PS, UK
2. Consorcio Mexicano de Vigilancia Genómica (CoViGen-Mex, http://mexcov2.ibt.unam.mx:8080/COVID-TRACKER/) 
3. CONACYT-UAEM-Centro de Investigación en Dinámica Celular 
4. Departamento de Ingeniería Genética, Unidad Irapuato, CINVESTAV, Mexico
Correspondence to: marina.escalerazamudio@zoo.ox.ac.uk

**Comment by chrisruis** [comment]
Thanks very much @MarinaEscalera. Would you be able to share a list of identifiers for the samples in the likely recombinant cluster? Thanks

**Comment by MarinaEscalera** [comment]
Sure, here is the text file with the list of sequences...

Best wishes
Marina
__

Marina Escalera Zamudio, Ph.D

Leverhulme Trust ECR fellow
Department of Zoology
University of Oxford
Oxford, United Kingdom
Webpage: http://evolve.zoo.ox.ac.uk<http://evolve.zoo.ox.ac.uk/>


________________________________

**Comment by MarinaEscalera** [comment]
Our results are now updated and available at: 
https://virological.org/t/re-proposal-to-redesignate-b-1-631-as-recombinant-lineage-xb/746

**Comment by shay671** [comment]
Hi @MarinaEscalera 

Did you do any analysis for B.1.634 as well ?
As analyzed in my [tweet](https://twitter.com/shay_fleishon/status/1425775733167820814) (which this PANGO issue is actually based on as noted in the beginning)  it is related in a not that less weird  way to the others. 

Here i run some samples of the 4 suspect variants (B.1.631,B.1.634, B.1.627,B.1.628) in USHER.  And painted using unique mutations to highlight the four variants. 
As can be seen - in the global tree USHER stuck them all together
![image](https://user-images.githubusercontent.com/80166370/131260653-e8333245-411f-4176-b998-659ee95db57f.png)

and here is zoomed out to show the relatedness to other variants 
![image](https://user-images.githubusercontent.com/80166370/131260709-447efb46-d5f8-49f7-9807-4d7af3afec9c.png)

**Comment by MarinaEscalera** [comment]
Hi @shay671 

We did not include 634, but from data derived from @benjamincjackson its seems like: 
- 631 is the recombinant offspring of 627x628
- 628 is the recombinant offspring of 631x634
We are currently working on this. However, I believe that USHER uses whole genomes for phylogenetic placement, this will distort the tree topology when comparing to single ORFs trees and thus the observation that in the global tree USHER stuck them all together...

Cheers 
M

**Comment by FedeGueli** [comment]
Has been designated them? i saw it in this release:
https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.97

@corneliusroemer

**Comment by FedeGueli** [comment]
This issue has been published as preprint :https://www.medrxiv.org/content/10.1101/2021.11.19.21266601v1

**Comment by MarinaEscalera** [comment]
Hi there, yes you are right! the Pango committee has reviewed the case and has approved renaming the recombinant lineage as XB. This will be soon formally announced. Also, that is the correct link to our preprint that hopefully soon will be peer reviewed.

Best,
Marina

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BernardoGG** [comment]
Regarding the preprint mentioned by @MarinaEscalera, these are some of our key findings:

1. We consistently found a recombination breakpoint at the start of the S protein reading frame - this is not new and coincides with the findings of other contributors to this thread and the preprint.

2. Phylogenetic trees for both genome segments for lineages B.1.627, B.1.628, B.1.631 and B.1.634 show that lineages B.1.628 and B.1.631 actually split into two groups each, for which we provisionally added the suffixes _major_ and _minor_ in our manuscript (these denote the number of sequences contained within each of these 'clusters').

![XB_Fig3-01](https://user-images.githubusercontent.com/19906478/142850989-0dcc25d9-fa6f-463f-b32e-002fce84f5d9.png)

3. B.1.628 _minor_ includes a group of sequences from various countries that cluster at the base of both trees and near the outgroup (Hu-1 reference genome). We propose that these sequences could be designated as lineage B.1.

4. B.1.631 _minor_ includes a group of sequences from a single country with unusually low genetic divergence from Hu-1 at the Orf1ab region. We exclude these sequences from our analyses.

5. We mapped 4 key deletions shared by these lineages (2 deletions on NSP6, 2 deletions on Orf3a) onto the phylogenies; we assume that deletions could have occurred more than once in our data set (as some of these deletions are shared with other lineages and VOIs/VOCs) but that reversions of these deletions are unlikely.

6. To reconcile the topological discrepancies between phylogenies and the occurrence of the deletions, the most parsimonious model shows that B.1.628 (_major_) would have emerged as a recombinant lineage between B.1.631 (_major_) and B.1.634. We therefore propose B.1.628 _major_ as a recombinant lineage to be renamed (as lineage XB) under the Pango nomenclature.

![XB_Fig5_v2-01](https://user-images.githubusercontent.com/19906478/142851155-71e0ad82-0aad-4fa5-9622-7ea897c2aaac.png)

**Comment by chrisruis** [comment]
Thanks @BernardoGG and @MarinaEscalera We've incorporated the changes @BernardoGG outlined above into [v1.2.97](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.97):
* B.1.628 _major_ is renamed XB as a recombinant lineage. The B.1.628 label is therefore withdrawn
* B.1.628 _minor_ sequences are designated B.1
* B.1.631 _minor_ sequences were not designated to a lineage
* Updated the designations for B.1.627, B.1.631 and B.1.634

**Comment by yexiao-cheng** [comment]
Both in Table1, Figure1 of the preprint and the lineage summary from cov-lineages.org, B.1.634 seems to emerge later than B.1.631 and XB. Given the genomic fact, do we assume that some of the B.1.634 genomes that emerged before XB were not monitored?
