### ISSUE TITLE
XBB.1.16 with orf3a:E242Q(30 seqs, 8 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1893]
Sub-lineage of: XBB.1.16
Mutations on top of XBB.1.16: G26116C(orf3a:E242Q)
GISAID query: G26116C,C29386T,T28297C
Sequences: 11 (2 Singapore, 1 New Zealand, 1 USA, 6 Shanghai 1 Anhui)

First seq: EPI_ISL_17262430(Singapore) 2023-3-10
Latest seq: C_AA009495(Shanghai) 2023-4-4

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice16_genome_38382_a19b80.json?label=id:node_5818044)
<img width="1386" alt="Screen Shot 2023-04-15 at 13 35 56" src="https://user-images.githubusercontent.com/10445944/232185428-3ff5418a-f434-4f3f-bf4f-c96899bbef2d.png">

**Comment by aviczhl2** [comment]
12 seqs and detected in Australia.

**Comment by aviczhl2** [comment]
28 seqs now, detected in Canada and is growing very fast in Shanghai.

**Comment by aviczhl2** [comment]
30 seqs and also in Germany.

**Comment by corneliusroemer** [comment]
Not sure why to designate at this point. We designate branches of fast-growing variants to help keep track of them, but that's done in a systematic way from big branches to small ones, and 30 sequences is below the current threshold.

There's no spike mutation that's particularly concerning here, which could justify exception from systematic branch designation.

Issues are most useful to highlight lineages that have interesting mutation signature that would justify designation before they are so big that they would be labelled due to their size.

Issues like this here make it harder to see those useful issues.

**Comment by Over-There-Is** [comment]
265 seq now, and 1 seq recombined with FL.21.

**Comment by aviczhl2** [comment]
317 now, Canada, Croatia, UK, France, Ireland, Italy, Japan, Laos, South Korea, Spain, Thailand,

**Comment by aviczhl2** [comment]
And with 300+ seqs it still has a small growth advantage against  XBB.1.16
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/b4c8f6e4-7ed0-4ced-9266-6fe96ab31bd4)

@corneliusroemer I think this branch deserve a designation now.

**Comment by FedeGueli** [comment]
@aviczhl2 could you re post the new Usher tree please?? agrre this should be reopened and reviewed

**Comment by aviczhl2** [comment]
Designated as XBB.1.16.22, please add a milestone.
