### ISSUE TITLE
CM.8.1.1 with S:R346T and M:E11Q (20 seqs as of 2023-04-28, multiple Asian countries)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#1901]
### Description
**Sublineage of**: CM.8.1.1 (BA.2.3.20 with additional S:K147N, S:G446S and S:F486S)
**Earliest sequence**: 2023/02/08 (Singapore ex-Philippines)
**Most recent sequence**: 2023/04/05 (Japan ex-Philippines)
**Countries circulating**: Korea (2), Hong Kong (2), Japan (2 local cases and 1 ex-Philippines), Singapore (1 ex-Philippines), Philippines (1)

**Mutations on top of CM.8.1.1**: C16391T (ORF1b:A975V), C18348A > G22599C (S:R346T), G26553C (M:E11Q)

**GISAID and Cov-spectrum query**: C16391T, C18348A, G26553C

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/232379058-760cc394-ba8f-4cc3-8a94-a9be259ea6ad.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_27903_cc7030.json?c=gt-nuc_26553&label=id:node_6158443

### Genomes:
EPI_ISL_16905205, EPI_ISL_17343862, EPI_ISL_17375073, EPI_ISL_17416484, EPI_ISL_17416487, EPI_ISL_17433559, EPI_ISL_17433563, EPI_ISL_17473628, EPI_ISL_17482093

**Comment by thomasppeacock** [comment]
This is a very interesting set of mutations - I'm suggesting monitoring for now but if more sequences come up I think this should be prioritised for designation.

**Comment by corneliusroemer** [comment]
Agreed, let's designate once it hits 20 sequences.

**Comment by c19850727** [comment]
15 seqs as of 2023-04-25. 
2 each from Japan, Korea and Hong Kong in last 2 days.
![image](https://user-images.githubusercontent.com/86835836/234204458-5ad02efe-7497-4021-aed4-e0f78b8edc54.png)

**Comment by HynnSpylor** [comment]
It has been designated as FV.1
@corneliusroemer could you add the milestone and source?

**Comment by c19850727** [comment]
20 seqs as of 2023-04-28. Newly found in Russia.

**Comment by FedeGueli** [comment]
@c19850727 this has been designated FV.1

**Comment by cvejris** [comment]
1x Austria 17th April 
EPI_ISL_17547974

**Comment by ryhisner** [comment]
FV.1 has been on a bit of a surge recently: 23 sequences have been uploaded in the past nine days, and 23 sequences with collection dates of April 17 or later. Notably, this is the first successful lineage ever to have both S:R346T and S:N450D. I did not expect this one to grow much, but it has somehow made R346T-N450D work out despite the salt-bridge issue. @c19850727's instincts were much better than mine on this one! 

@oobb45729, any ideas for why this mutational combo seems compatible for the first time? I don't understand the salt bridge thing at all—with my limited knowledge of structural issues, I would've guessed that R346-D450 would form a stronger salt bridge than T346-D450—so I can't really even speculate. 

Another thing—M:E11q is a very rare mutation. The only sequences with M:E11Q collected since September 19, 2022, have all been from this lineage. (I'm not counting one extremely poor-quality BQ* sequence from California.) Before this lineage, it had only ever appeared in 28 sequences all time. It's a G->C mutation, which is one of the rarest types, but even considering that, M:E11Q is much less common than one would expect unless there was strong selection pressure against it (until now).

**Comment by FedeGueli** [comment]
In the public report of MOH of Philippines the share of BA.2.3.20 after going down picked up a boost again  (https://twitter.com/T_Brautigan/status/1659491887256936451?s=20) while it can be different regional sampling .

**Comment by cvejris** [comment]
The last 5 collected samples are all from novel geographic sites:

Accession ID | Collection date | Location
EPI_ISL_17679996 | 01/05/2023 | Europe / United Kingdom / England
EPI_ISL_17646700 | 02/05/2023 | North America / USA / California / Los Angeles County
EPI_ISL_17675769 | 03/05/2023 | North America / USA / Minnesota
EPI_ISL_17684053 | 05/05/2023 | Asia / China / Yunnan
EPI_ISL_17671903 | 07/05/2023 | Asia / China / Hubei / Ezhou

**Comment by oobb45729** [comment]
> FV.1 has been on a bit of a surge recently: 23 sequences have been uploaded in the past nine days, and 23 sequences with collection dates of April 17 or later. Notably, this is the first successful lineage ever to have both S:R346T and S:N450D. I did not expect this one to grow much, but it has somehow made R346T-N450D work out despite the salt-bridge issue. @c19850727's instincts were much better than mine on this one!
> 
> @oobb45729, any ideas for why this mutational combo seems compatible for the first time? I don't understand the salt bridge thing at all—with my limited knowledge of structural issues, I would've guessed that R346-D450 would form a stronger salt bridge than T346-D450—so I can't really even speculate.
> 
> Another thing—M:E11q is a very rare mutation. The only sequences with M:E11Q collected since September 19, 2022, have all been from this lineage. (I'm not counting one extremely poor-quality BQ* sequence from California.) Before this lineage, it had only ever appeared in 28 sequences all time. It's a G->C mutation, which is one of the rarest types, but even considering that, M:E11Q is much less common than one would expect unless there was strong selection pressure against it (until now).

I think the issue is that R346T and N450D seem to cover similar types of antibodies, and N450D is less effective than R346T.
So lineages with R346T may not need N450D (for now), but lineages with N450D may still need R346T. I think that N450D probably makes the selection pressure for R346T lower, which makes it is harder to be gained, but R346T may still work if it is gained. @ryhisner 
By the way, L452R and F490S seem to a pair that don't work well together. https://jbloomlab.github.io/SARS-CoV-2-RBD_DMS_Omicron/RBD-heatmaps/ shows that F490S would result in a moderate RBD expression loss for Delta but not for other variants there.

**Comment by oobb45729** [comment]
Another thing I noticed is that most successful Omicron lineages seem to have similar levels of positive charges for RBD.
Comparing to BA.1, BA.2 has D405N and R408S.
The R493Q reversion is accompanied by L452R or N460K or A484R.
With D339H, BA.2.75 is more basic, but it quickly gained R346T or K356T.
For BA.4/BA.5, the spread of BA.4/BA.5 lineages with just N460K or K444X or G446D were limited. The most successfully ones are BA.4/BA.5 with N460K+K444X (or G446D).
For BA.2.75, variants with K444X weren't doing well initially. Then CH.1.1 came with K444T and L452R.
XBC1.6 gained R346S and M452R.
Maybe this is another reason why we haven't seen more cases of R346T+N450D, although R346T seems to be reliable gain no matter what the positive charge level of the RBD is.
