### ISSUE TITLE
Lineages reassigned as "None"

### ISSUE THREAD

**Issue by arahatdohmh** [cov-lineages/pango-designation#191]
After Pangolin update 3.1.10, some of the lineages are being reassigned as "None". Some of these include B.1.1.7, B.1.351, B.1.623, and some others (I can provide a full list with counts if necessary). The most affected was B.1.526. However, I do not see any "None" assignment in pango-designation.

**Comment by rambaut** [comment]
'None' means that Pangolin was unable to assign a lineage unambiguously. Usually this will be because there is a conflict between the classifier and Scorpio and rather than giving a false positive (i.e., a false VOC/VOI) it will return 'None'. 

However we intend to change this label to 'unassigned' to make this clearer but but some downstream pipelines will likely break and need updating.

**Comment by aretchless** [comment]
Would it be possible to resolve these "None" calls using usher? Perhaps assigning the sequence to the lowest common ancestor of the usher and pangoLEARN calls? If they both agree on the VOC/VOI that scorpio rejected, maybe assign it to the parent lineage.

I just bring this up because it's frustrating to report 'None' for a high-quality sequence.
Thanks for dealing with all these complexities.
