### ISSUE TITLE
XBB.1 (or XBB.1.5.24?) sublineage with S:E748V(A23805T) (161seqs)

### ISSUE THREAD

**Issue by HynnSpylor** [cov-lineages/pango-designation#1921]
Defining mutations: XBB.1.5.24 (by Usher, with C2710T)>C19524T>A23058T(S:E748V)
GISAID query: Spike_E748V, Spike_G252V, Spike_F486P, C19524T
Earliest seq: 2023-02-06 (Singapore, EPI_ISL_16905246)
Most recent seq: 2023-04-11 (China, EPI_ISL_17505635)
Countries detected: Germany (20), France (7), China (6), USA (5), Austria (6), Spain (4), Ireland (3), Isarel (2), Egypt (2), Japan (1), South Korea (1), Singapore (1), Canada (1), Denmark (1), Italy (1), Lithuania (1), Oman (1), Portugal (1)

Usher Tree:
![QQ截图20230420114857](https://user-images.githubusercontent.com/121703496/233254538-9bdb33fb-8f59-4029-93ee-5d9d39b8b3dc.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36129_b4fa0.json

Usher supposes the branch as XBB.1.5.24 sublineage. It confuses me that the definition of XBB.1.5.24 is "C2710T, pre T17124C", but the T17124C is indeed the definition of XBB.1.5. So how to separate the branches of XBB.1+C2710T without T17124C? Are they XBB.1.5.24 or XBB.1.X?  I suggest the definition of XBB.1.5.24 ought to be improved, and my proposal is more likely to be XBB.1.X. 
(The problem also revolves XBB.1.5.22/23) 
![QQ截图20230420120431](https://user-images.githubusercontent.com/121703496/233256679-53e59067-d437-4c06-91ee-3ac4f5602b9d.png)

 https://nextstrain.org/staging/nextclade/sars-cov-2/21L?c=gt-nuc_17124
Genomes:
EPI_ISL_16905246, EPI_ISL_16996102, EPI_ISL_17005249, EPI_ISL_17070410, EPI_ISL_17070875, EPI_ISL_17080494, EPI_ISL_17097492, EPI_ISL_17175232, EPI_ISL_17175241, EPI_ISL_17175248, EPI_ISL_17175420, EPI_ISL_17177983, EPI_ISL_17178048, EPI_ISL_17206870, EPI_ISL_17212917, EPI_ISL_17232339, EPI_ISL_17248055, EPI_ISL_17248893, EPI_ISL_17262967, EPI_ISL_17263843, EPI_ISL_17265216,
EPI_ISL_17274694, EPI_ISL_17285920, EPI_ISL_17285953, EPI_ISL_17296399, EPI_ISL_17296671, EPI_ISL_17296802, EPI_ISL_17296815, EPI_ISL_17324513, EPI_ISL_17327588, EPI_ISL_17327637, EPI_ISL_17344255, EPI_ISL_17359784, EPI_ISL_17388099, EPI_ISL_17394033, EPI_ISL_17400222-17400223, EPI_ISL_17406304, EPI_ISL_17406309, EPI_ISL_17406378, EPI_ISL_17412998, EPI_ISL_17415140, EPI_ISL_17421883, EPI_ISL_17423886, EPI_ISL_17424077, EPI_ISL_17426351, EPI_ISL_17428842, EPI_ISL_17428915, EPI_ISL_17468768,
EPI_ISL_17469441, EPI_ISL_17471128, EPI_ISL_17471135, EPI_ISL_17471224, EPI_ISL_17479928, EPI_ISL_17480929, EPI_ISL_17484219, EPI_ISL_17485133, EPI_ISL_17494031, EPI_ISL_17505628-17505629, EPI_ISL_17505635, EPI_ISL_17505648-17505649, EPI_ISL_17509124

**Comment by krosa1910** [comment]
Another point that I would like to add to HynnSplyor's comment is about this giant branch in the top of this figure: "1.5"+S:486P+17124C, then gained 10204C. As of now, it contains 17 variants, and many of them are fairly recently designated.
<img width="715" alt="81ED92DB-2BC9-42A6-95A7-B050CADFA5BE" src="https://user-images.githubusercontent.com/131021067/233257128-41471edc-34f6-4c72-bf06-03018b364f17.png">
First, without more evidence, I would use the Occam's razor to suggest that this 10204C mutation only happens once within the 1.5* family as all variants with this mutation seem to cluster in one branch, and this mutation does not appear in any variant's definition.
<img width="662" alt="12279594-C24D-4894-AD98-5295D3CC0832" src="https://user-images.githubusercontent.com/131021067/233257310-83955651-213e-4124-a9fc-65e9e1222675.png">
Secondly, variants with this mutation seems to be amazingly constant throughout the whole population of xbb.1.5*, which strengthen my hypothesis that some early event of T10204C happen with the spread of xbb.1.5*, and it just "settle down" because it is a silent mutation.
I am suggesting that at least we should follow HynnSpylor's suggestion and make T17124C upgraded to be the formal definition of xbb.1.5*. Moving all existing branches of xbb.1.5* with T17124C and 10204C to a new xbb.1.5.1* would likely lead to a need for roughly 15 more letters, and that is rather unnecessary for now, but people should consider my common origin theory when they encounter new issues with 10204C

**Comment by krosa1910** [comment]
> Defining mutations: XBB.1.5.24 (by Usher, with C2710T)>C19524T>A23058T(S:E748V) GISAID query: Spike_E748V, Spike_G252V, Spike_F486P, C19524T Earliest seq: 2023-02-06 (Singapore, EPI_ISL_16905246) Most recent seq: 2023-04-11 (China, EPI_ISL_17505635) Countries detected: Germany (20), France (7), China (6), USA (5), Austria (6), Spain (4), Ireland (3), Isarel (2), Egypt (2), Japan (1), South Korea (1), Singapore (1), Canada (1), Denmark (1), Italy (1), Lithuania (1), Oman (1), Portugal (1)
> 
> Usher Tree: ![QQ截图20230420114857](https://user-images.githubusercontent.com/121703496/233254538-9bdb33fb-8f59-4029-93ee-5d9d39b8b3dc.png)
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_36129_b4fa0.json
> 
> Usher supposes the branch as XBB.1.5.24 sublineage. It confuses me that the definition of XBB.1.5.24 is "C2710T, pre T17124C", but the T17124C is indeed the definition of XBB.1.5. So how to separate the branches of XBB.1+C2710T without T17124C? Are they XBB.1.5.24 or XBB.1.X? I suggest the definition of XBB.1.5.24 ought to be improved, and my proposal is more likely to be XBB.1.X. (The problem also revolves XBB.1.5.22/23) ![QQ截图20230420120431](https://user-images.githubusercontent.com/121703496/233256679-53e59067-d437-4c06-91ee-3ac4f5602b9d.png)
> 
> https://nextstrain.org/staging/nextclade/sars-cov-2/21L?c=gt-nuc_17124 Genomes: EPI_ISL_16905246, EPI_ISL_16996102, EPI_ISL_17005249, EPI_ISL_17070410, EPI_ISL_17070875, EPI_ISL_17080494, EPI_ISL_17097492, EPI_ISL_17175232, EPI_ISL_17175241, EPI_ISL_17175248, EPI_ISL_17175420, EPI_ISL_17177983, EPI_ISL_17178048, EPI_ISL_17206870, EPI_ISL_17212917, EPI_ISL_17232339, EPI_ISL_17248055, EPI_ISL_17248893, EPI_ISL_17262967, EPI_ISL_17263843, EPI_ISL_17265216, EPI_ISL_17274694, EPI_ISL_17285920, EPI_ISL_17285953, EPI_ISL_17296399, EPI_ISL_17296671, EPI_ISL_17296802, EPI_ISL_17296815, EPI_ISL_17324513, EPI_ISL_17327588, EPI_ISL_17327637, EPI_ISL_17344255, EPI_ISL_17359784, EPI_ISL_17388099, EPI_ISL_17394033, EPI_ISL_17400222-17400223, EPI_ISL_17406304, EPI_ISL_17406309, EPI_ISL_17406378, EPI_ISL_17412998, EPI_ISL_17415140, EPI_ISL_17421883, EPI_ISL_17423886, EPI_ISL_17424077, EPI_ISL_17426351, EPI_ISL_17428842, EPI_ISL_17428915, EPI_ISL_17468768, EPI_ISL_17469441, EPI_ISL_17471128, EPI_ISL_17471135, EPI_ISL_17471224, EPI_ISL_17479928, EPI_ISL_17480929, EPI_ISL_17484219, EPI_ISL_17485133, EPI_ISL_17494031, EPI_ISL_17505628-17505629, EPI_ISL_17505635, EPI_ISL_17505648-17505649, EPI_ISL_17509124

Yet A Major problem is that where to put"xbb.1.5", the unstarred version without considering any new mutation. According to covspectrum, this “nominate subspecies" now consists of 80% of all xbb.1.5* family, and it is actually not too slow within the group, although its share is recently diminishing slowly.
<img width="685" alt="27C4107D-8C56-43C3-AA1D-D02462AFE1C8" src="https://user-images.githubusercontent.com/131021067/233261586-babe1b59-0a1c-410f-8553-6559585a4428.png">
Most of the variant does contain T17124C, and it is hard to say whether the number is changing in a reliable pattern as recent datas are incomplete. 
<img width="680" alt="9B1F7CB3-0F0F-4D72-8ADE-ECB77BDE00BF" src="https://user-images.githubusercontent.com/131021067/233261565-e9874159-6f30-4fdb-968b-9e35ef4ad75d.png">
If we decide that new definition of xbb.1.5* to be applied, then this xbb.1.5 beast would be dissected into two varaints. We could make the majority of them still bearing name xbb.1.5, while the rest would be a new xbb.1.x, and this part is still very large (several percent of total samples is not something we could neglect). It seem just really weird to have xbb.1.5 and new xbb.1.x, which are major variants with essentially the same potency to be separated apart.

**Comment by AnonymousUserUse** [comment]
See discussion in issue https://github.com/cov-lineages/pango-designation/issues/1491.
I hold the view that T17124C should be included as a defining mutation of XBB.1.5. Otherwise, the assignment of XBB.1.5, especially by Nextclade, would be pretty unstable.
I agree that the order of certain mutations remains uncertain. To deal with the uncertainty, designating lineages with at least two mutations would help.
The inclusion of more XBB* + S:486P sequences within XBB.1.5 does not make sense any more. We use the query XBB* + S:486P to track XBB* + S:486P anyway.
@FedeGueli @AngieHinrichs @corneliusroemer

**Comment by AnonymousUserUse** [comment]
> A Major problem is that where to put"xbb.1.5", the unstarred version without considering any new mutation.

A major reason for this problem is that Nextclade has not been updated for a long time. Thus, a large number of recently designated lineages is not considered in CoV-Spectrim/Nextclade.

**Comment by FedeGueli** [comment]
https://github.com/cov-lineages/pango-designation/issues/1924

**Comment by corneliusroemer** [comment]
There are a few misunderstandings here:
> Secondly, variants with this mutation seems to be amazingly constant throughout the whole population of xbb.1.5*, which strengthen my hypothesis that some early event of T10204C happen with the spread of xbb.1.5*, and it just "settle down" because it is a silent mutation.

No one claimed that these involved 10 times independently - not every additional mutation leads to a new Pango lineage name. Otherwise we'd have some ~80 dots now.

If one could rewind history one could make the case for T10204C to start XBB.1.5.1 - but this is not how things played out and we don't usually change names after designation to keep things stable, there's nothing wrong with the way things are.

> A Major problem is that where to put"xbb.1.5", the unstarred version without considering any new mutation.

There is no problem, there will always be new mutations (see molecular clock) so it doesn't much sense to compare "pure" XBB.1.5 vs all descendants - the genotype of XBB.1.5 will disappear over time.

I will reply about changing XBB.1.5 definition on #1924

This issue has been somewhat derailed.

**Comment by corneliusroemer** [comment]
23058 is S:499 not S:748. The nuc is wrong, it should be A23805T.

This is just one small sublineage, no Spike RBD mutation, unlikely to be able to compete with 478 ones, so will close this.

**Comment by HynnSpylor** [comment]
@corneliusroemer Very sorry for my typo! it is indeed A23805T (S:E748V).
but the sublineage could monitor for a time. It can not compete with 478 lineages, but still positive growth rate to XBB.1.5. Also, the XBB.1.5.24 in China recently are all with S:E748V and still grows (35 seqs in a month by ChinaCDC weekly report). As the XBB* lineages gradually increase in China, it is still worth observing.
![QQ截图20230423024403](https://user-images.githubusercontent.com/121703496/233802254-beb4bbd2-5ab7-4da6-8abb-af4934c23548.png)

**Comment by aviczhl2** [comment]
152 seqs now, and it is growing quite fast. 

<img width="1083" alt="Screen Shot 2023-05-12 at 14 11 09" src="https://github.com/cov-lineages/pango-designation/assets/10445944/b9227de4-76fe-4a9d-979b-ba6432492a22">

**Comment by HynnSpylor** [comment]
Now the sublineage has sperad in China widely ( especially in Jiangsu and Anhui Province).
Red points are updated today in GenBase, mostly on a branch with two ORF mutations. So I suggest to reopen it.
![QQ截图20230514145516](https://github.com/cov-lineages/pango-designation/assets/121703496/964f0faa-ad96-4cb0-bd8e-6d6566088283)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35af4_851e0.json

**Comment by FedeGueli** [comment]
Agree with @HynnSpylor this lineage has a lot of recent samples and it is expanding in China.

cc @corneliusroemer i suggest you to review it

**Comment by FedeGueli** [comment]
@HynnSpylor i suggest toh reopen the issues that you think they need a second chance briefly in the other page.
Just tree, defining muts and query .
So we will track them here and ping cornelius from.there.

**Comment by HynnSpylor** [comment]
Finally it is designated as GF.1 (XBB.1.5.24.1). 
@corneliusroemer could you add the milestone and reference?
