### ISSUE TITLE
XBB.1.5 with S:K444R (33 seq., Italy, Slovenia, Austria, Germany)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#1922]
Proposal for a sublineage of XBB.1.5
Earliest sequence: 23.01.2023 (Italy)
Countries detected: Italy, Slovenia, Austria, Germany

Defining Mutations:
nuc	unique	T25833C, C18162T, A22893G, A29596G
ORF10	unique	I13M
S	unique	K444R

Sublcade also carries:
nuc	unique	A25326G, T27705C
S	unique	K1255R

![grafik](https://user-images.githubusercontent.com/102166254/233276561-00cd6cbe-e82a-4a42-bb49-dae1153e8f6c.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ab9d_d6ab0.json?c=userOrOld&label=id:node_5916546

![grafik](https://user-images.githubusercontent.com/102166254/233276890-6de956c4-92cc-45c5-9e6e-3f0577404a91.png)

EPI_ISL_17212933, EPI_ISL_17466283, EPI_ISL_17509249, EPI_ISL_17509241, EPI_ISL_17509236, EPI_ISL_17212908, EPI_ISL_17501246, EPI_ISL_17434309, EPI_ISL_17212953, EPI_ISL_17509245, EPI_ISL_17327013, EPI_ISL_17215584, EPI_ISL_17212910, EPI_ISL_17212927, EPI_ISL_17165330, EPI_ISL_17078886, EPI_ISL_17006092, EPI_ISL_16888988, EPI_ISL_16831269, EPI_ISL_17165336, EPI_ISL_17165322, EPI_ISL_17165326, EPI_ISL_17165327, EPI_ISL_17212960, EPI_ISL_17466269, EPI_ISL_17509257, EPI_ISL_17509240, EPI_ISL_17212951, EPI_ISL_17466278, EPI_ISL_17347578, EPI_ISL_17212935, EPI_ISL_17509232, EPI_ISL_17347561

**Comment by krosa1910** [comment]
I remember that when I was new to this field, the common sense of variant soup era was to count specific mutations at certain positions, and 444 was definitely one of those because of the insane immune escape effect it gives to a mutation on BA.2/5 basis. XBB inherit its pre-446 RBD mutations from the hypermutant BJ.1, meaning it already have 445P and 446S, greatly reducing the need for a 444 mutation. This is evident from jbloomlab's escape calculator.

<img width="844" alt="FEB944DE-0E53-4353-A783-8167C1EEE7BD" src="https://user-images.githubusercontent.com/131021067/233413689-9bf39157-fe37-4669-aca7-b7b91013b754.png">


<img width="822" alt="5999071F-C299-406A-961A-028AA032B4D0" src="https://user-images.githubusercontent.com/131021067/233413922-234e6c90-d870-48fe-8879-78de02af2a36.png">

Nevertheless, 444 is still a great site for escape mutation. Based on Richard Cao's article, besides the pretty strong E mutation, Q,T,N,M does not seem to differ much in escape ability (although that's much more complex if coupled with other sites). R is relatively weak at escape in that article. 
![F4 large](https://user-images.githubusercontent.com/131021067/233414028-a12a476c-449a-4ff1-a8ed-cb318982e664.jpg)

**Comment by Memorablea** [comment]
110 NOW

**Comment by DailyCovidCases** [comment]
Please close this issue
