### ISSUE TITLE
Proposal of restricting back XBB.1.5 to T17214C carrying lineages consequently renaming XBB.1.5.22 XBB.1.5.23 XBB.1.5.24

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1924]
Following discussions  in #1921 and #1491 i think it is better to step back from the broadening of XBB.1.5 beyond T17214C .
So i propose to retract XBB.1.5.22 XBB.1.5.23 XBB.1.5.24 and renaming as XBB.1 sublineages
<img width="1164" alt="Screenshot 2023-04-20 alle 13 38 55" src="https://user-images.githubusercontent.com/87669813/233355076-4a72d265-c586-4408-a769-5ce20bd3b43d.png">
https://nextstrain.org/staging/nextclade/sars-cov-2/21L?c=gt-nuc_17124&label=clade:23A

**Comment by corneliusroemer** [comment]
Strong homoplasy of 486P makes things messy. There's not much we can do about this. We decided more than 2 months ago to choose a simple definition of XBB.1.5 (XBB.1 with ORF8* and 486P and 486P not having been acquired on an obvious sublineage of XBB.1 and ORF8*). We don't usually rename things with hindsight, especially when there's no clear right or wrong way of doing things.

The current system works: XBB.1.16, XBB.1.9 all have 486P but are not XBB.1.5 because they clearly evolved 486P independently. There's a chance that some XBB.1.5.* also evolved 486P independently but the harm done by changing names is not worth the work of figuring this out.

**Comment by FedeGueli** [comment]
Ok @corneliusroemer without renaming anything  we can put a conventional rule that from now ahead we wont designate XBB.1.5 sublineage if not carrying T17214C .

You of course have noticed that luckily there are a lot of new people here contributing with proposal, a simple conventional rule(agreement) will make things easier and quicker. lemme know what you think.
