### ISSUE TITLE
XBB.2.3.2 with Orf1a:T1788M(54 seqs, 7 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#1962]
Orf1a:T1788M was widely appeared in BA.5.2.48 sub-lineages(DY.3 and DY.4 independently), and here it appears again in Indian XBB.2.3.2, with a slight growth advantage. 

sublineage of: XBB.2.3.2
mutations on top of XBB.2.3.2: C5628T(Orf1a:T1788M)
GISAID query: C5628T,C6740T,G22113T
No. of seqs: 54(Australia 1 USA 4 Singapore 6( 1 from Vietnam 1 from Malaysia) Japan 1 India 42)

First seq: EPI_ISL_17508234(India) 2023-1-4
Latest seq: EPI_ISL_17539829(Singapore local) 2023-4-13

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice13_genome_18bbb_8b4f80.json?label=id:node_6087106)
<img width="1378" alt="Screen Shot 2023-04-26 at 17 07 14" src="https://user-images.githubusercontent.com/10445944/234527305-8831ac4d-5c94-4e3f-adc2-20662d43b27e.png">
[cov-spectrum](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=XBB.2.3.2*&nucMutations1=C5628T&nextcladePangoLineage1=XBB.2.3.2*&analysisMode=CompareToBaseline&)

<img width="1354" alt="Screen Shot 2023-04-26 at 17 08 27" src="https://user-images.githubusercontent.com/10445944/234527619-526c14c8-284a-4ea0-aa93-b2e478a9b582.png">

**Comment by krosa1910** [comment]
@corneliusroemer  I disagree with your action of closing this issue here. XBB.1.16.2 does not have a Spike mutation either beyond XBB.1.16, yet it got designated and achieved the top place in collection 42. A lot of the earlier Chinese variants does not acquire Spike mutation at all, yet they were able to show superior performance compared to both their BA.5.2 parents and other imported variants with many Spike mutations. What stopped you from assigning XBC.1.6.3 with even less sequences and only non-sym mutation of N:173V

Judging from preliminary data, this variant does have potential. It acquired advantages beyond an already top-seat base variant XBB.2.3.2, and it had local spreads in a foreign country just several days after its recent appearance in India (@aviczhl2 Not sure if you noticed that the first sequence is way earlier than the rest, and the second sequence started at 03-17. Though the earliest sequence is submitted a week later than 03-17 sequences). If you don't think it is valuable or trust the numbers, you should put a monitor tag or something near it instead of closing it completely.

**Comment by corneliusroemer** [comment]
> achieved the top place in collection 42

Issues are most useful to highlight lineages that deserve special attention for early designation.

Global growth advantages from something like collection 42 are very much biased by speed of submission of the country where a lineage is most commonly found. Also, these growth advantages are very biased and unreliable for small lineages <500 sequences.

I designated XBB.1.16.2 not because of growth or particular mutations but because it is a large branch of a lineage that is growing fast. It is not expected to be fitter, but having XBB.1.16 broken into chunks helps break down the tree. This is a _systematics_ reason, there's no need or no benefit in having issues for such lineages as they are done systematically (look for biggest sublineages of fast-growing or big lineages).

The number of issues has been steadily increasing to the extent that it's difficult to stay on top of them.

**Comment by aviczhl2** [comment]
372,Argentina, Austria, China, Belgium, Canada, Chile, UK, France, Indonesia, Ireland, Italy, Mexico, Luxemburg, Nepal, Portugal, South Korea, Spain, Sweden, and still having a 6% advantage over its parent.

**Comment by FedeGueli** [comment]
Orf1a:T1788M = nSP3_T970M = PLPro_T225M , apparently undescribed.

**Comment by aviczhl2** [comment]
403 and detected in Ukraine

**Comment by aviczhl2** [comment]
Designated HH.7
