### ISSUE TITLE
XBB.1.22.1 from Kenya with S:Y451H and Orf3a:P42L (23 very recent samples, 21 Kenya + 1 Germany +1 Australia)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1979]
Tree:
![Schermata 2023-05-02 alle 21 09 05](https://user-images.githubusercontent.com/87669813/235762357-c7fc5af6-750a-483d-8afd-edf376eaf01e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_25f4c_1562f0.json?f_userOrOld=uploaded%20sample&label=id:node_10085822

Defining mutations:
XBB.1.22.1 >>A8374G, Orf3a:P42L (C25517T) > S:Y451H (T22913C )

Gisaid query: A8374G , T22913C finds 22 sequences

Samples: 22 
First sequence:EPI_ISL_17592823 | 2023-03-27
List of sequences
EPI_ISL_17480405, EPI_ISL_17592823-17592824, EPI_ISL_17592826-17592830,
EPI_ISL_17592832-17592845

**EDITED**
Further notes: Thx to **@krosa1910 and @hynnspylor** for trying to help with this, much appreciated here.
Be AWARE that EPI_ISL_17592838 has an apparent additional core spike mutation at S:N487Y with a further silent nuc mutation at S:486 
![Schermata 2023-05-02 alle 23 11 05](https://user-images.githubusercontent.com/87669813/235787034-599ef259-ab82-4118-aaec-334a66d42aaf.png)

Luckily the only three sequences with good coverage in that region dont show that additional mutation, while one has S:S494P and another has S:E554Q (German sample).

The predicted fitness is not superlative nor superior than XBB.1 currently circulating but i prefer to suspend any thought  until we will see how it goes outside Kenya.
![Schermata 2023-05-02 alle 23 14 15](https://user-images.githubusercontent.com/87669813/235787601-1f2f39e7-e71f-4b34-ad6c-1ed6c5e254b5.png)

**Comment by krosa1910** [comment]
As the original proposer of XBB.1.22.1, Hynnspylor discussed with me privately that Kenya was now dominated by this variant, although both of us did not see this. 
Kenya uploaded 22 sequences since 3/15, 21 being xbb.1.22.1, the outlier is really weird as EPI_ISL_17592831, which is labelled BQ.1.1 +478R.
of the 21 xbb.1.22.1, all of them have S:Y451H and A8374G, 18 of them has C25517T, so I suppose that the order of def muts are listed wrong, the silent and the S occur first, then the orf3a.
However, a lot of samples are low coverage, after reducing those you get only 5 samples.

**Comment by krosa1910** [comment]
Also there is a German sequence: PI_ISL_17480405 in 04-03. There is an early French seq in Feb 27th with only the silent mutation, and every lineage containing any of those three mutations contain the silent mutation, so very likely it is the backbone. But this one has the Orf3a mutation, so I now just guess that all three get there together, but the low quality of tests just blur things (of the 21 Kenyan seqs, only 5 remains when excluding low coverage)

**Comment by FedeGueli** [comment]
Thx @krosa1910 for your precious comments. consider i was having dinner while proposing ;)) i have adjusted the missing query and number of samples. The german one was already in the tree posted but thx for highlighting it i ve missed it.
There is one sequence that is crazy: it has two more consecutive nuc mutations after 486P giving a triple nuc mutated at 486 to P and N487 to Y.
cc @thomaspeacock @AngieHinrichs @corneliusroemer @InfrPopGen @ryhisner
![Schermata 2023-05-02 alle 23 02 41](https://user-images.githubusercontent.com/87669813/235785439-7af82466-174d-4274-9100-d04e29a6b994.png)

**Comment by FedeGueli** [comment]
>of the 21 xbb.1.22.1, all of them have S:Y451H and A8374G, 18 of them has C25517T, so I suppose that the order of def muts are listed wrong, the silent and the S occur first, then the orf3a. 
>
The ones without the Orf3a mutation have missing coverage at that position.
![Schermata 2023-05-02 alle 23 25 31](https://user-images.githubusercontent.com/87669813/235789681-46124045-63e6-47c6-84bc-8f2283580501.png)

**Comment by HynnSpylor** [comment]
Good catch! I preliminary noted the branch but not proposed as I go for a travel these days. Thx for the proposal! 
Although the site S:Y451 locates in RBD region, it is not a popular mutation site (even over the half of seqs in Cov-spectrum are low-quality seqs showing the all deletion of Spike), and S:Y451H are only about 230 seqs since 2020. Since it has become the vast majority of seqs in Kenya and detected outside Kenya, we ought to monitor it for potentially international spread.

**Comment by HynnSpylor** [comment]
one more seq in Australia

**Comment by FedeGueli** [comment]
thx @HynnSpylor not a good news.
While very encouraging that Kenyan bioinformatics are already aware and sound, tracking this sublineage, i had acknowledged via a brief twitter exchange with them.

**Comment by corneliusroemer** [comment]
I'll designate the cluster as FY.4 with A8374G, C25517T - presumably the S:Y451H is real but let's see whether this is confirmed by more labs around the world. The fact there are two non-RBD mutations make it quite definite that this cluster is real - so no reason not to designate.

**Comment by HynnSpylor** [comment]
Latest: Kenya updates 16 seqs today, all of them are FY.4, and 9 of 16 get S:S494P

**Comment by FedeGueli** [comment]
@HynnSpylor it is worse than that they are 26 new samples of FY.4 uploaded today from Kenya 

try the gisaid query A8374G , T22913C

**Comment by FedeGueli** [comment]
@corneliusroemer @HynnSpylor i think all the sequences has S:S494P too ( that could be interesting cause H-P -P -P 445-451 486-494 all together may give conformational changes to RBD) 
It is in only 9 sequences but all the 39 other sequences of FY.4 have NNN at 494:
![Schermata 2023-05-07 alle 10 58 48](https://user-images.githubusercontent.com/87669813/236668032-6fafaedb-88ed-4734-8af5-11e455
![Schermata 2023-05-07 alle 10 59 03](https://user-images.githubusercontent.com/87669813/236668046-997f404b-5d20-4450-bb6a-2f0f96160737.png)
5636ca.png)
![Schermata 2023-05-07 alle 10 59 25](https://user-images.githubusercontent.com/87669813/236668062-f90ead84-42b1-4dec-a109-6cdbe637a097.png)
![Schermata 2023-05-07 alle 10 59 49](https://user-images.githubusercontent.com/87669813/236668085-e915bce0-6e6b-46db-91b7-f2a1666bba35.png)


CC @thomaspeacock @AngieHinrichs @InfrPopGen i think this should have been flagged as potential thing , i know the african surveillance system is already on it.

**Comment by krosa1910** [comment]
Yes, P is known to be the most rigid amino acid with its amide on a ring and could not act as a hydrogen bond donor, and having many Proline in a close space would severely affect the folding of protein structure.

One of my early hypothesis in discussion with other Chinese variant hunters is that this could mean that there may exist an evolutionary lid by simply the number of P in the RBD, which could be stopping lineages with P at 445/486 to acquire a lot of additional P because of difficulty of folding causing instability, and actually hold back potentially useful P mutation, maybe 494P being the most important one.

From Gisaid, among sequences this year, 651 seqs with both 486 and 494 being P are submitted , 591 if additionally requesting V445P, yet solely S494P gives 2496 seqs. While there are 285818 out of 625757 lineage with F486P, 260363 if requesting V445P.

By math it showed that the population of seqs are 45% 486P, but the sample with 494P is only 26% 486P, showing ~57% ratio, the number seems similar in XBB and other 486P lineages. Meaning that 494P could be hindered by 486P.

However, Sars-Cov2 could counter this problem by probably getting other mutations to create pack space for the P, or create hydrogen bond to stable the structure. If this lineage show successfulness, we should closely examine why it makes those two P coexist.

**Comment by FedeGueli** [comment]
> Yes, P is known to be the most rigid amino acid with its amide on a ring and could not act as a hydrogen bond donor, and having many Proline in a close space would severely affect the folding of protein structure.
> 
> One of my early hypothesis in discussion with other Chinese variant hunters is that this could mean that there may exist an evolutionary lid by simply the number of P in the RBD, which could be stopping lineages with P at 445/486 to acquire a lot of additional P because of difficulty of folding causing instability, and actually hold back potentially useful P mutation, maybe 494P being the most important one.
> 
> From Gisaid, among sequences this year, 651 seqs with both 486 and 494 being P are submitted , 591 if additionally requesting V445P, yet solely S494P gives 2496 seqs. While there are 285818 out of 625757 lineage with F486P, 260363 if requesting V445P.
> 
> By math it showed that the population of seqs are 45% 486P, but the sample with 494P is only 26% 486P, showing ~57% ratio, the number seems similar in XBB and other 486P lineages. Meaning that 494P could be hindered by 486P.
> 
> However, Sars-Cov2 could counter this problem by probably getting other mutations to create pack space for the P, or create hydrogen bond to stable the structure. If this lineage show successfulness, we should closely examine why it makes those two P coexist.

pls open a P issue on the other page, it would be nice to discuss this point but better not herr

**Comment by FedeGueli** [comment]
One more sequence came from Austria this time without S:S494P

**Comment by FedeGueli** [comment]
58 sequences as today one from Shanghai the rest from Kenya.

Current tree is a bit unreliable due to NNN at S:405 and  S:494 
![Schermata 2023-05-13 alle 01 26 48](https://github.com/cov-lineages/pango-designation/assets/87669813/dde07a6a-1fc7-4d3b-86cb-736357678c40)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_8bc5_ecaea0.json?c=userOrOld&label=id:node_6725769

@corneliusroemer @thomaspeacock

 concerns i m seeing here:
1) fast detection in regions with known good surveillance (Austria,Australia, Shanghai)
2) High prevalence in the region where it likely originated
3) New mutation directly in the rbd  just next to 452 another residue able to give great differences in fitness
4) seqs are accumulating very fast in comparison to fast lineages although the main uploading country  is not one with an high sequencing intensity 

Possible bias:
All sequences are coming from one single region in the likely country of origin.
