### ISSUE TITLE
Potential new sublineage of B.1.617.2 circulating in Sri Lanka

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#199]
Michael Edwards brought to my attention this growing Delta sublineage in Sri Lanka
carrying two additional spike mutations:
S:A222V, A701S
Here the nexstrain build:
https://nextstrain.org/community/aicbu/ncov/srilanka?c=gt-S_222,701&m=div

![Screenshot_2021-08-23-01-54-02-390_com linkedin android](https://user-images.githubusercontent.com/87669813/130442818-50807405-d2d1-4591-be92-05c4321771b6.jpg)

**Comment by FedeGueli** [comment]
Author: @mkedwards

**Comment by zach-hensel** [comment]
I think S:A1078S precedes S:A701S and then there's a 6-sequence S:Q1208H branch on top of that. Noticed this a couple weeks ago and following a bit since then; now exported to UK (2), USA (1), Australia (1; probably travel quarantine?) and Japan (1; travel quarantine)... imo it would good to designate all sub-lineages with plausibly-significant-but-not-obviously-significant Spike mutations in a systematic way. There are now many of them e.g. #188 is similar.

**Comment by FedeGueli** [comment]
Thank you @zach-hensel  , Mr.Babar already noticed tbat S:A1078S precedes S:701S in the #196 issue. 
As said there, i am a" not technical' here, so thank.you very much for digging it

**Comment by chrisruis** [comment]
Thanks @FedeGueli, we've added this as AY.28 in [v1.2.68](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.68) with 108 sequence designations. We've started AY.28 on a branch with C8950T (synonymous), C9246T (Orf1ab:A2994V) and G24794T (S:A1078S) which appears to coincide with the introduction(s) into Sri Lanka
