### ISSUE TITLE
FL.13 with S:K356T in China(26 seqs, 3 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2073]
From (https://github.com/sars-cov-2-variants/lineage-proposals/issues/104)
FL.13+C21904T,T6334C,C7843T+A22629C(S:K356T)
GISAID query: C21904T,T6334C,C7843T,A22629C

No. of seqs: 26(China 24 Singapore 1(from China), South Korea 1(from China))
GISAID has 24, and also C_AA022306.1, C_AA024399.1 on GenBase.

First seq: EPI_ISL_17785084, Beijing, 2023-4-17
Latest: EPI_ISL_17850217, Fujian, 2023-6-15

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d524_b9b7e0.json)
![屏幕截图 2023-06-27 213504](https://github.com/cov-lineages/pango-designation/assets/10445944/234e79df-9083-4d41-a3fe-5745dbfaf907)

**Comment by corneliusroemer** [comment]
Agree this is interesting. It looks a bit strange in that it for something quite recent it should be less ladder like. Maybe there is homoplasy or recombination involved? Or maybe sequencing errors. I'll designate anyways as one as there's no benefit in overcomplicating.

**Comment by Over-There-Is** [comment]
C_AA022306.1 and C_AA024399.1 are also on GISAID, they are EPI_ISL_17794209 and EPI_ISL_17811154, but they have T6334C and/or C7843T dropout.
Canada/ON-PHL-23-25722/2023|EPI_ISL_17814590|2023-06-08 have C21904T, C7843T, A22629C, C11956T, C12789T mutations, seems that it is a FL.13.2 / XBL recombinant.

**Comment by ryhisner** [comment]
The reason the Usher tree here looks weird is because there's a 66-nucleotide deletion in NSP3 in this lineage—∆3278-3343 / ORF1a:1005-1026del / NSP3_187-208del. This is misread in all the Chinese sequences, and a few others—Ginkgo Bozoworks of course fails to register the deletion—but seven different countries have registered it correctly. In fact, every non-Chinese FL.13.2 sequence has the deletion, with the sole exception of the Ginkgo Bozoworks sequence.
<img width="1455" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/91ca3f87-0c7e-42d9-8bb8-2a73cf0c033f">
.

Some sequences have areas of missing coverage there, while others register multiple mutations, sometimes both preceding the deletion and sometimes on both sides of the deletion. Below are some of the different misreads, which make the Usher tree look so unusual. 
<img width="928" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/f28d1c12-5861-44fa-a351-503eac4ca461">
<img width="952" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/822fc771-48af-4455-b3ac-7f28b4828476">
<img width="1047" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/33738461/583ed21c-28d8-4e8b-a2d3-04c6849cc50a">

**Comment by Memorablea** [comment]
> Great finding @ryhisner . We should start to check every new lineage for this kind of things outside the spike. We usually are running out of time but i invite everyone to do that, me first ( @NkRMnZr, @aviczhl2 , @Fearuncle @HynnSpylor , @Memorablea, @BorisUitham). Also TRS thing when we notice a nuc mut at the end of a protein , we can tag @ryhisner that is the master of TRSes

Sorry, due to possible major issues with my network, GISAID cannot log in. Therefore, I cannot participate in your excellent work until the login page is restored. I'm very sorry!

**Comment by FedeGueli** [comment]
> > Great finding @ryhisner . We should start to check every new lineage for this kind of things outside the spike. We usually are running out of time but i invite everyone to do that, me first ( @NkRMnZr, @aviczhl2 , @Fearuncle @HynnSpylor , @Memorablea, @BorisUitham). Also TRS thing when we notice a nuc mut at the end of a protein , we can tag @ryhisner that is the master of TRSes
> 
> Sorry, due to possible major issues with my network, GISAID cannot log in. Therefore, I cannot participate in your excellent work until the login page is restored. I'm very sorry!

Dont worry you and your page are doing a huge work! Thank you!
