### ISSUE TITLE
Two potential sub-lineages of B.1.617.2 (Delta) characterized by mutations C23277T (Spike_T572I), T22293C (Spike_L244S) and C21304T

### ISSUE THREAD

**Issue by banijolly** [cov-lineages/pango-designation#209]
Sub-lineage of B.1.617.2
Countries circulating: Multiple countries including Netherlands, Bulgaria, Maldives, Italy, Germany, United Kingdom, USA, Turkey, Spain, Czech

The C23277T (S:T572I) branch further splits into two sub-clusters, one with T22293C (Spike_L244S) and the other having T22293C. 

![image](https://user-images.githubusercontent.com/47384613/131976689-f9c3fdbf-5e79-4b88-af3e-015225c1693e.png)
(source https://nextstrain.org/groups/neherlab/ncov/21A.Delta?c=gt-S_244,572&f_country=Maldives&label=mlabel:21A%20%28Delta%29/C23277T)

The L244S sub-cluster seems to be prevalent in Maldives

![image](https://user-images.githubusercontent.com/47384613/131977404-de92e74e-944c-499b-9da3-848248a501ce.png)

The two sub-clusters (orange and blue) are more clearly visible in the USHER Sub-tree built using these GISAID accession IDs
[Accession_IDs_T572I.txt](https://github.com/cov-lineages/pango-designation/files/7104545/Accession_IDs_T572I.txt)

![image](https://user-images.githubusercontent.com/47384613/131977737-1eba3419-3e44-48c1-9072-4c6ab10662b7.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_332f2_1d8200.json?c=gt-nuc_21304,22293,23277&label=nuc%20mutations:G15451A,C16466T,C22995A,T26767C,C27752T

**Comment by chrisruis** [comment]
Thanks @banijolly. It looks like there's an epidemiologically distinct clade of sequences from South Africa within the non-Spike_L244S part of the clade, downstream of C9286T (synonymous). We've added this clade as AY.32 in [v1.2.76](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.76)

The Spike_L244S clade is more tricky as it seems to contain interspersed sequences from lots of countries rather than being epidemiologically distinct. There are a number of smaller clades that are more geographically distinct but these are likely too small for a designation at this point. We therefore haven't added the Spike_L244S clade and recommend that these are referred to as B.1.617.2 for now. Thanks again

**Comment by banijolly** [comment]
Agree about Spike_L244S, the smaller clades will need to be monitored for now.
Thanks a lot, @chrisruis !

**Comment by FedeGueli** [comment]
CC: @corneliusroemer @chrisruis 

The remaining previously undesignated clades of this issue has been designated:
AY.95 starting with S:L244S (Maldives)
AY.104 (parent of both AY.95 and AY.32) starting with S:T572I (Sri Lanka)

Commits:
AY.95:
https://github.com/cov-lineages/pango-designation/commit/f6d835f18b9868970d1aecd937a44f8414e2287a
AY.104:
https://github.com/cov-lineages/pango-designation/commit/c3c5c8d3b1eba7056f612ba5dda486a90de78b63
