### ISSUE TITLE
Sublineage of B.1.214 in Congo/ France

### ISSUE THREAD

**Issue by aineniamh** [cov-lineages/pango-designation#21]
### Proposed lineage name
B.1.214.1

### Description

Sub-lineage of: B.1.214
Countries circulating:  Congo, France

### Taxa
17 sequences on GISAID

[B.1.214_2021-03-02.lineages.csv.zip](https://github.com/cov-lineages/pango-designation/files/6068697/B.1.214_2021-03-02.lineages.csv.zip)

### Evidence
<img width="921" alt="Screenshot 2021-03-02 at 12 50 42" src="https://user-images.githubusercontent.com/11678307/109651000-e804d700-7b55-11eb-8ae7-c05d22276b97.png">
Red = B.1.214
Green = B.1.214.1 (Congo/ France lineage)
Blue = B.1.214.2 (European/ Belgian lineage with key mutations and insertion mutation)

### Suggested by

Áine O'Toole, Andrew Rambaut

**Comment by AngieHinrichs** [comment]
I was looking into why USHER has a hard time finding the right node for B.1.214 given the set of samples in the latest pango-designtion/lineages.csv, and in our tree, the 240ish sequences in the attached B.1.214_2021-03-02.lineages.csv.zip fall into 4 very distinct clusters, with 3 distinct sets of countries (DRC/Uganda;  Denmark;  Belgium, France, etc.).  Here is a marked-up view showing the countries I see in each cluster:

![image](https://user-images.githubusercontent.com/186983/111853331-cb97c700-88d7-11eb-94d3-aee4b046e48f.png)

Here is the interactive link, where you can mouse over the red dots to see the sequence names with countries, and mouse over branches to see mutations:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/B.1.214_2021-03-02.lineages.json

One thing that we can't see in that heavily subsampled view is whether samples assigned to other lineages are also present on those branches in our tree.

**Comment by aineniamh** [comment]
[B.1.treesubtree_12_AOT.nexus.zip](https://github.com/cov-lineages/pango-designation/files/6180986/B.1.treesubtree_12_AOT.nexus.zip)
That looks reassuringly similar to our tree that was designated, but looking at it I realise I hadn't included the sublineages in the new designations. I can update that now and add in B.1.214.1. The second sublineage isn't quite so well resolved as you say, so for the moment I will leave it as B.1.214 without a designation.  
<img width="1180" alt="Screenshot 2021-03-22 at 09 33 45" src="https://user-images.githubusercontent.com/11678307/111969138-d4fc7b80-8af1-11eb-8e8e-b02f5de2ee77.png">

**Comment by AngieHinrichs** [comment]
Thanks!  I see that now -- sorry I sent that before figuring out better what was going on.  [There is a quirk of our tree that resulted in the DRC/Uganda branch being placed farther from root than it should be, with a couple back-mutations to compensate for mutations it was placed after.  The DRC/Uganda branch was identified as the best candidate for B.1.214 because it has the shared set of mutations common to B.1.214 samples -- but because of the suboptimal placement with back-mutations, it's not ancestral to the other branches like it should be, so there were too many samples not descended from that node, so assignment of B.1.214 failed.  I'll give matOptimize a try on our end and see if that helps.]
