### ISSUE TITLE
Discussion on whether HQ.1 (XBB.1.5.92.1) should be nested under XBB.1.5.92 or not

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2146]
As discussed with @AngieHinrichs here : https://github.com/sars-cov-2-variants/lineage-proposals/issues/362#issuecomment-1639250186

this lineage has C823T coming before the defining of XBB.1.5.92 ORF1a:T1168I so it is very likely a separate lineage or at least a recombination between XBB.1.5.92 and XBB.1.5 + C832T happened in Ecuador.

**Comment by corneliusroemer** [comment]
HR is completely unrelated to XBB.1.5.92.1 -  it's XBB.1.5.77.1. Can you double check your argument? I can't follow...

When I list mutations in lineage notes they don't imply a certain sequence, I put the more important ones first. 832T happened before ORF1a:T1168I but is listed after in lineage notes due to being a synonymous one.

<img width="1483" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/dc9db2ec-e526-47af-84bc-8b5f34b30ee4">

<img width="1279" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/2462f508-4e54-4686-8f29-089c37622cc7">

https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_368c6_17aa10.json?c=gt-nuc_823,3768,23222&f_userOrOld=uploaded%20sample

**Comment by corneliusroemer** [comment]
Oh I see, I changed the lineage notes today to include C823T - it wasn't there before. It's indeed not quite clear which of C823T and ORF1a:T1168I happened first.

**Comment by corneliusroemer** [comment]
Having looked at the lineage of interest here and where it's occurring most commonly, it's clear that:
1. In Ecuador, C3768T = ORF1a:T1168I is more common than C823T
2. The lineage currently designated as HR.1 has C3768T, C823T and C10615T
3. It is thus appears more plausible that the sequence of events for this lineage here is _first_ C3768T, then C823T, C10615T - mostly due to geographic constraints and the fact that in Ecuador C823T is uncommon on its own:
C823T but not C3768T: 3 in Ecuador
not C823T but C3768T: 80 in Ecuador

As a result, I think the current designation is correct - however I should revert the lineage notes back to the previous state, XBB.1.5.92 is an Ecuador lineage with C3768T as defining mutation, not requiring C823T

HR.1 is an Ecuadorian sublineage of XBB.1.5.92 with extra C823T, C10615T and S:E554K

The branch  C823T, C10615T should be moved to within XBB.1.5.92.

@AngieHinrichs

**Comment by FedeGueli** [comment]
> HR is completely unrelated to XBB.1.5.92.1 - it's XBB.1.5.77.1. Can you double check your argument? I can't follow...
> 
> When I list mutations in lineage notes they don't imply a certain sequence, I put the more important ones first. 832T happened before ORF1a:T1168I but is listed after in lineage notes due to being a synonymous one.
> 
> <img alt="image" width="1483" src="https://user-images.githubusercontent.com/25161793/256351290-dc9db2ec-e526-47af-84bc-8b5f34b30ee4.png"> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/25161793/256351470-2462f508-4e54-4686-8f29-089c37622cc7.png">
> https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_368c6_17aa10.json?c=gt-nuc_823,3768,23222&f_userOrOld=uploaded%20sample

yeah i was meaning HQ.1

**Comment by FedeGueli** [comment]
> Having looked at the lineage of interest here and where it's occurring most commonly, it's clear that:
> 
> 1. In Ecuador, C3768T = ORF1a:T1168I is more common than C823T
> 2. The lineage currently designated as HQ.1 has C3768T, C823T and C10615T
> 3. It is thus appears more plausible that the sequence of events for this lineage here is _first_ C3768T, then C823T, C10615T - mostly due to geographic constraints and the fact that in Ecuador C823T is uncommon on its own:
>    C823T but not C3768T: 3 in Ecuador
>    not C823T but C3768T: 80 in Ecuador
> 
> As a result, I think the current designation is correct - however I should revert the lineage notes back to the previous state, XBB.1.5.92 is an Ecuador lineage with C3768T as defining mutation, not requiring C823T
> 
> HQ.1 is an Ecuadorian sublineage of XBB.1.5.92 with extra C823T, C10615T and S:E554K
> 
> The branch C823T, C10615T should be moved to within XBB.1.5.92. That position is equally parsimonious from a pure mutational perspective, but adding migration into the mix, it becomes clear that the current position is less likely.
> 
> @AngieHinrichs



> Having looked at the lineage of interest here and where it's occurring most commonly, it's clear that:
> 
> 1. In Ecuador, C3768T = ORF1a:T1168I is more common than C823T
> 2. The lineage currently designated as HQ.1 has C3768T, C823T and C10615T
> 3. It is thus appears more plausible that the sequence of events for this lineage here is _first_ C3768T, then C823T, C10615T - mostly due to geographic constraints and the fact that in Ecuador C823T is uncommon on its own:
>    C823T but not C3768T: 3 in Ecuador
>    not C823T but C3768T: 80 in Ecuador

Thanks for looking into it

**Comment by corneliusroemer** [comment]
I will rename the issue as I think we don't want to retract - but waiting for @AngieHinrichs to have a look/share her view

**Comment by AngieHinrichs** [comment]
@corneliusroemer I see your point about the frequencies in Ecuador alone.  I like @FedeGueli's suggestion that perhaps C823T came in by recombination.  Well, we'll never know for sure. :)

I don't think I can trick usher/matOptimize into moving {C3768T, C823T and C10615T} to XBB.1.5 > C3768T when there are more samples in XBB.1.5 > C823T (I believe it uses number of samples in each branch as a tie-breaker).  But I can add an extra label to the tree so that both C3768T and C823T > C3768T(,C10615T) are considered XBB.1.5.92, if you want to keep the 3768-only branch as part of XBB.1.5.92.

I'll leave it up to you to resolve the current inconsistency between lineage_notes.txt and lineages.csv (lineage_notes.txt says C823T, but all the samples in lineages.csv are from XBB.1.5 > C3768T and do not have C823T).

**Comment by AngieHinrichs** [comment]
I'm going to remove C823T from lineage_notes.tsv before tagging the next release.  

The UShER tree still has separate branches for XBB.1.5 > C3768T (labeled XBB.1.5.92, corresponds to sequences in lineages.csv) and XBB.1.5 > C823T > C3768T,C10615T (labeled XBB.1.5.92_823, includes HQ.1).  After the next data release, pangolin will assign XBB.1.5.92 to sequences that map to either branch (or HQ.1, if a sequence also has S:E554K).
