### ISSUE TITLE
XBB.1.16.1 with s:P521S, ORF1a:L681F 119 seq.

### ISSUE THREAD

**Issue by Fearuncle** [cov-lineages/pango-designation#2178]
transferred from: https://github.com/sars-cov-2-variants/lineage-proposals/issues/366 
![image](https://github.com/cov-lineages/pango-designation/assets/78371872/c4f6f4b5-5b6b-4a3f-af7c-e973fc9697b4)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2d451_419da0.json?c=gt-S_521&label=id:node_6727721
gisaid query: C2306T, C23123T, A22101T

**Comment by FedeGueli** [comment]
It has slowed down a lot. thx for keeping it tracked.

**Comment by FedeGueli** [comment]
No chance to compete: https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=C2306T%2CC23123T%2CA22101T&analysisMode=CompareToBaseline& better closing down this and keep the focus on fast variatns , the landscape already mutated since the last month
