### ISSUE TITLE
XBB.1.9.1 with S:E484K (28 Seqs, Spain, Greece, Sweden, USA, Canary Islands, Switzerland,Portugal)

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#2206]
Lineage of:XBB.1.9.1 with ORF1A:A79T -> C22858T -> C7303T + [G23012A + C23013A (reversion)](S:E484K)
Earliest sequence:2023-05-22 (Spain)
Most recent sequence:2023-08-21 (USA)
GISAID Search： G500A,C22858T,C7303T,G23012A

[Tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_cf42_4ac5a0.json)
![image](https://github.com/cov-lineages/pango-designation/assets/94097102/3b8cbf52-c276-48af-8f5a-661a93616214)

Discussion: 
This is likely not a very fast lineage, but it seems to still be growing despite missing all of the convergent spike mutations as of late. I think that this does highlight the viability of S:E484K though, which requires a 2-nuc mutation. It of course is a focus of sorts in BA.2.86 which also has an adjacent deletion at S:483, but S:E484K has also come up in [EG.6.1](https://github.com/sars-cov-2-variants/lineage-proposals/issues/546), as well as [an interesting BQ.1.2.2](https://github.com/sars-cov-2-variants/lineage-proposals/issues/650) that may have recently emerged/be spreading.  

E484K is predicted to come at a slight benefit on XBB.1.5 for all 3 attributes- ACE2 binding, spike expression, and immune evasion. 
![image](https://github.com/cov-lineages/pango-designation/assets/94097102/32123015-ac9e-44dc-b020-3e7fc17e3517)
![image](https://github.com/cov-lineages/pango-designation/assets/94097102/53fff90d-222a-4533-a844-9d042ab41028)

As is visible in the tree, the Greek samples form a separate cluster from the rest of the sequences, and are also lacking the spike mutation S:A852S. However, due to the mutations leading up to this branch, it is still clear that they are in fact a part of the same lineage. 

The Aug 21 USA California sequence is not found by the query due to lack of coverage. Spike_E484K, Spike_A852S will find it.

**Comment by thiolist** [comment]
One thing that the E484K mutation does is to add a proteolytic cleavage site that is a target of the HAT (Human Airway Trypsin-like) protease, which could cleave the spike protein at this site. This would change the protein shape in the airway (nasal passage to lungs) without changing its shape elsewhere in the body (e.g. change transmissibility without affecting infectability of tissues outside of the airway).

The original sequence ...VEG... (amino acids 483-485) is not cleaved by a trypsin-like protease, as indicated by the online tool "Peptide Cutter" (https://web.expasy.org/peptide_cutter/). Here are the simulation results:
<img width="431" alt="Peptide cutter result for  VEG  sequence" src="https://github.com/cov-lineages/pango-designation/assets/142126282/d9a34ae8-d135-43d7-9521-86cb044b7194">

However, the new sequence ...VKG... is likely to be cleaved by the HAT trypsin like protease:
<img width="957" alt="Peptide cutter result for  VKG  sequence" src="https://github.com/cov-lineages/pango-designation/assets/142126282/ecbe3d32-8ce1-48b0-9577-dcde13c0655f">

Interestingly, TMPRSS2 (another trypsin-like protease) is membrane bound.The spike only becomes available to this enzyme after it has become bound to ACE2 at the cellular membrane.

Conversely, the HAT enzyme is soluble, so the spike is continuously available to this enzyme prior to binding to ACE2.

Therefore, the spike that antibodies "see" within the human airway prior to ACE2 binding can have this site already cleaved, and therefore not be recognized by the antibody.

*IMPORTANT*

Tissues other than the human airway will not have this site cleaved by HAT, and therefore antibodies that target this site on the spike should still function in the rest of the body. Hence disease severity is more effectively controlled by vaccine or previous infection induced antibodies in locations outside of the human airway.

**Comment by ryhisner** [comment]
One more from Switzerland. EPI_ISL_18129932
Collected July 31, making it the third most recent sequence. Appears to be identical to one of the sequences from Spain. Strangely, it appears to be identical to a sequence collected in Spain on May 22 (EPI_ISL_17780982).

**Comment by FedeGueli** [comment]
two more samples not yet on Gisaid from Scotland: 

Scotland/CLIMB-CM7YJCHJ/2023\|2023-08-11
Scotland/CLIMB-CM7YRZ6C/2023\|2023-08-11

Tree:

![Schermata 2023-08-26 alle 14 52 32](https://github.com/cov-lineages/pango-designation/assets/87669813/a694d1d6-ef32-48be-9506-f1016e367c68)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_7d42_9df3c0.json?c=country&label=id:node_6898554

**Comment by thiolist** [comment]
It helps evade RBM targeted antibody based immunity that was acquired either by vaccination or by prior infection by a variant that didn't have this mutation.

**Comment by thiolist** [comment]
The E484K mutation introduces a site on the S1 protein that can be cleaved by trypsin-like proteases such as the HAT (Human Airway Trypsin-like) protease that is released onto the mucus membrane (https://www.ncbi.nlm.nih.gov/gene?Db=gene&Cmd=DetailsSearch&Term=9407).

The E484 site on the S1 protein is on the surface of the RBM (Receptor Binding Motif) which is the binding site for ACE2. See "Antibody resistance of SARS-CoV-2 variants B.1.351 and B.1.1.7" (Nature. 2021; 593:130), Figure 1:

<img width="552" alt="RBM location of E484" src="https://github.com/cov-lineages/pango-designation/assets/142126282/8200ca38-5e12-4699-8328-102b4ec266e4">

This site appears to be accessible to the HAT protease, given the dramatic loss of efficacy of monoclonal antibodies that target this site. The B.1.351 variant (Beta). See Figure 2 of the paper:

<img width="704" alt="RBD-directed monoclonal antibodies" src="https://github.com/cov-lineages/pango-designation/assets/142126282/acbbfa39-ed6e-477e-ab78-e17f1afe60e3">
<img width="707" alt="Loss of RBD-directed neutralization" src="https://github.com/cov-lineages/pango-designation/assets/142126282/4919087e-1412-44ce-8aab-cfc13ffc6790">

An important fact that doesn't show up in these figures is that their method for the production of these pseudoviruses uses "HEK293T" cells ". ["HEK293T cells were grown to 80% confluency before transfection with the spike gene using Lipofectamine 3000 (Invitrogen). Cells were cultured overnight"] These cells moderately express TMRSS9, (https://www.ncbi.nlm.nih.gov/gene/360200) which is a soluble trypsin-like protease, that is analogous to the HAT (TMPRSS11d) protease that is present in the mucus that lines the human airway (sinus-to-lungs). All of the pseudovirus virions produced by these cells are subject to cleavage by this protese prior to their use in the neutralization assay. This is different from neutralization assays used by many other groups, which do not expose the virions to trypsin-like protease activity, and therefore miss the impact of the E484K mutation.

So, in most bodily tissues it doesn't matter much whether 484K comes back, because it won't be cleaved in tissues that lack a trypsin-like protease. But in the human airway, it becomes complicated.  People who have been previously infected by inhaling a variant that has E484K (see https://covariants.org/variants/S.E484) probably have good immunity against becoming infected by inhaling 484K. Other than that, no one has existing antibody protection for this mutation. In other words, people who have been infected by a SARS-CoV-2 that doesn't have 484K (or were vaccinated w/o 484K) will have little to no protection by the antibodies that they have that are directed to the E484 (or 484A, 484Q, ...) virion RBM.

E484K has not been included in any of the spike sequences used in vaccines (to the best of my knowledge). But that hardly matters, because the vaccines are not administered via the human airway. Even including it now would hardly matter without it being administered via the human airway (otherwise it will remain uncleaved, and therefore won't produce 484K directed antibodies). 

The catch-22 is that to prevent a person being infected via inhalation, you want antibodies that target the cleaved RBM, but to have antibody protection against severe disease (involving tissues that are not the human airway) you want antibodies that target the uncleaved RBM.
