### ISSUE TITLE
GK.2.1/XBB.1.5 recombinant with additional S:P1162S (43 seqs, 11 countries)

### ISSUE THREAD

**Issue by aviczhl2** [cov-lineages/pango-designation#2227]
From https://github.com/sars-cov-2-variants/lineage-proposals/issues/700

XBB.1.5(with 17124 but without 10204)+C27059T+C28005T(Orf8:P38S), T22928C(S:F456L),G22927T(S:L455F),C22624T,A25045G
+C15755G(Orf1b:S763C),G23093A,C23741T(S:V511I),C7417T,C25046T(S:P1162S)

C15755G,G23093A,C23741T,C27059T,C28005T,T22928C,G22927T,C22624T,A25045G are from GK.2.1
C7417T,C25046T are private mutations.

XBB.1.5--GK.2.1
Breakpoint between  12468 and 15754.

GISAID query: C7417T,C25046T,C15755G
No. of seqs: 31(Canary Islands 2 UK 14 Spain 3 Switzerland 2 USA 2 South Korea 1 Norway 1 Ireland 1 Israel 1 Italy 4 )
9-CLIMB seqs currently not on GISAID.

First: EPI_ISL_18119219, Italy, 2023-5-18
Latest: CLIMB-CM7YGPFT, UK, 2023-8-21

[usher](https://nextstrain.org/fetch/raw.githubusercontent.com/aviczhl2/lineage_proposal_jsons/main/gk_2_1_xbb_1_5_recomb.json?label=id:node_7217731)
![image](https://github.com/cov-lineages/pango-designation/assets/10445944/6c1b05a5-f598-459e-9797-18e68070248f)

![image](https://github.com/cov-lineages/pango-designation/assets/10445944/486c16d4-2b77-48cc-9e8c-98df33c829fc)

**Comment by aviczhl2** [comment]
Detected in France and Belgium.  36 on GISAID and 7 additional CLIMB seqs. Total 43.

**Comment by corneliusroemer** [comment]
Oh it actually matches this small branch of XBB.1.5.68 with 7417T:
<img width="1382" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/7d23b706-021f-4225-8658-2f7b1b2ca2b6">
https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3dd2f_1c52b0.json?label=id:node_7290583

Or these 3 sequences at the bottom just before FY.4.2 - though none of them are cmopatible due to extra ORF1a mutations
<img width="1375" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/c1193b64-4267-41f3-b434-81045d83586c">
https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_3dd2f_1c52b0.json?label=id:node_7290583

So I'll leave it open as XBB for the parent side

**Comment by FedeGueli** [comment]
Thx @corneliusroemer this seems fast

**Comment by JosetteSchoenma** [comment]
XCL
