### ISSUE TITLE
Two potential sublineages of B.1.621.1, one with Spike Y449N and E583D, the other with Spike S939F

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#232]
**Proposed sublineage 1**
**Description**
**Sub-lineage of: B.1.621.1** (98 sequences)
**Earliest sequence**: 2021/5/15 (Spain)
**Most recent sequence**: 2021/9/11 (Chile)
**Countries circulating**: Chile (19 sequences); also found in Cadada, Colombia, Peru and the US, likely extinct though.
**Mutations in addition to B.1.621.1**: 
M: R146H
N: T391I (defining)
S: Y449N, E583D
ORF1a: T812I
ORF7a: Q94H
**Genomes:**
[MU Y449N.csv](https://github.com/cov-lineages/pango-designation/files/7263516/MU.Y449N.csv)

**Proposed sublineage 2**
**Description**
**Sub-lineage of: B.1.621.1** (264 sequences)
**Earliest sequence**: 2021/5/19 (Spain)
**Most recent sequence**: 2021/9/8 (the US-CA)
**Countries circulating**: the US, predominantly California (212 sequences), and other states (41 sequences)
**Mutations in addition to B.1.621.1**: 
N: T379I (defining)
S: S939F (defining)
ORF1a: N2147D, K2148R (defining), T2952I
ORF3a: V259L
**Genomes**:
[MU S939F.csv](https://github.com/cov-lineages/pango-designation/files/7263718/MU.S939F.csv)

**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/135554599-38a6d70a-c1b6-430f-9d7d-62f144962f15.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_9c64_648aa0.json?c=gt-nuc_26959,24378&l=radial

**Comment by FedeGueli** [comment]
As cited in #299 there is an interesting thread on twitter on sublineage 1 by Ricardo Rivero @RicardoRH96
https://twitter.com/Ricardo__JRH/status/1450544232750620675?s=20

**Comment by MCB6** [comment]
A new GISAID upload just came from Colombia. It continues to look like the issue in #299 is real, and S:E583D+S:Y449N continues to expand even as the rest of Mu is close to extinction
![Mu-Colombia](https://user-images.githubusercontent.com/93294184/139880913-5f7482fe-65d2-461f-bbfa-129296508ebb.png)

**Comment by corneliusroemer** [comment]
It looks interesting, yes, because it seems to be able to almost compete with Delta - but only in Colombia, not Chile.

Colombia doesn't sequence much so the uncertainty is huge. But it does seem to have staying powers which is very interesting.

![image](https://user-images.githubusercontent.com/25161793/139951304-586a72ec-9d0d-4c73-b853-d7f5304833d7.png)

[covSpectrum](https://cov-spectrum.ethz.ch/explore/Colombia/AllSamples/Past3M/variants?aaMutations=S%3AY449N%2CS%3AE583D&pangoLineage=B.1.621*)
I support designation @chrisruis

**Comment by MCB6** [comment]
> Colombia doesn't sequence much so the uncertainty is huge. 

That's why I got excited today when they nearly doubled the number of last two month's sequences. I don't think it's visible at covSpectrum yet. But still with the grand total of 5 sequences in October,  it's too uncertain, and regional variation may obscure any real trends.  In Chile it see to be highly regional too, like Atacama in the North?

**Comment by FedeGueli** [comment]
@MCB6 you could search on CovSpectrum just the mutations.

https://cov-spectrum.ethz.ch/explore/South%20America/AllSamples/Past3M/variants?aaMutations=S%3A449N%2CS%3A583D

![VariantDivisionDistributionChart](https://user-images.githubusercontent.com/87669813/140061997-7ca7a53e-9149-48ad-a9be-9a6e68be278d.png)

**Comment by MCB6** [comment]
> @MCB6 you could search on CovSpectrum just the mutations.
> 
> https://cov-spectrum.ethz.ch/explore/South%20America/AllSamples/Past3M/variants?aaMutations=S%3A449N%2CS%3A583D
> 
And one can click on Chile's regions to realize that at one point, this Mu variety accounted for almost all of Atacama's sequences. But apparently not anymore. The strain dynamics in this region has several weirdly quick sweeps. Before mid-August it was Chile's usual Gamma / Lambda mix. Then Mu arrived and in just one months achieved total dominance (mostly, but not only, this substrain). Then Delta arrived and in another month the sweep was complete, with the classic Mu going away first, and the Mu+S:449N+S583D holding for only a little bit longer. 
The number of cases in Atacama has been quite low during all this era of sweeps, mostly in single digits daily, so we may be dealing with founder outbreaks rather than with true strain competition? Which might explain the unrealistically fast changes?
![Mu-Atacama](https://user-images.githubusercontent.com/93294184/140164058-4369cf98-a6e9-40a4-9494-e8f864357a67.png)
![Mu-Atacama1](https://user-images.githubusercontent.com/93294184/140164060-555417da-703c-454b-9b8e-66e77aa692a5.png)

**Comment by MCB6** [comment]
Mu+S:449N+S583D was also in Lima, Peru in early August, seems to have disappeared by mid-September. 10 samples from Peru (they only started extensive sequencing in recent weeks, added over 3,000 genomes so far).

Colombia added more October samples today. Mu+S:449N+S583D still accounts for ~10% of the recently collected samples (8 / 85 samples)

**Comment by MCB6** [comment]
Another batch from Colombia uploaded, including some late-October samples. The slight expansion trend of Mu+Spike_E583D,Spike_Y449N is holding well. In contrast, other varieties of Mu are nearly extinct.
![image](https://user-images.githubusercontent.com/93294184/142776154-c6a2fb2f-0bc0-4bdc-a255-76d74fcdce40.png)

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added proposal 1 as lineage BB.1 with 91 designated sequences in v1.2.113
and proposal 2 as lineage BB.2 with 238 designated sequences in v1.2.113
