### ISSUE TITLE
could you please update "curation_notes.tsv" file, please.

### ISSUE THREAD

**Issue by liamxg** [cov-lineages/pango-designation#2414]
Dear @cov-lineages team,
Could you please update "curation_notes.tsv" file, please.

**Comment by Memorablea** [comment]
？

**Comment by Memorablea** [comment]
？

**Comment by AngieHinrichs** [comment]
@liamxg the file has not been maintained since spring 2021 (before the global Delta wave).  Updating it now would require a very large effort and nobody has that much extra time.  Is there specific information that is not in [lineage_notes.txt](https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt) or searchable in this repository (or in sars-cov-2-variants/lineage-proposals), that you would find in the curation notes?

**Comment by DailyCovidCases** [comment]
Please close this issue
