### ISSUE TITLE
JN.1.4 with S:T572I in Canada and US (266 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2512]
Formerly known as Branch 20 of https://github.com/sars-cov-2-variants/lineage-proposals/issues/1097 
defined by a triple nuc mutation around Orf1a:S216 resulting in Orf1a:S216N = NSP2_S36N

Defining JN.1.4 > T18453C > G910A, Orf1a:S216N (T911A, C912A), C8668T, S:T572I (C23277T),    
Query: T18453C, C8668T,G910A,C23277T
Samples:90
Countries: Canada (5 states) , Us (5 states), Chile (2 regions) Japan
<Details>
<Summary> IDs: 
</Summary> 
EPI_ISL_18654302, EPI_ISL_18654322, EPI_ISL_18654325,
EPI_ISL_18654337-18654338, EPI_ISL_18729280, EPI_ISL_18732056,
EPI_ISL_18756540, EPI_ISL_18768597, EPI_ISL_18769233,
EPI_ISL_18769552, EPI_ISL_18772352, EPI_ISL_18772362,
EPI_ISL_18779573, EPI_ISL_18780020, EPI_ISL_18787749,
EPI_ISL_18803900, EPI_ISL_18810837, EPI_ISL_18826375,
EPI_ISL_18826671, EPI_ISL_18839447, EPI_ISL_18839500,
EPI_ISL_18839857, EPI_ISL_18856136, EPI_ISL_18863927,
EPI_ISL_18868391, EPI_ISL_18874137, EPI_ISL_18882629,
EPI_ISL_18892909, EPI_ISL_18897501, EPI_ISL_18897503,
EPI_ISL_18908883, EPI_ISL_18913982, EPI_ISL_18914159,
EPI_ISL_18914168, EPI_ISL_18914274-18914275, EPI_ISL_18917450,
EPI_ISL_18920866, EPI_ISL_18927451, EPI_ISL_18927533,
EPI_ISL_18928442, EPI_ISL_18928444, EPI_ISL_18928449,
EPI_ISL_18928467, EPI_ISL_18928490-18928493, EPI_ISL_18933533,
EPI_ISL_18933535, EPI_ISL_18933540, EPI_ISL_18933552,
EPI_ISL_18933559-18933560, EPI_ISL_18933633, EPI_ISL_18933662,
EPI_ISL_18935588, EPI_ISL_18937995, EPI_ISL_18938130,
EPI_ISL_18945881, EPI_ISL_18945896-18945897, EPI_ISL_18946145,
EPI_ISL_18946157, EPI_ISL_18946176-18946180, EPI_ISL_18946189,
EPI_ISL_18946214, EPI_ISL_18946543, EPI_ISL_18946565,
EPI_ISL_18950410, EPI_ISL_18950493, EPI_ISL_18950539,
EPI_ISL_18950541, EPI_ISL_18950592, EPI_ISL_18956508,
EPI_ISL_18956789, EPI_ISL_18959635, EPI_ISL_18959665,
EPI_ISL_18959710, EPI_ISL_18959712, EPI_ISL_18959731-18959732,
EPI_ISL_18959742-18959743, EPI_ISL_18959745
</Details>
Tree:
<img width="1166" alt="Screenshot 2024-03-07 alle 09 27 27" src="https://github.com/cov-lineages/pango-designation/assets/87669813/50dd3ea6-4f47-4198-9b31-d0ec372d5e77">

[https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_49a81_9794d0.json?f_userOrOld=uploaded%20sample&label=id:node_6944557
](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_49a81_9794d0.json?f_userOrOld=uploaded%20sample&label=id:node_6944557
)

**Comment by FedeGueli** [comment]
@ryhisner the 910A 911A 912A could be a TRS thing?

**Comment by AngieHinrichs** [comment]
When I see a run of mutations in successive positions, I usually suspect a sequencing error, but maybe that's only because it makes tree-building more difficult.  ?

**Comment by AngieHinrichs** [comment]
These 6 sequences have the 910-12 substitutions, but don't have C8668T, and are currently placed with the other sequences in JN.1.4 but with reversions on 774 and 18453 (so they are not JN.1.4):

SouthAfrica/CERI-KRISP-K060866/2024|EPI_ISL_18931030|2024-02-05
SouthKorea/KDCA282622/2023|EPI_ISL_18823418|2023-12-30
Italy/PIE_IRCC_15897055/2023|EPI_ISL_18674017|2023-12-13
Canada/QC-L00680666001/2023|EPI_ISL_18654280|2023-11-24
USA/CA-CDPH-6000018682/2024|EPI_ISL_18940861|2024-01-16
USA/CA-GBW-H20-361-5118/2024|EPI_ISL_18945941|2024-02-16

Initially all of these sequences were placed on a JN.1 branch with a flip-flop on 1060 (before and after 910-912).  When scanning around inJN.1 I saw that most of the sequences were really JN.1.4 but pulled in to the flip-flop branch by sharing 910-912 with those sequences.  So I temporarily pruned the above 6 sequences and reoptimized so that the JN.1.4 sequences would be pulled into JN.1.4 by C774T and T18453C.  But when the 6 sequences were added back (2024-03-06), they were now incorrectly pulled into JN.1.4 because 3 substitutions (910-912) beats 2 (774 and 18453).  

Maybe it's cynicism, and it's certainly speculative, but I find it a lot easier to believe that 3 successive bases would have substitutions in different lineages (JN.1 and JN.1.4) due to sequencing errors than due to some real biological effect that would favor those 3 bases turning to 'A'.  (But I know there are real exceptions like B.1.1's 28881-28883 (GGG > AAC), and @ryhisner made a plausible case for 21302,21304,21305 being real - though I still had to mask those in Delta and BA.2.86, and was tempted to mask them in prior Omicrons.)

**Comment by FedeGueli** [comment]
106 now

**Comment by FedeGueli** [comment]
163 still mostly Canada

**Comment by FedeGueli** [comment]
slowed down closing it
