### ISSUE TITLE
Can't find 9487 strains listed in lineages.csv in Nextstrain (and at least some not in GISAID)

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#257]
The following 9487 strains listed in lineages.csv I couldn't find in an up to date ncov-ingest processed output.

I checked these following randomly chosen 3 manually on GISAID and didn't find any matches 
Scotland/QEUH-169FE4F/2021
Indonesia/NTB-GSILab-544314/2021
Peru/LIM-UPCH-0467/2021

![image](https://user-images.githubusercontent.com/25161793/137602770-4801e5be-6ae2-4839-b05a-8bd490a67dd0.png)

So the problem at least partially doesn't seem to be with Nextstrain's ingest, but could be due to these strains having been removed from GISAID but not from lineages.csv?

Here's the full list of strains I couldn't find (strain names according to lineages.csv):

[not_found.txt](https://github.com/cov-lineages/pango-designation/files/7358296/not_found.txt)

**Comment by AngieHinrichs** [comment]
Thanks for finding these, Cornelius.  I think many COG-UK sequences that are not accepted by GISAID are still used in pangoLEARN training -- mixed in locally from local latest COG-UK data.  [Repositories such as GISAID and GenBank often reject sequences with frameshift-inducing or early stop codon mutations; submitters can manually verify those and convince the repositories to accept them, if the submitters have enough time for that, but if I understand correctly, due to the volume of sequences, COG-UK doesn't take that extra step when sequences are bounced back.]

It looks like the name of EPI_ISL_2875769 has changed from "Indonesia/NTB-GSILab-544314/2021" to "Indonesia/NB-GSILab-544314/2021".  

This is very strange, but Peru/LIM-UPCH-0467/2021 appears for me...  temporary glitch?
![image](https://user-images.githubusercontent.com/186983/137829619-55812cf3-6da9-48d8-9f02-e7912bef94c7.png)

I will take a look at the other non-COG-UK IDs... those are probably a sign that I need to update some of my local GISAID data as well, because I recently went looking for these cases, but I don't have access to full GISAID downloads -- I have to download GISAID sequences in batches of up to 10,000 sequences, so most of my local 'chunks' of GISAID are rather stale.  If my local GISAID data and lineages.csv are equally stale then it all seems fine on my end.
