### ISSUE TITLE
JN.1.16 + triple nuc mutation Orf7a:F59K got S:Q493E, [19 seqs, 10 countries including Taiwan and China, with further S:S31P(12) and then 346T(1) ] 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#2726]
from https://github.com/sars-cov-2-variants/lineage-proposals/issues/1702

Defining mutations:
Jn.1.16 >> A532G, **Orf1a.G400S** (G1463A). > **Orf7a:F59K** (T27568A, T27569A, T27570A) > **S:Q493E** (C23039G) >> **N:P279S** (C29108T) > **S:S31P** (T21653C) 
Query for Orf7a:F59K: A532G,C23039G,T3565C 
[Old queries: C23039G, C29108T, T27570A by @aviczhl2  or  A532G, G1463A,C4543T initial]
Query for S:S31P: T21653C, T27570A
Query for S:R346T: C29108T, T27570A,G22599C (by @aviczhl2 )
Samples: 18 (17 with S:Q493E) 
Countries: 10
sorted by date of collection: 
Taiwan (GBW), Singapore, Japan, Australia, Netherlands, Taiwan (not GBW), South Korea, US-NY, Canada, Italy, China

Tree (Updated on 08-10):
 <img width="1154" alt="Screenshot 2024-08-10 alle 08 06 26" src="https://github.com/user-attachments/assets/977a85d0-93ac-45ec-b873-33cc4aa8d719">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_5ada8_700150.json?f_userOrOld=uploaded%20sample&label=id:node_7234797

I strongly reccomend to read the @ryhisner analysis of Orf7a:F59K triple nuc mutation: [here](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1702#issuecomment-2211747082)

IDs:
EPI_ISL_19240822, EPI_ISL_19240865, EPI_ISL_19268033,
EPI_ISL_19282315, EPI_ISL_19287866, EPI_ISL_19287875,
EPI_ISL_19287877, EPI_ISL_19293072, EPI_ISL_19298328,
EPI_ISL_19304934, EPI_ISL_19305174, EPI_ISL_19305194,
EPI_ISL_19309288, EPI_ISL_19311730, EPI_ISL_19311825,
EPI_ISL_19324738, EPI_ISL_19324755, EPI_ISL_19324796

**Comment by ryhisner** [comment]
Just copying and pasting my previous comment on ORF7a:F59K below. 

ORF7a:F59K is a really bizarre mutation—it's a triple T->A mutation. T->A is the third-rarest type of nuc mutation, so there's no way this happened stepwise. It's happened numerous times independently throughout the pandemic, so I have no doubt that it's real. There are now 50 sequences total with ORF7a:F59K that I think are legit.
<img width="1092" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e825d057-a3d4-4a55-9423-1f6fa585165f">


There are other double-A or triple-A mutations but they usually fit one of a number of patterns, the main ones being TRS-like motifs and recombination with the region just before the N start codon. This one doesn't fit either pattern. However, with it, 25764-25774 makes for a perfect reverse complement of an 11-nucleotide stretch in NSP6 (11131-11141). I regard stretches of 8-9 nucleotides as likely being coincidental, but 11 nucleotides is unlikely to be a coincidence. 

<img width="1506" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/582217aa-1f5b-44fe-a610-2fe65ee3b21b">

So my guess is that this triple-T->A mutation is due to recombination with this this region of NSP6, though I don't feel overly certain about that. 

It's also worth noting that there's a second stretch of nucleotides, 7593-7602, that forms the ORF7a:F59K region forms a perfect reverse complement with over a 10-nucleotide stretch, which again is more than you'd expect to find by coincidence. 
<img width="1263" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/cf804169-1137-45f2-8880-a62b90501bc5">

**Comment by ryhisner** [comment]
And here's another fascinating aspect of this triple T->A mutation I'd discussed elsewhere but forgot to mention in the previous issue: it zips up three unpaired nucleotides on the stem part of a stem-loop, perfectly matching three unpaired T's on the opposite side. This is far from the only multi-nuc mutation to follow this pattern, some of which involve even more extensive mutations. 

<img width="1283" alt="image" src="https://github.com/user-attachments/assets/69421d74-49e9-4470-a77b-d84d2ebd3ec2">

**Comment by FedeGueli** [comment]
Thanks a lot @ryhisner !

**Comment by FedeGueli** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
> Designated JN.1.16.4 and MT.1 (C23039G, C29108T, T27570A,T21653C)

via  https://github.com/cov-lineages/pango-designation/commit/f7249dc8559ccbd3a4147ee9c4464993a4e1e375

**Comment by DailyCovidCases** [comment]
> Designated JN.1.16.4 via [f7249dc](https://github.com/cov-lineages/pango-designation/commit/f7249dc8559ccbd3a4147ee9c4464993a4e1e375) and MT.1 via [ac17fb3](https://github.com/cov-lineages/pango-designation/commit/ac17fb34b44c75851bc80c526587bae888fdb8f0)

This branch is designated, so you should close this issue

**Comment by FedeGueli** [comment]
@aviczhl2 please close it
