### ISSUE TITLE
Proposal for a potential sublineage of Lambda, with Spike L5F, L452Q, A475V, E484K, P499R, N501T, P681R (6 seqs, Peru)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#298]
Description
**Sub-lineage of**: C.37
**Earliest sequence**: 2021/9/28
**Most recent sequence**: 2021/9/28
**Countries circulating**: Peru (Lambayeque region, in the Northern part of Peru)

**Conserved substitutions**:
![image](https://user-images.githubusercontent.com/86835836/139516681-6e6a5c03-aed8-4363-a545-78acd6f78088.png)

**Genome**s:
EPI_ISL_5765587-5765588, EPI_ISL_5765597-5765598, EPI_ISL_5765604-5765605

**Evidence**:
![image](https://user-images.githubusercontent.com/86835836/139516805-cd58842a-6c16-4f8d-967e-c44f267e3a5e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_388e4_ca2d60.json?branchLabel=Spike%20mutations&c=gt-S_501,681&label=nuc%20mutations:C5893T,G7393A,C7712T,C9430T,C11124T,C16877T,C18395T,A20620G,A21488G,T21789C,C22267T,C22986T,G23012A,C23031T,C23058G,A23064C,C23525T,C23604G,C25207T,C26111A,G26199T,T26767C,T26894C

**Comment by georgimarinov** [comment]
Four sequences were posted from Arequipa with just N501T and with P681H:

EPI_ISL_6208676
EPI_ISL_6208675
EPI_ISL_6208674
EPI_ISL_5935407

**Comment by c19850727** [comment]
Yes. 
It's interesting that small subclades with lots of substitutions now begin popping out across different part of Lambda tree, or is it because folks there begin sequencing more frequently?

**Comment by c19850727** [comment]
@georgimarinov It just popped out again...EPI_ISL_6574278.

**Comment by georgimarinov** [comment]
> @georgimarinov It just popped out again...EPI_ISL_6574278.

As has another crazy version with R346S, G446S and E484V (EPI_ISL_6574198)

Also, there are now 16 sequences with both Q675H and Q677H, which seems to be another branch.

**Comment by chrisruis** [comment]
Thanks @c19850727 It looks like this clade still only has a few sequences in it currently so I'll add a monitor label for now and we can check back

**Comment by c19850727** [comment]
3 new sequences were just uploaded to GISAID, however they are all collected on September 29th (just one day after the initial 6 sequences) from the same region.

![image](https://user-images.githubusercontent.com/86835836/147172536-648f7dcf-d2e2-4460-bf47-ac6a44019f2e.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_18502_3ca0d0.json?branchLabel=aa%20mutations&c=gt-S_681&label=nuc%20mutations:C5893T,G7393A,C7712T,C9430T,C11124T,C16877T,C18395T,A20620G,A21488G,T21789C,C22267T,C22986T,G23012A,C23031T,C23058G,A23064C,C23525T,C23604G,C25207T,C26111A,G26199T,T26767C

**Comment by aineniamh** [comment]
Closing for now as is a stale issue.

**Comment by silcn** [comment]
A new extremely divergent sequence related to this cluster has just turned up: EPI_ISL_13915530. It is also from the Lambayeque region of Peru.

Shared spike mutations on top of Lambda: L5F, 68-71del, 144del, E484K, S490F (reversion), N501T, H655Y
Exclusive to the lineage in this issue: I76T (reversion), A475V, P499R, P681R
Exclusive to EPI_ISL_13915530: W64R, W152L, 210del, R346K, K417T, D420N, L441R, S477N, T478K, F486P, L727F, D950N

Would be interesting to know further details: in particular, which, if any, of the sequences were from chronic patients. The metadata from the new sequence doesn't match any of the September 2021 ones. 
@Wen1953 @OrsonMM @Vjimenez-vasquez @LuisBarcenaF

<img width="725" alt="EPI_ISL_13915530" src="https://user-images.githubusercontent.com/42699509/179852354-faab9643-db2d-412f-9fef-5f704220627b.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2d09d_71d210.json?c=userOrOld&label=nuc%20mutations:C16877T,A21488G,G23012A,C23031T,A23064C,C23525T,C25207T,T26767C](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2d09d_71d210.json?c=userOrOld&label=nuc%20mutations:C16877T,A21488G,G23012A,C23031T,A23064C,C23525T,C25207T,T26767C)

**Comment by FedeGueli** [comment]
Hi @silcn this one should not have S:681R, @ryhisner found it too and we discussed the absence of fcs mutation or maybe is it NNN?

**Comment by silcn** [comment]
@FedeGueli I think you must have misread my post? I list S:P681R as exclusive to the lineage in this issue (i.e. the one from September 2021) and not present in EPI_ISL_13915530. There are no NNNs in the spike, so it genuinely doesn't have an FCS mutation.

The 2nt mutation T23018C+T23019C = S:F486P, which goes via 486S or 486L, is starting to turn up increasingly often; it's also present in Constellation 1 from #844 and in a weird BA.2.10 from India uploaded yesterday (EPI_ISL_13929780) which also has W64R, 141-144del, 242-243del, F371S, G446S, R493Q, S494P, P1143L, and possibly even more because it has lots of NNNs.

S:L727F, which has never been seen before, is also a 2nt mutation (C23741T+A23743T). There's a silent mutation T23740C next to it too.

**Comment by FedeGueli** [comment]
oh sorry i misunderstood! yeah that Indian sequence found too by @ryhisner. agree it is popping up in very last days here and there. Thx

**Comment by AngieHinrichs** [comment]
> a 2nt mutation (C23741T+A23743T). There's a silent mutation T23740C next to it too.

FWIW when I see a single sample with multiple substitutions within a few bases of each other I'm a little suspicious because that's a pretty common error pattern (see "Neighbour linked variants" section of https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473/10).  That's not to say it couldn't be real (like B.1.1's 28881-28883!), but error is my default assumption for that condition.
