### ISSUE TITLE
Polish/(East) German Delta sublineage [10%/1%] with S:29I and potentially double deletion S:138/139-

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#301]
I spotted a surprisingly fast growing lineage in Poland, that's also present in Germany. It's grown remarkably fast from first observation in 2021-36 to 10% of all Polish sequences. Weirdly, it's appearing all over Poland, not concentrated in one region. Which makes me think it could be an artefact?

It has S:29I, which seems to be also slowly on the rise in UK and US within independent lineages (~1%/day), and also in Portugal.

I've spotted some S:138-/S:139- deletions popping up stochastically in Poland. Could this be a real property of the lineage that has issues with Artic primers? Or is the deletion the artefact? The site is interesting, it could be one way to explain the fast growth rate? S:29I seems advantageous but not hugely so.

This double deletion has been seen in Poland before, in fact it's the number one country in terms of frequency where this has been observed at around 5-10% for a while, so maybe artefact?

Here's the lineage on a Poland focal tree:
![image](https://user-images.githubusercontent.com/25161793/139948655-f3fc66a9-87a0-4da5-aad8-306fdbcdfea8.png)
https://nextstrain.org/groups/neherlab/ncov/poland?branchLabel=spike_mutations&c=gt-S_29&r=division

Here are some sequence names
[S29I.csv](https://github.com/cov-lineages/pango-designation/files/7463894/S29I.csv)

![image](https://user-images.githubusercontent.com/25161793/139949045-cb8f9cbc-e676-4909-b0cb-34b3787a2830.png)

I think the fact that it's pango classified as AY.47 is wrong. It's just plain B.1.617.2 at least for the current Usher release until AY.47.

![image](https://user-images.githubusercontent.com/25161793/139949460-d12d5fb2-b206-41a2-86b0-d40a56e3ec31.png)

https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3A29I%2COrf7a%3AT115I&pangoLineage=B.1.617.2*

**Comment by theosanderson** [comment]
The expectation would be that 138-/139- is a real deletion fixed in a dominant or prevalent Polish lineage, which is sometimes reverted to wildtype in sequences because it is part of amplicon 72 in ARTIC V3. The same effect explains the 95, 142 and 950 (different region, in a primer) mutations on the tree. But I have no explanation for an increase in S:T39I which is what defines this clade.

**Comment by zach-hensel** [comment]
Orf7A:A82V in these sequences reverts a Delta mutation that perhaps could reduce fitness.

**Comment by corneliusroemer** [comment]
Very interesting @zach-hensel, that reversion does pop up all over the tree, homoplasically. Which is what one indicate indeed if the mutation was deleterious.

I could identify one weird (unrelated to Poland) cluster with this reversion that is growing in Belgium and Denmark. It was first big in Israel where it's lingered around and popped up again from time to time. Very strange. Will open a designation issue for it.

**Comment by chrisruis** [comment]
Thanks @corneliusroemer We've added this as AY.121 in [v1.2.93](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.93). We've started it one branch upstream of S:29I as this upstream branch likely coincides with the introduction(s) into Poland. AY.121 therefore starts on a branch with T209C (synonymous), C27638T (Orf7a:A82V) and C27737T (Orf7a:T115I)

**Comment by mg14** [comment]
The designated lineage is part of a wider branch, roughly defined by ORF3a:202L, which is present in Eastern Europe and the Near East at frequencies between 10-25%. These comprise about 1% of sequenced cases globally, probably more due to oversampling in Western Europe and the US. 

Would it make sense to define this ancestral branch as `AY.121` and the current lineage with Orf7a:A82V as `AY.121.1` to reflect the larger global structure? 

https://cov-spectrum.ethz.ch/explore/World/AllSamples/from=2021-05-01&to=2021-11-06/variants?aaMutations=Orf3a%3AV202L&pangoLineage=B.1.617.2*

![image](https://user-images.githubusercontent.com/6615711/142436145-43887bd5-b08b-442d-b78a-369302333408.png)

![image](https://user-images.githubusercontent.com/6615711/142437984-45067b04-30fa-49f1-8c6d-cf832cbe0686.png)

**Comment by corneliusroemer** [comment]
Going through a subsampled Europe tree, I independently spotted the large clade defined by `ORF3a:V202L` respectively `nuc: C13168T, G25996T` that @mg14 talks about above.

I support renaming AY.121 into the broader lineage and making the Polish sub lineage AY.121.1.

I'll open this as a separate issue.

**Comment by chrisruis** [comment]
This clade has now been updated to AY.121.1 based on #344
