### ISSUE TITLE
COVID-19 cluster with unusual clinical presentation in France

### ISSUE THREAD

**Issue by Simon-LoriereLab** [cov-lineages/pango-designation#31]
Description
request by the French National Reference Center for viruses of respiratory infections headed by Pr. S. van der Werf

Sub-lineage of: B.1 
Earliest sequence: 2021-01-29
Most recent sequence:  2021-02-15 (more sequencing ongoing)
Countries circulating: France
Genomes
[Table_Lannion.tsv.txt](https://github.com/cov-lineages/pango-designation/files/6134860/Table_Lannion.tsv.txt)

Evidence
A cluster of COVID-19 cases with inconsistent detection by RT-PCR  in nasopharyngeal swabs at the time of onset of symptoms compatible with COVID-19  (including severe/lethal cases) is under investigation in Bretagne France.
More sequences are under way, but most samples are very difficult to sequence (low viral load with the usual sampling methods)
The genomes are characterized by a large number of mutations:

Spike_D215G,Spike_H655Y
Spike D215G D614G G142del G669S H66D H655Y N1187D Q949R V483A Y144V
E F20L T30I
M H125Y
N T325I 
NS3 Q57H
NSP2 T85I
NSP3 N506S S1443Y T820I
NSP4 Y397H
NSP5 A260V
NSP6 L37F
NSP12 P323L Q822R
NSP14 L157F
NSP16 K277R T140I
![Screenshot_2021-03-13-auspice](https://user-images.githubusercontent.com/60473383/111031810-a43d8780-8409-11eb-812b-e48025bf965f.jpg)

[tree_Lannion_20C_B.1.pdf](https://github.com/cov-lineages/pango-designation/files/6134864/tree_Lannion_20C_B.1.pdf)
[tree_Lannion_20C_B.1.nex.txt](https://github.com/cov-lineages/pango-designation/files/6134865/tree_Lannion_20C_B.1.nex.txt)

A Pango designation would greatly help exchanges on this cluster!

**Comment by AngieHinrichs** [comment]
GISAID sequence France/IDF-HMN-21022230289/2021|EPI_ISL_1110211|2021-01-29 also clusters with these:

![image](https://user-images.githubusercontent.com/186983/111053969-68142200-841d-11eb-83b8-85304c334f60.png)

**Comment by AngieHinrichs** [comment]
FWIW the three BRE-IPP* sequences and IDF-HMN-21022230289 also have a 29bp frameshift deletion in ORF6, 27267-27295 (or 27268-27296 depending on which way your aligner rolls).

Also, the deletion of 3 bases in spike appears to me to be not G142del, but rather Y144del or Y145del (depending on which way the aligner rolls): 21991-21993 ... 21994-21996.  B.1.1.7 has the same deletion.

**Comment by rambaut** [comment]
This doesn't currently qualify as a new lineage under the Pango designation criteria. It needs to a have at least 5 cases and at least 1 internal node. If more cases arise then it will be revisited. I am marking this as `monitor` but leaving it open.

**Comment by AngieHinrichs** [comment]
Still no internal node, but HT Anna Niewiadomska (JCVI) for pointing out two more sequences that cluster with these, EPI_ISL_1259297 and EPI_ISL_1259307.  EPI_ISL_1239370 does too.  That brings it up to 7:

```
France/IDF-HMN-21022230289/2021	EPI_ISL_1110211	2021-01-29
France/BRE-IPP03921/2021	EPI_ISL_1111064	2021-02-15
France/BRE-IPP03808/2021	EPI_ISL_1118892	2021-02-10
France/BRE-IPP03809/2021	EPI_ISL_1118893	2021-02-10
France/BRE-IPP04583/2021	EPI_ISL_1239370	2021-03-02
France/BRE-IPP04233/2021	EPI_ISL_1259297	2021
France/BRE-IPP04392/2021	EPI_ISL_1259307	2021-02-26
```

![image](https://user-images.githubusercontent.com/186983/111428448-be4ec280-86b4-11eb-9506-3f98fcd0461a.png)


Interactive view:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-31.json?branchLabel=nuc%20mutations&c=pangolin_lineage&label=nuc%20mutations:A6653G

It looks like my tree has France/BRE-IPP03809/2021|EPI_ISL_1118893 before the node with A22206G, but then UShER is placing the same sequence when uploaded after the node with A22206G -- ah OK, BRE-IPP03809 has 'N' at 22206 so UShER made different decisions in different contexts about whether to infer ref or alt for the missing base.  Test case for Yatish's matOptimize.

However, the relationship of France/BRE-**IPP04615**/2021|EPI_ISL_1262772 to the sequences in that cluster is... interesting.  It has 24 of these 26 mutations in common with the cluster (it appears not to have G25563T/ORF3a:Q57H and C1059T):

C241T > C14408T > A23403G > C3037T > G25563T > C1059T > C5884T > C1973T, C5178T, C7047A, T9743C, A15905G, C18508T, C21077T, A21488G, C21691T, A25121G, T26304G, C26333T, C26895T, C27128T, T27757A, T28297C, C29095T, C29247T, C29580T

-- and A22206G (S:D215G), which due to BRE-IPP03809's N and the timing of adding sequences to UShER, appears to happen later for the cluster but probably happened before the split with BRE-IPP04615.

It also shares the deletion of 21991-21993 (S:Y144del or S:Y145del) with the cluster.

But then the cluster has these 8 mutations that BRE-IPP04615 does **not** have:

A4236G, C10252T, C21758G (S:H66D), G21987T (S:G142V), T23010C (S:V483A), C23525T (S:H655Y), G23567A (S:G669S), A24408G (S:Q949R)

And BRE-IPP04615 has these 15 mutations that do not appear in any sequence in the cluster, but have 1 in common with B.1.1.7 (bolded):

**C5388A ORF1a:A890D**
**C5986T**
C8090T
T12496C
**T16176C**
A17615G
**del 21765-21770 S:69-70del**
**A23063T S:N501Y**
**C23604A S:P681H**
**C23709T S:T716I**
**G24914C S:D1118H**
**C27972T ORF8:Q27stop**
**G28048T**
**A28111G**
G29717A

B.1.1.7 mutations **not** in BRE-IPP04615:
C913T
C3267T
T6954C
del 11288-11296 (ORF1a 3675-3677)
C14676T
C15279T
C23271A (S:A570D)
T24506G (S:S982A)
del 28271
28881-28883 GGG -> AAC (N:203-204)
C28977T (N:S235F)

I don't see a tidy breakdown into a small number of regions of the genome that are clearly like the cluster vs. regions that are clearly like B.1.1.7.  I hope someone who knows much more about sequencing and viruses than I do can look at France/BRE-**IPP04615**/2021|EPI_ISL_1262772.

**Comment by rambaut** [comment]
Our general policy is to treat any signal that is in one genome sequence only with caution as will often be due to sequencing issue (i.e., contamination) or mixtures present in the sample. The fact that there is no simple split between B.1.1.7-like and cluster-like mutations suggest a mixture of amplicons from the two source variants.

**Comment by rambaut** [comment]
I am definitely going to call IPP04615 as a mosaic (the two mutations in ORF8 downstream of the Q27 stop codon are unlikely to have occurred independently - even though Q27 stop has occurred multiple times). Could be a recombinant of course but the switching back and forth makes it more likely a mixture with a consensus that is mosaic - the raw data needs inspection.

**Comment by Simon-LoriereLab** [comment]
Thanks to both for looking into this (it has hijacked a bit the unusual cluster thread, we are indeed generating more sequences and will post an update when/if the threshold is reached). The raw data appears partially mixed but we are checking this in more details, and will surely re-sequence, looks like a potential co-infection.

**Comment by rambaut** [comment]
Hi Etienne - thanks for looking into this. One other thing about the cluster - is it associated with a specific outbreak (I heard it was a hospital outbreak) or is it spreading more generally? The long unsampled branch connecting to genomes from the first half of 2020 is suggestive of an introduction from an area with limited genomic surveillance - is there any evidence of that?

**Comment by Simon-LoriereLab** [comment]
Hi Andrew, for now it is indeed a specific outbreak in a hospital(+care facility for the elderly) with cases in patients and HCW. The sequence outside of the region has a direct epi link. The difficulty to confirm these cases by RT-qPCR on nasal swabs possibly mean that it will be a challenge to capture it outside of the severe/hospitalized cases, but a lot of epi work is ongoing.
We currently have no evidence of introduction from another area. More analysis is on the way, but it might not be possible to get a proper answer on this.

**Comment by Simon-LoriereLab** [comment]
Dear colleagues, here is an update on the cluster, with more sequences on the way.

![2021-03-23_update_cluster_low_detec](https://user-images.githubusercontent.com/60473383/112319597-86481080-8cae-11eb-9f89-1365440bc718.jpg)

[2021-03-23_update_cluster_low_detec.nex.txt](https://github.com/cov-lineages/pango-designation/files/6197528/2021-03-23_update_cluster_low_detec.nex.txt)

**Comment by erikalmecdc** [comment]
Dear all,

This is a very high profile variant that could explode into a new VOC if it turns out to spread further. It would be very nice to get a lineage designation to be used instead of the now circulating designation "Brittany variant".

**Comment by chrisruis** [comment]
Hi All, we've now assigned this lineage as B.1.616. It should appear in the next update. Thanks!

**Comment by Simon-LoriereLab** [comment]
Dear Chris, dear colleagues, thank you for your help with this. It will be very useful.

**Comment by AngieHinrichs** [comment]
Looks like there are 4 additional sequences in this cluster, from as recently as 15 March:

```
hCoV-19/France/BRE-HCL021036256901/2021	EPI_ISL_1318289	2021-02-10
hCoV-19/France/BRE_8600536377/2021	EPI_ISL_1292807	2021-02
hCoV-19/France/BRE-IPP05435/2021	EPI_ISL_1381829	2021-03-10
hCoV-19/France/BRE-IPP05485/2021	EPI_ISL_1381830	2021-03-15
```
