### ISSUE TITLE
Potential new linegage A.2.4.X in Panama and Costa Rica with Spike L452R substitutions and 141-143 deletion.

### ISSUE THREAD

**Issue by AAMCgenomics** [cov-lineages/pango-designation#33]
Potential VOI circulating in Central America.

Sub-lineage of A.2.4
Earlies Sequence 2020-11-21
Most Recent Sequence 2021-02-04
Countries circulating: Costa Rica and Panama.
Genomes:

[listofaccession.txt](https://github.com/cov-lineages/pango-designation/files/6159919/listofaccession.txt)

Tree evidence:
<img width="798" alt="treeimage" src="https://user-images.githubusercontent.com/22726018/111543242-c5231700-8740-11eb-9abd-fddbe1e07f27.png">

Genome changes:
gene	nucleotide	aminoacid
Nsp4	C10029T	T492I
Nsp6	C11005A	H11Q
Sgene	A23403G      D614G
                T22917G	L452R
		deletion:  L141-,S:G142-,S:V143-
		insertion: 22205:CGGCAGGCT
ORF3a	C25613T	S74F
N	C28863T	S197L
	C28975T	M234I
	C29366T	P365S
	C29241T	P383L

**Comment by SVN-PhD** [comment]
There is another important mutation that is missed.

**Spike**: A23403G -> D614G

This is notable as the parent lineage is PANGO A / GISAID S / NextClade 19B. The D614G mutation is one of the main markers for the PANGO B lineages. This may have resulted from convergent evolution?

The spike L452R is notable as the same mutation is found in the newly designated Variants of Concern B.1.427 and B.1.429: [https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/variant-surveillance/variant-info.html#Concern](url)

A short dive in GISAID reveal this lineage has a global distribution, detected in the United States, Canada, Germany, Portugal, Luxembourg, Italy, United Arab Emirates, England, and Australia.

**Comment by AAMCgenomics** [comment]
Indeed, In Panama we saw that the lineage locally transmitted, acquired with the evolution of the pandemic in the country, the D614G mutation. Showing the convergent nature of this change in SARS-CoV-2.
Thank you for noting that I missed to include D614G in the list.

**Comment by SVN-PhD** [comment]
The **spike** Δ141-143 is shared with https://cov-lineages.org/lineages/lineage_P.3.html

**Comment by chrisruis** [comment]
Hi, thanks for this. Would you be able to upload a tree containing these sequences and their surrounding sequences to help us orientate ourselves? Thanks!

**Comment by AngieHinrichs** [comment]
In case it helps -- I uploaded the 31 sequences named in listofaccession.txt to the [UShER web interface](http://genome.ucsc.edu/cgi-bin/hgPhyloPlace) (after setting the subtree size to 500 instead of the default 50), clicked to view subtree 1 in Nextstrain, and got this view which can be saved as Newick or Nexus ("Download data" near bottom of the page):

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-33.json?branchLabel=nuc%20mutations&c=pangolin_lineage&label=nuc%20mutations:A5234G,C11005A,A22525G,C29421T

(that view is zoomed in to the proposed lineage; you can zoom out by clicking on the branch at the far left, or by clicking "reset layout" in the upper right corner)

The latest version of pangolin (pangolin 2.3.6, pangoLEARN 2021-03-16) assigns the sequences to A.2.5 not A.2.4.

**Comment by chrisruis** [comment]
Hi, thanks very much for submitting this. It looks like the blue clade within your tree is lineage A.2.5 which has been detected in multiple countries. The Panama sequences are spread throughout lineage A.2.5 and so we've left these sequences as A.2.5. It seems that a subclade of A.2.5 has been introduced into Costa Rica and has undergone continued transmission here, therefore meeting the requirements for a Pango lineage. We've named this lineage A.2.5.1 - this contains most of your Costa Rica sequences and some others from Costa Rica. This should appear in the next release. Thanks again
