### ISSUE TITLE
New sub-clade of AY.102 (delta) lineage circulating in Peru with E:L51I mutation

### ISSUE THREAD

**Issue by Vjimenez-vasquez** [cov-lineages/pango-designation#330]
**New sub-clade of AY.102 (delta) lineage circulating in Peru with E:L51I mutation**

**Description**
New sub-clade of AY.102 (delta) lineage circulating in Peru with S:D142G, E:L51I and orf1a: L3606F mutations

**Earliest sequence:** hCoV-19/Peru/AYA-INS-4171/2021 EPI_ISL_4080238 (2021/07/12, Peru)
**Most recent sequence:** hCoV-19/Peru/JUN-INS-8803/2021 EPI_ISL_6208699 (2021/10/18, Peru)
125 sequences from Peru 
Countries circulating : Peru (125)

**Genomes:** 
[genomes.txt](https://github.com/cov-lineages/pango-designation/files/7573328/genomes.txt)

**Evidence:** 
RaXML Phylogeny (205 genomes carrying Envelope L51I base mutation)

![IMAGEN_1](https://user-images.githubusercontent.com/89874227/142701532-64ccff97-2d17-4ab0-a5a3-70225e04752e.png)

**Comment by corneliusroemer** [comment]
The reversion at S:142 is most likely a nanopore sequencing artefact.

ORF1a:3606F I've seen in other lineages before, is it an artefact or
homoplasic site?

PS: I prefer issue titles not in caps locks ;)

**Comment by AngieHinrichs** [comment]
ORF1a:3606F is nucleotide 11083 which was identified early on (May 2020) as highly homoplasic: [Issues with SARS-CoV-2 sequencing data](https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473)

More info about S:D142G in Delta sequences using ARTIC V3 primers: [Variation at Spike position 142 in SARS-CoV-2 Delta genomes is a technical artifact caused by dropout of a sequencing amplicon](https://www.medrxiv.org/content/10.1101/2021.10.14.21264847v2)

**Comment by corneliusroemer** [comment]
Angie, do you know if nuc 11083 is homoplasic due to fitness benefit or
sequencing artefact or something else?

**Comment by AngieHinrichs** [comment]
I don't know -- I've been masking it & forgetting it all this time.  11083G follows a run of Us and has another U immediately after it: https://genome.ucsc.edu/s/AngieHinrichs/SARS-CoV-2_11083 -- dunno whether that makes sequencing error more likely.  I think if it were truly advantageous, it would spread instead of frequently appearing and disappearing.

**Comment by zach-hensel** [comment]
Nsp6 L37 is located nearby 104-108 in structure predictions so perhaps there's a similar mechanism, whatever it is, but with a lower fitness benefit. L37del is the top-ranked, in-frame Nsp6 deletion on CoV-GLUE after 104 through 108, but sequences are scattered through unrelated UShER subtrees disproportionately in the Netherlands so that seems to be an artifact.

**Comment by Vjimenez-vasquez** [comment]
@corneliusroemer Actually, I´ve noted that predominant mutation of this clade is E: L51I, is currently present and growing in Peru

**Comment by FedeGueli** [comment]
![VariantTimeDistributionChart (16)](https://user-images.githubusercontent.com/87669813/144928698-ab54d969-34a9-40ce-b20e-977c1e0dd026.png)
[CovSpectrum](https://cov-spectrum.org/explore/Peru/AllSamples/from=2021-10-15&to=2021-12-06/variants?aaMutations=E%3A51I) 
@corneliusroemer

**Comment by chrisruis** [comment]
Thanks @Vjimenez-vasquez We've added this as AY.102.2 in [v1.2.113](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.113) to start on the branch with C26395A (E:L51I)
