### ISSUE TITLE
B.1.617.2 (21J) sub lineage with a high mutational jump (saltation evolved). 

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#334]
Sub-lineage of: B.1.617.2 Clade 21J (223 sequences)
Earliest sequence: 08.2021
Most recent sequence: 10.2021
Countries circulating: Israel (210),USA (6),France (4),Germany (2),UK (1)

The importance of this lineage is not only from its distribution (which at the moment seems limited) but mainly from the fact that it shows the possibility of a “variant based variant”/"2nd generation variant", that will evolve from Delta.

Non synonymous mutations (11) : 
NSP2:P602L, NSP4:V129F, NSP4:H313Y, NSP5:S254F, NSP13:E319D, NSP14:I242V, NSP16:T35I,ORF3a:G18V,ORF3a:D142H,M:A2T,N:S183T

[added by Cornelius]:
```
ORF1b: P782L, V2892F, H3076Y, S3517F
ORF1b: E1242D, I1766V, T2332I
ORF3a: G18V, D142H
M: A2T
ORF7a: A82V
N: S183T
```

Synonymous mutations (3):
T6661C,C13665T, C14571T.

GISAID ref list :
[Delta 2nd gen .csv](https://github.com/cov-lineages/pango-designation/files/7579009/Delta.2nd.gen.csv)

USHER build:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3c4c4_b475b0.json?label=nuc%20mutations:G4181T,C7124T,C8986T,G9053T,C10029T,A11201G,A11332G,C19220T,C27874T,G28916T

![image](https://user-images.githubusercontent.com/80166370/142821752-1a85778c-e98c-4b5d-8408-22f1639cc3e5.png)

**Comment by corneliusroemer** [comment]
Could it be that the perceived jump is just due to the way this particular Usher tree subsamples?

On a Neherlab Israel tree it looks much less like a jump.
https://nextstrain.org/groups/neherlab/ncov/israel?c=gt-nuc_6661,13665&d=tree,entropy,frequencies&m=div&p=full

![image](https://user-images.githubusercontent.com/25161793/142862779-45d12c83-2722-4189-80c5-d4905217cdaa.png)

**Comment by shay671** [comment]
Thank you @corneliusroemer 

indeed, when using a focused sample from Israel the USHER build show there is no jump 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_242e9_bb54f0.json?c=gt-nuc_28820&label=nuc%20mutations:C10815T

as there is no Jump and no apparent epidemiological significance, I'm closing this issue

**Comment by AngieHinrichs** [comment]
@shay671 both of your UShER views are from clicking the 'view downsampled global tree in Nextstrain' button -- and the downsampling is from >5M sequences to only 2000 (and random, not focused on your sequences), so it's common for a cluster to appear on a very long branch in that view.  The purpose of that view is to show where your sequences fit in among the major Nextstrain clade-level / VoC / VoI branches (20C, Alpha, Delta, etc.)

I think when evaluating a cluster as a possible new lineage, it's usually better to pick a large subtree size (the max is 5000) and click on one of the 'view subtree _N_ in Nextstrain' buttons (or if there are so many subtrees that individual buttons are not shown, click through to subtrees from the pop-ups for uploaded samples in the downsampled global tree).  You will get more local context for your cluster, including more of the nodes upstream of your cluster.  (However, if the candidate lineage branch already has >~4500 sequences, then this doesn't work as well because there's no room for upstream context. Then it's time to step up to Taxonium.)  

For example, in your first link:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3c4c4_b475b0.json?label=nuc%20mutations:G4181T,C7124T,C8986T,G9053T,C10029T,A11201G,A11332G,C19220T,C27874T,G28916T
-- if you click on an uploaded sample like Israel/SMC-7016491/2021, the pop-up has a link [view subtree 1](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3c4c4_b475a0.json).  The subtree shows the stepwise path more similar to Cornelius's build.

In your second link, you have uploaded a lot more samples (990 instead of 219), so now enough context is available in the downsampled global tree to show the details.
