### ISSUE TITLE
Chilean AY.43 sublineage with ORF1b:T2163I [50%, 600 seq]

### ISSUE THREAD

**Issue by Vaduz4892** [cov-lineages/pango-designation#337]
By Hugo Gehant & Matthew Gustafson

Description

Sublineage of AY.43
Countries Circulating: Chile

We observed significant case increases in Chile for AY.43, and after further data analysis a significant portion of said uptick comes with the ORf1b:T2163I mutation, hosting a 44% advantage. Now is taking a significant portion of Chilean case growth, and appears to have exported and mutated in Europe. A follow-up issue will discuss that mutation as a possibility.

![image](https://user-images.githubusercontent.com/94639746/142955611-01b962c1-6603-416a-ac2b-22dce33ab6a3.png)

Attached:

https://cov-spectrum.ethz.ch/explore/Chile/AllSamples/AllTimes/variants?aaMutations=ORf1b%3AT2163I&pangoLineage=AY.43

UShER: https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&subtreeSize=1000&remoteFile=https%3A%2F%2Fcov-spectrum.ethz.ch%2Fgisaid%2Fapi%2Fv1%2Fsample%2Fgisaid-epi-isl%3Fhost%3DHuman%26orderBy%3Drandom%26limit%3D1000%26country%3DChile%26dateFrom%3D2020-01-06%26aaMutations%3DORf1b%253AT2163I%26pangoLineage%3DAY.43

Downsampled tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_39044_c39a20.json

Again, if data required is missing, please let us know so we can add it.

**Comment by corneliusroemer** [comment]
There are 600 sequences of this lineage in Chile so far, another hundred around the world.

Growth in Chile looks interesting. Worth designating.

![image](https://user-images.githubusercontent.com/25161793/142957788-41c39f79-f801-4218-8fba-c56fdbc3d295.png)


[more robust covSpectrum](https://cov-spectrum.ethz.ch/explore/Chile/AllSamples/AllTimes/variants?aaMutations=ORf1b%3AT2163I%2CN%3AQ9L&pangoLineage=B.1.617.2*)

**Comment by corneliusroemer** [comment]
It's interesting that this lineage is spread all over Chile.

https://nextstrain.org/groups/neherlab/ncov/sa-chile?branchLabel=Spike%20mutations%20%28internal%29&c=gt-nuc_19955&f_pango_usher=AY.43&m=div&r=division

Yellow is ORF1b:2163I
![image](https://user-images.githubusercontent.com/25161793/142958614-82b8a67e-de6e-4420-a450-e29744a4b180.png)

**Comment by MCB6** [comment]
Why does the UCSC's "Recurrent Bi-allelic Mutations in Nextstrain Subset of GISAID" panel show this NSP4 mutation at a nearly 50% allele frequency? It's virtually absent in when the Nextstrain subset is viewed on Nextrstrain itself (even though it existed in a small percentage of the genomes before Delta)
https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1219910555_rwsw2jPHUuRErTQ8QYOo6wikxAiS&db=wuhCor1&c=NC_045512v2&l=10006&r=10036&o=10028&t=10029&g=nextstrainSamplesRb&i=C10029T
![image](https://user-images.githubusercontent.com/93294184/143089813-35a2c6a6-05bb-4dda-9cc1-fa0f63c24fc6.png)

**Comment by AngieHinrichs** [comment]
@MCB6 Questions about the UCSC Genome Browser are best sent to either our public, [archived](https://groups.google.com/a/soe.ucsc.edu/forum/#!forum/genome) list genome@soe.ucsc.edu or (if it's not OK to archive) our private list genome-www@soe.ucsc.edu.

But since we're both here... in general, UCSC's Nextstrain track lags nextstrain.org by one to several days.  There is a regular update process on our development server (which sometimes fails), and then a sync to the main site (genome.ucsc.edu) which happens once a day.  The track currently on genome.ucsc.edu was last updated Nov. 19th.

When I look at Nextstrain's GISAID global build and color by nucleotide 10029, C>T looks pretty common to me, mostly thanks to 21J (Delta):

https://nextstrain.org/ncov/gisaid/global?c=gt-nuc_10029

When I filter by "genotype nuc 10029C" I see "Showing 1634 of 3544 ..." above the tree, and "genotype nuc 10029T" results in "Showing 1910 of 3544 ...".  1634 / 3544 = 0.461 for C, 1910 / 3544 = 0.539 for T, so actually that's pretty close to UCSC's slightly outdated numbers.

With >5M accumulated SARS-CoV-2 genomes in GISAID, and tens of thousands of new genomes added most days, Nextstrain must downsample to get to <5000 genomes for interactive display.  I believe their downsampling emphasizes recent sequences (with enough older sequences to build a reasonable tree), and that would mean Delta.  You might want to contact Nextstrain about how their downsampling should affect allele frequencies and/or how much they would expect those to vary from one build to the next.

**Comment by chrisruis** [comment]
Thanks @Vaduz4892 We've added this as lineage AY.43.3 in [v1.2.101](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.101) to start on the branch with C19955T (Orf1ab:T6564I)

**Comment by phwanka** [comment]
@MCB6 
I think you mixed up some information.

As you can see in your screenshot you are talking about ORF1a:T3255I, which is very common in Delta Lineages and not the same as ORF1b:T2163I.
In your comment in #343 you incorrectly claim that ORF1b:T2163I is NSP4:T492I and therefore present in B.1.1.529.
However, mutation NSP4:T492I is ORF1a:T3255I and therefore quite common.

Hope I brought some clarity, sadly cannot mention this in #343 as it is locked.

**Comment by MCB6** [comment]
> ORF1b:T2163I

yes, NSP15:T112I. Apologies for the confusion. It's at 50 sequences in the US and covSpectrum gives it 51% estimated growth advantage with the CI of 36% .. 67%.
