### ISSUE TITLE
Potential Sublineage of AY.39.1 with Reverse Mutation G13482A (~600 Seqs, ~4% in Australia)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#341]
This is an effort to fine-tune AY.39.1, the currently predominant lineage in Australia (~90% prevalence).

According to NeherLab:
![image](https://user-images.githubusercontent.com/86835836/142975975-0b78291e-71c1-414a-be0c-e1041c397e94.png)

There are 4 subclades that are visibly distinct:

- The one on the top with ORF1a:V438I and ORF3a:A59V, already submitted on #307  by @bitbyte2015.
- The second one with ORF1a:E633D and S:P1162A, prevalent in ACT and later NSW;
- The third with nuc T26187C, prevalent in VIC and later NSW;
- The last one with nuc T28921C, nuc G13482A, nuc G29179T and ORF1b:I527V, from NSW.

Here I would like to submit the subclade with nuc T28921C, nuc G13482A, nuc G29179T and ORF1b:I527V.
Noticeably, nuc G13482A is the reverse mutation from the lineage-defining mutation of AY.39.1, therefore those sequences are currently classified as AY.39 by Pango and Usher.

Description
Sub-lineage of: AY.39.1
Earliest sequence: 2021/8/10 (Australia-NSW)
Most recent sequence: 2021/11/12 (Australia-NSW)
Countries circulating: Australia (NSW)

Prevalence in each state as per Cov-spectrum is as follows:
![image](https://user-images.githubusercontent.com/86835836/142976468-8f373aba-7e52-40be-be2e-7670f3344e1b.png)

Transmission advantage as per Cov-spectrum:
![image](https://user-images.githubusercontent.com/86835836/142976492-959875fb-a747-4d4b-bad5-3abb6b627421.png)

Usher tree (in green color):
![image](https://user-images.githubusercontent.com/86835836/142976873-26b622b6-4a65-4214-aab1-1055255b70f4.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_107a6_c80d50.json?branchLabel=Spike%20mutations&c=gt-nuc_13482&l=radial

**Comment by corneliusroemer** [comment]
Are you _sure_ that the `reversion` isn't just a tree building error or sequencing artefact? So far, all reversions I've seen, and there are hundreds of them, have been tree building/sequencing artefacts.

**Comment by AngieHinrichs** [comment]
I agree... this is how the path to the cluster ends in the UCSC/UShER tree:
```
... > G27604A > G21372T > A13482G > T28921C > G13482A
```
The back-mutation on 13482 is almost immediate, separated by only one mutation -- probably an error.  The numbers of descendants of those nodes in the 2021-11-19 tree are
```
A13482G: 23613
T28921C:  5705
G13482A:   639
```
So there are >5000 sequences that have all the mutations up to G21372T, A13482G, and T28921C (or Ns)... but there are also 639 sequences that have the mutations up to G21372T and T28921C (but not G13482A).  From a maximum parsimony point of view, I believe `G27604A > G21372T > A13482G > T28921C > G13482A`  scores the same as `G27604A > G21372T > {T28921C , A13482G > T28921C}` (5 mutations either way) -- but since some important inferences are made based on the presence of mutations in these paths, we need to find a way to make back-mutations less common than they are currently.  Tagging @russcd and @yatisht - could this be helped by modifying the tie-breakers?

**Comment by yatisht** [comment]
This is a straightforward tie-breaking strategy to incorporate. I'll add it in later this week. Thanks for the analysis.

**Comment by chrisruis** [comment]
We haven't designated this at this stage due to the discussion above. Thanks @c19850727 for submitting
