### ISSUE TITLE
AY.75.1 has still been assigned

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pango-designation#349]
Hi,

I made an update tonight (pango --update) and reprocessed all our samples. I got several error messages, as AY.75.1 has still been assigned in my data set, even it it was removed. 

Best,
Anke

**Comment by AngieHinrichs** [comment]
Hi Anke,

There is a lag from updates of pango-designation to updates of pangoLEARN because it takes time to train and test the pangoLEARN model.  AY.75.1 was removed in pango-designation release [v1.2.98](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.98), but the latest release of pangoLEARN was [2021-11-18](https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-11-18) which was trained on pango-designation release v1.2.97.  There should be a new release of pangoLEARN some time in the next few days corresponding to pango-designation v1.2.101.  After that release (and another pangolin --update), AY.75.1 should no longer be assigned.

Angie
