### ISSUE TITLE
Alias of C.6 and C.10

### ISSUE THREAD

**Issue by aretchless** [cov-lineages/pango-designation#36]
Dear cov-lineages team,

I am trying to use the 'full_alias_key.txt' file to track the relationship between lineage names. I noticed that two "C" aliases are not listed in that table -- C.6 and C10. Likewise, in the 'lineage_notes' file they are not identified as aliases. 

Am I correct in understanding that "C" is an alias for "B.1.1.1", and therefore C.6 and C.10 are aliases?

Also, is this file (full_alias_key.txt) meant to be a comprehensive dictionary of aliases, that would be suitable as input for software that groups lineages based on ancestry?

Thank you for maintaining this incredibly useful resource.

Sincerely,
Adam

p.s. L4 is also missing from full_alias_key.txt (edit)

**Comment by aineniamh** [comment]
Hi @aretchless, thanks for pointing that out- I've added in C.6, C.10 and L.4 to that list now. 

I recently added that file as we'd had a couple of requests for an alias list. I haven't decided yet whether it stays in that format or only lists the alias mappings in future (i.e. just C -> B.1.1.1, rather than the full set of C.1, C.2 etc). We will continue to host something like this though, with the ancestry information. 

If it's helpful, I keep a [hash](https://github.com/cov-lineages/grinch/blob/7652c7b232a124cb22676e5104d45c3135460789/grinch/scripts/update_website.py#L152) of the aliases in this format too:
```
alias = {'C': 'B.1.1.1',
            'D': 'B.1.1.25',
            'G': 'B.1.258.2',
            'K': 'B.1.1.277',
            'L': 'B.1.1.10',
            'M': 'B.1.1.294',
            'N': 'B.1.1.33',
            'P': 'B.1.1.28',
            'R': 'B.1.1.316',
            'S': 'B.1.1.217',
            'U': 'B.1.177.60',
            'V': 'B.1.177.54',
            'W': 'B.1.177.53',
            'Y': 'B.1.177.52',
            'Z': 'B.1.177.50',
            'AA': 'B.1.177.15',
            'AB': 'B.1.160.16',
            'AC': 'B.1.1.405',
            'AD': 'B.1.1.315',
            'AE': 'B.1.1.306',
            'AF': 'B.1.1.305',
            'AG': 'B.1.1.297',
            'AH': 'B.1.1.241',
            'AJ': 'B.1.1.240',
            'AK': 'B.1.1.232',
            'AL': 'B.1.1.231',
            'AM': 'B.1.1.216',
            'AN': 'B.1.1.200',
            'AP': 'B.1.1.70',
            'AQ': 'B.1.1.39',
            'AS': 'B.1.1.317'}
```
