### ISSUE TITLE
Omicron sublineage with potentially beneficial mutation S:346K

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#360]
Too early for a lineage designation but worth watching:

About 10% of Omicrons (47) have the mutation S:346K which has already been seen in Mu and B.1.640.

Using the available sequences from GISAID it seems possible that Omicrons with S:346K grow faster than Omicrons without.

![image](https://user-images.githubusercontent.com/25161793/144732139-a4372f60-90f5-4bb3-82c8-c68fa4223e51.png)

https://nextstrain.org/groups/neherlab/ncov/21K-diversity

S:346 is also inferred to have a transmission advantage by @fritzo's pyro-cov: https://github.com/broadinstitute/pyro-cov/blob/master/paper/mutations.tsv#L281

**Comment by zach-hensel** [comment]
I think this lesson from Delta is that it's never too early to recognize diversity that exists early on and also the sub-sub-lineage with T716I (shared with Alpha, B.1.575, and apparently emerging within the last two weeks) and the other sub-lineage with A701V (shared with Beta, majority of B.1.526, and emerging in several AY.x) if those are legit per the sequencing and case data.

**Comment by fritzo** [comment]
@zach-hensel agreed. We recently started using a finer clustering than PANGO lineages in our growth rate estimation [tool](https://github.com/broadinstitute/pyro-cov), and found some PANGO lineages contain significant heterogeneity, with growth rate estimates of sub-lineages varying by nearly a factor of two ([source](https://github.com/broadinstitute/pyro-cov/blob/master/paper/lineage_heterogeneity.png)). We have not yet run on Omicron data.
![lineage_heterogeneity](https://user-images.githubusercontent.com/648532/144757667-5dab07da-b725-4e31-9d79-3c1ea62856ea.png)

**Comment by georgimarinov** [comment]
B.1.640 has R346S (and so do a few other minor ones such as C.36.3), not R346K, but that also seems to be beneficial. I have always been puzzled by the R->K change, it isn't that much of a differences, while in the same time you have R->S in other lineages, which is a big difference, and yet both give it a boost. You see a lot of recurrent R346S in various Delta sublineages, and in other variants too.

**Comment by FedeGueli** [comment]
Update from Sergej Pond on S:346K (whole thread)

https://twitter.com/sergeilkp/status/1468702272272183300?s=20

**Comment by FedeGueli** [comment]
I noticed that Sigal lab neutralization assay is with 346K mutation. Put here maybe someone interested in.

**Comment by FedeGueli** [comment]
This clade is growing quite everywhere 
Usa
![Screenshot_2021-12-28-13-09-31-782_com android chrome](https://user-images.githubusercontent.com/87669813/147599632-1dc39820-56d7-4c74-993a-d1761b8e0c54.jpg)

Switzerland (pic) 
![VariantTimeDistributionChart (18)](https://user-images.githubusercontent.com/87669813/147599357-2c02a529-7143-4540-9cc0-bbceeeec4b13.png)

Denmark (pic)
![VariantTimeDistributionChart (19)](https://user-images.githubusercontent.com/87669813/147599558-ffa5035a-933f-4a94-9618-7a7d57835de5.png)

I think it is worth a designation @chrisruis

**Comment by silcn** [comment]
@FedeGueli every clade of Omicron is growing like this everywhere. It's not clear yet whether this is growing relative to the rest of Omicron.

**Comment by corneliusroemer** [comment]
Indeed @silcn, it'd be nice if covSpectrum supported comparative plots, so we could fraction of this relative to BA.1

AFAIK @chaoran-chen is working on this

**Comment by shay671** [comment]
![image](https://user-images.githubusercontent.com/80166370/147777575-391a425d-d9d0-4ea3-84d9-0b278eeb6488.png)

**Comment by chrisruis** [comment]
Looking at the latest data on covSpectrum, this clade has increased as a proportion of BA.1 in some countries but not all countries. So it's not particularly conclusive but I think warrants a designation. We've therefore added this as BA.1.1 in [v1.2.122](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.122) to start on the branch with G22599A (S:R346K)

**Comment by MCB6** [comment]
Just a warning about occasional inability of the labs to call S:346K. In the US, there is an apparent regional anomaly with the absence of BA.1.1 in the more recent samples from Massachusetts / New England. But it's only because the bulk of the regional sequencing (and nearly all faster-turnaround sequencing) is done by Broad Inst. Its pipeline won't call R346K. 
The rest of the samples from the states where Broad draws samples from have ~2/3 BA.1.1. as expected.
Because Broad is responsible for 20-30% of the recent samples in the US, it distorts the nation-wide stats as well, but the effect is much stronger locally. Check for example New Hampshire, where December genomes came from a variety of labs, but January genomes from Broad:
![image](https://user-images.githubusercontent.com/93294184/151023527-d6924694-a791-4b46-a42e-958b13866e7b.png)

**Comment by bwlang** [comment]
I think that region of the S is going to be a problem for all common amplicon sets except VarSkip Long and VarSkip V2.

I'm trying to get to an update to primer-monitor.neb.com/lineages today to confirm with current variants - 
meanwhile (orange indicates a variant overlap with the primer, vertical lines indicate S346). Too many fires these days!
![image](https://user-images.githubusercontent.com/61636/151025993-b395a173-6a5a-4c79-8c8a-90a298dfc853.png)

Anecdotally, I see a mutation in that codon in 9/15 samples sequenced last week at NEB (low volume sequencing representing southern New Hampshire and Massachusetts)
e.g.
![image](https://user-images.githubusercontent.com/61636/151028949-4bef34df-dce4-426a-bcd7-926bcc887078.png)

**Comment by arodzh-sudo** [comment]
@bwlang are the Varskip Short v2 commercially available?

**Comment by dpark01** [comment]
@MCB6 thanks for flagging the issue and it's certainly something I want to pay attention to at the Broad.

I'll just note, the data I'm seeing, even from New Hampshire specifically, doesn't seem to line up with what you're seeing. Here is a plot of all Omicrons that the Broad has sequenced from New Hampshire broken down by PANGO lineage (I chose NH because you showed a plot of NH). I had to go back and re-run the latest pango on all the old genomes, but the following plot is 100% called with `pangolin: 3.1.19; pangolearn: 2022-01-20; constellations: v0.1.2; scorpio: 0.3.16; pango-designation used by pangoLEARN/Usher: v1.2.123` (pUSHER was used for calls) -- the Broad only genomes show an increase in BA.1.1 in NH (and similar patterns throughout New England) right at the turn of the new year.

![newplot (1)](https://user-images.githubusercontent.com/8513746/151639650-1f1a47cb-481e-409f-a110-5dde0bd9bb11.png)

If NEB varskip short 1a (used by the Broad) is vulnerable to amplicon dropouts on S:346, then either:
1. there was an unusual reduction in amplicon dropout rates around the new year for some non-epidemiological reason
2. or BA.1.1 has other SNPs in LD with S:346 that pUSHER is able to leverage to call BA.1.1 anyway, even in the absence of S:346

I haven't looked systematically at our genomes to see if the calls are correlated with coverage on Spike (which would be a bit of a wet lab mystery) or if these are being called despite the lack of coverage there (which would be phylogenetically interesting).

**Comment by MCB6** [comment]
@dpark01 So you think that the problem is specific to GISAID's lineage calls in BI's submissions? They don't have any NH BA.1.1's for this recent date range:
![image](https://user-images.githubusercontent.com/93294184/151644395-d68d9e8a-3e2e-459e-985c-54b440efb811.png)
and the only call with S:346K during this time frame is from MA, hCoV-19/USA/MA-CDCBI-CRSP_UUG4JE6ZCEKCDMZL/2022

LD variants is an interesting issue. covSpectrum has 65 LD (>0.05) calls for ~100,000 US BA.1.1's, but, alas, they are all common with BA.1,

**Comment by MattBashton** [comment]
I can't see any issues with calling S:R346K even on Artic V4 which this is an example of, it's not overlapping with any one primer specifically, see track below reads. The region with the dropout in would be the adjacent amplicon 76 (a dropout which is now fixed in V4.1), this region is covered by amplicon 75 and 75_LEFT and 75_RIGHT don't appear to be having any issues with depth here: 
![Screenshot 2022-02-03 at 20 00 35](https://user-images.githubusercontent.com/3043019/152419894-a056a943-69aa-49f6-8026-6d8c8284c42d.png)
