### ISSUE TITLE
3196 sequences from Germany assigned to AY.102 but missing the defining mutation A27690T 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#427]
I found that all the AY.102 sequences from Germany are not really AY.102, but they belongs to several different B.1.617.2 
 undesignated subclades.

They all miss the defining mutation A27690T
[CovSpectrum](https://cov-spectrum.org/explore/Germany/AllSamples/AllTimes/variants?nucMutations=A27690T&pangoLineage=AY.102*)

Usher didnt assign none of them to AY.102 and they are sparse in the tree:
[Usher tree ](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_40297_cc81a0.json)

List of sequences:
[contributors.csv](https://github.com/cov-lineages/pango-designation/files/8000652/contributors.csv)

cc @chrisruis @corneliusroemer

**Comment by FedeGueli** [comment]
Not of utmost importance but @AngieHinrichs have you checked why these seqs have been missassigned to AY.102?

**Comment by AngieHinrichs** [comment]
Hi @FedeGueli, it is still important 🙂, but to make sure I understand your question: Are you calling them "AY.102 sequences" because that is currently their assigned lineage on the GISAID website?  (e.g. "AY.102 (Pango v.3.1.20 2022-02-28), Delta (B.1.617.2-like) (Scorpio)")  They are not designated AY.102 in lineages.csv (which is good because as you point out they do not have A27690T).  It is possible that designating the ones that are B.1.617.2 in the UShER tree as B.1.617.2 would help the next release of pangoLEARN to discern better what is really AY.102.

I believe they are currently assigned to AY.102 by pangoLEARN because pangoLEARN was built for speed more than for accuracy -- every time there is a new data release with new sequences, GISAID has to reassign lineages to millions of sequences, now >9M!  I think pangoLEARN has trouble especially when a lineage is differentiated from its parent and/or sibling lineages by only one or two mutations.  AY.102 has many many siblings from which it is differentiated only by G1495T, A27690T and the sibling's defining mutations.  An [evaluation](https://virological.org/t/sars-cov-2-lineage-assignment-is-more-stable-with-usher/781) with Delta wave sequences from CA and NY found that pangolin's `--usher` mode is more stable from one data release to the next than the default pangoLEARN mode.

In the next major release of pangolin (4.0, still in development), UShER will be the default mode, while pangoLEARN will still be available with `--analysis-mode fast` or `--analysis-mode pangolearn`.  UShER is significantly slower than pangoLEARN, but a cache file with precomputed results for sequences in public repositories will be available to speed up pangolin runs on large numbers of pre-existing sequences.  Stay tuned... but it will take some time before pangolin v4.0 is tested and released, and then some more time for the new assignments to appear on GISAID's website.

**Comment by AngieHinrichs** [comment]
@chrisruis I'm attaching a file of @FedeGueli's IDs that place in B.1.617.2 in the current UCSC/UShER tree -- might help to fold those into lineages.csv.
[pango-designation-427.B.1.617.2.csv.gz](https://github.com/cov-lineages/pango-designation/files/8235303/pango-designation-427.B.1.617.2.csv.gz)

**Comment by FedeGueli** [comment]
Thank you very much @AngieHinrichs i wasnt aware about this difference and i was thinking the gisaid assignment was the same of lineage.csv.
Happy to hear it will be improved more and more.
Thank you very much for your explanation and your time for answering me 
So I'll close this issue

**Comment by FedeGueli** [comment]
@AngieHinrichs i opened a couple of issues #465 and #465 regarding putative misassignment, i do not know if there is the same explanation for them. In the case i will close them.
