### ISSUE TITLE
BA.2 + ORF1b:S959P sublineage with S:G798D in India, Singapore, Australia, US etc [3.3k seq]

### ISSUE THREAD

**Issue by Rezwanuzzaman** [cov-lineages/pango-designation#428]
Possible of BA.2 sublineage with S:G798D
by [Rezwanuzzaman Laskar](https://github.com/Rezwanuzzaman) and [Animesh K Singh](https://github.com/animesh-workplace)

**Description**
Sub-lineage of: BA.2
**Earliest sequence**: 23/12/2021
**Most recent sequence**: 18/01/2022
**Countries circulating**: India, also found in Singapore, Bangladesh and Germany

**Defining mutations**
Amino acids: Spike: G798D
Nuc: G23955A 

**Evidence:**

- Large cluster found in phylogentic tree marked with arrow

![BA 2_G798D_Phylotree](https://user-images.githubusercontent.com/92582414/152643959-3e90bf23-4d48-4a46-b87d-e5e14f1a18bd.png)

- List of mutations from CovSpectrum

![BA 2_G798D_Mutations](https://user-images.githubusercontent.com/92582414/152643820-45e344b1-650b-4d3f-9e3c-1817f2327b04.png)

- CovSpectrum Statistics

![BA 2_G798D_growth](https://user-images.githubusercontent.com/92582414/152643826-f4db4fa7-fa3b-4993-8490-a32f50092c9a.png)

**Proposed lineage name: BA.2.1**

**Comment by silcn** [comment]
This lineage is currently dominant in Western Australia, making up around 75% of sequences. This is the first major wave in Western Australia and as a result G798D is showing a large but highly misleading transmission advantage in Australia. Looking at other countries, there doesn't appear to be any actual advantage over the rest of BA.2, but this might still be worth designating due to its geographical concentration.

As far as I can tell there aren't any extra identifying mutations for the Australian cluster.

**Comment by c19850727** [comment]
There is a potential recombinant cluster with **S:G798D** from US-MD (which by the way may have dual breakpoints). 

Accessions: EPI_ISL_10078664, 10275588, 10275592, 10492415, 10492405, 10560408, 10624985, 10602162, 10892744.

![image](https://user-images.githubusercontent.com/86835836/161205179-c029f0d6-394f-463e-8f5b-4fdc018efb3e.png)

**Comment by FedeGueli** [comment]
This should have been designated today BA.2.10.1

**Comment by chrisruis** [comment]
This is indeed now designated BA.2.10.1
