### ISSUE TITLE
Large sublineage of BA.2 with Orf3a:H78Y (10000+ Sequences) circulating in Europe and globally

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#432]
As noted first by @shay671 long ago and recently by @bitbyte2015 in #390 and re [highlighted](https://twitter.com/JosetteSchoenma/status/1491808064588156933?s=20&t=IZbs8XsupbLLEjBu8n7HPQ) today by Josette Shoenmakers and by Staten Serum Institute in their report: 
"Ugentlige tendenser:
covid-19 og andre
luftvejsinfektioner
Uge 6 | 2022"  at [Pag.21](https://www.ssi.dk/-/media/cdn/files/covid19/tendensrapport/rapport/ugentlige-tendenser-covid19-andre-luftvejs-uge6-2022-8d2k.pdf?la=da)

There is a clear large subclade of BA.2 defined by Orf3a:H78Y circulating in Europe.
It represents around 4% of all sequences of the last three weeks in Europe and 3,5% globally.
![Schermata 2022-02-10 alle 17 24 26](https://user-images.githubusercontent.com/87669813/153451278-2b2e2ec6-4e31-46a6-a7f4-0af9f760d3c4.png)

Number of sequences: 10598
List of Sequences: [contributors (4).csv](https://github.com/cov-lineages/pango-designation/files/8042625/contributors.4.csv)
First sequence: 49/2021 Denmark
Country circulating:
Denmark ( 9000+ seqs)
Sweden (500+ seqs)
It has been sequenced in 4 continents: Europe, Asia, Oceania, North America,Central&South America

In comparison to BA.2* baseline [Its relative growth advantage is estimated in 6%(CI:5%-7%](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.2*&aaMutations1=Orf3a%3AH78Y&pangoLineage1=BA.2*&analysisMode=CompareToBaseline)
![Schermata 2022-02-10 alle 17 31 24](https://user-images.githubusercontent.com/87669813/153452519-9f7fcd6c-506f-4e08-beb3-216a9f50f461.png)
It means a +65% relative growth advantage against BA.1
![Schermata 2022-02-10 alle 17 34 47](https://user-images.githubusercontent.com/87669813/153453118-5fe71436-5ddd-44c9-9703-a1f8b2006091.png)

It is self evident in the [Neherlab tree fro denmark](https://nextstrain.org/groups/neherlab/ncov/denmark?c=gt-ORF3a_78&d=tree&f_country=Denmark&label=clade:21M%20%28Omicron%29&p=full&r=division)
![Schermata 2022-02-10 alle 17 40 32](https://user-images.githubusercontent.com/87669813/153454276-320f7883-5331-4faa-b77d-0c9ffca4fb35.png)

**Comment by RajLABN** [comment]
orf3a:H78Y is found in several BA.1 and BA.1.1 sequences as well. 

omicron w/ orf3H78Y mutation in 
Denmark -9559 sequences [BA.2 (99.93%); BA.1 (0.05%); BA.1.1 (0.02%)]
UK - 385 sequences [ BA.2 (62.08%); BA.1 (24.42%); BA.1.1 (13.51%)]
USA - 141 sequences [BA.1 (60.28%); BA.1.1 (31.91%); BA.2 (7.80%)]

**Comment by corneliusroemer** [comment]
This is a sub-lineage of the lineage proposed in #390 

So that issue should be resolved first, then this one here, since otherwise we're getting into trouble with renaming.

I think I am still in favour of #390 defining a lineage of its own, because it is very clearly associated with the growth of BA.2 in Denmark and spread from there to neighbouring countries (Sweden, Germany, ...). About 60% of all global BA.2 sequences have `nuc:C22792T`, however, this is largely because Denmark (and Germany and Sweden) sequence so much and BA.2 is very common there.

This lineage is very uncommon outside of Central/Northern Europe. The ORF3a:78Y mutation appeared within that lineage, but makes up only 25% of the lineage proposed here.

Furthermore, the ORF3a mutation _does not_ seem to provide any further growth advantage. Neither in Denmark, nor globally.

So overall, I think it's better to designate this lineage here, not the ORF3a:78Y one.

![image](https://user-images.githubusercontent.com/25161793/153709972-13103167-6b59-446d-a617-7667bda3239b.png)

https://cov-spectrum.org/explore/Denmark/AllSamples/Past6M/variants?nucMutations=C22792T&pangoLineage=BA.2&aaMutations1=ORF3a%3A78Y&nucMutations1=C22792T&pangoLineage1=BA.2&analysisMode=CompareToBaseline

![image](https://user-images.githubusercontent.com/25161793/153709973-68cd0948-1d56-4a12-9aa2-97798aecf3e9.png)

**Comment by FedeGueli** [comment]
Ok @corneliusroemer thank you!  i close this one waiting for when #390 would be resolved. Sorry i hurried up a bit it after seeing growing % in the SSI. Ready to re-open if requested or something new will pop up.

**Comment by beansrowning** [comment]
FYI, from SSI (https://files.ssi.dk/covid19/tendensrapport/rapport/ugentlige-tendenser-covid19-andre-luftvejs-uge7-2022-5l9s)

![image](https://user-images.githubusercontent.com/25888380/154569799-4a1830d2-b063-4872-bee5-2bacda6ba3a1.png)

**Comment by corneliusroemer** [comment]
Since #390 won't be designated, it makes sense to designate this one here

Is it clean on the Usher tree @AngieHinrichs @chrisruis?

**Comment by chrisruis** [comment]
Thanks @FedeGueli We've added this as BA.2.9 in [v1.2.140](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.140)
