### ISSUE TITLE
Potential BA.1/BA.2 Recombinant Lineage with Likely Breakpoint at NSP5/NSP6 (267 Sequences in the UK and Ireland)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#454]
### Description
**Recombinant between**: BA.1* & BA.2
**Earliest sequence**: 2022/1/16 (UK-England)
**Most recent sequence**: 2022/2/21 (UK-England)
**Countries circulating**: UK (England and Scotland), Ireland
**Likely breakpoint**: between 10448 and11287 (NSP5 or NSP6).
**Conserved Nuc mutations and AA change**s (those in red frames are likely from the donor from the BA.1 side):
![image](https://user-images.githubusercontent.com/86835836/156090173-45b85603-d963-4b5c-8eae-9e89dda704a4.png)

**Private mutations**: C14599T

### Evidence
**Nextclade downsampled tree** (unrooted):
![image](https://user-images.githubusercontent.com/86835836/156089191-029c8e8e-f23e-409a-836d-60e2fb148a54.png)

**Nextclade downsampled tree** (starting from 21M):
![image](https://user-images.githubusercontent.com/86835836/156089213-976452e9-57c3-4fd7-b59c-718a1414d5f2.png)

**Usher tree** (interestingly Usher puts #448 in the sibling branch):
![image](https://user-images.githubusercontent.com/86835836/156089309-fd1b620a-32eb-4473-a5f5-a0ef11da27c4.png)
https://nextstrain.org/fetch/genome-euro.ucsc.edu/trash/ct/subtreeAuspice1_genome_euro_b767_d79a40.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:G8393A,C25624T

**International comparison, geographical distribution and relative growth advantage as per Cov-spectrum**:
![image](https://user-images.githubusercontent.com/86835836/156089516-e8409944-72a8-4320-84b4-eac47016fa3d.png)

**Relative growth advantage over BA.2 in the UK from Jan. 1st, 2022 as per Cov-spectrum**:
![image](https://user-images.githubusercontent.com/86835836/156090436-a06421d9-e740-4ab2-aeed-9034a1230b78.png)
(Cov-spectrum somehow only shows 118 sequences out of a total of 145)

### Genomes:
[Genomes 20220309.txt](https://github.com/cov-lineages/pango-designation/files/8210993/Genomes.20220309.txt)

**Comment by c19850727** [comment]
208 sequences now and just popped out in UK-Wales.

**Comment by c19850727** [comment]
267 sequences as of 2022-03-08. Also found in Wales.

**Comment by corneliusroemer** [comment]
How do you monitor the number of sequences @c19850727? Could you share the covspectrum query? That'd be great.

**Comment by c19850727** [comment]
@corneliusroemer Sure I used to use **C3241T, T5386G, C12880T, C14599T, C15714T, A20055G, A29510C**,
until I realized some of them have A20055G reversed.
So now it's **C3241T, T5386G, C12880T, C14599T, C15714T, A29510C**.

Basically C14599T is the key.

**Comment by theosanderson** [comment]
@AngieHinrichs I think these get excluded from the Usher tree atm? (I guess because they look like artefacts) Would one have to manually place a few for them to start appearing? We have looked into a bit at our side as data-generators, and they do seem legit

**Comment by AngieHinrichs** [comment]
@theosanderson Yes, it looks like they are being excluded from the tree because of some new quality filters that I added at the beginning of Feb. 2022 to deal with Omicron sequence quality / amplicon dropout / assembly issues.  I have a file of IDs that I'm gleaning from pango-designation issues and exempting from those checks, but a) it's manually maintained and I have fallen a bit behind this week and b) I need to translate EPI_ISL_ IDs into GenBank IDs where possible and sometimes there's a lag before the GenBank ID becomes available so there's another way for my file to fall behind.

It looks like the 2022-03-09 tree has 1 GISAID and 18 GenBank IDs but there should be a lot more.
```
Ireland/D-Enfer-COV070222012_F3/2022|EPI_ISL_10035165|2022-02-07
England/MILK-35BF3FA/2022|OV954492.1|2022-02-06
England/MILK-3364C73/2022|OV783131.1|2022-01-19
England/MILK-3337981/2022|OV774910.1|2022-01-19
England/MILK-344ADBB/2022|OV822541.1|2022-01-26
England/LSPA-350DFAE/2022|OV894188.1|2022-01-30
England/MILK-34981A3/2022|OV869399.1|2022-01-29
England/MILK-33F8579/2022|OV835795.1|2022-01-24
England/MILK-3403158/2022|OV814889.1|2022-01-24
England/MILK-35940B8/2022|OV946413.1|2022-02-05
England/MILK-35C21CD/2022|OV954832.1|2022-02-06
England/MILK-35C2D9C/2022|OV954666.1|2022-02-06
England/MILK-3521302/2022|OV895377.1|2022-02-02
England/MILK-3572144/2022|OV934572.1|2022-02-03
England/MILK-3433E85/2022|OV840742.1|2022-01-25
England/MILK-33F209C/2022|OV815899.1|2022-01-24
England/MILK-345FD0E/2022|OV818161.1|2022-01-26
England/LSPA-350BF28/2022|OV894331.1|2022-01-29
England/LSPA-350A40C/2022|OV896176.1|2022-01-30
```

Those names/IDs can be pasted into the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace), but yeah, if you want to see a tree with sequences other than those today you'll need to upload fasta or run [usher](https://github.com/yatisht/usher/tree/master/workflows) locally.

I am working on updating the exemption-file today.  The sequences should be in the 2022-03-11 or 2022-03-12 build (which should become available in another 2 or 3 days).  (There are still other things that cause sequences to be omitted from the tree, I'll keep an eye out for those too.)  Thanks @c19850727 for updating the file [Genomes 20220309.txt](https://github.com/cov-lineages/pango-designation/files/8210993/Genomes.20220309.txt) in the description!

**Comment by theosanderson** [comment]
Thanks for the info and amazing work as ever @AngieHinrichs, I now have a much better sense of how that works!

**Comment by corneliusroemer** [comment]
In the last 13 days, the growth advantage with respect to BA.2* in the UK seems to have reduced. The growth advantage could possibly be due to something akin to a "funnel plot" bias, anything we observe will show growth advantage at first, otherwise it wouldn't be observed.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/25161793/158080418-ece39f43-4ba9-40af-9ff1-0ae531021d1f.png">

Will be interesting to keep an eye on, here's the query.
https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past6M/variants?pangoLineage=BA.2*&nucMutations1=C3241T%2CT5386G%2CC12880T%2CC14599T%2CA29510C&analysisMode=CompareToBaseline

**Comment by c19850727** [comment]
Yes @corneliusroemer , and if we filter it to UK from Jan. 13th, the growth advantage would be 10% only.

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as lineage XE in [v1.2.133](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.133)

**Comment by FedeGueli** [comment]
> Yes @corneliusroemer , and if we filter it to UK from Jan. 13th, the growth advantage would be 10% only.

Great take Saka! Ukhsa today estimated it in 9,8%
