### ISSUE TITLE
Best place to pull a canonical listing of all lineage names so far?

### ISSUE THREAD

**Issue by vincent-czi** [cov-lineages/pango-designation#456]
Hi,

I apologize if this is already explained some where and I just missed it, but **what is the best way to obtain a canonical listing of all the Pango lineages designated so far?** Is there a single, specific file that should be considered the "official" listing of lineages, or -- if it would be better / more official -- a way to import that list if I have `pangolin` installed? I should mention that I'm not worried about getting a listing of the "Withdrawn" lineages, just the current, non-withdrawn lineages is what I'm looking for (it's to provide filtering options to do Nextstrain tree builds).

------------------

I _think_ the answer to this question is to use the top-level `lineage_notes.txt` in this repo (discarding all the withdrawn `*` lineages at the bottom of the file):
https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt

But I think it's also possible that it's best to use the top-level `lineages.csv` in this repo (pulling all the unique lineages over the entirety of the CSV):
https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv

Or, finally, it's possible that the best source is the Lineage List page at https://cov-lineages.org/lineage_list.html.

-----------------

It appears that all three options above produce slightly different results though? [Below numbers are all from a few hours before the time of this posting on Fri, March 4, 2022.]

Between `lineage_notes.txt` and `lineages.csv`, the txt has 1637 non-withdrawn lineages, while the csv has 1639 unique lineages within it. They're very, very nearly the same set, but not quite. They share 1635 lineages. The txt has two lineages that are not contained in the csv (`B.1.1.529` and `B.1.640`), while the csv has four lineages that are not contained in the txt (`B.1.88.1`, `B.1.1.229`, `B.1.1.228`, `B.1.1.230`). [If you want to see the code I used for checking, happy to share it.]

I haven't gotten around to carefully checking the Lineage List webpage yet, but it also looks like it's not quite a perfect match to either. If I pull the HTML for that page, I see 1908 `<tr>` elements: each corresponding to a row in the table, with the very first row being the header row, so 1907 lineages on the page, including non-withdrawn and withdrawn lineages. The txt file -- if you include withdrawn lineages as well -- has  1909 lineages. I expect it's once again very nearly the same set, but with the slight difference between them, I'm not quite sure which one to consider the canonical listing.

-----------------

Any recommendations you can give for the best way to track all the current Pango lineages would be great, thanks!

Also, just wanted to thank you for all the work you do throughout the various CoV-lineages projects. I, and all my team mates on our project, deeply appreciate the effort you've put into all of this. Thank you for your hard work!

**Comment by FedeGueli** [comment]
bvxsz

**Comment by babarlelephant** [comment]
https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt is the official list yes
and https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv is the official list of designated sequences (from which pango learn how to recognize the lineage and can assign automatically new sequences to it)

So if you just need the big list then do a http request at https://raw.githubusercontent.com/cov-lineages/pango-designation/master/lineage_notes.txt

**Comment by vincent-czi** [comment]
Thanks very much! I'll make sure to pull `lineage_notes.txt` as the official listing then!

Just curious, do you know what causes the slight difference between the set of non-withdrawn lineages in the `.txt` file compared to the set of unique lineages present in the `.csv` file? I don't think it's actually going to cause any issues whatsoever for how I'll be using the list, but was interested in what's the difference if you knew off hand.

**Comment by corneliusroemer** [comment]
Do you have an example for a difference @vincent-czi between the two?

Since the `.csv` is what's used in training classifiers, and the `.txt` is basically just documentation and thus prone to lagging behind, any difference is probably just the `.txt` not being up to date. If you give an example I can confirm this hypothesis.

**Comment by corneliusroemer** [comment]
Thanks! B.1.1.529 and B.1.640 once had sequences but they were reassigned to sublineages when sublineages were designated. I'm not sure whether they qualify as withdrawn, depends a bit on the definition. @chrisruis will know best.

The lineages in the csv but not in the txt were probably forgotten to be added to the txt.

**Comment by babarlelephant** [comment]
My bad B.1.1.228 and B.1.1.229 disappeared there from the .txt probably due to a mistake https://github.com/cov-lineages/pango-designation/commit/46d59f4041f398a42e7b189cf9b255f24bcb368c

B.1.1.229 does exist, well-supported and so on, and should be included in the .txt https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_60e0_7939e0.json?c=pango_lineage

**Comment by AngieHinrichs** [comment]
I agree with @corneliusroemer -- lineages.csv is what is used in practice to train models to assign lineages, so it is the closest to ground truth, and the other files are probably incomplete or mistaken if they disagree with lineages.csv.

Thank you @vincent-czi for reporting the differences!

**Comment by AmyMikhail** [comment]
Not sure if this is the best place to flag this, but on a slightly related note - does anyone know why the `metadata.tsv` file in GISAID is still using an old Pangolin version dated 2 February 2022 (therefore doesn't have all the new Omicron sublineages)?

**Comment by AngieHinrichs** [comment]
@AmyMikhail there are several sources of delay from the time a new lineage is designated in pango-designation/lineages.csv until it is available from GISAID.
* First, the pangoLEARN model has to be retrained with the new lineages.  That happens when the pangolin/pangoLEARN team members have time for it, and I believe the training can take on the order of a week.
* There is also a testing & refinement period that can take on the order of a week -- or more, if there are any issues with the model training.
* Then there is an official [release](https://github.com/cov-lineages/pangoLEARN/releases) in the pangoLEARN repository.
* Then GISAID needs to update its installation of pangolin/pangoLEARN to get the newly released model, and re-run pangolin on all 9 million (and counting) sequences.

The [most recent pangoLEARN release](https://github.com/cov-lineages/pangoLEARN/releases/tag/2022-02-28) came out just yesterday and includes lineages defined in [pango-designation release](https://github.com/cov-lineages/pango-designation/releases/) v1.2.127 with new `AY.*` lineages;  it does not include the newest `BA.1.*`, `BA.1.1.*` and `BA.2.*` sub-lineages from v.1.128 and later.  So even after GISAID reruns pangolin with yesterday's pangoLEARN release, it still will not have the newest sublineages.

In the meantime, if you upload sequence name/IDs or a limited number of sequences in a FASTA file to the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace), it can place them on a phylogenetic tree that has been annotated with the newest sublineages, and provide assignments based on placement in the tree.  It also generates subtrees suitable for viewing in Nextstrain, to show the relationships with the most similar sequences.

**Comment by zach-hensel** [comment]
I was curious what some new BA.1.* were the other day and wrote these colab scripts to grab a few from lineages.csv and also list all BA -- maybe useful for someone finding this thread later -- https://colab.research.google.com/drive/1gcsgA91kD8TzS448JRbPIA0tOgKCgtY4?usp=sharing

**Comment by AmyMikhail** [comment]
@AngieHinrichs thanks for this explanation, that's very helpful.  I hadn't realised the extent of the model / learning process in this.

**Comment by vincent-czi** [comment]
Hi again!

In the [pangolin v4.0 release notes](https://github.com/cov-lineages/pangolin/releases/tag/v4.0), I saw this:
> Changes to dependencies: We’re rationalising the pangoLEARN repository and the file accessed from pango-designation into a single repository called pangolin-data, so pangoLEARN and pango-designation are no longer needed as dependencies.

I just wanted to check and see if that's likely to affect the `lineage_notes.txt` file in this repo being the source of truth for lineages, or if that part of the release notes is an implementation detail for how the pangolin tool comes together? I _think_ it doesn't change anything about `lineage_notes.txt` being the canonical listing in the foreseeable future, but please let me know if I'm wrong. Thanks!

**Comment by AngieHinrichs** [comment]
I would still argue for lineages.csv being the "source of truth", because it is used to train the pangoLEARN model and to determine lineage root nodes for the UShER tree.

lineage_notes.txt should be maintained to be consistent with lineages.csv, but we're humans so it's good to check for inconsistencies.  :)  

Regardless of that, pango-designation works the same way as before.  The change in pangolin v4 is in which repository is used to distribute the pangoLEARN model, UShER tree and alias file, and in the version string: now the pango-designation release used for training is the pangolin-data version (instead of the date on which pangoLEARN training started as in v3).

**Comment by vincent-czi** [comment]
Thanks for the clarification!

For anyone else that comes upon this issue, here's the **answer in summary:**
- The true canonical listing of lineages is pulling all the unique lineages out of the `lineages.csv` (because that's the ground truth used for everything else).
- The `lineage_notes.txt` is generally a very good alternative to the CSV. It _should_ be equivalent (if you drop all the "withdrawn", `*`-prefixed lineages), but it's derived from the CSV, so it's possible for it to have a few small errors.
- If you want some sample code for pulling the unique lineages from the CSV or comparing the two files, I posted a [Python snippet above](https://gist.github.com/vincent-czi/f081a5ca792cf0cbedc8e1c5834db47c).
