### ISSUE TITLE
Potential Delta/BA.1.1 Recombinant with Likely Breakpoint at NSP4 or NSP5 (37 Seqs in US as of 2022-03-27)

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#471]
### Description
**Recombinant between**: AY.x & BA.1.1
**Earliest sequence**: 2022/1/19 (US-CO)
**Most recent sequence**: 2022/2/26 (US-DC)
**Countries circulating**: US (CO, ND, DC, OH)
**Likely breakpoint**: between 9055 and 10447 (NSP4 or NSP5).
**Conserved Nuc mutations and AA changes** (those in red frames are likely from the donor from the Delta side):
![image](https://user-images.githubusercontent.com/86835836/158001366-9c51bb45-39f0-4410-8873-3121ea1e3034.png)
**Cov-spectrum query**: C5365T, C6196T, T13195C, C15240T, C21595T, C27807T

### Evidence
**Usher tree**:
![image](https://user-images.githubusercontent.com/86835836/158001061-cab7b2c0-4c2a-4423-8593-793341801096.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_30eb8_c0ae10.json?c=gt-nuc_5365&label=nuc%20mutations:G210T,A10449C

**Genomes**:
EPI_ISL_9425763, 9425850, 9425848, 9943603, 10256956, 10300280, 10300482, 10490160, 10605720, 10707609, 10841949 10842071, 10867031, 10871488

**Comment by SVN-PhD** [comment]
Great catch Saka.

Here is the NextClade analysis of these samples.
![Screenshot from 2022-03-14 13-27-44](https://user-images.githubusercontent.com/15314705/158227492-e2e8eb92-0d24-4a29-8e50-c63718698eb1.png)

There is a fantastic tool by Lena Schimmel for analyzing potential recombinants, check out her tool here: https://github.com/lenaschimmel/sarscov2recombinants

Data looks consistent:
![Screenshot from 2022-03-14 13-06-54](https://user-images.githubusercontent.com/15314705/158227815-7d0f600b-edce-488f-b6f0-3ef13badc9bc.png)

**Comment by SVN-PhD** [comment]
Raw reads for one of the sample is available here: https://www.ncbi.nlm.nih.gov/biosample/SAMN26348167/

Potential breakpoint region is too long for amplicons to cover (nt 9053 - nt 10029). However, the reads do look clean and show no evidence for different competing amplicons in those regions.
![Screenshot from 2022-03-14 14-46-50](https://user-images.githubusercontent.com/15314705/158240760-44cac370-e4b0-4954-98d3-e7e75fad941e.png)

**Comment by AngieHinrichs** [comment]
@lenaschimmel That looks awesome!  Some of those have 5 breakpoints -- does that mean that the sequence switches back and forth between 21I and 21J 5 times, or do blocks of Ns also count as breakpoints?

**Comment by lenaschimmel** [comment]
@AngieHinrichs The way that [sarscov2recombinants](https://github.com/lenaschimmel/sarscov2recombinants) currently counts "breakpoints" and "intermissions" is a bit arbitrary, because that tool is still very new.

I'll try to explain it shortly in the context of this specific proposed lineage: somewhere around C10039T there's the "proper" breakpoint, with only BA.1 (green or white) after it. To the left of it, a lot switching back and forth can be seen. Most of these switches are only indicated by one or two mutations which are specific to either BA.1 / 21K or AY / 21J. This is only considered a weak evidence of an actual breakpoint / template switching, and generally adds to the count of "intermissions" (a term with which I came up, probably isn't accepted terminology) instead of the count of "breakpoints" - except if the number of intermissions goes above a certain limit.

All the `N` should not affect the counts of breakpoints or intermissions.

For a deeper discussion of how it currently works, or how it should work instead to be more useful, we should probably switch to an [issue](https://github.com/lenaschimmel/sarscov2recombinants/issues) or a [discussion](https://github.com/lenaschimmel/sarscov2recombinants/discussions) in its own repository.

Btw., I've seen this switching back and forth with other (potential) recombinants as well, and I do not yet understand if this indicates real switching during the recombination event, or if it is just an indication that one of the two parental lineages was actually quite different from the one that was chosen to generate the graphic.

**Comment by c19850727** [comment]
Before I fully switch to @lenaschimmel 's amazing new tool, let me explain how I used to look for those recombinants in a primitive way.

It's all made possible by a recent update of Nextclade (enormous thanks to @corneliusroemer and Ivan Aksamentov!): https://twitter.com/nextstrain/status/1485730636564414469?s=20&t=9L2w_iWQnhq2IDQFCD36Xg

Let me borrow @SVN-PhD 's screenshot here:
![image](https://user-images.githubusercontent.com/86835836/158279952-6fe85a55-ad2a-4cf5-97a7-ef1b26047601.png)
So basically all recombinants have a very poor QC score in terms of "private mutation" relative to the tree, as they should be, but otherwise good score in other QC status in Nextclade, just like this:
![image](https://user-images.githubusercontent.com/86835836/158280235-30c5198d-1e34-46e8-89d5-345275ad9f3b.png)

What I do is just periodically download some recent fastas (preferably from those regions with relatively high co-circulation and good surveillance), filter them by QC scores, and manually go through those that have poor private mutation score but no other issues. 

Then if the 'reversions' and 'labeled private mutations' match, they might be potential recombinants (thanks again Nextclade folks!):
![image](https://user-images.githubusercontent.com/86835836/158284009-449461af-8506-4161-8c09-e9bf0d32c17b.png)

**Comment by AngieHinrichs** [comment]
Thanks @lenaschimmel!  Point taken about using [sarscov2recombinants](https://github.com/lenaschimmel/sarscov2recombinants) issues / discussions for more in-depth discussions.  But continuing the current one:

> Btw., I've seen this switching back and forth with other (potential) recombinants as well, and I do not yet understand if this indicates real switching during the recombination event, or if it is just an indication that one of the two parental lineages was actually quite different from the one that was chosen to generate the graphic.

There should not be a lot of switching -- usually one, occasionally two breakpoints is what we expect.  I see that all of the green characters in the mixed-red-and-green part to the left of the clear breakpoint in @SVN-PhD's screenshot are dots and I assume that means they match the reference instead of the red 21J-associated alt.  I think that's because [virus_properties.json](https://github.com/nextstrain/nextclade_data/blob/master/data/datasets/sars-cov-2/references/MN908947/versions/2022-03-14T12:00:00Z/files/virus_properties.json) includes a lot of positions that are in enough 21J sequences to be associated with 21J -- but they may not be in the majority of 21J sequences, so counting them as "Omicron"/not-21J is not quite right in this case.  For example, the first green-dot position, 1048, is a defining mutation for AY.122 but not the many other AY.* from 21J.  The next, 3948, is in AY.25.1 and some AY.25.  6040 is in AY.44 and AY.130.  And so on for the others.  I would expect many, if not most, 21J sequences to have the reference allele at those positions.

I don't know of a ready-made alternative to virus_properties.json within the Nextstrain umbrella -- [clades.tsv](https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv) has far too few mutations for this.  But then there's a lot I don't know about Nextstrain!  😄  As a possible alternative, I've been maintaining a list of substitutions that are found in each Nextstrain clade (and not masked in the UCSC/UShER build process) [here](https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/nextstrain.clade-mutations.tsv).  For example:
```
21J (Delta)	> C14408T > C241T > C3037T > A23403G > G29742T > T22917G > G210T,C21618G,T27638C,G28881T > C23604G,G29402T > C25469T > C22995A,G24410N > C27752T > A28461G > C16466T > T26767C > G15451A > C10029T > C19220T > G28916T > G4181T > C27874T > C7124T > G9053T > C8986T > A11332G > A11201G
```
Sorry about the file format, it allows me to be lazy and copy-paste the output of matUtils (and reuse input from another method to annotate clades and lineages on the UCSC/UShER tree using paths instead of sets of mutations).  If you specify a preferable format I'll send a sed/awk to convert.  :)  But I think using those mutations for each clade would reduce the number of green dots and intermissions.  @corneliusroemer does that sound reasonable?

**Comment by corneliusroemer** [comment]
@AngieHinrichs @lenaschimmel Yes you're right, that `virus_properties.json` contains mutations that are only found in some lineages in the clade.

For this purpose here, it would make sense to split the list of mutations in two: a) defining mutations that should be present in all, say `21J` (unless they actually reverted, which is rare) and b) mutations found often but not always in a clade

We included b) because it would make recombination and contamination detection more sensitive.

Unfortunately I don't have a list of defining mutations at hand right now. If I'm updating `virus_properties.json` I'll see whether I can create such a file quickly and share it.

**Comment by FedeGueli** [comment]
@corneliusroemer look at this one:
https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/utils/otto/sarscov2phylo/pango.clade-mutations.tsv
here there are  mutations driving to each of the AY.s lineages

**Comment by FedeGueli** [comment]
About this putative recombinant i found  one AY.103 sequence sampled in Colorado back in december carrying 210T, 6169T, 8986T :
USA/CO-CDPHE-2102387294/2021|OM015007.1|2021-12-07
(On usher it has been shown twice also with EPI_ISL_8064377)

If this belongs to the donor cluster it could explain the spread in 4 directions (maybe Colorado skying resorts served as mixing point of local strains with imported from other states and then it would have been a good hub to spread it in different states at the end of xmas holidays).

Just a suggestion.

**Comment by c19850727** [comment]
37 sequences as of 2022-03-27, according to cov-spectrum.

**Comment by FedeGueli** [comment]
@c19850727 I noticed that the last sequences come mainly from Washington State. 
[Covspectrum](https://cov-spectrum.org/explore/United%20States/AllSamples/from=2022-03-01&to=2022-03-27/variants?nucMutations=C5365T%2CC6196T%2CT13195C%2CC15240T%2CC21595T%2CC27807T)

**Comment by SVN-PhD** [comment]
We acquired 2 of the DC samples (2203180013, 2203180014) from LabCorp at the DC Public Health Laboratory (EPI_ISL_10842071, EPI_ISL_10841949). LabCorp had sequenced these with a PacBio instrument. Our lab uses Illumina sequencing but it has been a little slow in adopting Artic V4.1 so our assembly isn't as clean/good as the LabCorp ones. Regardless, the assembly looks to be in line with as real recombinants and the reads are clean as well with no evidence of co-infections. Ignore the XF designation from NextClade, but great catch from @c19850727 for identifying these recombinants.

![Screenshot from 2022-03-29 07-56-02](https://user-images.githubusercontent.com/15314705/160614388-8384f076-8585-4b44-ad47-f9aa54a50a54.png)

**Comment by chrisruis** [comment]
Thanks @c19850727 We've added this as XS in [v1.2.141](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.141)
