### ISSUE TITLE
BA.* sublineages with S:L452R and S:F486V (79 sequences as of 2022-04-05, mainly South Africa)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#517]
Proposal for a sublineage of BA.2
Earliest sequence: 2022-01-10 (South Africa)
Latest sequence: 2022-03-24 (Denmark)

Countries detected: South Africa (30 including 21 in Gauteng), Botswana (3), Denmark (3), United Kingdom (2)

Mutations on top of BA.2:
S: L452R, F486V
ORF7b: L11F*
N: P151S*
nuc: G12160A
*these two don't always seem to be picked up, G12160A is a better marker outside the spike

In addition, there might be reversions ORF1a:F3201L and S:R493Q, but someone with more expertise can weigh in on whether these are real.

Notably, 452 and 486 are two of the biggest antigenic sites that are not already hit by BA.2 mutations; 452R might knock out some of the same antibodies that 446S does in BA.1.

This lineage has risen quickly to a large proportion of BA.2 in Gauteng. The sample sizes are very small, but as there are signals that prevalence is rising again in South Africa, I think this is worth keeping an eye on.

<img width="564" alt="452_486_gauteng" src="https://user-images.githubusercontent.com/42699509/161433224-cf06613c-9763-4529-9f51-597840f09263.png">

[https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AL452R%2CS%3AF486V&pangoLineage=BA.2*&](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AL452R%2CS%3AF486V&pangoLineage=BA.2*&)

Genomes:
[452_486_genomes.txt](https://github.com/cov-lineages/pango-designation/files/8404737/452_486_genomes.txt)

**Comment by FedeGueli** [comment]
Agree with this proposal, @Rajeev_The_King  was asking some says ago about a sudden uptick in positivity rate there.
And the only thing i noticed was that S:F486V 
(https://twitter.com/siamosolocani/status/1509869619099717713?s=20&t=mRhZ_5c1dGFM-_mgSUMW1A) but really few sequences to say if anything was going on there.
Better monitoring it. thank you for proposing

**Comment by FedeGueli** [comment]
Usher tree (courtesely from @tompeacock):
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2049d_9d00a0.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:T21570G

**Comment by corneliusroemer** [comment]
Very interesting sequences. Just had a look at them in Nextclade.

In addition to S:452R (Delta mutation) and S:F486 (very rare during pandemic, only 75 sequences!):

- All have reversion to root ORF1a:F3201L (with respect to BA.2, which as F there, BA.1 is reference)
- All have reversion S:R493Q with respect to BA.2 (BA.1 is same as BA.2 there)
- Majority has ORF1a:141/143- deletion
- Majority has BA.1 deletion S:69/70- in addition to the BA.2 deletion S:24/26-
- Most have ORF:61L like BA.2, but some don't
- Most have ORF7b:11F
- Most have N:151S
- Some, including from Denmark, Scotland, SA have S:658N
- Some of them (many SA, 1 Denmark, 1 Botswana) have S:V3G

Silent mutations:
- All but one have 12160A (not present in any major lineage during entire pandemic)

The fact that there is so much commonality, especially nuc:12160A makes this cluster look very real to me, despite of all the variation. Too much coincidence.

**Comment by corneliusroemer** [comment]
Since the RBD region is often subject to amplicon dropout, I tried an alternative query to find potential members of this cluster that have amplicon dropout using `S:3G, 12160A` on covSpectrum. These are additional members, might overlap with @silcn's EPI_ISLs:
<details>
 <summary>Click to see EPI ISLS</summary>
```
EPI_ISL_11270161
EPI_ISL_11270160
EPI_ISL_11270126
EPI_ISL_10637554
EPI_ISL_11676915
EPI_ISL_11674447
EPI_ISL_11674443
EPI_ISL_11674448
EPI_ISL_11674426
EPI_ISL_11674413
EPI_ISL_11674368
EPI_ISL_11674380
EPI_ISL_11674382
EPI_ISL_11674389
EPI_ISL_11674390
EPI_ISL_11674411
EPI_ISL_11645323
```
</details>

**Comment by AngieHinrichs** [comment]
Caveat: 22917 (S:452) is one of several sites that I have been masking in BA.1 in the UCSC/UShER tree since the 2022-03-18 build ([22813 22898 22882 22917 23854](https://github.com/ucscGenomeBrowser/kent/blob/463db8f9dc1fe5145d9889dda60d4344860dee21/src/hg/utils/otto/sarscov2phylo/maskDelta.sh#L105)) because they caused a lot of split branches -- i.e. important lineage-defining mutations, that I think were not homoplasic, appeared to be highly homoplasic because they would sometimes appear with, and sometimes without, various combinations of the Omicron mutations at 22813, 22898, 22882 or 23854 or the Delta mutation at 22917, which I think can "sneak in" to amplicon dropout regions from stray contamination reads.  ... Or 22917 could be truly homoplasic, in which case, bummer!

Likewise, BA.2 has 22917 (along with 22786, 22882, and 23854) masked since the latest completed build, 2022-03-30.

Tom's tree there is the "downsampled global tree" output of [UShER](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace), which shows the uploaded sequences in the context of the whole tree but without their nearest neighbors.  If you click on one of the uploaded samples, there is a link to [view subtree 1](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2049d_9d00a0.json), which shows the local context (nearest neighbors in the tree and downsampled nearby branches).  Here I have copied the temporary URL for subtree 1 which will expire in a couple days to a URL that should last much longer:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-517.subtree1.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:T9866C,T23018G,G23040A

Note that for samples already in the tree and uploaded, the uploaded samples are placed one mutation past the tree placement -- that's 22917, not masked in uploaded fasta, but masked on BA.1 and BA.2:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/186983/161442806-94d027cb-a75f-415f-bb5a-d9ed2dfc8813.png">

which is all to say -- beware what you see in the UShER tree in BA.1 and BA.2 with respect to 22917.  It may appear more homoplasic in uploaded samples than it should.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/186983/161443446-a74a0a31-6539-4b58-81f0-7b044b2daa56.png">

[Meanwhile, the tree still has quite a few more sites that could be masked to make lineage-defining mutations more coherent, but I don't want to overdo it and make the currently known recombinants incorrect; the "reversions" accurately reflect their lack of some mutations for the branch on which they're placed.]

**Comment by corneliusroemer** [comment]
>... Or 22917 could be truly homoplasic, in which case, bummer!

22917G = S:L452R has already appeared as defining mutation independently in a number of lineages:
A.2.5, A.27, B.1.617, B.1, B.1.1.487, Epsilon (B.1.427, B.1.429O, B.1.604, B.1.629, B.1.630, B.1.633, B.1.637, C.16 (B.1.1.1.16), C.17 (B.1.1.1.17), C.36.3 (B.1.1.1.36.3), C.40 (B.1.1.1.40), L.3 (B.1.1.10.3), P.4 (B.1.1.28.4)

**Comment by corneliusroemer** [comment]
Here are UShER trees for all the 51 sequences.

They split in two clusters. Here's the global downsampled tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_334ad_a01370.json?c=country&label=nuc%20mutations:T670G,C2790T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10198T,G10447A,C12880T,T15240C,C15714T,C17410T,C19955T,A20055G,C21618T,T21762C,T21846C,T22200G,C22673T,A22688G,G22775A,A22786C,A24130C,C26060T,C26858T,G27382C,A27383T,T27384C,A29510C

Here's tree 1: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_334ad_a01370.json?c=country&label=nuc%20mutations:C28724T

And tree 2: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_334ad_a01370.json?c=country&label=nuc%20mutations:T9866C

**Comment by FedeGueli** [comment]
The two trees posted by @corneliusroemer  differ outside the spike for defining AA mutations M:D3N (tree 2) and N:151S + Orf7b:11F (tree1),
BA.2 + N:151S looks like circulating earlier in January in South Africa without the defining NUC: G12160A
[tree](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_121d7_a13d30.json?branchLabel=nuc%20mutations&c=gt-nuc_12160&label=nuc%20mutations:G12160A,G27788T)
![Schermata 2022-04-03 alle 23 53 02](https://user-images.githubusercontent.com/87669813/161450312-f9338e0d-38b1-47de-a11b-b27963067700.png)

M:D3N appeared only in March 


Earliest sequence of the G12160A,Orf7b:11F branch should be this one: EPI_ISL_10860989 from South Africa (26-01-2022)

**Comment by corneliusroemer** [comment]
I wouldn't draw strong conclusions based on these 2 UShER trees - placement is strongly affected by dropouts. The branch is too long for good placement.

**Comment by silcn** [comment]
24 more sequences from South Africa:
EPI_ISL_11752618
EPI_ISL_11752668
EPI_ISL_11763475
EPI_ISL_11763478
EPI_ISL_11763480-11763481
EPI_ISL_11763491
EPI_ISL_11763502
EPI_ISL_11763507
EPI_ISL_11763512-11763516
EPI_ISL_11763520-11763521
EPI_ISL_11763528-11763531
EPI_ISL_11763533-11763536

Includes 16 out of 40 uploads from KwaZulu-Natal today, 6 out of 30 from Eastern Cape and 2 out of 56 from Western Cape.

**Comment by FedeGueli** [comment]
@silcn great you are monitoring it could you update the title of the issue with the number of sequences you found day by day?
is a way to rapidly check the trend that @corneliusroemer started with recomb lineages

**Comment by FedeGueli** [comment]
@silcn great you are monitoring it could you update the title of the issue with the number of sequences you found day by day?
is a way to rapidly check the trend that @corneliusroemer started with recomb lineages

**Comment by silcn** [comment]
5 more from Gauteng today out of 12 uploads:
EPI_ISL_11773266
EPI_ISL_11773269
EPI_ISL_11773271
EPI_ISL_11773274
EPI_ISL_11773278

**Comment by silcn** [comment]
Changed the title to avoid confusion now that the cat's out of the bag. Interested to see the reasoning behind the decision.

**Comment by corneliusroemer** [comment]
Thanks @silcn, this has been included as BA.4 and BA.5 in release v1.3

**Comment by corneliusroemer** [comment]
CovSpectrum queries to track both lineages already:

BA.5: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=12160A%2C9866.%2C27259A&pangoLineage=BA.2*&nucMutations1=22792T%2C22916A%2C23767G&pangoLineage1=BA.2*&

BA.4: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=12160A%2C9866.%2C27788T&pangoLineage=BA.2*&nucMutations1=22792T%2C22916A%2C23767G&pangoLineage1=BA.2*&
