### ISSUE TITLE
Potential new BA.1 (+G5515T) sub-lineage with ORF1ab:E973K mutation [2% in Peru, 70 seq]

### ISSUE THREAD

**Issue by Wen1953** [cov-lineages/pango-designation#529]
**Description**
New possible omicron sub-lineage with ORF1ab:E973K mutation proposed by the Group of SARS-CoV-2 Genomic Surveillance of the Instituto Nacional de Salud (INS) from Peru.

**Earliest sequence:** 2022-01-03
Peru/TAC-INS-13275/2022 (EPI_ISL_9769340)

**Most recent sequence:** 2022-03-10
hCoV-19/Peru/TAC-INS-16008/2022 (EPI_ISL_11815610)
hCoV-19/Peru/TAC-INS-16008/2022 (EPI_ISL_11815610)

**Countries circulating:**
Peru (31), Chile (2), USA (2)

**Genomes**
[Genomes.csv](https://github.com/cov-lineages/pango-designation/files/8445864/Genomes.csv)

**Evidence**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1ec77_f026e0.json?c=gt-ORF1ab_973&label=nuc%20mutations:G3182A
![Captura de pantalla de 2022-04-07 11-55-58](https://user-images.githubusercontent.com/89021119/162280113-8d4a17cd-9b8f-4951-9a2d-b8a946684b5f.png)
![Captura de pantalla de 2022-04-07 14-10-51](https://user-images.githubusercontent.com/89021119/162280137-7d8e2c05-2357-4e27-8efa-aeac1a33b828.png)
![Captura de pantalla de 2022-04-07 14-11-21](https://user-images.githubusercontent.com/89021119/162280152-a1b54791-098e-4790-ba32-07a8f2e3364d.png)

**Proposed lineage name**
BA.1.X

**Comment by corneliusroemer** [comment]
Thanks for proposing this! It's on a branch with the synonymous mutation G5515T that's fairly common in BA.1s in Peru, but seems to have been acquired outside of South Africa, maybe in the US/Canada where G5515T is in 10% of all BA.1*. Suggests the route of importation into Peru may have been via North America.

This mutation does look like it could have a small growth advantage.

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/25161793/162594584-7bca2cb8-744f-422e-88e1-fe3e306076e8.png">

What's interesting is that Peru still mostly has BA.1 rather than BA.2. Probably due to less international travel to South Africa than say Denmark.

No BA.1 lineage with G5515T has yet been designated. It does make sense though given how common it is around the world.

**Comment by corneliusroemer** [comment]
This lineage has traveled the world
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/25161793/162594642-3778b19f-4710-46ec-b78c-6fe2268f7519.png">

**Comment by Wen1953** [comment]
Yes, we were looking S:K1205R mutation but it seems to be not monophyletic. We will continue with its surveillance. On the other side, we described S166G in #552.
![Captura de pantalla de 2022-04-11 15-20-56](https://user-images.githubusercontent.com/89021119/162825261-26f32ed4-b086-4f06-84ff-6369cfbf0033.png)

**Comment by chrisruis** [comment]
Thanks @Wen1953 We've added this as BA.1.22 to start on the branch with G3182A (Orf1ab:E973K)
