### ISSUE TITLE
Proposal of lineage P.1.2 - Brazil, Australia, Netherlands, Spain, England, United States

### ISSUE THREAD

**Issue by aplamarca** [cov-lineages/pango-designation#56]
**New lineage proposal P.1.2**

**Description**

Sub-lineage of: P.1
Earliest sequence: hCoV-19/Brazil/RS-8680/2021|EPI_ISL_983865|2021-02-01
Most recent sequence: hCoV-19/Spain/MD-HGUGM-21153350/2021|EPI_ISL_1511207|2021-04-03
Countries circulating: Brazil, Australia, Netherlands, Spain, England, United States

We have first identified the sublineage as a local transmission cluster in the state of Rio de Janeiro, Brazil. Since then, we have detected sequences from this lineage in other Brazilian states (São Paulo, Rio Grande do Sul), Netherlands (possibly also containing  local transmission clusters), Spain, England and the United States. We have dated the clade to have originated from P.1 lineage in late-January. 
This clade carries five lineage defining mutations: three in ORF1ab (synC1912T, D762G, T1820I), one in ORF3a (D155Y) and one in N protein (synC28789T). The mutation D155Y was proposed to lower the viral affinity to the host's caveolin-1 protein, avoiding cell apoptosis and extending the infection’s asymptomatic phase (Gupta et al. 2021, https://doi.org/10.1101/2021.03.26.437194).

We have also posted on Virological the description of this new lineage. 
https://virological.org/t/genomic-surveillance-of-sars-cov-2-in-the-state-of-rio-de-janeiro-brazil-technical-briefing/683

**Genomes**
[gisaid_P_1_2.txt](https://github.com/cov-lineages/pango-designation/files/6353759/gisaid_P_1_2.txt)

**Evidence**
![heatmap](https://user-images.githubusercontent.com/82976078/115617418-bf809a00-a2c7-11eb-9c0a-fb25a43e0e56.png)

**Comment by chrisruis** [comment]
Thanks for submitting this @aplamarca - we've added this as lineage P.1.2 in [v1.1.21](https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.21)

**Comment by aplamarca** [comment]
Dear @chrisruis 

PangoLearn (v2021-05-11, which includes pango-designation v1.2) is still missing lineage P.1.2. 
Has any problem occurred during model training?
Please let me know if any additional information is needed.

**Comment by chrisruis** [comment]
Hi @aplamarca thanks for letting us know. So it looks like P.1.2 is being included in PangoLEARN but there's some post-hoc VOC checks which are overwriting P.1.2 as P.1. There's a new version coming (hopefully will be merged in on 25th May) that should fix this

**Comment by afmarti** [comment]
Dear @chrisruis,
The sublineage P.1.2 is defining by five mutations: three in ORF1ab (synC1912T, D762G, T1820I), one in ORF3a (D155Y) and one in N protein (synC28789T).  We reviewed all of our sequences from 2020 and 2021 and in the phylogenetic tree (ML, GTR, 1000 bootstrap) 3 sequences have grouped with P.1.2 sequences from RJ: 90 (EPI_ISL_2086603), 101 (EPI_ISL_2086611) and 6 (6JCMHCPA - EPI_ISL_1133124) as cited in the aplarmarca´s work. Two of them have the five sublineage definition mutations but one of them (90) has just four (C1912T, D762G, D155Y, C28789T). My proposal is to consider these four mutations, instead of five, as P.1.2 
[P12RJ_P1POA.pdf](https://github.com/cov-lineages/pango-designation/files/6490248/P12RJ_P1POA.pdf)
[90_LABRESIS.txt](https://github.com/cov-lineages/pango-designation/files/6490249/90_LABRESIS.txt)
[101_LABRESIS.txt](https://github.com/cov-lineages/pango-designation/files/6490250/101_LABRESIS.txt)


sublineage definition. 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>




EPI_ISL_2086603
--





</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>




EPI_ISL_2086603
--





</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>




EPI_ISL_2086603
--





</body>

</html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/andre/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>




EPI_ISL_2086603
--





</body>

</html>
