### ISSUE TITLE
pangoLEARN: 67% of sequences assigned to BA.2.9 lacks defining ORF3a:H78Y 

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#568]
I dont know if it is a designation issue or a pangolearn issue. i put this here , sorry for bothering if wrong. ( @corneliusroemer please redirect to the right page eventually)
BA.2.9 actually has more than 300k sequences but i noticed that just 33% of them carries the defining orf3a:78Y  mutation.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2.9*&

@AngieHinrichs @chrisruis

**Comment by corneliusroemer** [comment]
@FedeGueli I was wrong about moving it - this type of issue belongs here. I'd just add pangoLEARN to the title to make it clear this is not a proposal but about accuracy of assignments.

**Comment by FedeGueli** [comment]
Thank you for your help @corneliusroemer

**Comment by AngieHinrichs** [comment]
Good find @FedeGueli, it looks like BA.2 + C22792T is getting called BA.2.9 by pangoLEARN, so some BA.2 + C22792T (but not C25624T/ORF3a:H78Y) sequences should be designated as BA.2 so that pangoLEARN knows C22792T can happen without C25624T/ORF3a:H78Y (currently it only sees them together).

@chrisruis just added designations to help with a similar situation with BA.1.16 and BA.2.12, but some more are needed for this.  And I believe Chris also has a plan for adding more parent-lineage designations in the future to prevent cases like this.

**Comment by FedeGueli** [comment]
Thank you @AngieHinrichs i leave this one open so @chrisruis could close it when solved.

**Comment by chrisruis** [comment]
Thanks @FedeGueli We added a large number of new BA.2 designations in [v1.8](https://github.com/cov-lineages/pango-designation/releases/tag/v1.8) and it looks like this has greatly helped the assignments in this region. They're still not perfect but much better. There's more designations to both BA.2 and BA.2.9 in the next release that should further help with this and we'll keep adding designations beyond this to hopefully help further with assignments

I'll close this for now as it looks like the assignments are better in this region
