### ISSUE TITLE
BA.2 [+ 22792T] sequences with Spike_ins213GRG + Spike_V213S from Denmark (1,887 seq as of April 23, 2022)

### ISSUE THREAD

**Issue by fabou-uobaf** [cov-lineages/pango-designation#583]
**New lineage proposal:** 1,887 BA.2.9 sequences with Spike_ins213GRG + Spike_V213S from Denmark (as of April 23, 2022)

**by (alphabetical order):** Andreas Bergthaler; Fabian Amman; Lukas Endler; Maria Novatchkova; Olga Frank; Petr Triska; Ulrich Elling

**Description:** Sublineage of BA.2.9 defined by a three AA insertion (Spike_ins213GRG) and an adjacent AA substitution (Spike_V213S)

**Sub-lineage of:** BA.2.9
**Earliest sequence:** 2022-01-07
**Most recent sequence:** 2022-04-16
**Countries circulating:** Denmark
**Defining mutation:** Spike_ins213GRG + Spike_V213S (aka S:L212insSGR + S:V213G); T22197TATCCGGCAG

**Evidence:**

In the course of the Austrian Variant surveillance program by partial genome sequencing of the S gene [https://doi.org/10.1038/s41467-021-22664-5] two particular samples drew attention to the combination of a three AA insertion SRG after Spike AA 212 (T22197TATCCGGCAG).
GISAID annotates the changes as Spike_ins213GRG and an adjacent AA substitution - Spike_V213S. Examination of this pattern in international sequences revealed that the mutation combination is not uncommon. 

In GISAID (as of April 21, 2022) sequences from the following countries harboured the genotype:

> 1,702x Denmark
> 27x Australia
> 17x Germany
> 16x United Kingdom
> 9x Italy
> 5x Denmark
> 3x France
> 3x Norway
> 2x Austria
> 1x Belgium
> 1x South Africa
> 1x Sweden
> 1x Switzerland
> 1x USA
> 1x Israel

These samples were associated with the following pango lineages:

> 1748x BA.2.9
> 23x BA.2.7
> 14x BA.2
> 3x BA.2.10
> 1x BA.2.5
> 1x BA.3

Determining the relative share of the described haplotype in all BA.2.* sequences across time, revealed an exponential increase in Denmark (and maybe Australia and Germany) with the most recent timepoint in Denmark amounting to ~5% of all BA.2.* samples.

![rel_omicron_lineages_coi](https://user-images.githubusercontent.com/11571552/164944582-46d6a0f8-3845-4561-a01c-93b9d94d5ff2.png)

Examining phylogenic relationship between the samples proofed difficult because most efficient tools ignore insertions and for less efficient tools the selection of a small but sensible background/context sample set is not trivial. However, a tree built with mafft and fasttree of 100 Danish Spike_ins213GRG+ sequences, 100 international Spike_ins213GRG+ sequences and 100 European BA.2.* sequeences without Spike_ins213GRG suggested that the mutations arose multiple time independently, contradicting a monophyletic relationship between all Spike_ins213GRG across Europe.

![iqtree_expanded_small](https://user-images.githubusercontent.com/11571552/164944701-4335c669-7e08-4125-8370-d36c36fc4606.png)

The examination with Nextclade of a reduced set of only Danish sequences with a BA.2.9 background displayed, not surprisingly, a more congenial picture.

<img width="1490" alt="Nextclade_tree_all_Danish" src="https://user-images.githubusercontent.com/11571552/164944788-34e8f7b9-6c7e-40ef-adc5-8600f0b0af35.png">

Altogether, if the above provided set of sequences with Spike_ins213GRG + Spike_V213S is indeed a sublineage according to pangolin's criteria can be disputed, and is challenging to quickly show. But than again, the fact that there is a prominent insertion, positioned in the 3D structure close to the antibody binding region in the NDT, which seems to gain ground within the BA.2 clade, and exhibits (at least for the Danish samples) close phylogenic relations, is per se noteworthy. This way we hope this mutation gets the deserved attention from the scientific community. 

**Genomes:**

[ids.txt](https://github.com/cov-lineages/pango-designation/files/8548534/ids.txt)

**Proposed lineage name:** BA.2.9.2

**Comment by FedeGueli** [comment]
Thank you for proposing this one.
A paper on this insertion has been preprinted by Marco Gerdol (Unitrieste) :
https://www.biorxiv.org/content/10.1101/2022.04.11.487924v1

**Comment by thomasppeacock** [comment]
Really interesting, I worry it might not be possible to assign based on just an insertion though as insertions tend to be one of the first things to be miscalled or to drop out of sequences during calling/downstream stuff and are quite often masked/ignored in a lot of applications because of this. Are you aware of any private mutations anywhere else in the genome that also co-segregate with the insertion? this might be a more reliable way for a sub-lineage to be assigned.

**Comment by corneliusroemer** [comment]
Thanks for reporting, very interesting!

I checked and these sequences don't have the BA.2.9 defining mutation at ORF3a:78 - so they are just BA.2, albeit on the 22792T branch (on which BA.2.9 resides among other lineages).

Those are all the lineages currently designated on that branch:
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/25161793/165043836-17a5220b-ebf5-4566-aab5-8c0280fb3029.png">
https://nextstrain.org/nextclade/sars-cov-2/2022-04-23?branchLabel=none

I would take apparent non-monophyly with a grain of salt as this could just be a result of many pipelines stripping insertions. How likely is it that the same insertion (exact nucleotides and position) arises on the same branch multiple times independently.

Is there a way in which these insertions could appear as artefacts?

Some additional mutations occurring in some of the recent samples with this insertion:

- T9100C, T9454C together
- C25521T
- C26013T
- G5432A, C12747T, C15848T together
- C27131T
- C27453T
- A28612G

If there was a single insertion event, all samples with these mutation clusters on the BA.2 + 22792T branch should have the insertion (unless stripped in error).

I verified the branch with `T9100C, T9454C`, it looks promising. Multiple countries in there that show insertion (Canary Islands, Germany, Scotland, England).

So what we could do is try to find big branches with the insertion and designate them. Meanwhile this is a good opportunity for pipelines and tools to figure out how to deal with insertions and use them in lineage assignment.

The lineage (at least the branch with `T9100C, T9454C`)  appears to have a solid growth advantage. It makes up 8% of BA.2 + 22792T in a Danish region - and 2% in Denmark overall.

https://cov-spectrum.org/explore/Denmark/AllSamples/Past6M/variants?nucMutations=22792T&pangoLineage=BA.2*&nucMutations1=T9100C%2CT9454C%2C22792T&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&

**Comment by luenling** [comment]
Dear @corneliusroemer, you are perfectly right, it should be called S:212insSGR + S:V213G, we only called it different, as GISAID does a right shift with the amino acid annotations.
We were also wondering whether this insertion could be an artefact, but it was identified by various labs with different approaches (at least nanopore and illumina) and primer sets, which speaks against that. In Austria Uli Elling's team found it with their SARSseq approach - which is quite different again both in primers used and fragment length. We got some samples from him and will sequence them this week with yet another primer set - varskip2 - and look into the results in detail around the insertion.

**Comment by corneliusroemer** [comment]
Thanks for the extra information on protocol etc. - I also don't think this is an artefact given the fact that there are these branches I listed above that have a large share of sequences with this insertion. What seems to be artefacts/errors is the share of sequences that doesn't have the insertion.

Many of the sequences with the insertion have reversions, which is another indicator of sequence quality issues. To get a clean tree, one may need to mask all BA.2 mutations so that these reversions don't cause spurious branches. I'd be curious if that makes your fasttree monophyletic or at least have only a few branches.

**Comment by marcogerdol** [comment]
> Thanks for the extra information on protocol etc. - I also don't think this is an artefact given the fact that there are these branches I listed above that have a large share of sequences with this insertion. What seems to be artefacts/errors is the share of sequences that doesn't have the insertion.
> 
> Many of the sequences with the insertion have reversions, which is another indicator of sequence quality issues. To get a clean tree, one may need to mask all BA.2 mutations so that these reversions don't cause spurious branches. I'd be curious if that makes your fasttree monophyletic or at least have only a few branches.

Exactly. That's pretty much what we tried to do while preparing the sequence dataset for our preprint (i.e. we excluded all the sequences showing any reversion). Monophyly was still not fully supported, even though the situation clearly improved. This might become a common issue for several other sublineages which carry an insertion as the only lineage-defining mutation, as gaps are simply treated as missing data and they are not as phylogenetically informative as they should be.
There are multiple other BA.2 sublineages sharing insertions at the very same site (RIR1), which we have previously described as an insertion hotspot (see https://doi.org/10.1016/j.virusres.2022.198674).
The most relevant ones (which have been circulating for over a month) are:
-ins212TVGG (ins213VGGG in GISAID) - mostly England
-ins211LTPT/ins212TPTL (ins213PTLG in GISAID) - Germany + England
-ins212MAEL (ins213AELG in GISAID) - USA
-ins212TGNTL (ins213GNTLG in GISAID) - mostly England

**Comment by corneliusroemer** [comment]
I've had a look at the most recent 375 sequences with this insertion.

Most fall in one of these 5 branches:
- 26577C (173/375)
- 26013G (45/375)
- 25521T (27/375)
- 5432A, 12747T (23/375)
- 9100C, 9454T (23/375)

That allows creation of a query that should catch a good share of the circulation via covSpectrum using an advanced query `BA.2* & 22792T & (26577C | 26013G | ...)`

**Comment by marcogerdol** [comment]
@corneliusroemer thank you! This seems like a handy workaround.

**Comment by corneliusroemer** [comment]
So here's a query that currently catches about half of the lineage - should have pretty good specificity, haven't looked it up exactly but these should almost all have the insertion.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26+22792T+%26+%28%28+24211A+%26+28612G%29+%7C+%2821137G+%26+203T+%26+25180C%29+%7C+%289100C+%26+9454C%29++%7C+%2826013T+%26++%2817825T+%7C+13815G+%7C+15450T+%7C+14913T+%7C+29421T+%7C+239C+%7C+683T%29%29%7C+%2827453T+%26+1060A%29+%7C+%2827603T+%26+%2816852T+%7C+4893T%29%29%29&

This is growth advantage in Denmark over BA.2 + 22792T, seems pretty clean at around 5% per day.

<img width="2076" alt="image" src="https://user-images.githubusercontent.com/25161793/165601227-e093be36-7439-49d8-bc9d-b00cee8da415.png">

**Comment by corneliusroemer** [comment]
@chrisruis I feel like we should designate this - problem is this will be difficult for pangoLEARN and other classifiers.

Any thoughts?

**Comment by fabou-uobaf** [comment]
Dear Cornelius

Thank you very much for keeping me in the loop here. We also tried on our side, namely @Lukas ***@***.***>, to find private mutations. We were not as successful as you were. I guess we have not mastered the dark art of cov-spectrum as you do. Your query is indeed magically.

I can only say that I tried to follow up on some comments in the designation issue, also from your side, that there might be an artefact in the data that for some sequences harboring the insertion, the insertion is ignored hance not reported. The only way I could have imagine this happens is if during variant calling or consensus construction the used tool simple does not report this. I used all BA.2.9 sequences with 22792T, C26013T between Jan 1 - May 1 (assuming that all of those should have the insertion) and checked if I find sequences with and without insertion from the same lab (assuming that a lab has not changed its bioinformatic pipeline in this period). And I do find sequences with and without the insertion from the same lab, ruling more or less out that (if my assumptions are true) there is a significant number of falsly insertion-less sequences. This would point to a multiple introduction of the insertion, which again I deem unlikely. You see I turn in circles, walls everywhere.

I do believe the insertions does provide a growth advantage. I do not dare to say if this is monophyletically or if pangoLearn can handle the complex query you come up with.

Bw, Fabian

From: Cornelius Roemer ***@***.***>
Date: Wednesday, 27. April 2022 at 21:27
To: cov-lineages/pango-designation ***@***.***>
Cc: Fabian Amman ***@***.***>, Author ***@***.***>
Subject: Re: [cov-lineages/pango-designation] BA.2 [+ 22792T] sequences with Spike_ins213GRG + Spike_V213S from Denmark (1,887 seq as of April 23, 2022) (Issue #583)

@chrisruis<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrisruis&data=05%7C01%7CFAmman%40cemm.oeaw.ac.at%7C4351961e1aaf458e905408da2883edf0%7Cca39edd17349449abbae314640be0def%7C0%7C0%7C637866844347295598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QZcz%2FxYdTMxrq7ceci9ah60aI7dHoWKufGAEA6ZMugs%3D&reserved=0> I feel like we should designate this - problem is this will be difficult for pangoLEARN and other classifiers.

Any thoughts?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcov-lineages%2Fpango-designation%2Fissues%2F583%23issuecomment-1111396250&data=05%7C01%7CFAmman%40cemm.oeaw.ac.at%7C4351961e1aaf458e905408da2883edf0%7Cca39edd17349449abbae314640be0def%7C0%7C0%7C637866844347295598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LrQE%2F1hDQTNx2%2B9kzIgHVQ%2F8Z%2F8OfPaMEg4DwYzxRLY%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYJCYHBGOQPVPZTDRDBXSTVHGII5ANCNFSM5UFFR5JQ&data=05%7C01%7CFAmman%40cemm.oeaw.ac.at%7C4351961e1aaf458e905408da2883edf0%7Cca39edd17349449abbae314640be0def%7C0%7C0%7C637866844347295598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f%2B3ryNUp52Cpex65lGX8u5AmWJNPpGmZ6JU%2F6bQ8fTM%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



___________________
Notice of confidentiality:
This email and any information and files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient, any use of this communication is unlawful. If you have received this transmission in error, please immediately notify us by return e-mail and destroy the original message. Thank you.

**Comment by corneliusroemer** [comment]
Hi Fabian,

I don't think there's any black magic there, I just entered the biggest branches with at least 2 private mutations as shown in the UShER tree. One could make the query even longer, thereby getting higher sensitivity but for now I think this is enough.

I tried adding branches with a single private mutation but that didn't have good specificity, as some of these mutations will occur homoplasically - with more than 200k sequences on the branch that got the insertion.

What I don't understand is why there are so many 26013T that have this insertion - but not all. Can't quite make sense of it, yet.

I've made the query a bit more specific by excluding common unrelated lineages on the 22792T branch:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.2*+%26++22792T+%26++25624C+%26+23767A+%26+%2129870A+%26+%2117502T+%26+%2117676T+%26+%2110000C+%26+%219565T+%26+%2826013T+%7C+%28+24211A+%26+28612G%29+%7C+%2821137G+%26+203T+%26+25180C%29+%7C+%289100C+%26+9454C%29++%7C+%2826013T+%26++%2817825T+%7C+13815G+%7C+15450T+%7C+14913T+%7C+29421T+%7C+239C+%7C+683T%29%29%7C+%2827453T+%26+1060A%29+%7C+%2827603T+%26+%2816852T+%7C+4893T%29%29%29&

**Comment by marcogerdol** [comment]
@fabou-uobaf hi Fabian, false insertion-less sequences deposited from some labs have been an issue in the past for other lineages due to the frequent use of insertion-unaware algorithms in the early phases of the pandemics. This was for example the case of B.1.214.2, with genomes sequenced in Switzerland not reporting the insertion for several months, as opposed to Belgium, where the insertion was always mapped correctly.
This issue has been fixed pretty much everywhere, in particular with the surge of BA.1 (which also has an "EPE" insertion pretty much at the same site), so we should not expect a large number of false insertion-less sequences being deposited in GISAID in 2022.
My personal interpretation is that the insertion was acquired only once on a genetic background which already carried 22792T (which therefore pre-dates the acquisition of the insertion). Multiple independent acquisitions of the very same nucleotide sequence at the very same site in the very same geographical location would be, by itselft, extremely unlikely. This might have happened somewhere around late December/early January, based on the earlier dates of sampling in Denmark (back then around 10% of all positive swabs were sequenced in the country). In the following months, several other point mutations (those identified by @corneliusroemer in his query) have been secondarily acquired, as expected from the overall SARS-CoV-2 substitution rate observed thus far. Some of these, as expected, are also shared by other BA.2 sublineages, where they have been independently acquired, leading to a significant background noise due to homoplasy.
The main issue here is that the TCCGGCAGA insertion was really the only lineage-defining phylogenetically informative mutation shared by all the early genomes belonging to this sublineage. Yet, gaps are considered as missing data by ML phylogeny, so the shared presence of this insertion does not really provide much help in supporting the monophyly of this clade, especially when it comes to the placement of early genomes from Janaury and February, before the acquisition of additional point mutations.
The growth advantage over BA.2 in Denmark is even more clear at the regional level, and I think the geographical spread of this sublineage over time further rules out the possibility of technical artefacts: the first cases were reported in Nordjylland (where this sublineage is now responsible for > 10% daily cases), followed by the neighboring Midtjylland and the capital Region Hovestaden and finally by the southernmost region Syddanmark and by the insular region Sjaelland.

**Comment by InfrPopGen** [comment]
Although this clade rose a bit initially, this is common with emerging clades, it has (since mid-April) declined in relative proportion to BA.2 in Denmark and worldwide. Over the past 3 months it's averaged -15% relative to BA.2 in Denmark. Consequently, there has been no evidence for a consistent advantage over the rest of BA.2. Unfortunately, in view of this lack of epidemiological significance, this clade does not meet the criteria for designation. The insert is interesting, and had the clade still been growing, or at least steady as a proportion, then a designation would have been possible.
