### ISSUE TITLE
BA.2 + S:ins212TVGG in England region (800 genomes as of 2022-05-08)

### ISSUE THREAD

**Issue by 54mu** [cov-lineages/pango-designation#586]
# Description
Sub-lineage of BA.2
labeled as Spike_ins213VGGG on GISAID
earliest collection date: 2022-01-05
latest collection date: 2022-04-19
Circulating in England, UK

Complete list of districts counts:
| division               |   virus |
|:-----------------------|--------:|
| England                |     298 |
| Scotland               |       7 |
| Baden-Wurttemberg      |       3 |
| Galway                 |       2 |
| Massachusetts          |       2 |
| Bavaria                |       1 |
| Borgerhout             |       1 |
| California             |       1 |
| Hovedstaden            |       1 |
| Namur                  |       1 |
| Nebraska               |       1 |
| North Rhine-Westphalia |       1 |
| Wales                  |       1 |

Proportion over the sequenced BA.2 genomes in England (rolling average of 7 days, 95% confidence interval):
![image](https://user-images.githubusercontent.com/50208988/165325526-99b8087c-7beb-41b1-85b7-051002b6f63c.png)

currently assigned in GISAID to 'BA.2', 'BA.2.5', 'BA.2.9', 'BA.2.16', 'BA.2.3', 'BA.2.10'

# Genomes
see this [gist](https://gist.github.com/54mu/05e67797c99f4e238a91dd81886ff3ac) for the list of GISAID genomes

# Evidence

We described this cluster in https://doi.org/10.1101/2022.04.11.487924, together with the one proposed in #583 

Phylogenetic tree (updated to 2022-03-27):
https://nextstrain.org/community/54mu/SARS-CoV-2_BA.2_RIR1insertions/treeViz?c=BA_group
the proposed lineage is here marked as BA.2+ins(LIII) as referenced in our preprint. BA.2+ins(L) marks the lineage proposed in #583 
for extended methods see [here](https://gist.github.com/54mu/5e858e0f4aa6a7236cf5849e6ec371c7)

**Comment by corneliusroemer** [comment]
Thanks for proposing this. I did an independent survey of insertions and also identified this as the second biggest BA.2 insertion in terms of sequences. So that's reassuring :)

In nucleotide coordinates this insertion is: `22198:insACAGTAGGAGGA`

With GISAID data up to around the 25th of April I counted 345 sequences.

Would be good to find nucleotide mutations that are shared by (nearly) 100% of these sequences to distinguish from other BA.2 and also some big branches with nuc mutations within it (so less than 100% but significant numbers).

PangoLEARN, UShER and Nextclade-Pango wouldn't be able to work off an insertion alone (at this point) unfortunately.

**Comment by corneliusroemer** [comment]
Turns out we are lucky! This insertion appeared on top of nuc mutations `4202T` followed by `25253T`, the latter one being  equivalent to `S:T1231S` [confirmed by dropping all sequences with this insertion into Nextclade]

The query for the combination of nuc mutations alone results in 654 sequences, of which at least half have that insertion. Some of the missing ones could miss due to bioinformatic errors.

So I think we should be able to easily designate this one as `BA.2* + 4202T, 25253T` rather than working with the insertion. @chrisruis 

https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?nucMutations=4202T%2C25253T&pangoLineage=BA.2*&pangoLineage1=BA.4&

One S2 mutation plus a 4 AA insertion in NTD of S1 makes an interesting lineage.

The branch with the insertion also seems to have a slight growth advantage on the order of a few percent per day.

<img width="2176" alt="image" src="https://user-images.githubusercontent.com/25161793/165526213-3b3a7564-8d0b-4caf-a129-32f37c35f60c.png">

**Comment by 54mu** [comment]
> It would be more useful if it was annotated with nucleotide mutations that are on different branches (it should be possible to reconstruct those with `augur ancestral`) - basically running a more complete version of the Augur ncov pipeline.

Hi, thank you for the tip, I updated the linked tree. 

May I ask how did you obtain the nucleotide substitutions? I ran a chi squared test on substitutions inferred from the alignment used for the tree and found the exact same substitutions, plus two that do not appear in cov-spectrum (I may need to recheck my script).

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.41 with 561 newly designated sequences, and 51 updated designations from BA.2. Defining mutation(s) A25253T (S:T1231S).
