### ISSUE TITLE
BA.2.12 sublineages which may have independently acquired S:L452Q circulating in Canada

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#596]
As highlighted by @silcn in #499 there are sublineages of BA.2.12 with S:L452Q, circulating mainly in Canada, which seem to be rooted differently from the main Ba.2.12.1 designated from #499 that is characterized by T15009C and C21721T

Here the proposal (Asking @AngieHinrichs @corneliusroemer @chrisruis if they arent just tree building issues, but i dont think so)

First sublineage of BA.2.12, that subsequently acquired S:L452Q, is BA.2.12 + C27654T + C16726T (Orf1b:1087Y) 
424sequences (347 from Canada , 70 from Usa)
[Covspectrum](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=Orf1b%3A1087Y&nucMutations=C27654T&pangoLineage=BA.2.12&nucMutations1=T15009C%2CC21721T&)

Second sublineage of BA.2.12 , that subsequently acquired S:L452Q,  is Ba.2.12 + A6107G(orf1a:1948E)
305 Seqs (154 from Canada 138 from USA)
[Covspectrum](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=orf1a%3A1948E%2CS%3A704L&pangoLineage=BA.2*&nucMutations1=T15009C%2CC21721T&)

Usher Tree:
![Schermata 2022-05-01 alle 08 13 47](https://user-images.githubusercontent.com/87669813/166137388-92308e88-e5e1-49b2-9d6e-768f7a965835.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_36181_e1c050.json?branchLabel=nuc%20mutations&c=country&label=nuc%20mutations:C241T,T670G,C2790T,C3037T,G4184A,C4321T,C9344T,A9424G,C9534T,C9866T,C10029T,C10198T,G10447A,C10449A,C11674T,C12880T,C14408T,C15714T,C17410T,A18163G,C19955T,A20055G,C21618T,T22200G,G22578A,C22674T,T22679C,C22686T,A22688G,G22775A,A22786C,G22813T,T22882G,G22992A,C22995A,A23013C,A23040G,A23055G,A23063T,T23075C,A23403G,C23525T,T23599G,C23604A,C23673T,C23854A,G23948T,A24424T,T24469A,C25000T,C25416T,C25584T,C26060T,C26270T,C26577G,G26709A,C26858T,A27259C,G27382C,A27383T,T27384C,C27807T,A28271T,C28311T,G28881A,G28882A,G28883C,A29510C

**Comment by garyvand** [comment]
Hey Gang,

Canada has been struggling with this issue for a while now, and it's kind of messing up our monitoring and communication of BA.2.12 and BA.2.12.1 in Canada. We are hoping that the designation of these Canadian BA.2.12.1-like sequences can be resolved soon! Let us know what we can do to help!

**Comment by RajLABN** [comment]
Sequences with BA.2.12 + S:L452Q in Canada 
 ![Dashboard 1 (10)](https://user-images.githubusercontent.com/98380390/166628894-e7014739-63d1-49d5-8b17-74af3c594f99.png)

This BA.2.12.1-like lineage is now in several countries 
![Dashboard 1 (11)](https://user-images.githubusercontent.com/98380390/166629167-1fcd62ea-e8e4-454e-a4fe-ec9394a76892.png)

**Comment by FedeGueli** [comment]
@RajLABN are you sure they are the same sublineages? i will take a look further into it.

@corneliusroemer could you help in clarifying this?

**Comment by corneliusroemer** [comment]
Having looked at the Canadian lineages, I think the apparent independent S:452Q mutations are tree building artefacts due to some low quality/dropout sequences.

I still don't understand why the early Canadian S:452Q didn't grow as as fast as the New York ones. Maybe they acquired some deleterious mutations or Canadian immunity landscape is different. In any case, S:452Q is also on the rise now all over Canada.

I think it makes sense to broaden BA.2.12.1 to include all BA.2.12 branches with S:452Q. Best would be if the artefactual homoplasy was cleaned up so that BA.2.12.1 could be one single Usher branch where S:452Q arose.

@AngieHinrichs can you have a look? @chrisruis is it possible to mark several branches in BA.2.12 as BA.2.12.1 if we are convinced that the apparent homoplasy of S:452Q is artefactual?

It would be good to give the Canadian BA.2.12 with S:452Q a proper Pango label that isn't BA.2.12.

The alternative to broadening would be to have multiple BA.2.12 lineages with S:452Q, like BA.2.12.2 etc, but I think this would create the wrong illusion that S:452Q arose independently - when it's probably one monophyletic clade.

**Comment by FedeGueli** [comment]
Thank you very much @corneliusroemer !

**Comment by AngieHinrichs** [comment]
Thanks @corneliusroemer -- I took a look at all of the little S:452Q clusters just upstream of the base of BA.2.12.1 in the UCSC/UShER tree and I agree they're separated by dropout/errors/artefacts not true homoplasy.  I will try some strategic pruning & optimizing and see if that moves the base of BA.2.12.1 back a bit.  (Currently it's set to BA.2.12 + C11674T > T15009C > C21721T > T22917A, but after looking more closely I think it should probably be just C11674T > T22917A.  There is a very solid-looking branch of Australian sequences that has C11674T and not T22917A (@chrisruis those would be good candidates for designating as BA.2.12 to help pangoLEARN distinguish them from BA.2.12.1 -- the branch with Australia/VIC45003/2022), but there aren't nearly as many sequences arguing convincingly for T15009C and C21721T without T22917A.)

**Comment by chrisruis** [comment]
Thanks All, based on that we've designated the Canada sequences with S:452Q to BA.2.12.1

And thanks @AngieHinrichs for spotting the Australia clade, I've designated these and some other nearby sequences to BA.2.12 to hopefully give BA.2.12.1 a clean starting node

**Comment by FedeGueli** [comment]
Just to be correct i see i didnt mention this issue was highlighted me by @RajLABN via twitter, sorry for not mentioning you in the first post.
