### ISSUE TITLE
BA.2.3 sublineage with S:S255F with global circulation in Quebec (324 in Quebec, 572 global)

### ISSUE THREAD

**Issue by ilevade** [cov-lineages/pango-designation#633]
Description
Sub-lineage of: BA.2.3
Earliest sequence: 2022-02
Most recent sequence: 2022-18
Countries circulating: Canada, USA, UK, Germany, France

Cov-spectrum: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AS255F&pangoLineage=BA.2.3*&pangoLineage1=BA.2.3*&

![image](https://user-images.githubusercontent.com/31353633/168312908-f5c036ef-523f-47d8-90b0-d2e6aa215b6c.png)

Growth advantage seems solid vs current BA.2 baseline (52%)
![image](https://user-images.githubusercontent.com/31353633/168312945-52e3ed6b-1022-43f2-8caf-a5ef0bd22bda.png)

Usher tree: 
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_3895c_e749d0.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:C8991T,C25810T

![image](https://user-images.githubusercontent.com/31353633/168313573-d8911baf-0a9f-4b09-9b95-22176cdf09c1.png)

The mutation S:S255F in NTD seems to be found in multiple previous lineages, like AY.106 (convergent evolution) and it seems it could have impact to the immune response (https://covdb.stanford.edu/search-drdb/?dosage=2&dosage=3&host=human&mutations=S%3A255F)

**Comment by FedeGueli** [comment]
Good catch!
This mutation S:255F has been highlighted by NNSF Neural network sequence filter build by @bitbyte2015 some times ago
I was monitored it since some weeks in multiple sublineages.
There are three main branch with this mutation:
this one with C4990T , another in the branch with C22792T and the last one of these three with N:368H.
Globally these lineages together show moderate growth advantage vs BA.2 baseline btw 10-20%.
Very happy you have done a proper analysis for this Quebec branch finding a solid growth advantage! Thank you!

**Comment by FedeGueli** [comment]
709 seqs as today

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.2.3.6 with 536 newly designated sequences, and 108 updated designations from BA.2.3. Defining mutation(s) C22326T (S:S255F).
