### ISSUE TITLE
Update to designations of lineage B.1.575 and B.1.575.1

### ISSUE THREAD

**Issue by aineniamh** [cov-lineages/pango-designation#64]
## Lineage description

USA and Aruba lineage with spike mutations "S:P681H","S:S494P" and "S:T716I". 

From all SARS-CoV-2 genomes on GISAID as of 2021-04-25, any sequences with at least 8 of the SNPs below were aligned with a selection of B.1 genomes to place them within B.1 diversity. These sequences include previously designated B.1.575 sequences and a couple of sequences that had previously been designated as B.1.1.335. 
```
snps = [
"S:D614G",
"S:P681H",
"S:S494P",
"S:T716I",
"N:T205I",
"orf1ab:T3750I",
"orf1ab:T3255I",
"orf1ab:T265I",
"M:182T",
"orf3a:Q57H"
]
```
<img width="1094" alt="Screenshot 2021-04-28 at 08 42 53" src="https://user-images.githubusercontent.com/11678307/116366014-bf1f5c00-a7fd-11eb-85cb-4167580bcedb.png">
The above phylogeny shows B.1.575 in red and B.1.575.1 in blue, both as monophyletic clades. 
The annotated tree is available here: 
[sequences.aln.fasta.tree.zip](https://github.com/cov-lineages/pango-designation/files/6389986/sequences.aln.fasta.tree.zip)

New designations:
```
B.1.575 1,560
B.1.575.1 167
```

Now total designations:
```
B.1.575 1,571
B.1.575.1 168
```
Changes enacted in commit: 
https://github.com/cov-lineages/pango-designation/commit/8a5d954ecf76b2d66c3b5d4f9c01c2985bd8f51b
[B.1.575.new_lineages.csv](https://github.com/cov-lineages/pango-designation/files/6389988/B.1.575.new_lineages.csv)

**Comment by aineniamh** [comment]
Now tagged as release: https://github.com/cov-lineages/pango-designation/releases/tag/v1.1.23

**Comment by oroak** [comment]
@aineniamh Thanks for your work I this. I spot checked a few of the sequences I flagged manually and they are still B.1 in the new release lineages.csv. Investigating the first three (below), I think the issue is they have gaps (including our sequence) over "orf1ab:T265I". Because of this they were not included in your reassignment pull above (they have all of the other mutations). My suggesting would be to remove the samples like this (those originally reassigned from B.1.617 to B.1 but not included in above) from the training data as I think they will just be creating trouble for both lineages.
hCoV-19/USA/OR-OHSU-10702/2021|EPI_ISL_1541883|2021-03-17 
hCoV-19/USA/NJ-CDC-LC0035972/2021|EPI_ISL_1609515|2021-03-27
hCoV-19/USA/NJ-CDC-LC0036132/2021|EPI_ISL_1609321|2021-03-25

**Comment by oroak** [comment]
@aineniamh I know you closed this but I believe the reassignment of samples from https://github.com/cov-lineages/pango-designation/issues/49 to B.1 is still causing issues. I ran our custom Oregon build and included many of these still assigned to B.1 (that is not reassigned above). You can see from these screenshots that we have genotypes at identical places in the tree getting misassigned.  

<img width="972" alt="Screen Shot 2021-05-03 at 2 02 13 PM" src="https://user-images.githubusercontent.com/41455895/116935058-ab6b5f80-ac1a-11eb-998f-637e3953891f.png">
<img width="972" alt="Screen Shot 2021-05-03 at 2 01 48 PM" src="https://user-images.githubusercontent.com/41455895/116935059-ac03f600-ac1a-11eb-942f-b17db445e808.png">


[nextstrain__metadata.txt](https://github.com/cov-lineages/pango-designation/files/6417794/nextstrain__metadata.txt)

**Comment by aineniamh** [comment]
Hi @oroak, thanks for providing the trees and IDs. 

I've now removed the following from designations:
```
-USA/OR-OHSU-10702/2021,B.1
-USA/NJ-CDC-LC0035972/2021,B.1
-USA/NJ-CDC-LC0036132/2021,B.1
-USA/NH-CDC-LC0019242/2021,B.1
-USA/MA-CDC-LC0013337/2021,B.1
-USA/PA-CDC-LC0022743/2021,B.1
```
I'm not certain what these sequences will be assigned once trained, but it sounds like they should be B.1.575 and it would be straightforward to flag a misassignment as due to missing data.
