### ISSUE TITLE
Two differents recombinants lineage for XU in lineages.csv

### ISSUE THREAD

**Issue by sanschiffre** [cov-lineages/pango-designation#646]
Lineages.csv containt 7 XU samples :

> Japan/IC-4679/2022,XU
> India/RJ-SMS-ICMR-INSACOG-TS-11049/2022,XU
> India/RJ-SMS-ICMR-INSACOG-TS-9433/2022,XU
> India/RJ-SMS-ICMR-INSACOG-TS-9434/2022,XU
> India/MH-KasturbaMCGM-ICMR-INSACOG-WG3595/2022,XU
> India/MH-KasturbaMCGM-ICMR-INSACOG-WG3600/2022,XU
> Australia/NSW-ICPMR-23049/2022,XU

But when you analysed them with Sc2rf, you can see that they are two differents lineages :
![Capture d’écran de 2022-05-17 09-40-01](https://user-images.githubusercontent.com/95621137/168756568-cadda5c2-d96d-4119-9734-f2cf4d51d9ac.png)
India/RJ-SMS-ICMR-INSACOG-TS-11049/2022 has a breakpoint between  12880 and 13195
The six others have their breakpoint between 5386 and 8393

**Comment by AngieHinrichs** [comment]
Good catch @sanschiffre!  I think it should be India/RJ-SMS-ICMR-INSACOG-TS-11440/2022 (EPI_ISL_10924169) instead of India/RJ-SMS-ICMR-INSACOG-TS-11049/2022 -- I suspect that was a copy-paste error in the original post for #522, where the tree screenshot shows RJ-SMS-ICMR-INSACOG-TS-11440 but the table of samples has -11049.

Chris is on holiday so I will make that change in lineages.csv.
