### ISSUE TITLE
BA.2 sublineage with Orf1a:S2193F, S:356R, C11308T circulating in northern europe (380 Sequences)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#674]
As Jesse Bloom pointed in a [twitter thread](https://twitter.com/jbloom_lab/status/1527872414528376832?s=20&t=XLJXEB668CMy5TkNepmugA) a few days ago residues 346 , 354, 356 are the ones expected to be prone to mutate further during the next steps of viral evolution.
Here i want to propose one already circulating that likely has arisen in Norway.
It evolved from a broader lineage with Orf1a:S2193F circulating earlier in Europe and Uk ( 759seqs ) 
that then acquired NUC: C11308T ( 536 seqs ) and finally S:K356R ( 360 seqs ) that likely emerged in Norway .
Nr. Sequences: 365
List of Sequences:
[contributors (12).csv](https://github.com/cov-lineages/pango-designation/files/8778508/contributors.12.csv)

Countries:
![Schermata 2022-05-26 alle 13 13 14](https://user-images.githubusercontent.com/87669813/170477145-cabc3f3d-0a5c-42ea-9162-228362dab26c.png)

Cov-Spectrum overview: 
https://cov-spectrum.org/explore/World/AllSamples/from=2022-01-01&to=2022-05-19/variants?aaMutations=orf1a%3A2193F%2CS%3A356R&nucMutations=C11308T&pangoLineage=BA.2*&aaMutations1=orf1a%3A2193F%2CS%3A356R&pangoLineage1=BA.2*&

Tree:
![Schermata 2022-05-26 alle 13 14 26](https://user-images.githubusercontent.com/87669813/170477409-90b08517-5c7c-4736-9bb0-13d6889f23d1.png)
UShER link:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_217d1_f53890.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C11308T

**Comment by InfrPopGen** [comment]
Thank you very much for proposing this. In order to maintain a faithful implementation of the Pango rules, we are re-highlighting the requirement for an associated epidemiological "event". The lineage proposed here is an interesting one, with its potential to inform us about virus evolutionary tracts. Unfortunately, it is not showing much of a growth advantage (in terms of increasing proportion of new cases) or association with a regional outbreak.
Example:
17% Current adv. 15-19% (6M)
-3% Current adv. -7-1% (3M)
-11% Current adv. -18--4% (2M)

Compared to the BA.2* parent:
1% Current adv. -1-4% (6M)
-5% Current adv. -9--2% (3M)
-11% Current adv. -18--3% (2M)

Please do submit a new proposal for this lineage if it does show signs of epidemic potential in the future.

**Comment by FedeGueli** [comment]
Thanks @InfrPopGen agree with you it isnt growing so much. Of course i will monitor it even if i think there are not much chances for the remaining undesignated BA.2 to compete vs BA.5.
