### ISSUE TITLE
Potential BA.5.5 sublineage with ORF1a:A76V mutation [444 sequences - mainly in USA]

### ISSUE THREAD

**Issue by RajLABN** [cov-lineages/pango-designation#680]
BA.5 + orf1a:A76V ( sub-lineage of BA.5 + S:T76I - https://github.com/cov-lineages/pango-designation/issues/656)
Circulating mainly in USA [ 50 USA; 1 Mexico and 1 England]
Earliest sequence: 4/12/2022

Nextstrain tree -
![image](https://user-images.githubusercontent.com/98380390/170921705-8463be31-c289-4ae7-8330-8912b8916748.png)
![image](https://user-images.githubusercontent.com/98380390/170921784-bf7d39b1-c293-4f35-b6d2-01c816f9c7e7.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_40f2b_44ce50.json?branchLabel=aa%20mutations&c=pango_lineage&label=nuc%20mutations:C492T

Cov-spectrum predicts a growth advantage of 35% over BA.5 

![image](https://user-images.githubusercontent.com/98380390/170922167-69907e07-effe-4412-a576-4c86d4567340.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=ORF1a%3AA76V&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

**Comment by agamedilab** [comment]
Hi, thank you for proposing!

At the moment the growth advantage of BA.5 + S:T76I is strong against BA.5 (#656).

As you mentioned, this is a sublineage BA.5 + S:T76I (https://github.com/cov-lineages/pango-designation/issues/656) therefore the growth advantage as measured now could be derived from S:T76I instead of orf1a:A76V.

In fact when you compare BA.5 + S:T76I versus BA.5 + orf1a:A76V than the advantage of the latter is not so clear tight now.

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=S%3AT76I&pangoLineage=BA.5&aaMutations1=ORF1a%3AA76V&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

Maybe after a few weeks we will know more!

All the best!

**Comment by FedeGueli** [comment]
444 sequences as today.

**Comment by InfrPopGen** [comment]
Thanks @RajLABN  As outlined [here,](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/) new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations.

There doesn't seem to be a clear epidemiological event associated with this clade, for example it is not showing an increase in proportion relative to its parent lineage, we therefore haven't designated this at this point.
