### ISSUE TITLE
BA.5.2.1 sublineage with N:S33I (101 seq. )

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#722]
Proposal for a sublineage of BA.5.2.1
Earliest sequence: 24.04.2022 (Israel)
Countries detected: mostly Israel (24 %), Germany (23 %) and Denmark (18 %) but also Australia, Austria, Belgium, Brazil,  France,  Italy, Netherlands, South Africa, Switzerland, USA

Defining mutations:
G28371T = N:S33I

This variant is defined by N:S33I and was first detected in Israel and multiple other countries. 

This variant is apparently a sublineage of BA.5.2.1 (but see also https://github.com/cov-lineages/pango-designation/issues/717).

![ns33i](https://user-images.githubusercontent.com/102166254/172331404-a571bf35-fe69-481b-a0d3-d005f75e1dea.PNG)
![ns33i_aa](https://user-images.githubusercontent.com/102166254/172331436-9e67de9e-af7b-4e97-b86e-1cae0fa343ab.PNG)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_32c51_efa090.json?branchLabel=nuc%20mutations&c=gt-N_33&label=nuc%20mutations:C1627T

EPI_ISL_12883237, EPI_ISL_12810213, EPI_ISL_12730150, EPI_ISL_12741233, EPI_ISL_12636091, EPI_ISL_12610579, EPI_ISL_12610587, EPI_ISL_12611442, EPI_ISL_12589340, EPI_ISL_12563489, EPI_ISL_12676008, EPI_ISL_13101484, EPI_ISL_12892643, EPI_ISL_13075052, EPI_ISL_13077172, EPI_ISL_13073793, EPI_ISL_13086884, EPI_ISL_13073943, EPI_ISL_13090302, EPI_ISL_13088544, EPI_ISL_13033928, EPI_ISL_12866409, EPI_ISL_12850560, EPI_ISL_12845588, EPI_ISL_12810243, EPI_ISL_13091277, EPI_ISL_13089899, EPI_ISL_13089959, EPI_ISL_13075060, EPI_ISL_13074893, EPI_ISL_13089900, EPI_ISL_13090023, EPI_ISL_13089951, EPI_ISL_13077174, EPI_ISL_13073892, EPI_ISL_13072491, EPI_ISL_13077176, EPI_ISL_13046997, EPI_ISL_13052247, EPI_ISL_13075179, EPI_ISL_13052237, EPI_ISL_13049733, EPI_ISL_13034391, EPI_ISL_13015385, EPI_ISL_13010881, EPI_ISL_12923374, EPI_ISL_12922635, EPI_ISL_12902140, EPI_ISL_12915568, EPI_ISL_12915763, EPI_ISL_12958126, EPI_ISL_12815464, EPI_ISL_12741881, EPI_ISL_12998132, EPI_ISL_12809284, EPI_ISL_12915756, EPI_ISL_12915591, EPI_ISL_13090198, EPI_ISL_13090148, EPI_ISL_13090134, EPI_ISL_13090067, EPI_ISL_13012752, EPI_ISL_13012765, EPI_ISL_13052169, EPI_ISL_12699895, EPI_ISL_13075002, EPI_ISL_13077362, EPI_ISL_13077224, EPI_ISL_13077181, EPI_ISL_12737342, EPI_ISL_13067442., EPI_ISL_13049611, EPI_ISL_13049726, EPI_ISL_13049866, EPI_ISL_13049652, EPI_ISL_13049216, EPI_ISL_13067442, EPI_ISL_13067323, EPI_ISL_13068437, EPI_ISL_13067294, EPI_ISL_13068182, EPI_ISL_13067481, EPI_ISL_13066955, EPI_ISL_13067470, EPI_ISL_12994662, EPI_ISL_13067126, EPI_ISL_13066744, EPI_ISL_13068188, EPI_ISL_13009953, EPI_ISL_12879681, EPI_ISL_13034609, EPI_ISL_13012796, EPI_ISL_13051205, EPI_ISL_13013142, EPI_ISL_12739063, EPI_ISL_13033644, EPI_ISL_12998295, EPI_ISL_12739153, EPI_ISL_12998321, EPI_ISL_12998283, EPI_ISL_12998299, EPI_ISL_12739142

**Comment by chrisruis** [comment]
Thanks @agamedilab As outlined [here](https://www.pango.network/the-pango-nomenclature-system/statement-of-nomenclature-rules/), new Pango lineages need to be associated with both an evolutionary event and an epidemiological event. These epidemiological events can include movement of the virus into a new geographical region, rapid and sustained growth in frequency compared to other co-circulating lineages, a jump into a novel host species and acquisition of a set of mutations of particular biological interest. Pango lineages therefore track more than just amino acid mutations

There doesn't seem to be a clear epidemiological event associated with this clade, we therefore haven't designated this at this point

**Comment by agamedilab** [comment]
1255 seq on Usher as of 27.06.22.

![grafik](https://user-images.githubusercontent.com/102166254/175917807-f2bad784-dd48-4f99-ae52-6eed66782ec6.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1c2a9_97e400.json?branchLabel=aa%20mutations&c=gt-N_33&label=nuc%20mutations:C5284T

Advantage versus global BA.5:

![grafik](https://user-images.githubusercontent.com/102166254/175917513-669d26ec-1904-4328-8512-d0ee0925d27c.png)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.5*&nucMutations1=G28371T&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

**Comment by agamedilab** [comment]
@FedeGueli Many thanbks for spotting this! I didnt notice that this is in fact N:S33F! Must be a bug in NExtclade for displaying this mutation (as it shows N:S33I on the tree while it is in fact N:S33F)?!

**Comment by AngieHinrichs** [comment]
Ah, the UShER tree masks out deleted bases 28362-28370 in the BA.1 and BA.2 branches (and the BA.5 branch is placed as an offshoot of BA.2), so it sees only G28371T, which by itself would cause N:S33I.  I have seen a lot of sequences that, based on lineage assignment, really should have a deletion but instead have reference bases and/or Ns and/or apparent substitutions that I think are symptoms of imperfect genome assemblies, so I mask deletion locations and sometimes adjacent bases that seem flaky.

G28371T appears in at least 3 branches in BA.5.2.1 in the UShER tree -- hard to tell whether it's homoplasy or inconsistent detection of G28371T in sequences.

The deletion of bases 28362-28370 appears to be in BA.5 too.  The deletion corresponds to N:G30 remaining a G, and the amino acids ERS deleted (N:31-33).  If I'm reading it correctly, the deletion of 28362-28370 would change the N:30 codon from GGA to GGU and then G28371T (G28371U really) would change the codon to GUU which is V.  So I think the combined effect is really N:30_33delGERSinsV not N:S33F or N:S33I, correct me if I'm wrong.

**Comment by agamedilab** [comment]
@AngieHinrichs many thanks for your sharing your insight!  I missed the importance of the deletions here!!!

In nextclade it looks like TTT (UUU) which is F?

![grafik](https://user-images.githubusercontent.com/102166254/178095871-20d91e42-8ec0-4e7e-b567-1ca74596adc7.png)

growth advantage vs BA.5 global 3 months:

![grafik](https://user-images.githubusercontent.com/102166254/178096141-8e0293fb-b982-4ea9-bff7-ce729d45c72e.png)


https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?aaMutations=N%3AS33F&nucMutations=C1627T&pangoLineage=BA.5*&aaMutations1=N%3AS33F&nucMutations1=C1627T&pangoLineage1=BA.5*&

2412 seqs. on covspectrum as of 09.07.22.

**Comment by AngieHinrichs** [comment]
> In nextclade it looks like TTT (UUU) which is F?

Interesting -- I'm using `mafft --keeplength` to align sequences, and it places the deletion one base to the left of where Nextclade is placing it:
```
2         2
8         8
3         3
6         7
0         0
TGGAGAACGCAGT
T---------TTT
```
so instead of the G28361T from Nextclade's alignment, mafft gives A28370T... but then I'm masking bases 28362 to 28370, so usher sees only G28371T not A28370T (nor G28361T because of the alignment).  Deletions make assembly trickier too, and compounded with ambiguities about where they align, it's really hard to get right.  But if the consensus genome sequence is correct with the two substitutions combined with the deletion, then yes, that would be an F not V.

**Comment by corneliusroemer** [comment]
We unfortunately started off right aligning deletions in case of
ambiguities in Nextclade and now it would be a big breaking change to left
align.

It's an option that was introduced in version 2 though and we'll stick to
the convention in future pathogens.

**Comment by agamedilab** [comment]
3839 seqs. on covspectrum as of 14.07.22.

growth advantage vs BA.5 global 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/178926702-f48e7c2e-0421-4010-92fc-325a88005488.png)
https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.5*&aaMutations1=N%3AS33F&nucMutations1=C1627T&pangoLineage1=BA.5*&analysisMode=CompareToBaseline&

**Comment by AngieHinrichs** [comment]
@corneliusroemer that's a perfectly reasonable default for nextclade, I didn't mean it as a criticism!  Ambiguity of alignment edges just goes with the territory of indels.

**Comment by Sinickle** [comment]
The two nucleotide mutations around the deletion here actually create a mutation on two adjacent AAs in ORF9b -- ORF9b:30L and ORF9b:29I. I think this might matter in the context of the apparent growth advantage this sublineage has.

**Comment by agamedilab** [comment]
@chrisruis @InfrPopGen @corneliusroemer this is now designated BF.7 (G28371T, see first post) please if you have time add the milestone to this issue (see also #855).  

![grafik](https://user-images.githubusercontent.com/102166254/180606564-dee508ba-487b-44c2-8267-8be2614c02ce.png)

**Comment by AngieHinrichs** [comment]
BF.7 is a sub-lineage of this proposed lineage -- it also has S:R346T, and was proposed in #827.  The table above only list the mutation(s) associated with the final node in the UShER tree at time of designation, not all the mutations that distinguish a new sublineage from its parent lineage.  The complete set of mutations that distinguish BF.7 from BA.5.2.1 in the UShER tree are 

G22599C (S:R346T) > C7528T > G28371T ("N:S33I" in UShER because of deletion-masking)

-- G28371T is the last of the three, so it is the one used in the table, but order of mutations is subject to change as new sequences are added to the tree (and occasionally some are removed) and the tree is re-optimized daily.

This reminds me of @corneliusroemer's recent request to document all of the mutations that separate a sublineage from its parent lineage...  sometimes there's only one, sometimes half a dozen!

**Comment by Sinickle** [comment]
This one is currently at around a 13% growth advantage over BA.5*, and makes up around 5.5% of global sequences currently.

**Comment by FedeGueli** [comment]
I just noticed and also @agamedilab noticed in the original proposal but then got lost in this proposal and in the two other BF.7 original proposal (mine that ignored N:S33X) and @Ryhisner that got it right, and then here @Sinickle noticed the Orf9b mutation coming because the complex del/Mut pattern in N in this branch) looking at the sequence it seem ALL this BA.5.2.1 branch has also G28361T in addition to G28371T and this would have explained why  CovSpectrum showed N:S33F and why @AngieHinrichs concluded it was N:S33V.
Now after two years it has popped up gain in a very fast XDK spotted, proposed and analyzed by @Over-There-Is 
first
https://github.com/sars-cov-2-variants/lineage-proposals/issues/1572
then:
https://github.com/cov-lineages/pango-designation/issues/2610

In that case it has no G28361T mutastion so the result is as @AngieHinrichs predicted to be for this one N:S33V.
