### ISSUE TITLE
Duplicate BA.2* at XAC in alias_key.json file

### ISSUE THREAD

**Issue by silenus092** [cov-lineages/pango-designation#758]
Hi everyone,

@akifoss 
We use your method to construct a parent-child relationship, and today we have the error 
```
aliases = pd.read_json(alias_file) <--- error raise at here
..
.
.
 raise ValueError("All arrays must be of the same length")

ValueError: All arrays must be of the same length
```
when we exam at alias_key.json file we saw the duplicated **BA.2***
`"XAC": ["BA.2*","BA.1*","BA.2*"].`

Are there any intentions to duplicate the lineage or accidentally added it?

Best regards

**Comment by corneliusroemer** [comment]
Hi @silenus092, I think this may be intentional - to show that there's a double breakpoint.
But this has not been done very consistently till now, since for example order has been ignored in the past.
I'll bring this up with the committee. For now you should probably just rewrite the script you're using to be able to deal with duplicates. I don't think we make any promises about the content of the alias.json list.

**Comment by InfrPopGen** [comment]
Hi @silenus092 @corneliusroemer I am sorry to hear that the change has impacted pipelines, but yes, this was intentional (to denote the presence of two break points). We decided to include all parents. It is unfortunate that in the past the parents have been given in alpha-numeric order, the system has been evolving and hopefully improving!
