### ISSUE TITLE
BA.2.10  sub lineage with S: T22N, S:L368I, S:N969S. (21 samples, India)

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#762]
Earliest sequence: 2022-05-28
Countries detected: India (21 seq)

Nucsubs :C9870A, C13170T, G19872T, C21627A, C22664A, A24468G, C27970T, C29218T, C29686T
ORF1ab:T3202K, T4302I
S:T22N, L368I, N969S
ORF8:T26I

Beside the RBD mutation in position 368 this lineage has a 2nd mutation in the codon of position 969 which was highlighted in @thomasppeacock in the paper linked bellow regarding the alternative entry mechanism :
https://www.biorxiv.org/content/10.1101/2021.12.31.474653v2.full.pdf

Usher build :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_382cd_8e7c70.json

Ref list :
[GISAID ref list.xlsx](https://github.com/cov-lineages/pango-designation/files/8906536/GISAID.ref.list.xlsx)

![image](https://user-images.githubusercontent.com/80166370/173761816-eedcc1c4-d02e-48eb-98fd-fd4501aa2875.png)

**Comment by silcn** [comment]
The correct mutation is S:969R. 969S would be the effect of the additional nucleotide mutation on its own.
In addition there is S:69/70del.

I noticed this one too, but I didn't submit it because from the ages in the metadata it looks like this was probably a single outbreak at an educational institution. The district this came from (Chengalpattu, Tamil Nadu) has a history of this: in early May there was a BA.2 cluster of about 50 sequences with S:W64R where once again the metadata pointed towards an outbreak at a university. That one artificially bumped the apparent proportion of S:W64R in India up to 9%, after which it dropped straight back down again.

I agree the mutations are interesting (in addition to the ones listed above it has S:69/70del too), but any analysis needs to take into account the targeted nature of the sequencing. If (and it's a big if) S:969R switches the entry mechanism back and leads to more severe disease, that might explain why this particular outbreak was sequenced.

**Comment by shay671** [comment]
For monitoring in CovSpectrum this query does the trick -

[3-of:C9870A, C13170T, G19872T, C21627A, C22664A, A24468G, C27970T, C29218T, C29686T]
