### ISSUE TITLE
Has BA.2.75 been released?

### ISSUE THREAD

**Issue by richardgoater** [cov-lineages/pango-designation#830]
Hi folks, we updated to pangolin 4.1.1 last Friday and we appear to have some samples matching the mutation profile in https://github.com/cov-lineages/pango-designation/issues/773, but they appear to be called as BA.2.7**3**.

I don't think I can see BA.2.75 in the release notes here: https://github.com/cov-lineages/pango-designation/releases

I can also see that CovSpectrum is showing nothing for BA.2.75: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2.75*&

Can you offer any guidance on this?

**Comment by ryhisner** [comment]
GISAID describes every BA.2.75 as BA.2.73. I have no idea why. As for CovSpectrum, it can be difficult to find all BA.2.75 sequences due to the high percentage of them that are low-coverage sequences, but @corneliusroemer shared this CovSpectrum advanced search query that appears to work fairly well: 

nextcladePangoLineage:BA.2* & [6-of:  S:I210V, S:G257S, S:D339H, S:G446S, S:N460K, S:K147E, S:W152R, S:F157L, ORF1a:S1221L]

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=nextcladePangoLineage%3ABA.2*+%26+%5B6-of%3A++S%3AI210V%2C+S%3AG257S%2C+S%3AD339H%2C+S%3AG446S%2C+S%3AN460K%2C+S%3AK147E%2C+S%3AW152R%2C+S%3AF157L%2C+ORF1a%3AS1221L%5D&

On GISAID, @silcn recently recommended searching for NSP3_S403L, NSP8_N118S

**Comment by AngieHinrichs** [comment]
There's a pipeline from pango-designation to lineages appearing in GISAID, with variable delays at each stage:

* First a lineage is officially designated by the addition of representative sequences to pango-designation/lineages.csv.  For BA.2.75 (#773), that happened on June 24 ([comment](https://github.com/cov-lineages/pango-designation/issues/773#issuecomment-1165610030)).
* At some point after that, a [release](https://github.com/cov-lineages/pango-designation/releases) is tagged on pango-designation.  The most recent release, [v1.11](https://github.com/cov-lineages/pango-designation/releases/tag/v1.11), was tagged on June 22.  So BA.2.75 missed v1.11 by a couple days, and will be in the next release which hasn't happened yet.
* After the pango-designation release is tagged, a new pangoLEARN model is trained and a new minimized version of the UCSC/UShER tree is generated for use by pangolin.  Testing and refinement of the model and tree can take a week or two.  Then a new release is tagged on pangolin-data with the new model and tree.
* After a new release of pangolin-data (and the optional cache repo, pangolin-assignment), running `pangolin --update-data` will install the new model and tree and then pangolin will be able to assign the lineages in the tagged release of pango-designation from which the new model and tree were built -- but not all of the brand new lineages that have been added to pango-designation in the meantime.
* It takes time for GISAID to re-run pangolin with the latest pangolin-data release on all of its sequences.

In the meantime, there's a variable but shorter delay from pango-designation to the UCSC/UShER tree: I try to annotate newly designated lineages on the tree within a day or two of designation.  Uploading sequences (or pasting sequence IDs) to the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) shows their placement in the tree and should result in more up-to-date lineage assignments.

> GISAID describes every BA.2.75 as BA.2.73. I have no idea why.

I haven't looked in detail at the sequences, but I bet this is happening because BA.2.73 was designated before the v1.11 tag (it was in pango-designation release [v1.10](https://github.com/cov-lineages/pango-designation/releases/tag/v1.10)) and is the most similar lineage in v1.11 for BA.2.75 sequences -- G22331A (S:G257S) is the defining mutation for BA.2.73, and is also found in BA.2.75 sequences, but not other BA* lineages so far.

**Comment by ryhisner** [comment]
Thank you for the very detailed explanation! Much appreciated.

**Comment by richardgoater** [comment]
Thanks very much indeed @AngieHinrichs, we'll await the next release patiently.

**Comment by karyakarte** [comment]
Thanks @AngieHinrichs! We caught all our BA.2.74, BA.2.75, and BA.2.76 on UShER. We found that out of 110 of our previously identified BA.2, after a re-run on UShER, showed 45 (40.91%) to be BA.2.74, 14 (12.73%) to be BA.2.75, 21 (19.09%) to be BA.2.76, and 30 (27.27%) remained BA.2. I am still doubtful of the remaining 30 BA.2, I will be re-running those now. Thanks again for the clarification.
