### ISSUE TITLE
BA.5 sublineage with ORF1a:I3758V mainly in genomes from Germany

### ISSUE THREAD

**Issue by akifoss** [cov-lineages/pango-designation#841]
**Sub-lineage of:** Potential new sublineage of BA.5
**Earliest sequence:** EPI_ISL_13351624 (06.04.2022, Indonesia)
**Most recent sequences:** EPI_ISL_13662398, EPI_ISL_13662402, EPI_ISL_13662397, EPI_ISL_13662399, EPI_ISL_13662401 (25.06.2022, Netherlands)
**Defining mutation:** ORF1a:I3758V

**Countries circulating**
    393 Germany
      84 Netherlands
      51 France
        3 Denmark
        1 South Africa
        1 Singapore
        1 Italy
        1 Indonesia
        1 Eswatini
        1 Belgium

**Sublineage composition**
    208 BA.5.1
    142 BE.1
      46 BA.5.2.1
      43 BA.5.3.2
      34 BA.5.3
      29 BA.5
      20 BA.5.2
       7 BF.1
       4 BA.5.5
       4 BA.5.3.1

**Genomes**

[BA5sublin-GISAID-ORF1a_I3758V-2022-07-13.txt](https://github.com/cov-lineages/pango-designation/files/9103063/BA5sublin-GISAID-ORF1a_I3758V-2022-07-13.txt)

**Evidence**

Genomes with this mutation are sitting on a long branch in a one-time constructed BA.5* phylogeny (top left corner):

![image](https://user-images.githubusercontent.com/22683250/178754358-019fd483-2d21-42bf-b655-76336fbc3fcb.png)

https://cov-spectrum.org/explore/Europe/AllSamples/Past6M/variants?aaMutations=ORF1a%3AI3758V&pangoLineage=BA.5*&aaMutations1=ORF1a%3AI3758V&pangoLineage1=BA.5*&

![image](https://user-images.githubusercontent.com/22683250/178752493-d5907b44-67b6-4b77-884a-561a18b7a7d0.png)

![image](https://user-images.githubusercontent.com/22683250/178752759-8ef9a14e-1d9c-4637-bbc8-62b10a4b3984.png)

**Comment by AngieHinrichs** [comment]
Caution... I've noticed that almost exclusively in Germany/RKI sequences, A11537G (ORF1a:I3758V) and T11524C occur together really frequently, but in sequences whose other mutations map them to many different branches of BA.2 and BA.5.  In other words, many different BA.2* and BA.5* lineages (and undesignated branches of BA.2) include a cluster of German sequences with A11537G and T11524C.  I wonder if there's some kind of systematic error behind that.

To illustrate a few of the many places I see this in the tree, here are Taxonium views, colored by country (darker green = Germany, bright green = Netherlands, purple = France), with blue circles around nodes with a change at 11537 (min 10 samples) and green circles around nodes with a change at 11524 (min 10 samples):

BA.5.3.2 (the second green circle is a reversion on 11524):
<img width="291" alt="image" src="https://user-images.githubusercontent.com/186983/178815383-2e3bc0e9-1640-4644-b97f-0720fbdc9c39.png">
BE.1.1 (BA.5.3.1.1.1):
<img width="688" alt="image" src="https://user-images.githubusercontent.com/186983/178815690-29f9f2c3-b4a2-46d5-a239-d1e32ef2eb1f.png">
BA.5.1:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/186983/178816111-80e558db-edf0-46d9-95e8-8919da2069d0.png">
BA.5.2.1:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/186983/178816412-8c6d1226-5357-4260-ac71-57f93b3001c6.png">
BA.2 + C25416T + C8092T + C2062T + C29420T:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/186983/178816677-7474cd52-bc5c-480f-af00-d78354cc1c29.png">
BA.2 + C22792T + G3692T + A25927G + C952T:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/186983/178817826-87d366a0-21b7-43c4-82d4-5720c74d48b0.png">
... and many more, you get the idea.

I'd be tempted to mask those two positions except A11537G is a BA.1 mutation and matters when detecting BA.1 / BA.2 recombinants, and some of those A11537G's could certainly be real.  I just think it's suspicious that A11537G and T11524C appear together in so many different branches, almost always from the same country (although TBF Germany does seem to have contributed an outsized share of BA.2 and BA.5 sequences, especially since UK testing dropped off).  Here's a zoomed-out country-colored view of BA.2 (and nested BA.5):
<img width="825" alt="image" src="https://user-images.githubusercontent.com/186983/178819999-6967e92f-aa9a-43cb-b3c6-d87565f9f03e.png">

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs i think ORF1a:I3758V is a known sequencing issue in Germany, if i dont recall badly @josetteshoenma digged a bit on it cause it appeared also in Netherlands and they solved it.

Wow, that's great, @JosetteSchoenma maybe you can help the RKI folks solve it too!  🙂

**Comment by JosetteSchoenma** [comment]
@AngieHinrichs @CoolenJordy actually fixed this, after we discussed it. He mentions it in his GitHub issue here.
https://github.com/JordyCoolen/easyseq_covid19/releases/tag/v0.9

Are you maybe in contact with the RKI?

**Comment by JosetteSchoenma** [comment]
Most Dutch sequences are from Microvida. I will try and contact somebody from that lab.
Note for me: ORF1a:I3758V = NSP6_I189V on GISAID.

**Comment by AngieHinrichs** [comment]
Ah, thanks @JosetteSchoenma (and @JordyCoolen)!  Looks like this commit changed a primer trimming region to start at 11520 instead of 11525, which would affect position 11524 too I suppose: https://github.com/JordyCoolen/easyseq_covid19/commit/e2412313ddaaf39a0b8014e4209d01c32a4d3245
Please do pass that on to anyone you know at RKI and I'll see if I can find contact info for someone there too!  Thanks!

**Comment by MarieLataretu** [comment]
Thanks to all for the input!

The RKI is in contact with the labs, see https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/27#issuecomment-1201352032

We were able to solve that with https://github.com/JordyCoolen/easyseq_covid19/commit/e2412313ddaaf39a0b8014e4209d01c32a4d3245!
