### ISSUE TITLE
Potential BF.5 sublineage with ORF1a:I2873V and ORF1b:S1273L (154 seqs. Denmark and Israel as of 2022-08-08)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#876]
There may be a BF.5 sublineage with ORF1a:I2873V (nucleotide A8882G) and ORF1b:S1273L (nucleotide  C17285T) originating in the Israel with rapid growth in Denmark.

As of  25 July 2022, Cov-Spectrum reports 102 BF.5+ORF1a:I2873V+ORF1b:S1273L sequences with 97 from Denmark and 5 from Israel.
![BF 5+ORF1a_2873V+ORF1b_1273L_Counts](https://user-images.githubusercontent.com/88959107/180893770-3eacd45b-6249-4ecc-ac1a-a60ddcaae166.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=ORF1a%3A2873V%2CORF1b%3A1273L&pangoLineage=BF.5*&

Cov-Spectrum calculates a growth advantage of  86% compared to BF.5*.
![BF 5+ORF1a_2873V+ORF1b_1273L_Growth](https://user-images.githubusercontent.com/88959107/180893624-ee918019-2ee8-4c94-9a00-9021f03f774a.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations1=ORF1a%3A2873V%2CORF1b%3A1273L&pangoLineage=BF.5*&pangoLineage1=BF.5*&analysisMode=CompareToBaseline&

UShER shows all of the GenBank samples are on a single subtree:
![BF 5+ORF1a_2873V+ORF1b_1273L_UShER](https://user-images.githubusercontent.com/88959107/180893526-a7aec6e5-58cb-4922-923c-0d79a0da90de.png)
To visualize on UShER: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BF.5%2BORF1a_2873V%2BORF1b_1273L.json

First Outbreak.info sequence: Israel 15 June 2022

First GenBank sequence: Denmark 23 June 2022 

Most recent GenBank sequence: Denmark 11 July 2022

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at 
[Support_BF.5+ORF1a_873V+ORF1b_1273L.zip](https://github.com/cov-lineages/pango-designation/files/9185453/Support_BF.5%2BORF1a_873V%2BORF1b_1273L.zip)

There may also be an intermediate lineage with just BF.5+ORF1a:I2873V.

Outbreak.info's Situation Report for this potential lineage is https://outbreak.info/situation-reports?pango=BF.5&muts=ORF1a%3AI2873V&muts=ORF1b%3AS1273L&selected=ISR&loc=ISR&loc=DNK&overlay=false

Edit: Corrected an errant date.

**Comment by alurqu** [comment]
Exploring the BF.5+BF.5+ORF1a:2873V+ORF1b:1273L growth advantage a little more, here's its growth versus BA.5 showing as of 25 July 2022:
![BF 5+ORF1a_873V+ORF1b_1273L_Growth_vs_BA 5](https://user-images.githubusercontent.com/88959107/180896466-52c55fad-fc0e-4820-a2a3-3c337eafc5bf.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=BA.5*&aaMutations1=ORF1a%3A2873V%2CORF1b%3A1273L&pangoLineage1=BF.5*&analysisMode=CompareToBaseline&

and then here is its growth advantage versus all of Omicron showing as of 25 July 2022:
![BF 5+ORF1a_873V+ORF1b_1273L_Growth_vs_Omicron](https://user-images.githubusercontent.com/88959107/180896572-185936f2-bc99-4409-9cf6-c180b08ef78f.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?pangoLineage=B.1.1.529*&aaMutations1=ORF1a%3A2873V%2CORF1b%3A1273L&pangoLineage1=BF.5*&analysisMode=CompareToBaseline&

**Comment by corneliusroemer** [comment]
You shouldn't use "World" when you derive growth advantages, it just biases towards countries that do more sequencing.

This looks like predominantly a founder effect in Denmark, not to say this shouldn't be a lineage but I'd no ascribe too much significance to these growth advantage plots.

**Comment by alurqu** [comment]
@corneliusroemer To answer your critique and focus on growth rates of this potential lineage in Denmark,

Cov-Spectrum calculates a growth advantage in Denmark of 69% compared to BF.5*:
![BF 5+ORF1a_2873V+ORF1b_1273L_Growth_Denmark](https://user-images.githubusercontent.com/88959107/181040225-7904ca71-79ea-4262-b230-0dc86c49a04f.png)
https://cov-spectrum.org/explore/Denmark/AllSamples/AllTimes/variants?aaMutations1=ORF1a%3A2873V%2CORF1b%3A1273L&pangoLineage=BF.5*&pangoLineage1=BF.5*&analysisMode=CompareToBaseline&

then versus BA.5* in Denmark:
![BF 5+ORF1a_2873V+ORF1b_1273L_Growth_vs_BA 5_Denmark](https://user-images.githubusercontent.com/88959107/181040255-77d9cc01-7bd1-49b5-875a-13f3b96e568b.png)
https://cov-spectrum.org/explore/Denmark/AllSamples/AllTimes/variants?pangoLineage=BA.5*&aaMutations1=ORF1a%3A2873V%2CORF1b%3A1273L&pangoLineage1=BF.5*&analysisMode=CompareToBaseline&

then versus all Omicron in Denmark:
![BF 5+ORF1a_2873V+ORF1b_1273L_Growth_vs_Omicron_Denmark](https://user-images.githubusercontent.com/88959107/181040314-c5fd5ece-d305-4aab-aaf7-92afb4657398.png)
https://cov-spectrum.org/explore/Denmark/AllSamples/AllTimes/variants?pangoLineage=B.1.1.529*&aaMutations1=ORF1a%3A2873V%2CORF1b%3A1273L&pangoLineage1=BF.5*&analysisMode=CompareToBaseline&

As to the possibility of a founder effect, I can only note that the GenBank data contains sequences for this potential lineage from all five administrative regions of Denmark.  There is also some developing genetic diversity.  The following are the novel mutations in this potential lineage beyond the common BF.5 mutations, ORF1a:I2873V, and  ORF1b:S1273L, from an amino acid substitution perspective:
Count   Novel Mutation
5       ORF1a:I3619T
2       S:P1162L
2       ORF1b:K417R
2       ORF1a:T1881I
2       N:A336V
1       S:T547I
1       S:P217S
1       ORF8:C102S
1       ORF3a:V29F
1       ORF1b:K82R
1       ORF1b:A370V
1       ORF1b:A1805V
1       ORF1a:V1118I
1       ORF1a:T163I
1       ORF1a:S1561P
1       ORF1a:R1404C
1       ORF1a:E87K

from a nucleotide substitution perspective:
Count   Novel Mutation
5       T11121C
5       C29311T
3       G5509A
2       C5907T
2       C29280T
2       C25047T
2       A14717G
1       T4946C
1       T24706C
1       G3617A
1       G29734T
1       G28198C
1       G25477T
1       C753T
1       C4475T
1       C27131T
1       C23202T
1       C22211T
1       C18881T
1       C14576T
1       C11074T
1       A4414G
1       A13712G

and from a nucleotide deletion perspective:
Count   Novel Mutation
2       509-523
1       519-524
1       135-138

and all of these novel mutations are from Danish sequences, so this potential lineage is at picking up some genetic diversity in Denmark.  Also, from checking https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants/international-comparison?pangoLineage=BF.5*, with 97 Danish sequences this potential lineage is less than a third of the 341 BF.5 sequences from Denmark.

**Comment by silcn** [comment]
I think it's good to mentally apply Bayes' Theorem in situations like this. If you see a new lineage with an apparent large growth advantage from a small number of sequences, that advantage is more likely to be sustained if the lineage has a few spike mutations including in the RBD than if it has no spike mutations. After all, if the growth advantage is real then there has to be a reason for it. I expect this is part of the reason why @corneliusroemer is suspicious about the growth advantage being real, though he doesn't mention it.

See #801 for an example of a lineage with no spike mutations that initially appeared to have a substantial advantage but eventually turned out not to. There are doubtless many more such examples.

That's not to say that non-spike mutations can't have an effect: after all, they must be responsible for the small advantage that BA.5 has over BA.4. But a 69% advantage would be (as far as I'm aware) unprecedented.

**Comment by alurqu** [comment]
@silcn While spike mutations can increase SARS-CoV-2 transmission by enhancing ACE2 binding and cell entry while assisting evasion of neutralizing antibodies, non-spike mutations have the potential to increase SARS-CoV-2 transmission through processes including but not limited to enhancing production of proteins that decrease the effectiveness of the innate immune system's antiviral interferon defenses (Thorne et al https://doi.org/10.1038/s41586-021-04352-y, Liu and Gack https://doi.org/10.1038/s41590-022-01148-8, Guo et al https://doi.org/10.1073/pnas.2203760119, Reuschl et al preprint https://doi.org/10.1101/2022.07.12.499603), and SARS-Cov-1 has several proteins known to effect the innate immune systems' interferon defenses in one way or another (DeDiego et al https://doi.org/10.1016/j.virusres.2014.07.024).  To quote Thorne et al discussing non-spike mutations in Alpha, “The importance of mutations outside the spike coding region in the adaptation of SARS-CoV-2 to humans is underscored by the observation that similar mutations exist in the N and Orf9b regulatory regions of the Delta and Omicron variants.”

Future data may yet reduce estimates of this potential lineage's growth advantage.  However, reductions from these estimates would still be reductions from high starting points, and with additional future data later estimates may remain high.

**Comment by corneliusroemer** [comment]
@silcn Yes indeed, I may be missing something but I don't think we've seen huge growth advantages based on a few small mutations - though it is possible that a deleterious mutation gets reverted  - but that may actually happen much faster (given how many times we see the same Spike mutations in BA.5 already).

Also, there's an observer bias. There will, just by pure chance, be lineages with apparent growth advantages.

That's why it's good to wait a week or two after the initial report to see how things go. From the date of report, the observer bias is removed (unless there's something systematic going on, like sampling, but that would also go away over time).

**Comment by silcn** [comment]
@alurqu yes, I'm aware that there is plenty of evidence for some non-spike mutations being advantageous to the virus, and there's clear evidence for selection at N:202-205, the nsp6 deletions, etc. In fact, most lineages with a large advantage have included potentially advantageous mutations outside the spike (BA.1.1 and BA.2.12.1 being notable exceptions). But as far I know we have yet to observe a *large* growth advantage resulting *only* from mutations outside the spike. That doesn't mean it isn't possible, and so it's important to monitor this lineage! 

But each time previously that a lineage without any additional spike mutations has popped up with a large apparent growth advantage, the advantage has eventually turned out to be much smaller or nonexistent. (21J had a 25-30% advantage vs other Delta but that wasn't just a couple of mutations) Maybe this is the one that's different! Though from a public health perspective I hope it isn't.

**Comment by FedeGueli** [comment]
I think looking at the AY.s stuff  where Delta Spike seemed to be 'optimized' still biggest jump have been seen with spike mutations (501S, 145H+222V, 414X , 354) but also we have seen a few mutations with apparent boosting effect outside the spike (as AY.122, AY.36.1, AY.43, AY.46.6, AY.103) but limited to an extra +10-15% in trasmissibility. @silcn @corneliusroemer @alurqu

**Comment by alurqu** [comment]
As predicted by @corneliusroemer, the growth advantage over BF.5 for this potential lineage in Denmark has indeed dropped substantially.  However, it is still showing at 19%.
![BF 5+ORF1a_2873V+ORF1b_1273L_Growth_Denmark_20220801](https://user-images.githubusercontent.com/88959107/182207576-bc476973-5629-4cc8-ad89-33305b318783.png)

Current sequence counts are 133 in Denmark and 6 (one more) in Israel.

**Comment by alurqu** [comment]
As foreseen by @corneliusroemer and @silcn, this lineage now appears to be slightly under-performing its parent BF.5 with CoV-Spectrum showing a -1% growth advantage versus BF.5 in Denmark.  Consequently, I will close this proposal.
