### ISSUE TITLE
BA.2 in India with 8 spike mutations [12 sequences]

### ISSUE THREAD

**Issue by Sinickle** [cov-lineages/pango-designation#877]
This was noticed by @Ryhisner when it was just 2 sequences due to its unusual mutation profile, but there are now 9 sequences, found so far in the Indian states of Maharashtra and Telangana. 

**Earliest sequence: June 6**
**Second sequence: June 23**

The main reason for proposing this sublineage is the unusual spike profile. 

Mutations beyond BA.2 are present in 3+ sequences, and 100% of them that don't have the region dropped out:
<html>
<body>

Gene | Mutation
-- | -- 
ORF1a | P1640H
S | W64R, G75V, S:138-144del, S:242-243del, R493Q, T572N, D843G, Q1113R

</body>
</html>

Notably, there is some difficult with identifying what mutations are present, due to dropout. Just looking at the spike mutations.. 

- The only one that has S:137-144 present has S:138-144del. 

- Of the 2 that have S:241-243 present, one of them has S:242del, and both have S:243del.

- 3/6 that have S:440 present have S:440N, the other 3 have S:440K.

- One of them with S:440K has S:S443L and S:K444R.

- 3/3 of them with S:493 have S:493Q

- 2/8 that have S:526 present, have S:G526R. One of these has S:V327P. 

**[Cov-Spectrum Query](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A75V%2CS%3A572N%2CS%3A843G%2CS%3A1113R%2CS%3A64R&)**

**EPI_ISL IDs:** EPI_ISL_13988810, EPI_ISL_13422063, EPI_ISL_13988950, EPI_ISL_13611346, EPI_ISL_13988817, EPI_ISL_13847300, EPI_ISL_13847296, EPI_ISL_13988940, EPI_ISL_13988781

I would like to additionally thank @chaoran-chen, for creating [collections](https://cov-spectrum.org/collections/14) on cov-spectrum, which has made it very easy to throw these odd sequences onto a list and be alerted if any more sequences like them show up!

Edit: With new samples coming in, it appears that the S:138-144 del is legitimate, as well as the S:242-243del.

**Comment by ryhisner** [comment]
Two more sequences of this uploaded today from India, Telangana, Hyderabad. 

EPI_ISL_14196487
EPI_ISL_14196544

These are higher quality than most previous ones, and both have S:138-144del and S:242-243, so these deletions are very likely shared by the other sequences, which didn't have coverage in this area. Both have ORF1a:A3730V, not found in any of the previous sequences, and ORF1a:3675-3677del, which was in just one previous sequence. Below is the spike profile from all 11 sequences as they appear on NextClade, with the two newest ones at the bottom.

![Screen Shot 2022-08-02 at 1 21 57 PM](https://user-images.githubusercontent.com/33738461/182436292-fbc039ce-a434-462b-8a09-fe5ba4afe7cb.png)

Usher puts these two in an entirely different tree from all the others, but that's due to the very low coverage of the others. They clearly belong together. 

Subtree #1 (with 9 of the 11 sequences): https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_14e50_95a990--9-of-11.json
![Screen Shot 2022-08-02 at 1 25 07 PM](https://user-images.githubusercontent.com/33738461/182436613-dc9cdc9e-8c7e-46bb-84b5-1561fd6f126d.png)


Subtree #2 (with 2 most recent sequences): https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/subtreeAuspice1_genome_428ba_95c510--2-New.json
![Screen Shot 2022-08-02 at 1 27 55 PM](https://user-images.githubusercontent.com/33738461/182437041-6183e997-b14a-4d53-ba9f-45ad27a9ddb4.png)

**Comment by Sinickle** [comment]
EPI_ISL_14502420 -- US sequence from 8/4. No new spike mutations.
