### ISSUE TITLE
BA.5.2 sublineage with S:K444M (148 seq. as of 21.08.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#924]
Proposal for a sublineage of BA.5.2
Earliest sequence: 15.06.2022 (Japan)
Countries detected: Austria, Belgium, Denmark, England, Finland, France, Germany, Greece, Hong Kong, Israel, Japan, Netherlands, Pakistan, Scotland, Slovakia, Turkey, United Kingdom, USA, Wales

Defining mutations:
A22893T = S:K444M
T2058C = ORF1a:M598T
C17958T

This variant is defined by S:K444M, ORF1a:M598T, C17958T and was first detected in Japan. Now it is present in 19 countries. 76 seq on Usher as of 10.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/183881666-c784abe4-7fb3-4b5e-80c9-57484c6aa5fb.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_daec_387a00.json?branchLabel=aa%20mutations&c=gt-nuc_22893,2058&label=nuc%20mutations:C17958T

EPI_ISL_13463983, EPI_ISL_13565965, EPI_ISL_13604922, EPI_ISL_13727149, EPI_ISL_13727152, EPI_ISL_13729640, EPI_ISL_13729814, EPI_ISL_13766463, EPI_ISL_13802459, EPI_ISL_13827313, EPI_ISL_13846135, EPI_ISL_13886940, EPI_ISL_13906834, EPI_ISL_13925714, EPI_ISL_13933213, EPI_ISL_13933456, EPI_ISL_13937067, EPI_ISL_13938688, EPI_ISL_13939289, EPI_ISL_13944456, EPI_ISL_13944907, EPI_ISL_13946712, EPI_ISL_13946963, EPI_ISL_13958704, EPI_ISL_13963797, EPI_ISL_13985712, EPI_ISL_13985752, EPI_ISL_13985849, EPI_ISL_13985853, EPI_ISL_13989820, EPI_ISL_14030581, EPI_ISL_14030590, EPI_ISL_14052745, EPI_ISL_14062993, EPI_ISL_14071648, EPI_ISL_14072783, EPI_ISL_14091451, EPI_ISL_14101585, EPI_ISL_14138821, EPI_ISL_14139383, EPI_ISL_14170744, EPI_ISL_14181932, EPI_ISL_14182421, EPI_ISL_14185017, EPI_ISL_14191404, EPI_ISL_14197196, EPI_ISL_14207240, EPI_ISL_14215401, EPI_ISL_14215410, EPI_ISL_14217433, EPI_ISL_14217694, EPI_ISL_14217694, EPI_ISL_14261389, EPI_ISL_14266844, EPI_ISL_14294623, EPI_ISL_14304631, EPI_ISL_14311114, EPI_ISL_14312898, EPI_ISL_14317862, EPI_ISL_14320149, EPI_ISL_14320150, EPI_ISL_14320239, OX218757.1, OX247989.1

Growth advantage vs. BA.5.2 Europe 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/183882694-12dd81dc-6680-4a58-857a-f0337a62d726.png)
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?pangoLineage=BA.5.2*&aaMutations1=S%3AK444M%2CORF1a%3AM598T&nucMutations1=C17958T&pangoLineage1=BA.5.2*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
@ryhisner spotted this top and we were monitoring it since. I would like to see if its remarkable advantage will be mantained or start to decline as we have seen multiple times.
One thing that makes me think it could be real is that the sequences are sparse and the tree shows quite a lot of diversity.

**Comment by ryhisner** [comment]
Important to note that 10 of the 58 sequences returned by GISAID query "NSP2_M418T, Spike_K444M" are from Pakistan and that all four sequences of this sublineage from Japan—including that June 15, EPI_ISL_13565965—were detected by airport surveillance and had travel history in Pakistan. This sublineage most likely originated in Pakistan (or a nearby country with no sequencing), and is almost certainly more prevalent there than anywhere else. One sequence from Lahore, Pakistan—EPI_ISL_13728988—has a collection date of January 26, 2022 listed, but I think this has to be a data entry error.

**Comment by agamedilab** [comment]
124 seq. on usher as of 17.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/185048751-51d5b366-5268-4fab-9a8e-78f8d1b1e169.png)

Growth advantage vs. BA.5.2 Europe 3 months:
![grafik](https://user-images.githubusercontent.com/102166254/185049019-ee480378-4c58-4be1-906a-a21457d95ee9.png)
https://cov-spectrum.org/explore/Europe/AllSamples/Past3M/variants?pangoLineage=BA.5.2*&aaMutations1=S%3AK444M%2CORF1a%3AM598T&nucMutations1=C17958T&pangoLineage1=BA.5.2*&analysisMode=CompareToBaseline&

**Comment by FedeGueli** [comment]
Along with BH.1 and BE.1.1 plus S:444T proposed in #931 this is the only one lineage with more than 100 Sequences with a growth rate superior to BA.2.75 baseline (without additional spike mutation).
But if that  comparison is too spurious and it will become clearer in the next few weeks , what struck me since the start is the growth advantage versus BA.5.2 with orf1b:1050N that is the most transmissible among the biggest BA.5 branches and it is leading  BA.5.2 to global dominance (>50%) over all the other circulating lineages.
![Schermata 2022-08-21 alle 00 42 54](https://user-images.githubusercontent.com/87669813/185768453-4bd1b1c2-9400-4056-be87-ada23bced74a.png)

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=Nextcladepangolineage%3ABA.5.2*+%26+Orf1b%3A1050N&variantQuery1=Nextcladepangolineage%3ABa.5.2*+%26+S%3AK444M&analysisMode=CompareToBaseline&

**Comment by agamedilab** [comment]
148 seq on usher as of 21.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/185777958-0fbad93e-12e9-422a-a78d-550267fa2450.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_21e2b_1ca490.json?branchLabel=aa%20mutations&c=country&label=nuc%20mutations:A22893T

**Comment by shay671** [comment]
This variant has six mutations over BA.5.2:
 A22893T
C16616A
C17958T
C27513T
T2058C
C27012T

But I assume the S: K444M (A22893T) that defines it?
@corneliusroemer @ryhisner

**Comment by AngieHinrichs** [comment]
> This variant has six mutations over BA.5.2:

I also get G12310A (common in BA.5.2 but not in BA.5.2.1).  And yes, A22893T is the final/defining mutation.
