### ISSUE TITLE
Potential BA.5.2 + ORF1b:T1050N Sublineage with ORF1a:T1022I (Global spread, 1929 seqs as of 2022-09-16)

### ISSUE THREAD

**Issue by alurqu** [cov-lineages/pango-designation#945]
There may be a BA.5.2 sublineage with ORF1a:T1022I (C3330T) first detected in Germany.

As of 2022-08-13, Cov-Spectrum reports 764 BA.5.2+ORF1a:1022I sequences:
![BA 5 2+ORF1a_1022I_Counts_20220813](https://user-images.githubusercontent.com/88959107/184504368-c09e4a30-bb0c-4525-960a-f899e3ce8e65.png)
Source: https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AT1022I&

As of 2022-08-13, Cov-Spectrum calculates strong growth advantages compared to BA.5.2* and BA.5* in the USA:

Relative to BA.5.2* in the USA: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.2*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AT1022I&analysisMode=CompareToBaseline&

Relative to BA.5* in the USA: https://cov-spectrum.org/explore/United%20States/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5*&variantQuery1=nextcladePangoLineage%3ABA.5.2+%26+ORF1a%3AT1022I&analysisMode=CompareToBaseline&

As of 2022-08-13, UShER shows most of the GenBank samples on a single subtree with a few failing on other subtrees:
![BA 5 2+ORF1a_1022I_UShER_Subtree1_20220813](https://user-images.githubusercontent.com/88959107/184504429-fcfe47a1-717a-41e3-bb7d-402473503b21.png)
To visualize the main UShER subtree: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_genome_BA.5.2%2BORF1a_1022I.json?c=userOrOld

To visualize the other minor UShER subtrees:
https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice2_genome_BA.5.2%2BORF1a_1022I.json?c=userOrOld
https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice3_genome_BA.5.2%2BORF1a_1022I.json?c=userOrOld
https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice4_genome_BA.5.2%2BORF1a_1022I.json?c=userOrOld

To visualize all of the UShER subtrees in the down-sampled tree:
Zoomed-In:
![BA 5 2+ORF1a_1022I_UShER_Single_Subtree_Zoomed-In_20220813](https://user-images.githubusercontent.com/88959107/184504452-2f4c34e9-a5c1-4ea7-92d8-0f2ebbd4e793.png)
Zoomed-Out:
![BA 5 2+ORF1a_1022I_UShER_Single_Subtree_Zoomed-Out_20220813](https://user-images.githubusercontent.com/88959107/184504462-109189a4-972c-4811-bfda-56e599980dd1.png)
https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/singleSubtreeAuspice_genome_BA.5.2%2BORF1a_1022I.json?c=userOrOld

Please note that this proposal is intended for the main subtree only.

First Outbreak.info sequence: Germany 2022-05-17 

First GenBank sequence: Zürich, Switzerland 2022-06-11 

Most Recent GenBank sequence: Mississippi, USA 2022-08-03

A zip archive of GenBank-formatted and derived metadata and FASTA files plus UShER output files for these sequences is available at 
[Support_BA.5.2+ORF1a_1022I.zip](https://github.com/cov-lineages/pango-designation/files/9331907/Support_BA.5.2%2BORF1a_1022I.zip)

The Outbreak.info link for this potential lineage is https://outbreak.info/situation-reports?pango=BA.5.2&muts=ORF1a%3AT1022I.

**Comment by FedeGueli** [comment]
@alurqu i would add that this one is a sublineage of BA.5.2 + Orf1b:1050N , 
When comparing it on a global landscape its advantage vs orf1b:1050n goes near 0 but in Usa it remains quite significant. Maybe we could monitor it here for a while.

**Comment by alurqu** [comment]
@FedeGueli I had missed that this was a sublineage of BA.5.2 + Orf1b:1050N.  I'll update the title.

Since this sublineage shows a significant growth advantage over BA.5.2 + Orf1b:1050N in the USA, and since the USA has much of the most recent sampling reported in GenBank, yes I assess that this sublineage may merit continued monitoring.

**Comment by FedeGueli** [comment]
Thx @alurqu for adding.  I didnt know United States had a preference upload to GenBank, Do you have an idea on the delay?

**Comment by corneliusroemer** [comment]
Thanks - it's a good idea to break down the BA.5.2 + ORF1b:1050N polytomy to reduce unspecific BA.5.2 calls.

This lineage seems most common in Thailand.

Please designate @InfrPopGen @aq-sun

I've designated two large lineages without proposal that were also on that polytomy. That should help make analysis of sequences in that part of the tree easier in the future.

**Comment by AnonymousUserUse** [comment]
Is it really meaningful to designate the lineage C23707T on the branch BA.5.2 + ORF1b:T1050N, as well as the lineage C5284T on the branch BA.5.2 + ORF1b:T1050N? C23707T and C5284T are both synonymous mutations (do not fulfill the designation criterion 1b), and do not show any growth advantage. BA.5.2 + ORF1b:T1050N + C23707T has a geographical focus in northern Africa, while BA.5.2 + ORF1b:T1050N + C5274T do not even reach the border line 5% for a geographical focus. 
I agree with the view that a parent lineage of several sublineages may be designated even if the parent lineage does not fully meet the designation criterions, but the presence of a parent lineage itself should not be sufficient to designate as an explicit lineage. 
Specifically, the designation of a lineage with geographical focus with a synonymous mutation as defining mutation does not bring much, but makes the name a step longer; the use of alias can shorten the name, but it is difficult to remember all those alias that is not used so frequently.  
So I suggest to withdraw BA.5.2.20 and BA.5.2.21.

**Comment by corneliusroemer** [comment]
Yes it is meaningful, because otherwise a large chunk of sequences is BA.5.2 - some with the important ORF1b:T1050N, some without.

Designating diversity makes it clear what clusters together and what doesn't. If you see a bunch of BA.5.2 with S:460K it's not immediately clear whether they are related. But now if they all are BA.5.2.20 then you know immediately that they are clustering.

Also, you're not right about the name getting longer. In fact, in this case it makes the name of sublineages shorter. They'd get an alias. You can see what the aliases stand for by using the BA.2 dataset on Nextclade, which has an unaliased column: 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/25161793/190922787-283ad398-1d31-4524-a67b-d2b77b5a04f5.png">

In the end most non-synonymous mutations aren't that meaningful in themselves either, as they hardly change anything. A lot of lineage designations are useful just to see what shared a recent common ancestor, and what didn't. If you see BA.5.2.20 now, you know much more than if it didn't exist.

Both .20 and .21 make up a decent share of that branch with ORF1b:1050N - so being able to give these a name _is_ useful.

**Comment by FedeGueli** [comment]
@corneliusroemer it is enough to look.at C25416T branch of BA.2  to see that sometimes Nuc had an impact too.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=25416T&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&

**Comment by AnonymousUserUse** [comment]
@corneliusroemer
I understand the sense of recent common ancestors. But is it necessary to designate _all_ recent common ancestors and make the unaliased form of the name longer and longer? It seems for me to be more counterproductive.

We have to compromise the length of the unaliased lineage name and the information that is given in the lineage name. I suggest to keep the rule that a lineage will only be designated if there is at least one nonsynonymous mutation or recombination.

I would take BA.2 + C22792T (geographical focus in Denmark and other European countries) as exemple: though the designation of this lineage can make the phylogeny a little bit more clearly, it makes the name unnecessarily longer and brings extra alias for BA.2.9.1, BA.2.13.1, and BA.2.25.1. I think the decision of not designating BA.2 + C22792T was good.

I know that homoplastic mutations may occur more than one time within a lineage if a sublineage cannot be designated because of the restriction of nonsynonymous mutation. It is confusing to some extent, but does not harm much.

Nevertheless, it is the decision of Lineage Designation Committee to designate a lineage or not. The current rule of designating lineage does not regard a recent common ancestor of several sublineages as a designation criterion, and requires a nonsynonymous mutation for the designation. A discussion whether to designate a recent common ancestor without a nonsynonymous mutation as a defining mutation should be done within Lineage Designation Committee if this has not happened, and the rule of designating lineage may be changed accordingly.

**Comment by AnonymousUserUse** [comment]
@FedeGueli 
The property of a variant is not determined by a single mutation (regardless of synonymous mutation or nonsynonymous mutation), but by the combination of all mutations together. The change of prevalence of the variant defined by nuc:C25416T is apparently driven by the increase and the drop of the lineage BA.2.12.1.

**Comment by FedeGueli** [comment]
> @FedeGueli The property of a variant is not determined by a single mutation (regardless of synonymous mutation or nonsynonymous mutation), but by the combination of all mutations together. The change of prevalence of the variant defined by nuc:C25416T is apparently driven by the increase and the drop of the lineage BA.2.12.1.

i was not referring at prevalence that is biased by sequencing intensity
 but at the fact it is the parent branch of BA.2.12.1, BA.2.75,  BA.2.38 all lineages able to become dominant at least in one big country and orher interesting one as BA.2.74 and BA.2.76.
And instead of you i think one single mutation can enavvle or tolerate more beneficial (or evading) mutation. So every single mutation counts. You can just give weigh to the potential effect of a mutation based on papers or historical success/unsuccess.

**Comment by AnonymousUserUse** [comment]
> > @FedeGueli The property of a variant is not determined by a single mutation (regardless of synonymous mutation or nonsynonymous mutation), but by the combination of all mutations together. The change of prevalence of the variant defined by nuc:C25416T is apparently driven by the increase and the drop of the lineage BA.2.12.1.
> 
> i was not referring at prevalence that is biased by sequencing intensity but at the fact it is the parent branch of BA.2.12.1, BA.2.75, BA.2.38 all lineages able to become dominant at least in one big country and orher interesting one as BA.2.74 and BA.2.76. And instead of you i think one single mutation can enable or tolerate more beneficial (or evading) mutation. So every single mutation counts. You can just give weigh the potential effect of a mutation based on papers or historical success/unsuccess.

The prevalence of nuc:C25416T is not mainly biased by sequencing intensity, but biased by the change of the prevalence of variant containing nuc:C25416T.
It is interesting to note that BA.2.12, BA.2.38, BA.2.74, BA.2.75, BA.2.76 are all sublineages of BA.2 + C25416T, but I think it is hard to prove whether C25416T has some specific property or it is just coincidence. It is to consider that BA.2.38, BA.2.74, BA.2.75, BA.2.76 are all developed in India where BA.2 + C25416T contributes to ~50% of BA.2.

**Comment by InfrPopGen** [comment]
Thanks for submitting. We've added lineage BA.5.2.22 with 1209 newly designated sequences, and 11 updated designations from BA.5.2.21, one from BA.5.2.16, and 87 from BA.5.2. Defining mutation C3330T (ORF1a:T1022I), which followed C27012T and C27513T.

**Comment by jinyu-ncbi** [comment]
From the data we have at NCBI, it seems C27012T and C27513T evolved before C3330T. The two mutations C27012T and C27513T are found in the following lineages: BA.5.2.3, BA.5.2.6-8, BA.5.2.13-16, BA.5.2.18-22. It would be more convenient if a sublineage were created for these mutations.

**Comment by jinyu-ncbi** [comment]
From the data we have at NCBI, the following lineages all have mutations C27513T and C27012T: BA.5.2.3, BA.5.2.6-7, BA.5.2.13-16,, BA.5.2.18-22. Also these lineages and BA.5.2.2 were probably evolved from a common ancestor with mutations G12310A and C16616A. It would be convenient if lineages were designated to these common ancestors.

**Comment by FedeGueli** [comment]
> From the data we have at NCBI, the following lineages all have mutations C27513T and C27012T: BA.5.2.3, BA.5.2.6-7, BA.5.2.13-16, BA.5.2.18-22. Also these lineages and BA.5.2.2 were probably evolved from a common ancestor with mutations G12310A and C16616A (ORF1b:T1050N). It would be convenient if lineages were designated to these common ancestors.

@jinyu-ncbi 

It was proposed very early by @agamedilab but never got designated then i tried a last attempt to adjust proposing to broaden BA.5.2.2 starting with Orf1b:1050N but that was made imossible cause BA.5.2.6 and .7 got designated quite immediately after i opened that issue. So since it would have been a real mess to withdrawn every designated lineage with orf1b:1050N to designate it as independent branch (As it is , clearly).

**Comment by alurqu** [comment]
@jinyu-ncbi, to extend @FedeGueli's response, as I understand it the current practice is to generally not designate branches marked solely by synonymous nucleotide mutations.  While I agree that 27513T and 27012T appear to have occurred between C16616A (ORF1b:T1050N) and C3330T (ORF1a:T1022I), this rule would have prevented or at least discouraged designation of BA.5.2+ORF1b:T1050N+27513T+27012T on its own.

Regarding the positioning of 27513T and 27012T, if you inspect the tree https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/singleSubtreeAuspice_genome_BA.5.2%2BORF1a_1022I.json?branchLabel=nuc%20mutations&c=userOrOld&label=nuc%20mutations:C1627T,A28330G from my original submission with branches labeled and zoomed in, you will see that 27513T and 27012T are the branches between C16616A and C3330T.

I'd also like to note that Delta has contained structure not captured in the pando designations.  If there was (or is) any pango designation structure capturing the distinction between Delta's [Nextstrain clades](https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/06-clade-assignment.html) 21A, 21I, and 21J, I am not aware of it at this time.  Furthermore, while [Stern et al](https://doi.org/10.1101/2021.08.05.21261642) proposed the existence of five distinct Delta clades, I'm not aware of a simple way to determine those clades by the AY.* pango Delta sublineage designations.   So this is not the first time that situation like this one has happened.

Finally, please be aware that some contributors such as myself, @FedeGueli, and @ryhisner are unpaid volunteers contributing as we have time available.  My input ends with submitting these issues and comments.  Lineage designations and the related rules are governed by the [Pango and Lineage Designation Committee](https://www.pango.network/committees/committee-structure/), and lineage designation process adjustments might be best addressed in those environments.  To the members of both committees: Thank you for your work!
