### ISSUE TITLE
BA.2.75.3 sublineage with S:F486S, ORF1a:Q1198K (23 seq. India, Singapure, Australia, Israel, Belgium, USA. 21.08.22)

### ISSUE THREAD

**Issue by agamedilab** [cov-lineages/pango-designation#957]
Proposal for a sublineage of BA.2.75 on ORF1b:V1706I branch (see #965)
Earliest sequence: 20.07.2022 (India)
Countries detected: India, Singapure, Australia

GISAID query: `NSP3_Q380K, Spike_F486S`

Defining mutation:
G18583A = ORF1b:V1706I 
T23019C = S:F486S
C3857A = ORF1a:Q1198K 

Currently there are c. 34 BA.2.75 genomes with S:F486S on GISAID which apparently arose multiple times independently (convergence).  Here I am proposing one of the bigger clusters defined by S:F486S, ORF1a:Q1198K.  The cluster is apparently distinct from those mentioned in  #944. However one of the sequences (EPI_ISL_14303286) was mentioned in #918.
7 seq on usher as of 17.08.22.

![grafik](https://user-images.githubusercontent.com/102166254/185068641-9d1dac9d-bb31-4fc5-8dbe-11016aba1332.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_f031_c99030.json?branchLabel=aa%20mutations&c=gt-S_486&label=nuc%20mutations:C3857A

![grafik](https://user-images.githubusercontent.com/102166254/185069174-a5e38287-2f3e-4dea-b3c7-55b1f0c0245f.png)

![grafik](https://user-images.githubusercontent.com/102166254/185069509-c5068fac-5fa9-4f3c-aba1-2ac4392b595b.png)
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=ORF1a%3AQ1198K%2CS%3AF486S&pangoLineage=BA.2.75*&

EPI_ISL_14228614
EPI_ISL_14303286
EPI_ISL_14355866
EPI_ISL_14434640
EPI_ISL_14445845
EPI_ISL_14458973
EPI_ISL_14458981

**Comment by agamedilab** [comment]
2 more sequences (EPI_ISL_14496326, EPI_ISL_14496331) from Israel today forming a subclade containing S:F490S. Also i a reversion ORF1a:K1198Q. If this subclade become dominant for the group than ORF1a:Q1198K is likely not a good defining mutation.

![grafik](https://user-images.githubusercontent.com/102166254/185158484-6e9c6454-468f-44b3-b168-7610454efa69.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_10665_cf6f60.json?branchLabel=aa%20mutations&c=gt-nuc_23019&label=nuc%20mutations:T23019C

**Comment by silcn** [comment]
I first mentioned the 346T+486S+490S cluster in #918 when it consisted of two sequences from West Bengal that are misplaced by Usher because of some artefactual reversions. The Israel and Singapore sequences cluster with these two once they are cleaned up.

I think the apparent ORF1a:Q1198K reversion is actually a sign that these 4 sequences don't belong in this lineage. ORF1a:Q1198K = C3857A is listed as homoplasic by Usher, but I'm not sure why, as mutations at 3857 are pretty rare. On the other hand, we already have plenty of evidence that S:R346T and S:F486S are highly homoplasic within BA.2.75. In my opinion, it's therefore much more likely that the 346T+486S+490S branch is an independent lineage, possibly part of #918 (BA.2.75+ORF1b:V1706I+S:R346T).

**Comment by agamedilab** [comment]
Hi @silcn many thanks for your comment! 

There are only 2 sequences ( = the new Israel and Singapure sequences EPI_ISL_14496326, EPI_ISL_14496331) in the proposed lineage that share the "346T+486S+490S combo" mentioned in #918. However those 2 sequences additonally carry G261A which is apparently not present in the combo sequences of #918. Therefore I believe that they probably arose independently.

Also the sequences of issue #918 currently do not cluster together with those of this issue #957. When i perform a Usher search with both sets combined the sequences end up on two distinct clades:

#918
EPI_ISL_14049579
EPI_ISL_14101261
EPI_ISL_14175839
EPI_ISL_14215511
EPI_ISL_14215585
EPI_ISL_14295558
EPI_ISL_14302969
EPI_ISL_14175700
EPI_ISL_14303178

#957
EPI_ISL_14228614
EPI_ISL_14303286
EPI_ISL_14355866
EPI_ISL_14434640
EPI_ISL_14445845
EPI_ISL_14458973
EPI_ISL_14458981
EPI_ISL_14496326
EPI_ISL_14496331

![image](https://user-images.githubusercontent.com/102166254/185319792-2922fd15-1c89-4eb2-853f-1660413b4276.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3d036_dda470.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G18583A

As a consequence I would like to keep the issue open for the time being. However if it turns out to be a dupliicate i see no problem in closing it.

**Comment by silcn** [comment]
@agamedilab this issue is fine. This and #918 are separate. It's only the position of the four 346T+486S+490S sequences that I disagree on: the Israel and Singapore sequences, and EPI_ISL_14175700 and EPI_ISL_14303178 from West Bengal.

EPI_ISL_14175700 and EPI_ISL_14303178 are currently placed in a totally different position on the tree from both this lineage and #918. That is because they are fairly poor quality and both have artefactual reversions in the S:371-376 region; they get placed with other sequences which have similar artefacts. They both have NNNs at nuc:261 so they could still have G261A, but in any case that would be a poor argument for independent acquisition unless there was a larger branch with G261A but not S:486S+S:490S. In fact, there is a third West Bengal sequence listed in #918, namely EPI_ISL_14302969, which has S:346T and nuc:G261A, plus NNNs at S:482-491 so it could also have S:486S and S:490S.

When proposing #918 I edited the fastas to remove the artefactual reversions and get Usher to place the sequences properly. Once I've done that, EPI_ISL_14175700 and EPI_ISL_14303178 cluster with the Israel and Singapore sequences, and EPI_ISL_14302969 is pulled in and placed immediately before the S:F490S branch. Usher still puts the whole cluster in what I believe to be the wrong place: have them branch off #918 before the acquisition of nuc:C28657T and you don't need a highly unlikely reversion to explain what happened.

<img width="599" alt="BA275_F490S" src="https://user-images.githubusercontent.com/42699509/185383927-923edfed-e786-4ae9-85df-7a1d6ec74981.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2cf39_e1d780.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:C3857A](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_2cf39_e1d780.json?branchLabel=aa%20mutations&c=userOrOld&label=nuc%20mutations:C3857A)

**Comment by corneliusroemer** [comment]
I've edited the proposal slightly to add the fact that this lineage is on the ORF1b:V1706I branch (otherwise my head will explode with the amount of homoplasy we're seeing here with S:346, S:486 etc) - I hope that's OK @agamedilab

**Comment by AngieHinrichs** [comment]
> Usher still puts the whole cluster in what I believe to be the wrong place: have them branch off https://github.com/cov-lineages/pango-designation/issues/918 before the acquisition of nuc:C28657T and you don't need a highly unlikely reversion to explain what happened.

True, although you would also have to add T23019C (S:F486S) there, so T23019C would happen twice (once in each branch).  Equivalent from a strict parsimony point of view, although I wish there were a way to penalize reversions just a bit without harming the performance and/or complicating things quite a bit for usher and matOptimize.

**Comment by silcn** [comment]
> True, although you would also have to add T23019C (S:F486S) there, so T23019C would happen twice (once in each branch). Equivalent from a strict parsimony point of view, although I wish there were a way to penalize reversions just a bit without harming the performance and/or complicating things quite a bit for usher and matOptimize.

Yes, we do have to assume S:F486S occurred twice independently, but given there are more BA.2.75+S:F486S sequences that definitely aren't part of this branch, I think it's fair to say that S:F486S is homoplasic on a BA.2.75 background.

**Comment by agamedilab** [comment]
23 on usher/gisaid as of 21.08.22. Expansion into Belgium, USA.

![grafik](https://user-images.githubusercontent.com/102166254/185778804-85b1a257-1f9d-4bc0-ab80-7b5cee4b8fcb.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2aefd_1d1470.json?c=pango_lineage_usher&label=nuc%20mutations:C3857A

**Comment by corneliusroemer** [comment]
Hard to say where to start this lineage - could do either S:486 or S:346 - I guess we have to wait to see where more sequences pop up.

**Comment by chrisruis** [comment]
We need new issues to either have an epidemiological event or be close to exhibiting an epidemiological event before opening. Will therefore close this one for now

**Comment by agamedilab** [comment]
Hi, I noticed that the lineages was already designated as BM.1 by the F486S mutation as the ORF1a:Q1198K was not a good defining mutation (as discussed above). In this case it would be great if a milestone & designate label could be added to the issue. Otherwise the issue could be closed for redundancy.

Sequences of the original proposal:
![grafik](https://user-images.githubusercontent.com/102166254/188302270-a32bbdaf-7fe4-42e4-a934-0008327325b2.png)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_432cd_440660.json?branchLabel=aa%20mutations&c=pango_lineage_usher&label=nuc%20mutations:C3857A

![grafik](https://user-images.githubusercontent.com/102166254/188302329-0fb7baf8-853e-4de8-bb6e-d90d44017814.png)

**Comment by corneliusroemer** [comment]
This lineage has _not_ been designated - I understand this issue as talking about the S:F486S, ORF1a:Q1198K lineage

Everything that starts from the ORF1a:Q1198K reversion in the Usher tree is an Usher tree error and does _not_ belong to this lineage.

I should probably designate the ORF1a:Q1198K one to help distinguish things and help Usher and humans understand the homoplasic mess that BA.2.75 is.

**Comment by corneliusroemer** [comment]
Thanks @InfrPopGen

I think it's important to clarify that BM.4 is BA.2.75.3 + ORF1a:Q1198K, in contrast to the proposal which included S:F486S

I'll designate an additional BM.4.1 with S:F486S to show the homoplasy here.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer really hard to keep everything at his place with BA.2.75 , could i suggest to extend https://www.pango.network/summary-of-designated-omicron-lineages/ 
to more than one main defining mutation for just BA.2.75?

**Comment by jinyu-ncbi** [comment]
After checking the BA.2.75 sequences at NCBI, I am wondering that S:R346T is not a convergent mutation that appears in multiple sublineages, but likely a mutation difficult to be correctly called (probably because it is near primer-binding sites?). We might need to be careful when designating sublineages using S:R346T.
